#
# Makefile for discretization
#
C_DIR=../../..
#
include ../../../main/Makefile.option


src = Edge.cc Hexahedron.cc  MeshReader.cc Octahedron.cc  Quadrangle.cc   Triangle.cc \
	GridLevel.cc  Jacobian.cc    MultilevelGrid.cc  Pyramid.cc     Tetrahedron.cc  Vertex.cc

#
CFLAGS3 =
#


include ../../makefile.inc

-include $(DEPEND_FILE)

#ifeq ($(Adaptivity),yes)
#  -include $(DEPEND_FILE)
#else
#endif
# DO NOT DELETE


