#
C_DIR=../../../..
#
src = output.cc basemesh.cc mymesh.cc squaremesh.cc neurofemmesh.cc \
	netgenmesh.cc filesystem.cc gmvwriter.cc pilesgmvwriter.cc \
	interface_f77.cc bemmesh.cc

#
lib = general-piles

libpath = libsrc/AlgebraicSystem/PILES/general
CFLAGS3 =
#
include ../../../makefile.inc

# DO NOT DELETE

