# mock fluid partner spec for flapFSI2D (generated by make_mesh.py)
participant Fluid
dimensions 2
loadVector 0.0 -2.0e4
rampTime 5.0e-3
mesh Fluid-Faces write Stress
5
0.001 0.001
0.003 0.001
0.005 0.001
0.007 0.001
0.009 0.001
mesh Fluid-Nodes read Displacement
6
0 0.001
0.002 0.001
0.004 0.001
0.006 0.001
0.008 0.001
0.01 0.001
end
