#
# Makefile for discretization
#
C_DIR=../../..
src = ansysfile.cc 
#
lib = ansysfile
libpath = libsrc/DataInOut/AnsysFile
CFLAGS3 =
#
include ../../makefile.inc
-include $(Dependencies)
# DO NOT DELETE


