#
# Makefile for Parameter Handling module
#
C_DIR = ../../..
src = Settings.cc BaseCommandLineHandler.cc CommandLineHandlerSetting.cc

#
CFLAGS3 =
#
include ../../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE


