#
# Makefile for Parameter Handling module
#
C_DIR = ../../..
src = Settings.cc CommandLineHandlerSetting.cc

#
lib = commandline
libpath = libsrc/DataInOut/CommandLine
CFLAGS3 =
#
include ../../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE


