EXEC_PROGRAM("${CMAKE_CXX_COMPILER} --version | head -1"
  ARGS
  OUTPUT_VARIABLE CFS_CXX_COMPILER_INFO
  RETURN_VALUE RETVAL)

EXEC_PROGRAM("${CMAKE_Fortran_COMPILER} --version | head -1"
  ARGS
  OUTPUT_VARIABLE CFS_FORTRAN_COMPILER_INFO
  RETURN_VALUE RETVAL)

# Check if we are using the GNU compiler suite
IF(CMAKE_COMPILER_IS_GNUCXX AND
    CFS_FORTRAN_COMPILER_INFO MATCHES "GNU")

#  MESSAGE("We are using the GNU C++ compiler. ${CMAKE_CXX_COMPILER}")

  # Set the compiler name and compiler version
  SET(CFS_CXX_COMPILER_NAME "GCC")
  EXEC_PROGRAM("${CMAKE_CXX_COMPILER} --version | head -1"
    ARGS
    OUTPUT_VARIABLE CFS_CXX_COMPILER_VER
    RETURN_VALUE RETVAL)

  STRING(REGEX MATCH 
    "[0-9]+\\.[0-9]+\\.[0-9]+"
    CFS_CXX_COMPILER_VER
    ${CFS_CXX_COMPILER_VER})

  EXEC_PROGRAM("${CMAKE_Fortran_COMPILER} --version | head -1"
    ARGS
    OUTPUT_VARIABLE CFS_FORTRAN_COMPILER_VER
    RETURN_VALUE RETVAL)

  # Determine name of Fortran compiler
  STRING(REGEX MATCH 
    "GNU"
    CFS_FORTRAN_COMPILER_NAME
    ${CFS_FORTRAN_COMPILER_VER})

  # Determine version of Fortran compiler
  STRING(REGEX MATCH 
    "[0-9]+\\.[0-9]+\\.[0-9]+"
    CFS_FORTRAN_COMPILER_VER
    ${CFS_FORTRAN_COMPILER_VER})

  # Determine compiler/linker flags according to build type
  IF(DEBUG)

    SET(CFS_C_FLAGS "-ansi -Wall -pedantic")
    SET(CFS_CXX_FLAGS "-ftemplate-depth-55")
    SET(CFS_SUPPRESSIONS "-Wno-long-long -Wno-unknown-pragmas -Wno-comment")
    SET(CHECK_MEM_ALLOC 1)
    SET(CHECK_TYPE_CASTS 1)

    IF(CFS_PROFILING)
      SET(CFS_PROF_FLAGS "-pg")
    ENDIF(CFS_PROFILING)

  ELSE(DEBUG)

    SET(CFS_SUPPRESSIONS "-Wno-long-long -Wno-unknown-pragmas -Wno-comment -Wno-unused -Wno-sign-compare")
    SET(CFS_C_FLAGS "-ansi -Wall -pedantic")
    SET(CFS_CXX_FLAGS "-ftemplate-depth-55")

    IF(CFS_ARCH STREQUAL "I386")
      SET(CFS_OPT_FLAGS "-m32 -march=pentium4")
    ENDIF(CFS_ARCH STREQUAL "I386")

    IF(CFS_ARCH STREQUAL "X86_64")
      SET(CFS_OPT_FLAGS "-m64 -march=k8")
    ENDIF(CFS_ARCH STREQUAL "X86_64")

    IF(CFS_ARCH STREQUAL "IA64")
      SET(CFS_OPT_FLAGS "-m64 -mtune-arch=itanium2")
    ENDIF(CFS_ARCH STREQUAL "IA64")

  ENDIF(DEBUG)

ENDIF(CMAKE_COMPILER_IS_GNUCXX AND
    CFS_FORTRAN_COMPILER_INFO MATCHES "GNU")




# Check for Intel compilers
IF(CFS_CXX_COMPILER_INFO MATCHES "ICC" AND
    CFS_FORTRAN_COMPILER_INFO MATCHES "IFORT")

  # Set the compiler name and compiler version
  SET(CFS_CXX_COMPILER_NAME "ICC")
  SET(CFS_FORTRAN_COMPILER_NAME "IFORT")

  STRING(REGEX MATCH 
    "[0-9]+\\.[0-9]+"
    CFS_CXX_COMPILER_VER
    ${CFS_CXX_COMPILER_INFO})

  STRING(REGEX MATCH 
    "[0-9]+\\.[0-9]+"
    CFS_FORTRAN_COMPILER_VER
    ${CFS_FORTRAN_COMPILER_INFO})

  # Determine compiler/linker flags according to build type
  IF(DEBUG)

    SET(CFS_C_FLAGS "-g -ansi -w1 -Wcheck")
    SET(CHECK_MEM_ALLOC 1)
    SET(CHECK_TYPE_CASTS 1)

    IF(CFS_PROFILING)
      SET(CFS_PROF_FLAGS "-pg")
    ENDIF(CFS_PROFILING)

  ELSE(DEBUG)

    SET(CFS_C_FLAGS "-ansi -w0 -O2")

  ENDIF(DEBUG)


ENDIF(CFS_CXX_COMPILER_INFO MATCHES "ICC" AND
  CFS_FORTRAN_COMPILER_INFO MATCHES "IFORT")

# Check if we have a valid combination of C++ and Fortran compilers.
IF(CFS_CXX_COMPILER_NAME STREQUAL "" OR
    CFS_FORTRAN_COMPILER_NAME STREQUAL "")

  MESSAGE(SEND_ERROR "Combination of C++ and Fortran compilers not supported!")

ENDIF(CFS_CXX_COMPILER_NAME STREQUAL "" OR
  CFS_FORTRAN_COMPILER_NAME STREQUAL "")

# Set compiler/linker flags for all build types
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CFS_C_FLAGS} ${CFS_PROF_FLAGS} ${CFS_OPT_FLAGS} ${CFS_SUPPRESSIONS}")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CFS_C_FLAGS} ${CFS_CXX_FLAGS} ${CFS_PROF_FLAGS} ${CFS_OPT_FLAGS} ${CFS_SUPPRESSIONS}")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${CFS_PROF_FLAGS}")
SET(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${CFS_PROF_FLAGS}")
SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${CFS_PROF_FLAGS}")

# MESSAGE("C++ name: ${CFS_CXX_COMPILER_NAME}")
# MESSAGE("C++ version: ${CFS_CXX_COMPILER_VER}")
# MESSAGE("FORTRAN Compiler ${CFS_FORTRAN_COMPILER_NAME}")
# MESSAGE("FORTRAN Compiler version ${CFS_FORTRAN_COMPILER_VER}")
# MESSAGE("CMAKE BUILD TYPE: ${CMAKE_BUILD_TYPE}")
# MESSAGE("CFS_ARCH_STR: ${CFS_ARCH_STR}")
