
EXEC_PROGRAM("${CFS_SOURCE_DIR}/cmake_modules/distro.sh"
  ARGS -c
  OUTPUT_VARIABLE CFS_ARCH_TEST
  RETURN_VALUE RETVAL)

LIST(GET CFS_ARCH_TEST 0 CFS_DISTRO)
LIST(GET CFS_ARCH_TEST 1 CFS_DISTRO_VER)
LIST(GET CFS_ARCH_TEST 2 CFS_ARCH)

SET(CFS_DISTRO "${CFS_DISTRO}"
  CACHE INTERNAL "String specifying the distribution CFS is built on.")
SET(CFS_ARCH_STR "${CFS_DISTRO_VER}"
  CACHE INTERNAL "Version of the distribution CFS is built on.")
SET(CFS_ARCH_STR "${CFS_ARCH}"
  CACHE INTERNAL "Architecture CFS is built on.")
SET(CFS_ARCH_STR "${CFS_DISTRO}_${CFS_DISTRO_VER}_${CFS_ARCH}"
  CACHE INTERNAL "String specifying the architecture CFS is built on.")

# MESSAGE("CFS_DISTRO: ${CFS_DISTRO}")
# MESSAGE("CFS_DISTRO_VER: ${CFS_DISTRO_VER}")
# MESSAGE("CFS_ARCH: ${CFS_ARCH}")
# MESSAGE("CFS_ARCH_STR: ${CFS_ARCH_STR}")

