SET(DISTRO_SCRIPT "${CFS_SOURCE_DIR}/share/scripts/distro.sh")

EXEC_PROGRAM("${DISTRO_SCRIPT}"
  ARGS -c
  OUTPUT_VARIABLE CFS_DISTRO_TEST
  RETURN_VALUE RETVAL)

EXECUTE_PROCESS(
  COMMAND "${CMAKE_COMMAND}" -E make_directory "${CFS_BINARY_DIR}/tmp"
  WORKING_DIRECTORY "${CFS_BINARY_DIR}"
  RESULT_VARIABLE RETVAL
  )

FILE(WRITE "${CFS_BINARY_DIR}/tmp/distro_test.cmake" "${CFS_DISTRO_TEST}")

INCLUDE("${CFS_BINARY_DIR}/tmp/distro_test.cmake")

SET(CFS_FULL_DISTRO "${DIST}")
SET(CFS_FULL_DISTRO_VER "${REV}")

IF(DIST_FAMILY)
  SET(CFS_DISTRO "${DIST_FAMILY}")
  SET(CFS_DISTRO_VER "${MAJOR_REV}")
ELSE()
  SET(CFS_DISTRO "${DIST}")
  SET(CFS_DISTRO_VER "${REV}")
ENDIF()

SET(CFS_ARCH "${ARCH}")
SET(CFS_ARCH_STR "${CFS_DISTRO}_${ARCH}_${CFS_DISTRO_VER}")
# Determine the subarchitecture of the platform.
SET(CFS_SUBARCH "${SUBARCH}")


# MESSAGE("CFS_DISTRO: ${CFS_DISTRO}")
# MESSAGE("CFS_DISTRO_VER: ${CFS_DISTRO_VER}")
# MESSAGE("CFS_ARCH: ${CFS_ARCH}")
# MESSAGE("CFS_ARCH_STR: ${CFS_ARCH_STR}")
# MESSAGE("CFS_SUBARCH: ${CFS_SUBARCH}")

# Set a few distribution specific variables (FORTRAN libs, ...)
# G2C_LIBRARY and GFORTRAN_LIBRARY are defined in
# cmake_modules/FindFortranLibs.cmake
IF(CFS_DISTRO STREQUAL "SUSE" OR
   CFS_DISTRO STREQUAL "OPENSUSE" OR
   CFS_DISTRO STREQUAL "SLE")

 IF(CFS_DISTRO_VER GREATER 9.3)
   SET(CFS_PCKG_HINT ${CFS_PCKG_HINT} gfortran)
   SET(CFS_FORTRAN_LIBS ${CFS_FORTRAN_LIBS} ${GFORTRAN_LIBRARY})   
 ENDIF(CFS_DISTRO_VER GREATER 9.3)
 
ENDIF(CFS_DISTRO STREQUAL "SUSE" OR
  CFS_DISTRO STREQUAL "OPENSUSE" OR
  CFS_DISTRO STREQUAL "SLE")

IF(CFS_DISTRO STREQUAL "DEBIAN")
  IF(CFS_DISTRO_VER GREATER 3)
    SET(CFS_FORTRAN_LIBS ${GFORTRAN_LIBRARY})
    SET(CFS_PCKG_HINT ${CFS_PCKG_HINT} "gfortran, libgfortran1-dev")
  ELSE(CFS_DISTRO_VER GREATER 3)
    SET(CFS_FORTRAN_LIBS ${G2C_LIBRARY})
  ENDIF(CFS_DISTRO_VER GREATER 3)

ENDIF(CFS_DISTRO STREQUAL "DEBIAN")


IF(CFS_DISTRO STREQUAL "UBUNTU")
  # The CFS_FORTRAN_LIBS variable has been set empirically.
  # At the moment I just have Edgy Eft (6.10)!
  IF(CFS_DISTRO_VER GREATER 6)
    SET(CFS_FORTRAN_LIBS ${GFORTRAN_LIBRARY})
    SET(CFS_PCKG_HINT ${CFS_PCKG_HINT} "libgfortran1-dev")
  ENDIF(CFS_DISTRO_VER GREATER 6)

ENDIF(CFS_DISTRO STREQUAL "UBUNTU")

IF(CFS_DISTRO STREQUAL "FEDORA" OR
   CFS_DISTRO STREQUAL "REDHAT" OR
   CFS_DISTRO STREQUAL "RHEL" OR
   CFS_DISTRO STREQUAL "CENTOS")

   # Fortran support for Fedora/Redhat/RHEL never tested
   # TODO: add a sane check here
   SET(CFS_FORTRAN_LIBS ${GFORTRAN_LIBRARY})

ENDIF(CFS_DISTRO STREQUAL "FEDORA" OR
   CFS_DISTRO STREQUAL "REDHAT" OR
   CFS_DISTRO STREQUAL "RHEL" OR
   CFS_DISTRO STREQUAL "CENTOS")

IF(CFS_DISTRO STREQUAL "MANDRAKE" OR
   CFS_DISTRO STREQUAL "MANDRIVA")

   # Fortran support for Mandrake/Mandriva never tested
   # TODO: add a sane check here
   SET(CFS_FORTRAN_LIBS ${G2C_LIBRARY} ${GFORTRAN_LIBRARY})

ENDIF(CFS_DISTRO STREQUAL "MANDRAKE" OR
   CFS_DISTRO STREQUAL "MANDRIVA")


IF(CFS_DISTRO STREQUAL "MACOSX")

  IF(NOT ${CFS_FORTRAN_COMPILER_NAME} STREQUAL "IFORT")
    SET(CFS_FORTRAN_LIBS ${GFORTRAN_LIBRARY})
  ENDIF(NOT ${CFS_FORTRAN_COMPILER_NAME} STREQUAL "IFORT")

  IF(CMAKE_OSX_ARCHITECTURES)
    LIST(LENGTH CMAKE_OSX_ARCHITECTURES NUM_ARCH)

    IF(NUM_ARCH GREATER 1)
      MESSAGE(FATAL_ERROR "Only binaries for one Mac OS X architecture can be built at a time!")
    ENDIF(NUM_ARCH GREATER 1)

    LIST(GET CMAKE_OSX_ARCHITECTURES 0 OSX_ARCH)
    # MESSAGE("OSX_ARCH ${OSX_ARCH}")

    IF(OSX_ARCH STREQUAL "i386")
      SET(CFS_ARCH "I386")
    ELSE(OSX_ARCH STREQUAL "i386")
      IF(OSX_ARCH STREQUAL "x86_64")
	SET(CFS_ARCH "X86_64")
      ELSE(OSX_ARCH STREQUAL "x86_64")
	MESSAGE(FATAL_ERROR "Building for architecture ${OSX_ARCH} not supported!")
      ENDIF(OSX_ARCH STREQUAL "x86_64")
    ENDIF(OSX_ARCH STREQUAL "i386")

  ELSE(CMAKE_OSX_ARCHITECTURES)
    IF(CFS_DISTRO_VER GREATER 10.5)
      SET(CMAKE_OSX_ARCHITECTURES "x86_64")
    ELSE(CFS_DISTRO_VER GREATER 10.5)
      SET(CMAKE_OSX_ARCHITECTURES "i386")
    ENDIF(CFS_DISTRO_VER GREATER 10.5)
  ENDIF(CMAKE_OSX_ARCHITECTURES)

 
ENDIF(CFS_DISTRO STREQUAL "MACOSX")

# Macro which prints a list of libraries which are needed to compile CFS++
MACRO(SUGGEST_INSTALL_PCKG)
  MESSAGE("Either try installing the following packages to compile CFS++:")
  FOREACH(PCKG ${CFS_PCKG_HINT})
    MESSAGE(${PCKG})
  ENDFOREACH(PCKG)
  MESSAGE("or try to set the corresponding advanced variables.")
ENDMACRO(SUGGEST_INSTALL_PCKG)


IF(CFS_ARCH STREQUAL "I386")
  # Set path suffix for system libs
  SET(LIB_SUFFIX "lib")
ENDIF(CFS_ARCH STREQUAL "I386")

IF(CFS_ARCH STREQUAL "X86_64")
  # Set path suffix for system libs
  SET(LIB_SUFFIX "lib64")
ENDIF(CFS_ARCH STREQUAL "X86_64")


IF(CFS_ARCH STREQUAL "IA64")
  # Set path suffix for system libs
  SET(LIB_SUFFIX "lib")
ENDIF(CFS_ARCH STREQUAL "IA64")

# Determine the system in bits
IF(CFS_ARCH STREQUAL "I386")
  SET(SYSTEM_BITS "32")
ELSE(CFS_ARCH STREQUAL "I386")
  SET(SYSTEM_BITS "64")
ENDIF(CFS_ARCH STREQUAL "I386")

SET(SYSTEM_BITS "${SYSTEM_BITS}"
  CACHE INTERNAL "Determins if this is a '32' or '64' bit system.")
SET(CFS_DISTRO "${CFS_DISTRO}"
  CACHE INTERNAL "String specifying the distribution CFS is built on.")
SET(CFS_DISTRO_VER "${CFS_DISTRO_VER}"
  CACHE INTERNAL "Version of the distribution CFS is built on.")
SET(CFS_ARCH "${CFS_ARCH}"
  CACHE INTERNAL "Architecture CFS is built on.")
SET(CFS_ARCH_STR "${CFS_DISTRO}_${CFS_DISTRO_VER}_${CFS_ARCH}"
  CACHE INTERNAL "String specifying the architecture CFS is built on.")
SET(CFS_SUBARCH "${CFS_SUBARCH}"
  CACHE INTERNAL "Sub-Architecture CFS is built on.")
