# - Find BLAS library.
# This module finds if BLAS is installed and determines where the
# library is. It also determines what the name of the library is.
# This code sets the following variables:
#  BLAS_LIBRARY        = path to BLAS library (blas)
#  BLAS_FOUND          = bool which says if BLAS has been found

SET (FORTRAN_POSSIBLE_LIB_PATHS
  "$ENV{CFSDEPS_ROOT}/lib64"
  "$ENV{CFSDEPS_ROOT}/lib64/gfortran64"
  "$ENV{CFSDEPS_ROOT}/lib64/gfortran64_mp"
  "$ENV{CFSDEPS_ROOT}/lib"
  /opt/lse/lib64
  /opt/lse/lib
  /usr/lib64
  /usr/lib
  /usr/local/lib64
  /usr/local/lib
  /usr/lib64/atlas
  /usr/lib/atlas
)

#-------------------------------------------------------------------------------
# The g77 library for linking to C g2c should not be required any more in the
# future. But we leave it here. Who knows...
#-------------------------------------------------------------------------------
FIND_LIBRARY(G2C_LIBRARY
  NAMES g2c
  PATHS ${FORTRAN_POSSIBLE_LIB_PATHS}
  NO_DEFAULT_PATH
  NO_CMAKE_ENVIRONMENT_PATH
  NO_CMAKE_PATH
  NO_SYSTEM_ENVIRONMENT_PATH
  NO_CMAKE_SYSTEM_PATH 
)

IF(G2C_LIBRARY)
  SET(G2C_FOUND 1)
ENDIF(G2C_LIBRARY)

IF(NOT CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")
  SET(GFORTRAN_EXECUTABLE "gfortran")
ELSE(NOT CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")
  SET(GFORTRAN_EXECUTABLE "${CMAKE_Fortran_COMPILER}")
ENDIF(NOT CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")

EXEC_PROGRAM("${GFORTRAN_EXECUTABLE} -print-search-dirs | tail -1 | cut -d'=' -f 2 | sed -e 's/:/;/g'"
  ARGS
  OUTPUT_VARIABLE GFORTRAN_SEARCH_DIRS
  RETURN_VALUE RETVAL)

IF(NOT RETVAL EQUAL 0)
  SET(GFORTRAN_SEARCH_DIRS "")
ENDIF(NOT RETVAL EQUAL 0)

FIND_LIBRARY(GFORTRAN_LIBRARY
  NAMES gfortran
  PATHS ${GFORTRAN_SEARCH_DIRS} ${FORTRAN_POSSIBLE_LIB_PATHS}
  NO_DEFAULT_PATH
  NO_CMAKE_ENVIRONMENT_PATH
  NO_CMAKE_PATH
  NO_SYSTEM_ENVIRONMENT_PATH
  NO_CMAKE_SYSTEM_PATH 
)

IF(GFORTRAN_LIBRARY)
  SET(GFORTRAN_FOUND 1)

  IF(CFS_DISTRO STREQUAL "MACOSX")
#    STRING(REGEX REPLACE "gfortran\\..*" "gfortran.dylib"
#      GFORTRAN_LIBRARY_SHARED "${GFORTRAN_LIBRARY}")
    SET(GFORTRAN_LIBRARY_SHARED "${GFORTRAN_LIBRARY}")
  ELSE(CFS_DISTRO STREQUAL "MACOSX")
    STRING(REGEX REPLACE "gfortran\\..*" "gfortran.so"
      GFORTRAN_LIBRARY_SHARED "${GFORTRAN_LIBRARY}")
  ENDIF(CFS_DISTRO STREQUAL "MACOSX")

  STRING(REGEX REPLACE "gfortran\\..*" "gfortran.a"
    GFORTRAN_LIBRARY_STATIC "${GFORTRAN_LIBRARY}")
  
  IF(CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")
    SET(CFS_FORTRAN_DYNRT_LIBS 
      ${GFORTRAN_LIBRARY_SHARED})
    
    SET(CFS_FORTRAN_STATRT_LIBS
      ${GFORTRAN_LIBRARY_STATIC}
      )
  ENDIF(CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")

  SET(GFORTRAN_LIBRARY "${GFORTRAN_LIBRARY_STATIC}" CACHE PATH
    "Path to GFORTRAN library." FORCE)
ENDIF(GFORTRAN_LIBRARY)

MARK_AS_ADVANCED(
  BLAS_LIBRARY
  BLAS_FOUND
  LAPACK_LIBRARY
  LAPACK_FOUND
  G2C_LIBRARY
  G2C_FOUND
  GFORTRAN_LIBRARY
  GFORTRAN_FOUND
  )
