SET(LAPACK_FOUND 0)

FIND_LIBRARY(LAPACK_STANDARD_LIB
  NAMES lapack
  PATHS ${FORTRAN_POSSIBLE_LIB_PATHS}
  )

MARK_AS_ADVANCED(LAPACK_STANDARD_LIB)

IF(LAPACK_STANDARD_LIB)
  SET(LAPACK_FOUND 1)
ENDIF(LAPACK_STANDARD_LIB)
