# - Find glib2 installation 
# This module finds if glib2 is installed and determines where 
# the include files and libraries are. It also determines what the name of
# the library is. This code sets the following variables:
#  
#  MPCCI_FOUND     = system has glib2 
#  MPCCI_LIBRARIES = path to the glib2 libraries
#  MPCCI_CXX_FLAGS  = Compiler flags for glib2 
#  MPCCI_INCLUDE_DIR      = where to find "glib2.h"
#  MPCCI_DEFINITIONS      = extra defines
# 
# DEPRECATED
#
# OPTIONS 
# 
# USAGE 
# 
# NOTES
#
# AUTHOR
# Simon Triebenbacher simon.triebenbacher@uni-klu.ac.at (02/2009)


SET (MPI_POSSIBLE_ROOT_PATHS
  "$ENV{CFSDEPS_ROOT}"
  "/opt/mpich/ch-p4"
  #          "/home/data/programs/MpCCI/MpCCI_3.0.5/AMD64/MPICH64/mpich-1.2.7p1"
  #	"/home/data/programs/mpich-1.2.7"
  #	"/opt/mpich/ch-p4mpd"
  )


FIND_PATH(MPI_ROOT_DIR include/mpi.h 
  ${MPI_POSSIBLE_ROOT_PATHS} )

SET(MPI_ROOT_DIR "${MPI_ROOT_DIR}" CACHE INTERNAL "MPI_ROOT_DIR")

SET(MPI_INCLUDE_DIR "${MPI_ROOT_DIR}/include" CACHE FILEPATH "MPI include directory.")

SET (MPI_POSSIBLE_LIB_PATHS
  "${MPI_ROOT_DIR}/lib64"
  "${MPI_ROOT_DIR}/lib"
  ) 

FIND_LIBRARY(MPI_LIBRARY
  NAMES mpich mpi
  PATHS ${MPI_POSSIBLE_LIB_PATHS}
  DOC "MPI library" ) 

SET(MPI_LIBRARIES
  "${MPI_LIBRARY}"
  ) 

MARK_AS_ADVANCED(MPI_INCLUDE_DIR)
MARK_AS_ADVANCED(MPI_LIBRARY)

#/opt/mpich/ch-p4/lib64/libmpich.a
#      MESSAGE("DBG found MPI_LIBRARIES: ${MPI_LIBRARIES}")

STRING(REGEX REPLACE "/libmpich.*" #"[^/]*$"
  "" MPI_LIBRARY_DIR
  ${MPI_LIBRARIES})

#      MESSAGE("DBG found MPI_LIBRARY_DIR: ${MPI_LIBRARY_DIR}")

SET(MPCCI_ROOT_DIR "/home/data/programs/MpCCI/MpCCI_3.0.5" CACHE FILEPATH "MpCCI root directory (MPCCI_ROOT_DIR/bin/mpcci).")
MARK_AS_ADVANCED(MPCCI_ROOT_DIR)

#    MESSAGE("DBG found MPCCI_ROOTDIR: ${MPCCI_ROOT_DIR}")

EXEC_PROGRAM("${MPCCI_ROOT_DIR}/bin/mpcci"
  ARGS arch -n
  OUTPUT_VARIABLE MPCCI_ARCH
  RETURN_VALUE RETVAL)

IF(MPCCI_ARCH STREQUAL "linux_amd64")
  SET(MPCCI_LIBRARY -lmpccisdk-64)
ENDIF(MPCCI_ARCH STREQUAL "linux_amd64")

IF(MPCCI_ARCH STREQUAL "linux_em64t")
  SET(MPCCI_LIBRARY -lmpccisdk-64)
ENDIF(MPCCI_ARCH STREQUAL "linux_em64t")

IF(MPCCI_ARCH STREQUAL "linux_x86")
  SET(MPCCI_LIBRARY -lmpccisdk-32)
ENDIF(MPCCI_ARCH STREQUAL "linux_x86")

SET(MPCCI_LIBRARIES "-L${MPCCI_ROOT_DIR}/lib/${MPCCI_ARCH};${MPCCI_LIBRARY};-L${MPI_LIBRARY_DIR};${MPI_LIBRARY}")
SET(MPCCI_INCLUDE_DIR "${MPCCI_ROOT_DIR}/include;${MPI_INCLUDE_DIR}/include")
SET(MPCCI_CXX_FLAGS "-fPIC -O3 -Wall")

EXEC_PROGRAM("${MPCCI_ROOT_DIR}/bin/mpcci"
  ARGS info -release
  OUTPUT_VARIABLE MPCCI_RELEASE
  RETURN_VALUE RETVAL)

# MESSAGE("DBG found MPCCI_RELEASE: ${MPCCI_RELEASE}")

STRING(REGEX MATCH "3\\.0\\.[0-9]+"
  MPCCI_RELEASE
  ${MPCCI_RELEASE})

STRING(REGEX REPLACE "\\." ""
  MPCCI_RELEASE
  ${MPCCI_RELEASE})

# MESSAGE("DBG found MPCCI_RELEASE: ${MPCCI_RELEASE}")

#    MESSAGE("DBG found MPCCI_LIBRARIES: ${MPCCI_LIBRARIES}")
#    MESSAGE("DBG found MPCCI_INCLUDE_DIR: ${MPCCI_INCLUDE_DIR}")
#    MESSAGE("DBG found MPCCI_CXX_FLAGS: ${MPCCI_CXX_FLAGS}")
#    MESSAGE("DBG found MPCCI_LD_FLAGS: ${MPCCI_LD_FLAGS}")


IF(MPCCI_LIBRARIES)
  IF(MPCCI_INCLUDE_DIR OR MPCCI_CXX_FLAGS)
    ## found all we need.
    SET(MPCCI_FOUND 1)
    SET(MPCCI_INCLUDE_DIR "${MPCCI_INCLUDE_DIR}"
        CACHE INTERNAL "MPCCI_INCLUDE_DIR")
    SET(MPCCI_CXX_FLAGS "${MPCCI_CXX_FLAGS}"
        CACHE INTERNAL "MPCCI_CXX_FLAGS")
    SET(MPCCI_LIBRARIES "${MPCCI_LIBRARIES};-lnsl;-lm"
        CACHE INTERNAL "MPCCI_LIBRARIES")
    SET(MPCCI_RELEASE "${MPCCI_RELEASE}"
        CACHE INTERNAL "MPCCI_RELEASE")
    
  ENDIF(MPCCI_INCLUDE_DIR OR MPCCI_CXX_FLAGS)
ENDIF(MPCCI_LIBRARIES)

#MESSAGE("DBG found MPCCI_FOUND: ${MPCCI_FOUND}")
