IF(NOT CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")
  SET(GFORTRAN_EXECUTABLE "gfortran")
ELSE(NOT CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")
  SET(GFORTRAN_EXECUTABLE "${CMAKE_Fortran_COMPILER}")
ENDIF(NOT CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")

EXECUTE_PROCESS(
  COMMAND "${GFORTRAN_EXECUTABLE}" -print-search-dirs
  WORKING_DIRECTORY "${CFS_BINARY_DIR}"
  OUTPUT_VARIABLE GFORTRAN_SEARCH_DIRS
  RESULT_VARIABLE RETVAL
  )

STRING(REPLACE ";" "#____#" GFORTRAN_SEARCH_DIRS "${GFORTRAN_SEARCH_DIRS}")
STRING(REPLACE "\n" ";" SEARCH_DIRS "${GFORTRAN_SEARCH_DIRS}")
foreach(line IN LISTS SEARCH_DIRS)
  IF(line MATCHES "libraries")
    STRING(REPLACE "=" ";" line "${line}")
    LIST(GET line 1 line)
    IF(NOT WIN32)
      STRING(REPLACE ":" ";" GFORTRAN_SEARCH_DIRS "${line}")
    ELSE()
      STRING(REPLACE "#____#" ";" GFORTRAN_SEARCH_DIRS "${line}")
    ENDIF()
#    MESSAGE("GFORTRAN_SEARCH_DIRS ${GFORTRAN_SEARCH_DIRS}")
  ENDIF()
endforeach()



IF(NOT RETVAL EQUAL 0)
  SET(GFORTRAN_SEARCH_DIRS "")
ENDIF(NOT RETVAL EQUAL 0)

FIND_LIBRARY(GFORTRAN_LIBRARY
  NAMES gfortran
  PATHS ${GFORTRAN_SEARCH_DIRS}
  NO_DEFAULT_PATH
  NO_CMAKE_ENVIRONMENT_PATH
  NO_CMAKE_PATH
  NO_SYSTEM_ENVIRONMENT_PATH
  NO_CMAKE_SYSTEM_PATH 
)

IF(GFORTRAN_LIBRARY)
  SET(GFORTRAN_FOUND 1)

  IF(CFS_DISTRO STREQUAL "MACOSX")
#    STRING(REGEX REPLACE "gfortran\\..*" "gfortran.dylib"
#      GFORTRAN_LIBRARY_SHARED "${GFORTRAN_LIBRARY}")
    SET(GFORTRAN_LIBRARY_SHARED "${GFORTRAN_LIBRARY}")
  ELSEIF(MINGW)
    SET(GFORTRAN_LIBRARY_SHARED "${GFORTRAN_LIBRARY}")
  ELSE()
    STRING(REGEX REPLACE "gfortran\\..*" "gfortran.so"
      GFORTRAN_LIBRARY_SHARED "${GFORTRAN_LIBRARY}")
  ENDIF(CFS_DISTRO STREQUAL "MACOSX")

  STRING(REGEX REPLACE "gfortran\\..*" "gfortran.a"
    GFORTRAN_LIBRARY_STATIC "${GFORTRAN_LIBRARY}")
  
  IF(CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")
    SET(CFS_FORTRAN_DYNRT_LIBS 
      ${GFORTRAN_LIBRARY_SHARED})
    
    SET(CFS_FORTRAN_STATRT_LIBS
      ${GFORTRAN_LIBRARY_STATIC}
      )
  ENDIF(CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")

  SET(GFORTRAN_LIBRARY "${GFORTRAN_LIBRARY_STATIC}" CACHE PATH
    "Path to GFORTRAN library." FORCE)
ENDIF(GFORTRAN_LIBRARY)

MARK_AS_ADVANCED(
  BLAS_LIBRARY
  BLAS_FOUND
  LAPACK_LIBRARY
  LAPACK_FOUND
  G2C_LIBRARY
  G2C_FOUND
  GFORTRAN_LIBRARY
  GFORTRAN_FOUND
  )
