SET(ACML_FOUND 0)

#-------------------------------------------------------------------------------
# Look for metis header.
#-------------------------------------------------------------------------------
BUILD_EXTLIB("ACML"
  "${CFS_BINARY_DIR}/include/acml.h"
  "${CFS_DEPS_ROOT}/acml/build_acml.pl"
  "build_acml.log")

IF(CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")
  SET(COMPSTR "gfortran")
ENDIF(CFS_FORTRAN_COMPILER_NAME STREQUAL "GNU")

IF(CFS_FORTRAN_COMPILER_NAME STREQUAL "IFORT")
  SET(COMPSTR "ifort")
ENDIF(CFS_FORTRAN_COMPILER_NAME STREQUAL "IFORT")

IF(CFS_ARCH STREQUAL "I386")
  SET(BITS "32")
ENDIF(CFS_ARCH STREQUAL "I386")

IF(CFS_ARCH STREQUAL "X86_64")
  SET(BITS "64")
ENDIF(CFS_ARCH STREQUAL "X86_64")

#-------------------------------------------------------------------------------
# Determine paths of ACML libraries.
#-------------------------------------------------------------------------------
SET(ACML_BLAS_SERIAL_LIB
  "${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}/${COMPSTR}${BITS}/libacml.a"
  CACHE FILEPATH "AMD Performance Library (ACML) serial.")

SET(ACML_BLAS_OPENMP_LIB
  "${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}/${COMPSTR}${BITS}_mp/libacml_mp.a"
  CACHE FILEPATH "AMD Performance Library (ACML) OpenMP.")

MARK_AS_ADVANCED(ACML_BLAS_SERIAL_LIB)
MARK_AS_ADVANCED(ACML_BLAS_OPENMP_LIB)

SET(ACML_LAPACK_OPENMP_LIB "${ACML_BLAS_OPENMP_LIB}" CACHE FILEPATH "AMD Performance Library (ACML).")
MARK_AS_ADVANCED(ACML_LAPACK_OPENMP_LIB)

SET(ACML_LAPACK_SERIAL_LIB "${ACML_BLAS_SERIAL_LIB}" CACHE FILEPATH "AMD Performance Library (ACML).")
MARK_AS_ADVANCED(ACML_LAPACK_SERIAL_LIB)

# MESSAGE("ACML_LIB_PATH ${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}/${COMPSTR}${BITS}")
# MESSAGE("ACML_BLAS_OPENMP_LIB ${ACML_BLAS_OPENMP_LIB}")
# MESSAGE("ACML_BLAS_SERIAL_LIB ${ACML_BLAS_SERIAL_LIB}")

IF(CFS_BLAS_LAPACK STREQUAL "ACML")
  IF(USE_OPENMP)
    IF(ACML_BLAS_OPENMP_LIB)
      SET(ACML_FOUND 1)
      SET(BLAS_LIBRARY ${ACML_BLAS_OPENMP_LIB})
      SET(LAPACK_LIBRARY ${ACML_LAPACK_OPENMP_LIB})
    ENDIF(ACML_BLAS_OPENMP_LIB)
  ELSE(USE_OPENMP)
    IF(ACML_BLAS_SERIAL_LIB)
      SET(ACML_FOUND 1)
      SET(BLAS_LIBRARY ${ACML_BLAS_SERIAL_LIB})
      SET(LAPACK_LIBRARY ${ACML_LAPACK_SERIAL_LIB})
    ENDIF(ACML_BLAS_SERIAL_LIB)
  ENDIF(USE_OPENMP)
ENDIF(CFS_BLAS_LAPACK STREQUAL "ACML")
