SET(ACML_FOUND 0)

#-------------------------------------------------------------------------------
# Determine paths of ACML libraries.
#-------------------------------------------------------------------------------
FIND_LIBRARY(BLAS_ACML_SERIAL_LIB
  NAMES acml
  PATHS ${FORTRAN_POSSIBLE_LIB_PATHS}
  )

FIND_LIBRARY(BLAS_ACML_OPENMP_LIB
  NAMES acml_mp
  PATHS ${FORTRAN_POSSIBLE_LIB_PATHS}
  )

MARK_AS_ADVANCED(BLAS_ACML_SERIAL_LIB)
MARK_AS_ADVANCED(BLAS_ACML_OPENMP_LIB)

IF(USE_OPENMP)
  IF(BLAS_ACML_OPENMP_LIB)
    SET(ACML_FOUND 1)
    SET(LAPACK_ACML_OPENMP_LIB "${BLAS_ACML_OPENMP_LIB}" CACHE FILEPATH "AMD Performance Library (ACML).")
    MARK_AS_ADVANCED(LAPACK_ACML_OPENMP_LIB)
  ENDIF(BLAS_ACML_OPENMP_LIB)
ELSE(USE_OPENMP)
  IF(BLAS_ACML_SERIAL_LIB)
    SET(ACML_FOUND 1)
    SET(LAPACK_ACML_SERIAL_LIB "${BLAS_ACML_SERIAL_LIB}" CACHE FILEPATH "AMD Performance Library (ACML).")
    MARK_AS_ADVANCED(LAPACK_ACML_SERIAL_LIB)
  ENDIF(BLAS_ACML_SERIAL_LIB)
ENDIF(USE_OPENMP)


