SET (MKL_POSSIBLE_PATHS
  /opt/intel/mkl/9.1.021
  /home/data/programs/intel/mkl/9.1.021
  )

FIND_FILE(MKL_ROOT_DIR
  NAMES include/mkl.h
  PATHS ${MKL_POSSIBLE_PATHS}
  NO_DEFAULT_PATH
  NO_CMAKE_ENVIRONMENT_PATH
  NO_CMAKE_PATH
  NO_SYSTEM_ENVIRONMENT_PATH
  NO_CMAKE_SYSTEM_PATH
  )

STRING(REPLACE "/include/mkl.h" "" MKL_ROOT_DIR "${MKL_ROOT_DIR}")

SET(MKL_ROOT_DIR ${MKL_ROOT_DIR} CACHE INTERNAL "Directory of MKL." FORCE)

MARK_AS_ADVANCED(MKL_ROOT_DIR)

IF(NOT MKL_ROOT_DIR)
  SET(MKL_FOUND 0)
ELSE(NOT MKL_ROOT_DIR)
  SET(MKL_FOUND 1)
ENDIF(NOT MKL_ROOT_DIR)
