SET(ARPACK_FOUND 0)

FIND_LIBRARY(ARPACK_LIBRARY
  NAMES arpack
  PATHS ${CFSDEPS_LIBRARY_DIR}
)

IF(ARPACK_LIBRARY)
  SET(ARPACK_FOUND 1)
ENDIF(ARPACK_LIBRARY)

MARK_AS_ADVANCED(ARPACK_LIBRARY)

IF(NOT ARPACK_FOUND)
  MESSAGE("Warning: ARPACK could not be found! Please specify proper paths.")
ENDIF(NOT ARPACK_FOUND)
