SET(ARPACK_FOUND 0)

FIND_LIBRARY(ARPACK_LIBRARY
  NAMES arpack
  PATHS ${CFSDEPS_LIBRARY_DIR}
)

IF(ARPACK_LIBRARY)
  SET(ARPACK_FOUND 1)
  STRING(REGEX REPLACE "arpack\\.so" "arpack.a"
    ARPACK_LIBRARY "${ARPACK_LIBRARY}")

  SET(ARPACK_LIBRARY "${ARPACK_LIBRARY}" CACHE PATH "Path to ARPACK library." FORCE)
ENDIF(ARPACK_LIBRARY)

MARK_AS_ADVANCED(ARPACK_LIBRARY)

IF(NOT ARPACK_FOUND)
  MESSAGE("Warning: ARPACK could not be found! Please specify proper paths.")
ENDIF(NOT ARPACK_FOUND)
