SET(PARDISO_FOUND 0)

FIND_LIBRARY(PARDISO_STANDARD_LIB
  NAMES pardiso
  PATHS ${CFSDEPS_LIBRARY_DIR}
  DOC "PARDISO library"
  NO_DEFAULT_PATH
  NO_CMAKE_ENVIRONMENT_PATH
  NO_CMAKE_PATH
  NO_SYSTEM_ENVIRONMENT_PATH
  NO_CMAKE_SYSTEM_PATH)   

IF(PARDISO_STANDARD_LIB)
  SET(PARDISO_FOUND 1)
ENDIF(PARDISO_STANDARD_LIB)

MARK_AS_ADVANCED(PARDISO_STANDARD_LIB)
