SET(Boost_FOUND 0)

BUILD_EXTLIB("Boost"
  "${CFS_BINARY_DIR}/include/boost"
  "${CFS_DEPS_ROOT}/boost/build_boost.pl"
  "build_boost.log")

SET(Boost_INCLUDE_DIR "${CFS_BINARY_DIR}/include" CACHE PATH "Boost include dir.")
SET(Boost_LIBRARY_DIR "${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}" CACHE PATH "Boost library dir.")

MARK_AS_ADVANCED(Boost_INCLUDE_DIR)
MARK_AS_ADVANCED(Boost_LIBRARY_DIR)



#-------------------------------------------------------------------------------
# On Windows we have to determine the correct suffix for 
# the Boost libraries according to our compiler and build type.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Disable automatic linking feature of Boost on Windows
# Only link against DLLs on Windows.
#-------------------------------------------------------------------------------
#  IF(WIN32)
#  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /DBOOST_ALL_NO_LIB /DBOOST_ALL_DYN_LINK")
#ENDIF(WIN32)

#-------------------------------------------------------------------------------
# Specify path to header which has to be preprocessed to get some infos
# about Boost.
#-------------------------------------------------------------------------------
SET(BOOST_TEST_FILE "${CFS_BINARY_DIR}/include/get_boost_infos.hh")
  
FILE(WRITE ${BOOST_TEST_FILE}
  "#include <boost/config/auto_link.hpp>\n"
  "#include <boost/version.hpp>\n\n"
  "<CFS_MSC_VER>_MSC_VER</CFS_MSC_VER>\n"
  "<CFS_BOOST_VERSION>BOOST_LIB_VERSION</CFS_BOOST_VERSION>"
  )

FILE(TO_NATIVE_PATH ${BOOST_TEST_FILE} BOOST_TEST_FILE)
# MESSAGE("BOOST_TEST_FILE ${BOOST_TEST_FILE}")

#-----------------------------------------------------------------------------
# Build command line for preprocessing the Boost info header
#-----------------------------------------------------------------------------
SET(BOOST_INFO_CMD "${CMAKE_CXX_COMPILER} ${CMAKE_CXX_FLAGS}")

IF(DEBUG)
  SET(BOOST_INFO_CMD "${BOOST_INFO_CMD} ${CMAKE_CXX_FLAGS_DEBUG}")
ELSE(DEBUG)
  SET(BOOST_INFO_CMD "${BOOST_INFO_CMD} ${CMAKE_CXX_FLAGS_RELEASE}")
ENDIF(DEBUG)

IF(WIN32)
  SET(BOOST_INFO_CMD "${BOOST_INFO_CMD} /I${Boost_INCLUDE_DIR} /nologo /DBOOST_LIB_NAME=boost_regex /EP \"${BOOST_TEST_FILE}\"")
ELSE(WIN32)
  SET(BOOST_INFO_CMD "${BOOST_INFO_CMD} -I${Boost_INCLUDE_DIR} -DBOOST_LIB_NAME=boost_regex -E \"${BOOST_TEST_FILE}\"")
ENDIF(WIN32)

# MESSAGE("CFS_CXX_COMPILER ${CFS_CXX_COMPILER}")
# MESSAGE("BOOST_INFO_CMD ${BOOST_INFO_CMD}")

#-----------------------------------------------------------------------------
# Preprocess the Boost info header
#-----------------------------------------------------------------------------
EXEC_PROGRAM(${BOOST_INFO_CMD}
  ARGS
  OUTPUT_VARIABLE BOOST_INFO_STR
  RETURN_VALUE RETVAL)

FILE(REMOVE ${BOOST_TEST_FILE})
# MESSAGE("BOOST_INFO_STR ${BOOST_INFO_STR}")


#-----------------------------------------------------------------------------
# Obtain Boost version.
#-----------------------------------------------------------------------------
STRING(REGEX MATCH "<CFS_BOOST_VERSION>.*</CFS_BOOST_VERSION>"
  BOOST_VERSION "${BOOST_INFO_STR}")

STRING(REGEX REPLACE "\"" ""
  BOOST_VERSION "${BOOST_VERSION}")
STRING(REGEX MATCH "[0-9]+\\_[0-9]+"
  BOOST_VERSION
  "${BOOST_VERSION}")

STRING(REGEX REPLACE "_" "."
  CFS_BOOST_VERSION "${BOOST_VERSION}")

# MESSAGE("CFS_BOOST_VERSION ${CFS_BOOST_VERSION}")

#-----------------------------------------------------------------------------
# Extract Boost library suffix from preprocessed output string.
#-----------------------------------------------------------------------------
STRING(REGEX MATCH "boost_regex.*" BOOST_INFO_STR "${BOOST_INFO_STR}")
STRING(REGEX MATCH "\"-\".*\"-\"" BOOST_LIB_SUFFIX "${BOOST_INFO_STR}")

# MESSAGE("BOOST_LIB_SUFFIX ${BOOST_LIB_SUFFIX}")

STRING(REGEX REPLACE "\"" ""
  BOOST_LIB_SUFFIX "${BOOST_LIB_SUFFIX}")
STRING(REGEX REPLACE " " ""
  BOOST_LIB_SUFFIX "${BOOST_LIB_SUFFIX}")

SET(BOOST_LIB_SUFFIX "${BOOST_LIB_SUFFIX}${BOOST_VERSION}.lib")

#-----------------------------------------------------------------------------
# Obtain version of Microsoft compiler. For the Intel compiler this reflects
# the setting of -Qvc7 => CFS_MSC_VER=1300, -Qvc71 => CFS_MSC_VER=1310,
# -Qvc8 => CFS_MSC_VER=1400. This should be specified in the file
# $ENV{ICLCFG}.
#-----------------------------------------------------------------------------
STRING(REGEX MATCH "<CFS_MSC_VER>.*</CFS_MSC_VER>"
  CFS_MSC_VER
  "${BOOST_INFO_STR}")
STRING(REGEX REPLACE "<CFS_MSC_VER>" ""
  CFS_MSC_VER "${CFS_MSC_VER}")
STRING(REGEX REPLACE "</CFS_MSC_VER>" ""
  CFS_MSC_VER "${CFS_MSC_VER}")

# MESSAGE("CFS_MSC_VER ${CFS_MSC_VER}")
#-----------------------------------------------------------------------------
# Set Boost toolset id according to M$ compatibility level of Intel compiler.
#-----------------------------------------------------------------------------
IF(CFS_MSC_VER EQUAL 1310 OR
    CFS_MSC_VER EQUAL 1400)
  
  IF(CFS_CXX_COMPILER_NAME STREQUAL "ICC")
    IF(DEBUG)
      SET(BOOST_LIB_SUFFIX_DEBUG "${BOOST_LIB_SUFFIX}")
      STRING(REGEX REPLACE "-mt-gd" "-mt"
	BOOST_LIB_SUFFIX_RELEASE "${BOOST_LIB_SUFFIX}")
    ELSE(DEBUG)
      STRING(REGEX REPLACE "-mt" "-mt-gd"
	BOOST_LIB_SUFFIX_DEBUG "${BOOST_LIB_SUFFIX}")
      SET(BOOST_LIB_SUFFIX_RELEASE "${BOOST_LIB_SUFFIX}")
    ENDIF(DEBUG)
  ELSE(CFS_CXX_COMPILER_NAME STREQUAL "ICC")
    
    IF(DEBUG)
      SET(BOOST_LIB_SUFFIX_DEBUG "${BOOST_LIB_SUFFIX}")
      STRING(REGEX REPLACE "-mt-gd" "-mt"
	BOOST_LIB_SUFFIX_RELEASE "${BOOST_LIB_SUFFIX}")
    ELSE(DEBUG)
      STRING(REGEX REPLACE "-mt" "-mt-gd"
	BOOST_LIB_SUFFIX_DEBUG "${BOOST_LIB_SUFFIX}")
      SET(BOOST_LIB_SUFFIX_RELEASE "${BOOST_LIB_SUFFIX}")
    ENDIF(DEBUG)
    
# MESSAGE("BOOST_LIB_SUFFIX ${BOOST_LIB_SUFFIX}")
  ENDIF(CFS_CXX_COMPILER_NAME STREQUAL "ICC")
  
ENDIF(CFS_MSC_VER EQUAL 1310 OR
  CFS_MSC_VER EQUAL 1400)

#  MESSAGE("BOOST_INFO_STR ${BOOST_INFO_STR}")
#  MESSAGE("BOOST_VERSION ${BOOST_VERSION}")
#  MESSAGE("BOOST_LIB_SUFFIX ${BOOST_LIB_SUFFIX}")
#  MESSAGE("CFS_MSC_VER ${CFS_MSC_VER}")
IF(UNIX)
  SET(BOOST_LIB_SUFFIX_DEBUG "-mt.a")
  SET(BOOST_LIB_SUFFIX_RELEASE "-mt.a")
  
  SET(BOOST_LIB_PREFIX "${Boost_LIBRARY_DIR}/lib")
ENDIF(UNIX)

IF(WIN32)
  SET(BOOST_LIB_PREFIX "${Boost_LIBRARY_DIR}/lib")
ENDIF(WIN32)

#-----------------------------------------------------------------------------
# Set Boost Debug library paths in cache.
#-----------------------------------------------------------------------------
SET(BOOST_DATE_TIME_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_date_time${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_DATE_TIME_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_DATE_TIME_LIB_DEBUG)
SET(BOOST_FILESYSTEM_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_filesystem${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_FILESYSTEM_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_FILESYSTEM_LIB_DEBUG)
SET(BOOST_IOSTREAMS_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_iostreams${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_IOSTREAMS_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_IOSTREAMS_LIB_DEBUG)
SET(BOOST_PRG_EXEC_MONITOR_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_prg_exec_monitor${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_PRG_EXEC_MONITOR_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_PRG_EXEC_MONITOR_LIB_DEBUG)
SET(BOOST_PROGRAM_OPTIONS_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_program_options${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_PROGRAM_OPTIONS_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_PROGRAM_OPTIONS_LIB_DEBUG)
SET(BOOST_PYTHON_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_python${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_PYTHON_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_PYTHON_LIB_DEBUG)
SET(BOOST_REGEX_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_regex${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_REGEX_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_REGEX_LIB_DEBUG)
SET(BOOST_SERIALIZATION_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_serialization${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SERIALIZATION_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_LIB_DEBUG)
SET(BOOST_SERIALIZATION_HDF5_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_serialization_hdf5${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SERIALIZATION_HDF5_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_HDF5_LIB_DEBUG)
SET(BOOST_SIGNALS_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_signals${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SIGNALS_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SIGNALS_LIB_DEBUG)
SET(BOOST_SYSTEM_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_system${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SYSTEM_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SYSTEM_LIB_DEBUG)
SET(BOOST_TEST_EXEC_MONITOR_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_test_exec_monitor${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_TEST_EXEC_MONITOR_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_TEST_EXEC_MONITOR_LIB_DEBUG)
SET(BOOST_THREAD-MT_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_thread-mt${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_THREAD-MT_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_THREAD-MT_LIB_DEBUG)
SET(BOOST_THREAD_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_thread${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_THREAD_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_THREAD_LIB_DEBUG)
SET(BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_unit_test_framework${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG)
SET(BOOST_WSERIALIZATION_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_wserialization${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_WSERIALIZATION_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_WSERIALIZATION_LIB_DEBUG)


#-----------------------------------------------------------------------------
# Set Boost Release library paths in cache.
#-----------------------------------------------------------------------------
SET(BOOST_DATE_TIME_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_date_time${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_DATE_TIME_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_DATE_TIME_LIB_RELEASE)
SET(BOOST_FILESYSTEM_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_filesystem${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_FILESYSTEM_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_FILESYSTEM_LIB_RELEASE)
SET(BOOST_IOSTREAMS_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_iostreams${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_IOSTREAMS_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_IOSTREAMS_LIB_RELEASE)
SET(BOOST_PRG_EXEC_MONITOR_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_prg_exec_monitor${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_PRG_EXEC_MONITOR_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_PRG_EXEC_MONITOR_LIB_RELEASE)
SET(BOOST_PROGRAM_OPTIONS_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_program_options${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_PROGRAM_OPTIONS_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_PROGRAM_OPTIONS_LIB_RELEASE)
SET(BOOST_PYTHON_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_python${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_PYTHON_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_PYTHON_LIB_RELEASE)
SET(BOOST_REGEX_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_regex${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_REGEX_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_REGEX_LIB_RELEASE)
SET(BOOST_SERIALIZATION_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_serialization${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SERIALIZATION_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_LIB_RELEASE)
SET(BOOST_SERIALIZATION_HDF5_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_serialization_hdf5${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SERIALIZATION_HDF5_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_HDF5_LIB_RELEASE)
SET(BOOST_SIGNALS_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_signals${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SIGNALS_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SIGNALS_LIB_RELEASE)
SET(BOOST_SYSTEM_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_system${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SYSTEM_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SYSTEM_LIB_RELEASE)
SET(BOOST_TEST_EXEC_MONITOR_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_test_exec_monitor${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_TEST_EXEC_MONITOR_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_TEST_EXEC_MONITOR_LIB_RELEASE)
SET(BOOST_THREAD-MT_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_thread-mt${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_THREAD-MT_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_THREAD-MT_LIB_RELEASE)
SET(BOOST_THREAD_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_thread${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_THREAD_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_THREAD_LIB_RELEASE)
SET(BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_unit_test_framework${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE)
SET(BOOST_WSERIALIZATION_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_wserialization${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_WSERIALIZATION_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_WSERIALIZATION_LIB_RELEASE)


#-----------------------------------------------------------------------------
# Set Boost library paths according to current config.
#-----------------------------------------------------------------------------
IF(DEBUG)
  SET(BOOST_DATE_TIME_LIB "${BOOST_DATE_TIME_LIB_DEBUG}")
  SET(BOOST_FILESYSTEM_LIB "${BOOST_FILESYSTEM_LIB_DEBUG}")
  SET(BOOST_IOSTREAMS_LIB "${BOOST_IOSTREAMS_LIB_DEBUG}")
  SET(BOOST_PRG_EXEC_MONITOR_LIB "${BOOST_PRG_EXEC_MONITOR_LIB_DEBUG}")
  SET(BOOST_PROGRAM_OPTIONS_LIB "${BOOST_PROGRAM_OPTIONS_LIB_DEBUG}")
  SET(BOOST_PYTHON_LIB "${BOOST_PYTHON_LIB_DEBUG}")
  SET(BOOST_REGEX_LIB "${BOOST_REGEX_LIB_DEBUG}")
  SET(BOOST_SERIALIZATION_LIB "${BOOST_SERIALIZATION_LIB_DEBUG}")
  SET(BOOST_SERIALIZATION_HDF5_LIB "${BOOST_SERIALIZATION_HDF5_LIB_DEBUG}")
  SET(BOOST_SIGNALS_LIB "${BOOST_SIGNALS_LIB_DEBUG}")
  SET(BOOST_SYSTEM_LIB "${BOOST_SYSTEM_LIB_DEBUG}")
  SET(BOOST_TEST_EXEC_MONITOR_LIB "${BOOST_TEST_EXEC_MONITOR_LIB_DEBUG}")
  SET(BOOST_THREAD-MT_LIB "${BOOST_THREAD-MT_LIB_DEBUG}")
  SET(BOOST_THREAD_LIB "${BOOST_THREAD_LIB_DEBUG}")
  SET(BOOST_UNIT_TEST_FRAMEWORK_LIB "${BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG}")
  SET(BOOST_WSERIALIZATION_LIB "${BOOST_WSERIALIZATION_LIB_DEBUG}")
ELSE(DEBUG)
  SET(BOOST_DATE_TIME_LIB "${BOOST_DATE_TIME_LIB_RELEASE}")
  SET(BOOST_FILESYSTEM_LIB "${BOOST_FILESYSTEM_LIB_RELEASE}")
  SET(BOOST_IOSTREAMS_LIB "${BOOST_IOSTREAMS_LIB_RELEASE}")
  SET(BOOST_PRG_EXEC_MONITOR_LIB "${BOOST_PRG_EXEC_MONITOR_LIB_RELEASE}")
  SET(BOOST_PROGRAM_OPTIONS_LIB "${BOOST_PROGRAM_OPTIONS_LIB_RELEASE}")
  SET(BOOST_PYTHON_LIB "${BOOST_PYTHON_LIB_RELEASE}")
  SET(BOOST_REGEX_LIB "${BOOST_REGEX_LIB_RELEASE}")
  SET(BOOST_SERIALIZATION_LIB "${BOOST_SERIALIZATION_LIB_RELEASE}")
  SET(BOOST_SERIALIZATION_HDF5_LIB "${BOOST_SERIALIZATION_HDF5_LIB_RELEASE}")
  SET(BOOST_SIGNALS_LIB "${BOOST_SIGNALS_LIB_RELEASE}")
  SET(BOOST_SYSTEM_LIB "${BOOST_SYSTEM_LIB_RELEASE}")
  SET(BOOST_TEST_EXEC_MONITOR_LIB "${BOOST_TEST_EXEC_MONITOR_LIB_RELEASE}")
  SET(BOOST_THREAD-MT_LIB "${BOOST_THREAD-MT_LIB_RELEASE}")
  SET(BOOST_THREAD_LIB "${BOOST_THREAD_LIB_RELEASE}")
  SET(BOOST_UNIT_TEST_FRAMEWORK_LIB "${BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE}")
  SET(BOOST_WSERIALIZATION_LIB "${BOOST_WSERIALIZATION_LIB_RELEASE}")
ENDIF(DEBUG)

SET(Boost_FOUND 1)
