SET(BLAS_FOUND 0)

FIND_LIBRARY(BLAS_STANDARD_LIB
  NAMES blas
  PATHS ${FORTRAN_POSSIBLE_LIB_PATHS}
  )

IF(BLAS_STANDARD_LIB)
  SET(BLAS_FOUND 1)
ENDIF(BLAS_STANDARD_LIB)

MARK_AS_ADVANCED(BLAS_STANDARD_LIB)
