SET(USE_MESH_DEFAULT ON)
SET(USE_COMSOL_DEFAULT ON)
SET(USE_GIDPOST_DEFAULT ON)
SET(USE_GMV_DEFAULT ON)
SET(USE_GMSH_DEFAULT ON)
SET(USE_UNV_DEFAULT ON)
SET(USE_ENSIGHT_DEFAULT ON)
SET(USE_ANSYSRST_DEFAULT OFF)

SET(CFS_BLAS_LAPACK_DEFAULT "OPENBLAS")

# the established one, libxml2 is lighter
SET(XML_READER_DEFAULT "xerces")

SET(USE_PARDISO_DEFAULT ON)
SET(USE_ARPACK_DEFAULT ON)
SET(USE_PHIST_DEFAULT OFF)
SET(USE_ILUPACK_DEFAULT ON)
SET(USE_SUITESPARSE_DEFAULT ON)
SET(USE_LIS_DEFAULT ON)
SET(USE_SUPERLU_DEFAULT ON)

SET(USE_HDF5_DEFAULT ON)
SET(USE_CGNS_DEFAULT ON)
SET(USE_CCMIO_DEFAULT OFF) # proprietary, distribution not allowed
SET(USE_CFXIO_DEFAULT OFF) # proprietary, distribution not allowed
SET(USE_METIS_DEFAULT ON)
SET(USE_ZEROMQ_DEFAULT OFF)

SET(USE_SCPIP_DEFAULT OFF)  
SET(USE_SNOPT_DEFAULT OFF)  

SET(USE_IPOPT_DEFAULT OFF)
SET(USE_CGAL_DEFAULT ON)
SET(USE_LIBFBI_DEFAULT OFF)
SET(USE_FLANN_DEFAULT ON)
SET(USE_FFTW_DEFAULT OFF)

SET(USE_OPENMP_DEFAULT ON)
SET(DEBUG_DEFAULT OFF)
SET(PROFILING_DEFAULT OFF)

SET(CFSTOOL_DEFAULT OFF)
SET(CFSDAT_DEFAULT ON)
SET(BUILD_PARAVIEW_DEFAULT OFF)
SET(BUILD_HDFVIEW_DEFAULT OFF)

SET(USE_PYTHON_DEFAULT OFF)

SET(EXPLICIT_TEMPLATE_INSTANTIATION_DEFAULT ON)

SET(CFS_DEPS_CACHE_DIR_DEFAULT "${CFS_BINARY_DIR}/cfsdeps/cache")
SET(CFS_DEPS_PRECOMPILED_DEFAULT ON)

SET(INTEL_OPT_REPORT_DEFAULT OFF)

IF(CFS_BUILD_HOST MATCHES "altix")
  INCLUDE("cmake_modules/platform_defaults_altix.cmake")
ENDIF(CFS_BUILD_HOST MATCHES "altix")

IF(CFS_BUILD_HOST MATCHES "lse")
  INCLUDE("cmake_modules/platform_defaults_lse.cmake")
ENDIF(CFS_BUILD_HOST MATCHES "lse")

IF(CFS_BUILD_HOST MATCHES "woody")
  INCLUDE("cmake_modules/platform_defaults_woody.cmake")
ENDIF(CFS_BUILD_HOST MATCHES "woody")

SET(CMAKE_HOST_DEFAULTS_INC "${CFS_SOURCE_DIR}/cmake_modules/platform_defaults_${CFS_BUILD_HOST}.cmake") 
IF(EXISTS "${CMAKE_HOST_DEFAULTS_INC}")
  INCLUDE("${CMAKE_HOST_DEFAULTS_INC}")
ENDIF(EXISTS "${CMAKE_HOST_DEFAULTS_INC}")

SET(CMAKE_HOST_DEFAULTS_INC_HOME "$ENV{HOME}/.cfs_platform_defaults.cmake") 
IF(EXISTS "${CMAKE_HOST_DEFAULTS_INC_HOME}")
  INCLUDE("${CMAKE_HOST_DEFAULTS_INC_HOME}")
ENDIF(EXISTS "${CMAKE_HOST_DEFAULTS_INC_HOME}")

SET(CMAKE_HOST_DEFAULTS_INC_HOME_HOST "$ENV{HOME}/.cfs_platform_defaults_${CFS_BUILD_HOST}.cmake") 
IF(EXISTS "${CMAKE_HOST_DEFAULTS_INC_HOME_HOST}")
  INCLUDE("${CMAKE_HOST_DEFAULTS_INC_HOME_HOST}")
ENDIF(EXISTS "${CMAKE_HOST_DEFAULTS_INC_HOME_HOST}")
