SET(USE_GIDPOST_DEFAULT OFF)
SET(USE_GMV_DEFAULT ON)
SET(USE_GMSH_DEFAULT ON)
SET(USE_ENSIGHT_DEFAULT OFF)

SET(USE_BLAS_LAPACK_DEFAULT "MKL")
SET(CFS_PARDISO_DEFAULT "MKL")

# the established one, libxml2 is lighter
SET(USE_XML_READER_DEFAULT "xerces")

SET(USE_PARDISO_DEFAULT ON)
SET(USE_ARPACK_DEFAULT ON)
SET(USE_PHIST_CG_DEFAULT OFF)
SET(USE_PHIST_EV_DEFAULT OFF)
SET(BUILD_GHOST_DEFAULT OFF)
SET(USE_FEAST_DEFAULT ON)
SET(USE_ILUPACK_DEFAULT OFF)
SET(USE_SUITESPARSE_DEFAULT ON)
SET(USE_LIS_DEFAULT ON)
SET(USE_SUPERLU_DEFAULT OFF)

SET(BUILD_QUADEIGENSOLVER_DEFAULT ON)

SET(USE_CGNS_DEFAULT OFF)
SET(USE_METIS_DEFAULT ON)

SET(USE_SCPIP_DEFAULT OFF)  
SET(USE_SNOPT_DEFAULT OFF)

SET(USE_IPOPT_DEFAULT OFF)
SET(USE_CGAL_DEFAULT OFF)
SET(USE_LIBFBI_DEFAULT OFF)
SET(USE_FLANN_DEFAULT ON)
SET(USE_FFTW_DEFAULT OFF)

SET(USE_OPENMP_DEFAULT ON)
SET(DEBUG_DEFAULT OFF)

SET(BUILD_CFSTOOL_DEFAULT ON)
SET(BUILD_CFSDAT_DEFAULT OFF)
SET(BUILD_UNIT_TESTS_DEFAULT ON)
SET(BUILD_HDFVIEW_DEFAULT OFF)
set(TESTSUITE_DIR_DEFAULT "${CFS_SOURCE_DIR}/Testsuite")

SET(CFS_DEPS_CACHE_DIR_DEFAULT "${CFS_BINARY_DIR}/cfsdeps/cache")
SET(CFS_DEPS_PRECOMPILED_DEFAULT OFF)

SET(CMAKE_HOST_DEFAULTS_INC "${CFS_SOURCE_DIR}/cmake_modules/platform_defaults_${CFS_BUILD_HOST}.cmake") 
IF(EXISTS "${CMAKE_HOST_DEFAULTS_INC}")
  INCLUDE("${CMAKE_HOST_DEFAULTS_INC}")
ENDIF(EXISTS "${CMAKE_HOST_DEFAULTS_INC}")

SET(CMAKE_HOST_DEFAULTS_INC_HOME "$ENV{HOME}/.cfs_platform_defaults.cmake") 
IF(EXISTS "${CMAKE_HOST_DEFAULTS_INC_HOME}")
  INCLUDE("${CMAKE_HOST_DEFAULTS_INC_HOME}")
ENDIF(EXISTS "${CMAKE_HOST_DEFAULTS_INC_HOME}")

SET(CMAKE_HOST_DEFAULTS_INC_HOME_HOST "$ENV{HOME}/.cfs_platform_defaults_${CFS_BUILD_HOST}.cmake") 
IF(EXISTS "${CMAKE_HOST_DEFAULTS_INC_HOME_HOST}")
  INCLUDE("${CMAKE_HOST_DEFAULTS_INC_HOME_HOST}")
ENDIF(EXISTS "${CMAKE_HOST_DEFAULTS_INC_HOME_HOST}")
