SET(USE_TCL_DEFAULT ON)
SET(USE_PYTHON_DEFAULT OFF)
SET(USE_MESH_DEFAULT ON)
SET(USE_GIDPOST_DEFAULT ON)
SET(USE_GMV_DEFAULT ON)
SET(USE_GMV_INPUT_DEFAULT OFF)
SET(USE_GMV_OUTPUT_DEFAULT ON)
SET(USE_UNV_DEFAULT ON)
SET(USE_ANSYSRST_DEFAULT OFF)
SET(USE_MPCCI_DEFAULT OFF)

SET(CFS_BLAS_LAPACK_DEFAULT "NETLIB")
SET(CFS_PARDISO_DEFAULT "SCHENK")

SET(USE_PARDISO_DEFAULT ON)
SET(USE_ARPACK_DEFAULT ON)
SET(USE_ILUPACK_DEFAULT OFF)

SET(USE_HDF5_DEFAULT ON)
SET(USE_XERCES_DEFAULT ON)
SET(USE_METIS_DEFAULT ON)

SET(USE_SCPIP_DEFAULT OFF)  

SET(USE_IPOPT_DEFAULT OFF)
SET(USE_INTERPOLATION_DEFAULT OFF)
SET(USE_ADAPTGRID_DEFAULT OFF)

SET(USE_OPENMP_DEFAULT OFF)
SET(DEBUG_DEFAULT ON)
SET(PROFILING_DEFAULT OFF)

SET(CFSTOOL_DEFAULT OFF)
SET(CPLREADER_DEFAULT OFF)
SET(BUILD_PARAVIEW_DEFAULT OFF)

SET(EXPLICIT_TEMPLATE_INSTANTIATION_DEFAULT ON)

SET(CFS_DEPS_ROOT_DEFAULT "/opt/CFSDEPS")

IF(CFS_BUILD_HOST MATCHES "altix")
  INCLUDE("cmake_modules/platform_defaults_altix.cmake")
ENDIF(CFS_BUILD_HOST MATCHES "altix")

IF(CFS_BUILD_HOST MATCHES "lse")
  INCLUDE("cmake_modules/platform_defaults_lse.cmake")
ENDIF(CFS_BUILD_HOST MATCHES "lse")

IF(CFS_BUILD_HOST MATCHES "mac")
  INCLUDE("cmake_modules/platform_defaults_mac.cmake")
ENDIF(CFS_BUILD_HOST MATCHES "mac")

IF(CFS_BUILD_HOST MATCHES "rom")
  INCLUDE("cmake_modules/platform_defaults_rom.cmake")
ENDIF(CFS_BUILD_HOST MATCHES "rom")

IF(CFS_BUILD_HOST MATCHES "woody")
  INCLUDE("cmake_modules/platform_defaults_woody.cmake")
ENDIF(CFS_BUILD_HOST MATCHES "woody")
