# This file is used to define the CI pipeline for GitLab
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - configure
  - build
  - test

# cache the build files see https://docs.gitlab.com/ee/ci/caching/index.html
# use the ref-name, e.g. `master` as key -> same for sucessive builds
cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - build

# only include a config step for the start
configure:
  stage: configure
  script:
    - pwd # show where we are
    - ls # list source
    - mkdir -p build # make build dir
    - cd build
    - rm -f CMakeCache.txt # clear any old chache
    - cmake ..
    - cmake .
  # provides artifacts in gitlab (can be downloaded)
  artifacts:
    paths:
      - build/CMakeCache.txt
    expire_in: 1 week

build:
  stage: build
  script:
    - cd build
    - make
  dependencies:
    - configure

test:
  stage: test
  script:
    - cd build
    - ctest -S run_testsuite.ctest -V
  dependencies:
    - build
