# This file is used to define the CI pipeline for GitLab
# https://docs.gitlab.com/ee/ci/yaml
#
# Syntax tipps:
# * check on https://cfs-dev.mdmt.tuwien.ac.at/ci/lint
# * do not use a command `echo "warning: the : is not allowed in a string"`

# include common stuff to make this file shorter
include:
  - local: .gitlab/ci/linux.yml
  - local: .gitlab/ci/windows.yml
  # this switches the CACHE_POLICY by including the file with a variable definition (and an info job)
  # see https://docs.gitlab.com/ee/ci/yaml/includes.html#merge-method-for-include
  # and https://docs.gitlab.com/ee/ci/yaml/includes.html#use-nested-includes-with-duplicate-include-entries
  - local: .gitlab/ci/cache-default.yml
  # since it is included __after__ the above cache-default, it wins (and variables are overwritten)
  - local: .gitlab/ci/cache-policy-push.yml
    rules:
      - if: $CLEAR_CACHE != null
      - if: $CI_COMMIT_MESSAGE =~ /clear-cache/
      - if: $CI_MERGE_REQUEST_LABELS =~ /clear-cache/
      - if: $CACHE_POLICY == "push" # effectively just add the info job


# https://docs.gitlab.com/ee/ci/variables/#variables-expressions
variables:
  GIT_STRATEGY: fetch # this is faster than clone and should re-use a workspace
  GIT_SUBMODULE_STRATEGY: recursive # by default clone the testsuite, switch to 'none' to save time if not required
  CDASH_TRACK: Gitlab # will be overwritten by nightly schedule
  CTEST_PROGRESS_OUTPUT: "ON" # makes the ctest output shorter, see https://cmake.org/cmake/help/latest/envvar/CTEST_PROGRESS_OUTPUT.html#envvar:CTEST_PROGRESS_OUTPUT
  # build options for the maximal config
  MAX_CONFIG_OPTIONS: " -DUSE_EMBEDDED_PYTHON=ON -DUSE_CGAL=ON -DUSE_SUITESPARSE=ON -DUSE_EIGEN=ON -DUSE_SGP=ON"
  MUSL_CONFIG_OPTIONS: "-DCMAKE_EXE_LINKER_FLAGS=-static -DMKL_THREADING=gnu_thread" # link statically
  # Select which tag of the build containers we use. Update the tag when there are breaking changes in the conainers!
  # This way pipelines for old CFS-commits can still run on old container versions.
  # see https://gitlab.com/openCFS/build-environment/-/tags
  # or https://hub.docker.com/u/opencfs for the available images
  BUILD_ENVIRONMENT_TAG: 2025.01
  BUILD_ENVIRONMENT_REGISTRY: "opencfs" # defaults to using docker-hub, change to "registry.gitlab.com/opencfs/build-environment" to use the one on GitLab
  # configure ccache, see https://ccache.dev/manual/latest.html
  CCACHE_BASEDIR: $CI_PROJECT_DIR/build
  CCACHE_DIR: $CI_PROJECT_DIR/ccache
  CCACHE_SLOPPINESS: "file_macro,locale,time_macros"
  CCACHE_STATSLOG: $CI_PROJECT_DIR/build/ccache.log
  CCACHE_MAXSIZE: 200M
  # define the testsuite branch to test against - altered if there are changes
  TESTSUITE_BRANCH: master

# stages in the pipeline run in succession
stages:
  - check
  - platform
  - cfsdeps
  - build
  - test # we may have several test configs for one build
  - test_extra # here we test everything that is not required to pass (broken and too unstable stuff)
  - docs
  - deploy

# determine when pipelines are created
# https://docs.gitlab.com/ee/ci/yaml/#workflowrules
# https://docs.gitlab.com/ee/ci/jobs/job_control.html#common-if-clauses-for-rules
# we create pipelines for merge requests, schedules, and the web-ui
# se set the variable CFS_PIPELINE_TYPE to indicate which jobs should be run in which way
#  - test : run a maximum amount of tests automatically
#  - manual : create all tests but set them to manual (default)
#  - release : create jobs for releases
#  - nightly : regular tests for the CDash dashboard
workflow:
  name: "$CFS_PIPELINE_NAME"
  rules:
  # put the most specific rules first - we have a release tag (in the correct format)
  # tags with 20* should be protected in the GitLab repo settings
  - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /20[0-9][0-9][A-Z]/
    variables:
      CFS_PIPELINE_TYPE: "release"
      CFS_PIPELINE_NAME: "Release for tag $CI_COMMIT_TAG"
  # We need pipelines to deploy stuff -> set the 'release' type
  # for tags on the default branch we create releases
  # this will run for accepted merge requests
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE !~ /schedule/
    variables:
      CFS_PIPELINE_TYPE: "release"
      CFS_PIPELINE_NAME: "Release for ${CI_DEFAULT_BRANCH}: $CI_COMMIT_TITLE"
  # We want pipelines to 'test' for merge requests
  # set to manual if the merge request title start with Draft:
  - if: $CI_MERGE_REQUEST_TITLE =~ /^Draft:.*/
    variables:
      CFS_PIPELINE_TYPE: "manual"
      CFS_PIPELINE_NAME: "Manual for MR${CI_MERGE_REQUEST_IID}: $CI_COMMIT_TITLE"
  # run automatically for not-Draft merge requests
  - if: $CI_MERGE_REQUEST_IID
    variables:
      CFS_PIPELINE_TYPE: "test"
      CFS_PIPELINE_NAME: "Test for MR${CI_MERGE_REQUEST_IID}: $CI_COMMIT_TITLE"
  # do not run branch pipelines if a merge request is open (avoid duplicates)
  - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE !~ /web/ && $CI_PIPELINE_SOURCE !~ /schedule/
    when: never
  # run for schedules - this emulates a commit on a branch
  - if: $CI_PIPELINE_SOURCE == "schedule"
    variables:
      CFS_PIPELINE_TYPE: "nightly"
      CFS_PIPELINE_NAME: "Scheduled for branch ${CI_COMMIT_BRANCH}: $CI_COMMIT_TITLE"
  # create a manual pipeline via the web interface (for any branch) by setting the variable CFS_PIPELINE_TYPE=manual
  - if: $CI_PIPELINE_SOURCE == "web" && $CFS_PIPELINE_TYPE == "manual"
    variables:
      CFS_PIPELINE_NAME: "Manual for branch ${CI_COMMIT_BRANCH}: $CI_COMMIT_TITLE"
  # automatically run if branch name starts or ends with test or is scheduled
  - if: $CI_COMMIT_BRANCH =~ /^test.*$/ || $CI_COMMIT_BRANCH =~ /^.*test$/ || $CI_PIPELINE_SOURCE == "web"
    variables:
      CFS_PIPELINE_TYPE: "test"
      CFS_PIPELINE_NAME: "Test for branch ${CI_COMMIT_BRANCH}: $CI_COMMIT_TITLE"
  # when no rule triggers, no pipeline is created

#################################################
# Check STAGE
#################################################
# the jobs in this stage are purely informational at the moment
# some only get created in certain cases (pipeline-changes) and then fail 
# to generate a warning (they are allowed to fail)

.check:
  stage: check
  tags:
    - saas-linux-small-amd64
  # switch off cloning any code
  variables:
    GIT_SUBMODULE_STRATEGY: none
    GIT_STRATEGY: none
  cache: {} # disable

# Check the revision of the testsuite submodule
.Testsuite_changes: &Testsuite_changes
      changes:
        paths:
          - Testsuite
        compare_to: 'refs/heads/master'

testsuite-revision:
  extends: .check
  image:
    name: alpine/git:2.47.1
    entrypoint: ["/bin/sh","-c"]
  variables:
    # we clone to make sure we have everything (including current names of the SHAs)
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: none
  rules:
    # only create the job if there are changes in the Testsuite submodule
    - if: $CFS_PIPELINE_TYPE == "test"
    - if: $CFS_PIPELINE_TYPE == "nightly"
    - if: $CFS_PIPELINE_TYPE == "manual"
      when: manual
      #<<: *Testsuite_changes
      #when: on_success
      #allow_failure: true # only for info
    #- if: $CFS_PIPELINE_TYPE != /test/
    #  <<: *Testsuite_changes
    #  when: manual
    #  allow_failure: true # only for info
  before_script:
    - git --no-pager log -1 --pretty=tformat:'%h %D'
    - echo "The Testsuite in $CI_COMMIT_REF_NAME has changes compared to master!"
  script:
    # obtain the testsuite reference
    - git submodule status # debug
    # save the Testsuite submodule SHA
    - echo "TESTSUITE_SHA=$( git submodule status |grep Testsuite | sed 's/[\+-]\([0-9a-z]\+\).\+/\1/g' )" | tee -a dot.env
  after_script:
    - cat dot.env | ls # debug
  artifacts:
    reports:
      dotenv: dot.env

# this is a trigger job to check the testsuite revision
trigger-testsuite:
  stage: test
  rules:
    - if: $CFS_PIPELINE_TYPE == "test" || $CFS_PIPELINE_TYPE == "nightly" # $CI_MERGE_REQUEST_IID # this is a merge request & there are changes in the testsuite
      <<: *Testsuite_changes
      variables:
        TESTSUITE_BRANCH: $CI_COMMIT_REF_NAME
    - if: $CFS_PIPELINE_TYPE == "manual"
      <<: *Testsuite_changes
      variables:
        TESTSUITE_BRANCH: $CI_COMMIT_REF_NAME
      when: manual
    # there are no changes, take the default value for the TESTSUITE_BRANCH
    - if: $CFS_PIPELINE_TYPE == "test" || $CFS_PIPELINE_TYPE == "nightly"
    - if: $CFS_PIPELINE_TYPE == "manual"
      when: manual
  trigger:
    project: $CI_PROJECT_NAMESPACE/Testsuite
    branch: $TESTSUITE_BRANCH #same as the parent pipeline
  needs:
    - job: testsuite-revision

# the testsuite pipeline should have a check job that needs artifacts from this pipeline. The test job must compare the testsuite SHA

# check the links in markdown files using https://github.com/tcort/markdown-link-check
markdown-link-check:
  extends: .check
  image: 
    name: $BUILD_ENVIRONMENT_REGISTRY/markdown-link-check:$BUILD_ENVIRONMENT_TAG
    entrypoint: ["/bin/sh","-c"]
  variables:
    GIT_STRATEGY: fetch
  rules:
    - if: $CFS_PIPELINE_TYPE == "test"
      allow_failure: true # do not prevent merge
    - if: $CFS_PIPELINE_TYPE == "manual"
      when: manual
      allow_failure: true # do not prevent merge
  script:
    - markdown-link-check README.md
    - markdown-link-check CONTRIBUTING.md
    # check all in source, share/doc/developer/build-dependencies and .gitlab
    - find source -name '*.md' -print0 | xargs -0 -n1 markdown-link-check --config markdown-link-check-config.json
    - find share/doc/developer/build-dependencies -name '*.md' -print0 | xargs -0 -n1 markdown-link-check --config markdown-link-check-config.json
    - find .gitlab -name '*.md' -print0 | xargs -0 -n1 markdown-link-check --config markdown-link-check-config.json

# this job is intended as a warning if the pipeline has changed
# it is running only if there are changes, and will always fail if there are some
.pipeline_changes: &pipeline_changes
      changes:
        paths:
        - .gitlab-ci.yml
        - .gitlab/ci/*.yml
        compare_to: 'refs/heads/master'
pipeline-changes:
  extends: .check
  image:
    name: alpine/git:2.47.1
    entrypoint: ["/bin/sh","-c"]
  # switch off cloning the Testsuite submodule
  variables:
    GIT_STRATEGY: none
  rules:
    # only run the job for merge requests if there are changes in the pipeline definition
    - if: $CFS_PIPELINE_TYPE == "test"
      <<: *pipeline_changes
      allow_failure: true # only for info, do not prevent merge
    - if: $CFS_PIPELINE_TYPE == "manual"
      <<: *pipeline_changes
      when: manual
      allow_failure: true # only for info, do not prevent merge
  before_script:
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME 
    - git diff remotes/origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME -- .gitlab-ci.yml || git diff HEAD~1 -- .gitlab-ci.yml
  script:
    - /the/pipeline/has/changed

runner-debug:
  extends: .check
  image: alpine
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CFS_PIPELINE_TYPE == "manual" || $CFS_PIPELINE_TYPE == "test"
      when: manual
      allow_failure: true # only for info, do not prevent merge
  script:
    - echo "$CFS_PIPELINE_NAME"
    - echo "$CFS_PIPELINE_TYPE"
    - echo "$CACHE_POLICY:$INSTALL_POLICY"
    - echo $CI_SERVER_HOST
    - echo $CI_SERVER
    - echo $GITLAB_USER_ID
    - echo $GITLAB_USER_LOGIN
    - echo $CI_RUNNER_ID
    - echo $CI_RUNNER_SHORT_TOKEN
    - echo $CI_PROJECT_NAMESPACE
    - echo $CI_PROJECT_DIR
    - echo $CI_PIPELINE_URL
    - echo $CI_PAGES_URL
    - echo $CI_MERGE_REQUEST_IID
    - echo $CI_JOB_URL
    - echo $CI_COMMIT_BRANCH
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_PIPELINE_SOURCE
    - echo $CI_PIPELINE_IID
    - echo $CI_JOB_IMAGE
    - echo $CI_JOB_NAME_SLUG
    - echo $CI_MERGE_REQUEST_LABELS

# this job is created when there is a skip-build in the commit message
skip-build:
  extends: .check
  image: alpine
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /skip-build/ && $CFS_PIPELINE_TYPE == "test"
      allow_failure: true # only for info, do not prevent merge
    - if: $CI_COMMIT_MESSAGE =~ /skip-build/ && $CFS_PIPELINE_TYPE == "manual"
      when: manual
      allow_failure: true # only for info, do not prevent merge
  script:
    - /commit/message/contained/skip-build

.require-rebuild-changes: &require-rebuild-changes
  # changes that require the c++ builds to run
  # works like only/except changes
  # for examples, see https://docs.gitlab.com/ee/ci/yaml/#onlychanges--exceptchanges
  changes:
    - "**/CMakeLists.txt"
    - "**/*.cmake"
    - "**/*.cmake.in"
    - source/**/*.{hh,cc,h,c}
    - Testsuite

cpp-code-changes:
  extends: .check
  image: alpine
  tags:
    - saas-linux-small-amd64
  rules:
    - if: $CFS_PIPELINE_TYPE == "test"
      <<: *require-rebuild-changes
      allow_failure: true # only for info, do not prevent merge
    - if: $CFS_PIPELINE_TYPE == "manual"
      <<: *require-rebuild-changes
      when: manual
      allow_failure: true # only for info, do not prevent merge
  script:
    - /merge/request/ and /the/code/has/changed

#######################################################################
# PLATFORM STAGE
#######################################################################
# here we test the build dependency installation instructions (from share/doc/developer/build-dependencies)
# and the build instructions (from README.md)
# all jobs in the stage have no needs, and are manual (one can start them by the play-button)

# Template for the platform builds
.platform:
  stage: platform
  tags:
    - saas-linux-small-amd64
  image:
    name: $IMAGE:$TAG
  after_script: []
  rules:
    # set variable PLATFORM to activate the job for test or nightly pipelines
    - if: $PLATFORM  && ( $CFS_PIPELINE_TYPE == "test" || $CFS_PIPELINE_TYPE == "nightly" ) 
      when: on_success
    - if: $CFS_PIPELINE_TYPE == "test" || $CFS_PIPELINE_TYPE == "manual"
      when: manual
      allow_failure: true # we need this to not stop the pipeline if the manual job is not triggered
  # disable cache
  cache: {}
  # switch off cloning the Testsuite submodule
  variables:
    GIT_SUBMODULE_STRATEGY: none
  # install dependencies in the docker image
  before_script:
    # ensure build does not exist
    - rm -rf build
    # debug output
    - echo "IMAGE=$IMAGE"
    - echo "TAG=$TAG"
    - echo "PLATFORM=$PLATFORM"
    - cat /etc/*release
    # run the setup instructions for this IMAGE
    - ./share/scripts/mdsh --eval "share/doc/developer/build-dependencies/${IMAGE}_${TAG}.md" | bash -e -x
  # run the README which contains build instructions
  script:
    - ./share/scripts/mdsh --eval 'README.md' | bash -l -e -x
  # store possible error logs as artifacts for debugging
  artifacts:     
    paths:       
      - build/**/*.log
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"     
    expire_in: 6 hours
    when: on_failure
  # run this job immediately, since it has not needs
  needs: []

# add all platforms we can build on.
# the IMAGE variable should be set according to the 'image' (docker runner option) and requires
# a correctly named instruction in share/doc/developer/build-dependencies

# fedora releases, see https://hub.docker.com/_/fedora
# latest stable release
fedora:latest:
  extends: .platform
  variables:
    IMAGE: "fedora"
    TAG: "latest"
  image: # workaround due to 'shell not found'-bug: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27614
    entrypoint: [ '/bin/sh', '-c' ]

# latest development release
fedora:rawhide:
  extends: .platform
  variables:
    IMAGE: "fedora"
    TAG: "rawhide"
  image: # workaround due to 'shell not found'-bug: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27614
    entrypoint: [ '/bin/sh', '-c' ]

# ubuntu releases, see https://hub.docker.com/_/ubuntu
# latest LTS release 
ubuntu:latest:
  extends: .platform
  variables:
    IMAGE: "ubuntu"
    TAG: "latest"

# the latest stable release, regardless of LTS status
ubuntu:rolling:
  extends: .platform
  variables:
    IMAGE: "ubuntu"
    TAG: "rolling"
  image: # workaround due to bug: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27614
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ] 

# older LTS releases ...
ubuntu:20.04:
  extends: .platform
  variables:
    IMAGE: "ubuntu"
    TAG: "20.04"

# debian releases, see https://hub.docker.com/_/debian
# latest stable release (dynamic image name)
debian:latest:
  extends: .platform
  variables:
    IMAGE: "debian"
    TAG: "latest"

# older releases ... https://www.debian.org/releases/
debian:11: # (bullseye)
  extends: .platform
  variables:
    IMAGE: "debian"
    TAG: "11"

# RHEL derivatives
# rockylinux 8, see https://hub.docker.com/_/rockylinux
rhel:8:
  extends: .platform
  variables:
    IMAGE: "rockylinux"
    TAG: "8"

# rockylinux 9, see https://hub.docker.com/_/rockylinux
rhel:9:
  extends: .platform
  variables:
    IMAGE: "rockylinux"
    TAG: "9"

#######################################################################
# cfsdeps stage
#######################################################################
# here we build the cfsdeps and store them and
# store the precompiled ones as artifacts
# we need to precompile for all GCC versions independently

.before-script-build:
  script:
    # git repo info
    - export DEBUG_SECTION_TITLE='git repository info'
    - !reference [.linux-debug-start_collapsed, script]
    - git rev-list -n 1 HEAD -- || echo "git failed, should return ${CI_COMMIT_SHA}" # debug for command run by CTestUpdate
    # make sure the Testsuite submodule is OK
    - git status # debug
    - git diff -- Testsuite # debug
    - git diff --exit-code -- Testsuite || (mv Testsuite Testsuite_ignore && git checkout Testsuite)
    - git status # debug
    - !reference [.linux-debug-end, script]
    # report disk space
    - export DEBUG_SECTION_TITLE='disk space info'
    - !reference [.linux-debug-start_collapsed, script]
    - df -h # disk space debug
    - du -h --max-depth=1 . # repos space debug
    - ls -l build/cfsdeps || ls # debug
    - !reference [.linux-debug-end, script]
    # setup build directory
    - mkdir -p build # create if it does not exist
    - cd build # descend in build
    - rm -f CMakeCache.txt # clear old cache
    # show the contents of the caches
    - !reference [.linux_list_cache, script]
    # analyze ccache
    - export DEBUG_SECTION_TITLE='ccache setup and debug info'
    - !reference [.linux-debug-start_collapsed, script]
    - ls $CCACHE_DIR || true #debug
    - ccache --verbose --show-stats || ccache -s || true
    - ccache --verbose --zero-stats || ccache -z || true
    - $CMAKE_CXX_COMPILER_LAUNCHER --version || true
    - !reference [.linux-debug-end, script]

# if testsuite_ignore is there, restore it
.restore_Testsuite_ignore: &restore_Testsuite_ignore
  - (ls Testsuite_ignore && mv -T Testsuite_ignore Testsuite) || ls Testsuite
  - git status # debug

# define when csdeps need to be rebuilt based on changes
.cfsdeps-rebuild-changes: &cfsdeps-rebuild-changes
  # changes that require the cfsdeps to be re-built
  changes:
    paths:
      - "cfsdeps/**/*"
      - "cmake_modules/FindCFSDEPS.cmake"
    compare_to: 'refs/heads/master'

.build_rules: &build_rules
  rules:
    # there should be changes (in cfsdeps or cfs) but a user has skipped the build
    - if: $CFS_PIPELINE_TYPE == "test" && $CI_COMMIT_MESSAGE =~ /skip-build/
      <<: *cfsdeps-rebuild-changes # cfsdeps have changed -> keep them as needs
      when: manual
    - if: $CFS_PIPELINE_TYPE == "test" && $CI_COMMIT_MESSAGE =~ /skip-build/
      <<: *require-rebuild-changes
      when: manual
      needs: [] # allow to be triggered manually without cfsdeps
    # builds & tests are required
    - if: $CFS_PIPELINE_TYPE == "test"
      <<: *require-rebuild-changes
    # all manual
    - if: $CFS_PIPELINE_TYPE == "manual"
      <<: *cfsdeps-rebuild-changes # cfsdeps have changed -> keep them as needs
      when: manual
    - if: $CFS_PIPELINE_TYPE == "manual"
      <<: *require-rebuild-changes
      when: manual
      needs: [] # allow to be triggered manually without cfsdeps
    # If there are no c++ changes, place manual jobs & allow failure to not block the pipeline
    - if: $CFS_PIPELINE_TYPE == "manual" || $CFS_PIPELINE_TYPE == "test" 
      when: manual
      allow_failure: true
      needs: [] # allow to be triggered manually without cfsdeps
    # nightly always builds
    - if: $CFS_PIPELINE_TYPE == "nightly"
    # otherwise no builds

.release_build_rules: &release_build_rules
  rules:
    - if: $CFS_PIPELINE_TYPE == "release"
    - !reference [.build_rules, rules]

.cfsdeps: &cfsdeps
  stage: cfsdeps
  # the IMAGE variable needs to be defined in the job defintion
  image: $BUILD_ENVIRONMENT_REGISTRY/$IMAGE:$BUILD_ENVIRONMENT_TAG
  tags:
    - saas-linux-small-amd64
  # switch off cloning the Testsuite submodule
  variables: &cfsdeps-variables
    GIT_SUBMODULE_STRATEGY: none
    CI_PIPELINE_NO_TESTSUITE: "ON" # we define it to ignore the inclusion of TESTSUITE_DIR
  rules:
    # include the cfsdeps stage even if there are no changes by setting the variable BUILD_CFSDEPS or merge request label "build-cfsdeps"
    # manual
    - if: $BUILD_CFSDEPS == "manual" || ( $BUILD_CFSDEPS && $CFS_PIPELINE_TYPE == "manual" )
      when: manual
    - if: $CI_MERGE_REQUEST_LABELS =~ /build-cfsdeps/ && $CFS_PIPELINE_TYPE == "manual"
      when: manual
    # automatic
    - if: $BUILD_CFSDEPS 
    - if: $CI_MERGE_REQUEST_LABELS =~ /build-cfsdeps/
    # only add cfsdeps jobs if there are changes
    # ... in a "test" pipeline
    - if: $CFS_PIPELINE_TYPE == "test"
      <<: *cfsdeps-rebuild-changes
    # ... in a 'manual' pipeline
    - if: $CFS_PIPELINE_TYPE == "manual"
      <<: *cfsdeps-rebuild-changes
      when: manual
  cache: !reference [.cache_linux_cfsdeps-job, cache]
  before_script:
    - pwd # debug
    - !reference [.before-script-build, script]
  script:
    - cmake $CFS_CONFIG_OPTIONS ..
    - cmake .
    - cmake --build . --target cfsdeps --parallel 1
  after_script:
    # show the contents of the caches
    - !reference [.linux_list_cache, script]
    - *restore_Testsuite_ignore
  artifacts:
    paths:
      - build/cfsdeps/cache/precompiled/*.zip
      - build/cfsdeps/cache/sources/
    name: "${CI_JOB_NAME_SLUG}__${CI_COMMIT_REF_SLUG}"
    expire_in: 12 hours
  needs: []

cfsdeps:gcc7:
  extends: .cfsdeps
  variables:
    <<: *cfsdeps-variables
    IMAGE: centos7-gcc7

# intel assumes that CC,CXX,FC are set (e.g. in bash_profile of the Dockerfile)
cfsdeps:intel:
  extends: .cfsdeps
  variables:
    <<: *cfsdeps-variables
    IMAGE: rhel8-intel

cfsdeps:gcc14-musl:
  extends: .cfsdeps
  variables:
    <<: *cfsdeps-variables
    CFS_CONFIG_OPTIONS: $MUSL_CONFIG_OPTIONS # add the MUSL-options
    IMAGE: alpine

cfsdeps:MSVC2022-Ifort2021:
  extends: .windows-shared-build
  stage: cfsdeps
  rules:
    - !reference [.cfsdeps,rules]
  variables:
    BUILD_COMMAND: "cmake --build . --target cfsdeps"
  after_script:
    # just debug
    - !reference [.powershell_debug_dir_listing, script]
  artifacts:
    when: on_success
    paths:
      - build/cfsdeps/cache/precompiled/*.zip
      - build/cfsdeps/cache/sources/
    name: "${CI_JOB_NAME_SLUG}__${CI_COMMIT_REF_SLUG}"
    expire_in: 12 hours
  # Set optional needs for install job (only available for clear-cache case)
  needs:
    - job: install:MSVC2022-Ifort2021
      optional: true

#######################################################################
# BUILD STAGE definitions
#######################################################################
# Here we define the build jobs, if one fails we do not need to test

# set environment for URL on CDash
# see https://docs.gitlab.com/ee/ci/environments/index.html#set-dynamic-environment-urls-after-a-job-finishes
.save_cdash_buildid:
  script:
  - export DEBUG_SECTION_TITLE='Save CDash build ID'
  - !reference [.linux-debug-start_collapsed, script]
  - ls -R Testing # debug
  - cat Testing/*/Done.xml # debug
  - grep -Po '<buildId>\K.*?(?=<.*?>)' Testing/*/Done.xml # debug
  # get build ID from file
  - BUILD_ID=$( grep -Po '<buildId>\K.*?(?=<.*?>)' Testing/*/Done.xml )
  # save links as variables
  - CDASH_BUILD_URL=$( echo "http://movm.mi.uni-erlangen.de/cdash/buildSummary.php?buildid=${BUILD_ID}" )
  - CDASH_TEST_URL=$( echo "http://movm.mi.uni-erlangen.de/cdash/viewTest.php?buildid=${BUILD_ID}")
  # output to annotations
  # https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportsannotations
  - echo '{"CDash":[{"external_link":{"label":"CDash Build","url":"'$CDASH_BUILD_URL'"}},{"external_link":{"label":"CDash Tests","url":"'$CDASH_TEST_URL'"}}]}' > annotations.json
  - !reference [.linux-debug-end, script]
  # output to job log
  - echo "Build on CDash - $CDASH_BUILD_URL"
  - echo "Tests on CDash - $CDASH_TEST_URL"

.default_build_job: &default_build_job
  stage: build
  image: $BUILD_ENVIRONMENT_REGISTRY/$IMAGE:$BUILD_ENVIRONMENT_TAG
  tags:
    - saas-linux-small-amd64
  variables:
    GIT_SUBMODULE_STRATEGY: none # we do not need the testsuite for building
    CI_PIPELINE_NO_TESTSUITE: "ON" # we define it to ignore the inclusion of TESTSUITE_DIR
  cache: !reference [.cache_linux_build-job, cache ]
  script:
    # configure once to have dashboard ready
    - echo "$CFS_CONFIG_OPTIONS"
    - cmake -DBUILDNAME="$CI_COMMIT_REF_SLUG / $BUILD_NAME" -DCTEST_UPDATE_VERSION_ONLY:BOOL=ON -DCTEST_GIT_INIT_SUBMODULES:BOOL=OFF -DBUILD_TESTING=ON ${CFS_CONFIG_OPTIONS} ..
    # start cdash dashboard
    - ctest -D ExperimentalStart --track $CDASH_TRACK -V
    # update to current revision (gives link on CDash)
    - ctest -D ExperimentalUpdate --track $CDASH_TRACK -V
    # configure
    - ctest -D ExperimentalConfigure --track $CDASH_TRACK -V
    - ctest --quiet -O submit.log -D ExperimentalSubmit --track $CDASH_TRACK || cat submit.log # intermittent submit to get live CDash results
    # build
    - ctest -D ExperimentalBuild --track $CDASH_TRACK -V |& tee build.log
    - ctest --quiet -O submit.log -D ExperimentalSubmit --track $CDASH_TRACK  || cat submit.log
    # install test to create arifacts (first delete stuff to make space for packing)
    - export DEBUG_SECTION_TITLE='Delete stuff to make space for packing'
    - !reference [.linux-debug-start_collapsed, script]
    - df -h # debug
    - du -h --max-depth=1 . # debug
    - find cfsdeps/* -type d -not -wholename "*/cache" -not -wholename "*/cache/*" -prune -exec rm -rf {} + # delete cfsdeps (except cache)
    - find -name CMakeFiles -type d -exec rm -rf {} + # delete cmake directories
    - find -iregex ".*\(\([.]a\)\|\([.]hpp\)\)$" -delete # delete *.a and *.hpp files
    - du -h --max-depth=1 . # debug
    - df -h # debug
    - !reference [.linux-debug-end, script]
    - ctest -D ExperimentalTest --track $CDASH_TRACK # test build and install
    - mv "CFS-$CI_COMMIT_SHA-Linux.tar.gz" "CFS-$CI_COMMIT_REF_SLUG-Linux.tar.gz" # rename to a (branch/tag-)constant name
  after_script:
    - export DEBUG_SECTION_TITLE='debug information and cleanup'
    - !reference [.linux-debug-start_collapsed, script]
    - git status # debug
    # restore testsuite
    - *restore_Testsuite_ignore
    - ls -la # debug
    - df -h # debug
    - du -h --max-depth=1 $CI_PROJECT_DIR # debug
    - du -h --max-depth=1 $CI_PROJECT_DIR/build # debug
    # clean up a bit to free disk space for cache-creation, leave artifacts and cache
    - rm -rf $CI_PROJECT_DIR/build/_CPack_Packages $CI_PROJECT_DIR/build/vtk $CI_PROJECT_DIR/build/include $CI_PROJECT_DIR/build/source $CI_PROJECT_DIR/build/bin $CI_PROJECT_DIR/build/lib
    - df -h # debug
    - !reference [.linux-debug-end, script]
    # show the contents of the caches
    - !reference [.linux_list_cache, script]
    # submit test results
    - cd build
    - ctest --quiet -O submit.log -D ExperimentalSubmit --track $CDASH_TRACK || cat submit.log # only output submit.log on fail
    - cp CMakeCache.txt CMakeCache_build-stage.txt # rename CMakeCache to avoid conflicts
    # ccache info & clean
    - ccache --verbose --show-stats || ccache -s || true
    - export DEBUG_SECTION_TITLE='ccache details'
    - !reference [.linux-debug-start_collapsed, script]
    - ccache --verbose --show-log-stats || true
    - ccache --verbose --cleanup || ccache -c || true
    - ccache --verbose --show-stats || ccache -s || true
    - !reference [.linux-debug-end, script]
    # save buildid for environment
    - !reference [.save_cdash_buildid,script]
  artifacts:
    paths: # just an example
      - ./build/CFS-${CI_COMMIT_REF_SLUG}-Linux.tar.gz # the packed binaries for distribution
      - build/CMakeCache_build-stage.txt
      - build/ccache.log # for debug
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    # show files on the MR page, see https://docs.gitlab.com/ee/ci/yaml/#artifactsexpose_as
    expose_as: 'job logs'
    expire_in: 1.2 days            

.except-skip-gcc: &except-skip-gcc
  # do not add this job if commit message contains 'skip-gcc-builds'
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-gcc-builds/

.except-skip-intel: &except-skip-intel
  # do not add this job if commit message contains 'skip-intel-builds'
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-intel-builds/

.gcc_before: &gcc_before
  before_script:
    # debug output
    - gcc --version
    # general build before script
    - !reference [.before-script-build, script]

.intel_before: &intel_before
  before_script:
    # we assume CC, CXX and FC is set in the image properly (e.g. in the file bash_profile)
    - (icc -v || icx -v)
    - (icpc -v || icpx -v)
    - (ifort -v || ifx -v)
    - $CC -v
    - $CXX -v
    - $FC -v
    - git status # debug
    # ensure the testsuite is not there (to save space)
    - rm -rf Testsuite
    - git checkout Testsuite
    # general build before script
    - !reference [.before-script-build, script]

# ensure maximal build is tested never tested automatically in forks 
# if someone wants to enable max-builds one has to manually define the variable "DO_MAX_BUILD" and set its value to "ON"
.max_never_auto_rule: &rule_max_never_auto_rule
  rules:
    - if: '$DO_MAX_BUILD != "ON"'
      when: never

.max_rules: &max_rules
  rules:
    - !reference [.max_never_auto_rule, rules]
    - !reference [.build_rules, rules]

#######################################################################
# BUILD STAGE
#######################################################################


# maximal build using as many options as possible
linux:gcc7max-debug:
  extends: .default_build_job
  variables:
    IMAGE: centos7-gcc7
    BUILD_NAME: "GCC7 maximal debug"
    CFS_CONFIG_OPTIONS: "-DDEBUG=ON -DUSE_OPENMP=OFF $MAX_CONFIG_OPTIONS"
    # use ccache
    CMAKE_CXX_COMPILER_LAUNCHER: ccache
  <<: [ *max_rules, *gcc_before ]
  needs: 
    - job: cfsdeps:gcc7
      optional: true

# maximal build using as many options as possible
linux:gcc7max:
  extends: .default_build_job
  variables:
    IMAGE: centos7-gcc7
    BUILD_NAME: "GCC7 maximal"
    CFS_CONFIG_OPTIONS: $MAX_CONFIG_OPTIONS
    # use ccache
    CMAKE_CXX_COMPILER_LAUNCHER: ccache
  <<: [ *max_rules, *gcc_before ]
  needs: 
    - job: cfsdeps:gcc7
      optional: true

linux:gcc7:
  extends: .default_build_job
  variables:
    IMAGE: centos7-gcc7
    BUILD_NAME: "GCC7"
    # use ccache
    CMAKE_CXX_COMPILER_LAUNCHER: ccache    
  <<: [ *build_rules, *gcc_before ]
  needs: 
    - job: cfsdeps:gcc7
      optional: true

# this is the official release build
linux:gcc14-musl:
  extends: .default_build_job
  variables:
    IMAGE: alpine
    BUILD_NAME: "GCC14-MUSL"
    CFS_CONFIG_OPTIONS: $MUSL_CONFIG_OPTIONS
    # use ccache
    CMAKE_CXX_COMPILER_LAUNCHER: ccache
    # use Ninja (which actually is 'samurai' on Alpine)
    CMAKE_GENERATOR: Ninja
  <<: [ *release_build_rules, *gcc_before ]
  needs: 
    - job: cfsdeps:gcc14-musl
      optional: true

linux:gcc7min:
  extends: .default_build_job
  variables:
    IMAGE: centos7-gcc7
    BUILD_NAME: "GCC7 minimal"
    CFS_CONFIG_OPTIONS: "-DBUILD_CFSDAT=OFF -DUSE_BLAS_LAPACK=NETLIB -DBUILD_UNIT_TESTS=OFF -DUSE_ARPACK=OFF -DUSE_CGAL=OFF -DUSE_CGNS=OFF -DUSE_DUMAS=OFF -DUSE_ENSIGHT=OFF -DUSE_EXPRESSION_TEMPLATES=OFF -DUSE_FEAST=OFF -DUSE_FLANN=OFF -DUSE_GIDPOST=OFF -DUSE_IPOPT=OFF -DUSE_LIS=OFF -DUSE_METIS=OFF -DUSE_OPENMP=OFF -DUSE_PARDISO=OFF -DUSE_SUITESPARSE=OFF -DUSE_SUPERLU=OFF "
    # use ccache
    CMAKE_CXX_COMPILER_LAUNCHER: ccache
  <<: [ *build_rules, *gcc_before ]
  needs:
    - job: cfsdeps:gcc7
      optional: true

# closed build using as many options as possible and containing closed source software AND tests
linux:gcc7closed:
  extends: .default_build_job
  variables:
    IMAGE: centos7-gcc7
    BUILD_NAME: "GCC7 closed"
    # embedded_python is not closed but technically not that easy deployable
    CFS_CONFIG_OPTIONS: "-DUSE_SCPIP=ON -DUSE_SNOPT=ON -DUSE_EMBEDDED_PYTHON=ON -DUSE_SUITESPARSE=ON -DBUILD_CFSDAT=OFF" 
    # use ccache
    CMAKE_CXX_COMPILER_LAUNCHER: ccache
  # ensure closed build is tested only when the keys are set
  rules:
    - if: $CFS_KEY_SCPIP == null || $CFS_KEY_SNOPT == null # check if one key is not defined (null) which is equivalent to checking if both are defined - we only build if both keys are defined
      when: never
    - !reference [.build_rules, rules]
  <<: [*gcc_before]
  # make sure artifacts are not accessible, see https://docs.gitlab.com/ee/ci/yaml/#artifactsaccess
  artifacts:
    access: 'none'
  needs:
    - job: cfsdeps:gcc7
      optional: true  

# intel compiler builds
linux:intel:
  extends: .default_build_job
  variables:
    IMAGE: rhel8-intel
    BUILD_NAME: "Intel2025"
    # use ccache
    CMAKE_CXX_COMPILER_LAUNCHER: ccache
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /skip-builds-intel/'
      <<: *require-rebuild-changes
      when: manual
    - !reference [.build_rules, rules]
  <<: [ *intel_before ]
  needs:
    - job: cfsdeps:intel
      optional: true

# LLVM clang compiler builds
linux:clang-debug:
  extends: .default_build_job
  variables:
    IMAGE: fedora37-clang
    BUILD_NAME: "Clang debug"
    CFS_CONFIG_OPTIONS: "-DDEBUG=ON "
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /skip-builds-clang/'
      when: manual
      allow_failure: true
    - !reference [.build_rules, rules]
  before_script:
    # ensure clang is installed
    - clang --version
    # general build before script
    - !reference [.before-script-build, script]
  cache:
    - key: cfsdeps-precompiled-Clang-${CI_COMMIT_REF_NAME}
      paths:
        - build/cfsdeps/cache/precompiled
      fallback_keys:
        - cfsdeps-precompiled-Clang-$CI_DEFAULT_BRANCH
    - key: cfsdeps-sources-$CI_COMMIT_REF_NAME
      paths:
        - build/cfsdeps/cache/sources/
      fallback_keys:
        - cfsdeps-sources-$CI_DEFAULT_BRANCH
  needs: []

# windows build
windows:MSVC2022-Ifort2021:
  extends: .windows-shared-build
  stage: build
  <<: *release_build_rules
  variables:
    BUILD_NAME: "MSVC2022-Ifort2021"
    # see https://yaml-multiline.info/ for multiline info
    BUILD_COMMAND: "ctest -D ExperimentalStart --track $CDASH_TRACK -V &&
                    ctest -D ExperimentalUpdate --track $CDASH_TRACK -V &&
                    ctest -D ExperimentalConfigure --track $CDASH_TRACK -V &&
                    ctest -D ExperimentalSubmit --track $CDASH_TRACK &&
                    ctest -D ExperimentalBuild --track $CDASH_TRACK -V | tee build.log &&
                    ctest -D ExperimentalSubmit --track $CDASH_TRACK &&
                    ctest -D ExperimentalTest --track $CDASH_TRACK -V"
    # use ccache
    CMAKE_CXX_COMPILER_LAUNCHER: ccache.exe
  script:
    # inherit the standard script, then extend by mv command
    - !reference [.windows-shared-build, script]
    # rename packaged file to branch-based name
    - mv "CFS-$CI_COMMIT_SHA-win64.zip" "CFS-$CI_COMMIT_REF_SLUG-Windows.zip"
  artifacts:
    when: always
    paths:
      - build/CFS-*-Windows.zip
      - build/logs.zip
    expire_in: 1 days
  needs:
    # set the needs to 'optional' since the cfsdeps job might not be present
    - job: cfsdeps:MSVC2022-Ifort2021
      optional: true
    - job: install:MSVC2022-Ifort2021
      optional: true


#######################################################################
# TEST STAGE
#######################################################################
# the test stage might run on a different runner than the build, thus
# the binaries are shared via the gitlab server (artifacts/dependencies)
#
# We have the following different test configurations
# * stable - runs the Testsuite on a single thread and disabling some unstable tests via -LE unstable (and python tests)
# * testsuite - runs the Testsuite on all available cores (disabling python tests) with two threads (multicore_all)
# * no-slow - run debug builds and skip unstable and slow (bow by label) and no python tests
#             the tool tests.py in the Testsuite can be used for setting and checking the slow label for the tests.
# * python - runs the Python-Tests of the testsuite, independent of the c++ build
# Both _stable_ and _testsuite_ are run for all build configs (GCCx),
# _python_ is seperate as not to re-run python tests for all GCCx versions.

# test for cmake or install it
.cmake_test_or_install:
  script:
  - export DEBUG_SECTION_TITLE='cmake test or install'
  - !reference [.linux-debug-start_collapsed, script]
  - cmake --version || ls -l cmake || ( wget https://cmake.org/files/v3.22/cmake-3.22.6-linux-x86_64.sh && mkdir $(pwd)/cmake && sh cmake-3.22.6-linux-x86_64.sh --prefix=$(pwd)/cmake --skip-license)
  - cmake --version || export PATH=$(pwd)/cmake/bin:$PATH
  - echo $PATH
  - ctest --version
  - cmake --version
  - !reference [.linux-debug-end, script]

.after_cdash_submit: &after_cdash_submit
  after_script:
    - cd build
    # optionally install cmake if not present
    - !reference [.cmake_test_or_install,script]
    # CDash submit
    - ctest -VV -D ExperimentalSubmit --track $CDASH_TRACK || true # very-verbose output, do not stop after script on fail
    # save buildid
    - !reference [.save_cdash_buildid,script]
  artifacts:
    # display ctest output as junit, see https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportsjunit
    reports:
      junit: build/${CI_JOB_ID}.xml
      annotations: build/annotations.json
    when: always

# test preparation starts by extracting the build files from assets
.ctest_default: &ctest_default
  image: $BUILD_ENVIRONMENT_REGISTRY/$IMAGE:$BUILD_ENVIRONMENT_TAG
  rules:
    - !reference [.build_rules, rules]
  before_script:
    - mkdir -p build
    - cd build # descend in build
    - ls # debug
    # install CFS
    - tar -xzvf "CFS-$CI_COMMIT_REF_SLUG-Linux.tar.gz" --strip-components=1 # extract to correct location
    # obtain the build config
    - ./bin/cfs --dependencies config.cmake
    # optionally install cmake if not present
    - !reference [.cmake_test_or_install,script]
# [global setting](https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing) applies to last test only
# https://docs.gitlab.com/ee/ci/yaml/#coverage
# in the format '/REGEX/' - one can test REGEX at http://rubular.com/
  coverage: '/(\d+\%)\s+tests\s+passed,\s+\d+\s+tests?\s+failed\s+out\s+of\s+\d+/'
  # after-script
  <<: *after_cdash_submit
  # cache the local cmake install
  cache:
    key: cmake
    paths:
      - build/cmake

# Generic testsuite execution job.
# - will do junit submission to gitlab
# - excludes PYTHON since they do not need to be tested for every compiler configuration
# - the "Install" tests are always excluded
# Behaviour can be changed with variables:
# - TEST_CONFIG_OPTIONS: to set Testsuite configure options like threads
# - CTEST_OPTIONS: to passed to ctest execution, e.g. -LE <label> tor exclude labels
.test_generic: &test_generic
  <<: *ctest_default
  script:
    # show variables for debug
    - echo "TEST_CONFIG_OPTIONS="$TEST_CONFIG_OPTIONS
    - echo "CTEST_OPTIONS="$CTEST_OPTIONS
    # configure and run the testsuite
    - cmake -DCTEST_UPDATE_VERSION_ONLY:BOOL=ON -DBUILDNAME="$CI_COMMIT_REF_SLUG / ${BUILD_NAME}" -DBUILD_TESTING=ON -DCFS_BUILD_CONFIG_FILE=$(pwd)/config.cmake -DTESTSUITE_DIR=$(pwd)/../Testsuite -DTESTSUITE_PYTHON=OFF ${TEST_CONFIG_OPTIONS} .. # multicore = default
    - ctest -D ExperimentalStart --track $CDASH_TRACK # start a new dashboard
    - ctest -D ExperimentalUpdate --track $CDASH_TRACK # SHA is visible in CDash
    - ctest -D ExperimentalConfigure --track $CDASH_TRACK # show config
    - ctest -D ExperimentalTest ${CTEST_OPTIONS} --track $CDASH_TRACK --output-junit ${CI_JOB_ID}.xml


# we were not able to assign -LE "unstable|slow" via CTEST_OPTIONS to test_generic, therefore this is our copy & paste version only for gcc7max-debug
.test_no_slow: &test_no_slow
  <<: *ctest_default
  script:
    # show variables for debug
    - echo "TEST_CONFIG_OPTIONS="$TEST_CONFIG_OPTIONS
    # configure and run the testsuite
    - cmake -DCTEST_UPDATE_VERSION_ONLY:BOOL=ON -DBUILDNAME="$CI_COMMIT_REF_SLUG / ${BUILD_NAME}" -DBUILD_TESTING=ON -DCFS_BUILD_CONFIG_FILE=$(pwd)/config.cmake -DTESTSUITE_DIR=$(pwd)/../Testsuite -DTESTSUITE_PYTHON=OFF ${TEST_CONFIG_OPTIONS} .. # multicore = default
    - ctest -D ExperimentalStart --track $CDASH_TRACK # start a new dashboard
    - ctest -D ExperimentalUpdate --track $CDASH_TRACK # SHA is visible in CDash
    - ctest -D ExperimentalConfigure --track $CDASH_TRACK # show config
    - ctest -D ExperimentalTest -LE "unstable|slow" --track $CDASH_TRACK --output-junit ${CI_JOB_ID}.xml

# now we define the actual tests, i.e. we decide which build we want to test
# the build is taken from the dependencies
# Naming scheme for ci-jobs: <test-set_parallelism>:<build-name>:<system>
# Naming scheme for BUILD_NAME: build config / test-set parallelism
stable_ser:gcc7min:linux:
  tags:
    - saas-linux-small-amd64
  stage: test
  variables:
    IMAGE: ubuntu22.04
    BUILD_NAME: "GCC7 minimal / stable serial"
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
    CTEST_OPTIONS: "-LE unstable|broken"
  <<: *test_generic
  needs:
    - linux:gcc7min

unstable_ser:gcc7min:linux:
  tags:
    - saas-linux-small-amd64
  stage: test
  variables:
    IMAGE: ubuntu22.04
    # is built without opnemp  
    BUILD_NAME: "GCC7 minimal / unstable serial"
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
    CTEST_OPTIONS: "-L unstable"
  <<: *test_generic
  needs:
    - linux:gcc7min

stable_par:gcc7max:linux:
  extends: .test_generic
  tags:
    - saas-linux-small-amd64
  stage: test
  rules: # overwrite rules given via extends: .test_generic
    - !reference [.max_rules, rules]
  variables:
    IMAGE: centos7-gcc7
    BUILD_NAME: "GCC7 maximal / stable parallel"
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=2
    CTEST_OPTIONS: "-LE unstable|broken"
  needs:
    - linux:gcc7max

unstable_ser:gcc7max:linux:
  extends: .test_generic
  tags:
    - saas-linux-small-amd64
  stage: test
  rules: # overwrite rules given via extends: .test_generic
    - !reference [.max_rules, rules]
  variables:
    IMAGE: centos7-gcc7
    BUILD_NAME: "GCC7 maximal / unstable serial"
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
    CTEST_OPTIONS: "-L unstable"
  needs:
    - linux:gcc7max

stable_par:gcc7closed:linux:
  extends: .test_generic
  tags:
    - saas-linux-small-amd64
  stage: test
  rules: # overwrite rules given via extends: .test_generic
    - !reference [linux:gcc7closed, rules]
  variables:
    IMAGE: centos7-gcc7
    BUILD_NAME: "GCC7 closed / stable opt parallel"
    TEST_CONFIG_OPTIONS: "-DTESTSUITE_THREADS=2 -DTESTSUITE_PYTHON=OFF "
    CTEST_OPTIONS: "-LE unstable|broken -R Opt"
  needs:
    - linux:gcc7closed

stable_ser:gcc14-musl:linux:
  tags:
    - saas-linux-small-amd64
  stage: test
  variables:
    IMAGE: ubuntu22.04
    BUILD_NAME: "GCC14-MUSL / stable serial"
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
    CTEST_OPTIONS: "-LE unstable|broken"
  <<: *test_generic
  needs:
    - linux:gcc14-musl

stable_par:gcc14-musl:linux:
  tags:
    - saas-linux-small-amd64
  stage: test
  variables:
    IMAGE: ubuntu22.04
    BUILD_NAME: "GCC14-MUSL / stable parallel"
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=2
    CTEST_OPTIONS: "-LE unstable|broken"
  <<: *test_generic
  needs:
    - linux:gcc14-musl

stable_par:intel:linux:
  tags:
    - saas-linux-small-amd64
  stage: test
  variables:
    IMAGE: ubuntu22.04
    BUILD_NAME: Intel2025 / stable parallel
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=2
    CTEST_OPTIONS: "-LE unstable|broken"
  <<: *test_generic
  needs:
    - linux:intel

unstable_ser:intel:linux:
  tags:
    - saas-linux-small-amd64
  stage: test
  variables:
    IMAGE: ubuntu22.04
    BUILD_NAME: Intel2025 / unstable serial
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
    CTEST_OPTIONS: "-L unstable"
  <<: *test_generic
  needs:
    - linux:intel

# windows tests
stable_ser:MSVC2022-Ifort2021:windows:
  extends: .windows-shared-test
  stage: test
  variables:
    BUILD_NAME: MSVC2022-Ifort2021 / stable serial
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
  script: 
    - !reference [.windows-test_stable, script]
  needs:
    - windows:MSVC2022-Ifort2021

stable_par:MSVC2022-Ifort2021:windows:
  extends: .windows-shared-test
  stage: test
  variables:
    BUILD_NAME: MSVC2022-Ifort2021 / stable parallel
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=2
  script: 
    - !reference [.windows-test_stable, script]
  rules:
    #make it optional since MSVC builds currently are not running in parallel
    - if: $CFS_PIPELINE_TYPE == "test" || $CFS_PIPELINE_TYPE == "manual"
      <<: *require-rebuild-changes
      when: manual
      allow_failure: true
    - !reference [.ctest_default, rules]
  needs:
    - windows:MSVC2022-Ifort2021

unstable_ser:MSVC2022-Ifort2021:windows:
  extends: .windows-shared-test
  stage: test
  variables:
    BUILD_NAME: MSVC2022-Ifort2021 / unstable serial
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
  script:
    - !reference [.windows-test_unstable, script]
  needs:
    - windows:MSVC2022-Ifort2021

python:linux:
  image: $BUILD_ENVIRONMENT_REGISTRY/ubuntu22.04:$BUILD_ENVIRONMENT_TAG
  extends: .ctest_default
  tags:
    - saas-linux-small-amd64
  stage: test
  rules:
    # activate in schedule
    - if: $CFS_PIPELINE_TYPE == "nightly"
    # run when we have changes in python files
    - if: $CFS_PIPELINE_TYPE == "test"
      changes:
        - "**/*.py"
    - if: $CFS_PIPELINE_TYPE == "manual"
      changes:
        - "**/*.py"
      when: manual
  variables:
    TEST_NAME: "stable"
    EXCLUDE: ""
  before_script:
    - git rev-list -n 1 HEAD -- || echo "git failed, should return ${CI_COMMIT_SHA}" # debug for command run by CTestUpdate
    - mkdir -p build
    - cd build
    - !reference [.cmake_test_or_install,script] # optionally install cmake if not present
    - cmake -DBUILDNAME="$CI_COMMIT_REF_SLUG / python / $TEST_NAME" -DCTEST_UPDATE_VERSION_ONLY:BOOL=ON -DBUILD_TESTING=ON -DTESTSUITE_DIR=$(pwd)/../Testsuite -DTESTSUITE_PYTHON=ON ..
  script:
    - ctest -D ExperimentalStart --track $CDASH_TRACK # start a new dashboard
    - ctest -D ExperimentalUpdate --track $CDASH_TRACK # SHA is visible in CDash
    - ctest -D ExperimentalConfigure --track $CDASH_TRACK # show config
    - ctest -D ExperimentalTest -R PYTHON -E "$EXCLUDE" --track $CDASH_TRACK --output-junit ${CI_JOB_ID}.xml
  dependencies: [] # python tests do not need any dependencies (no cfs required)
  <<: *after_cdash_submit
  needs: [] # run as soon as possible


#######################################################################
# TEST_EXTRA STAGE - similar to before, but here we collect everything that is currently not working as intended (everything that is allowed to fail)
#######################################################################

# the extra stage is irrelevant for the merge request (alloed to fail)
# therefore we set it to manual by default
# it should auto-run for nightly tests
.test_extra:
  <<: *test_generic
  stage: test_extra
  # then overwrite rules
  rules:
    # Scheduled pipelines run all tests
    - if: $CFS_PIPELINE_TYPE == "nightly"
      allow_failure: true
    # Set the tests to manual for test-pipelines
    - if: $CFS_PIPELINE_TYPE == "test" || $CFS_PIPELINE_TYPE == "manual"
      when: manual
      allow_failure: true

broken_ser:gcc7min:linux:
  extends: .test_extra
  tags:
    - saas-linux-small-amd64
  variables:
    IMAGE: ubuntu22.04
    # is built without opnemp  
    BUILD_NAME: "GCC7 minimal / broken serial"
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
    CTEST_OPTIONS: "-L broken"
  needs:
    - linux:gcc7min

# this test has the speciality that it shall run at an unspecified image 
all_par:gcc14-musl:any-linux:
  extends: .test_extra
  tags:
    - saas-linux-small-amd64
  variables:
    BUILD_NAME: "GCC14-MUSL / all parallel any-linux"
    # no special options - we take all default (should be all tests & in parallel if NCPU>1)
  needs:
    - linux:gcc14-musl

unstable_par:gcc7max:linux:
  extends: .test_extra
  tags:
    - saas-linux-small-amd64
  rules:
    - !reference [.max_never_auto_rule, rules]
    - !reference [.test_extra, rules]
  variables:
    IMAGE: centos7
    BUILD_NAME: "GCC7 maximal / unstable parallel"
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=2
    CTEST_OPTIONS: "-L unstable"
  needs:
    - linux:gcc7max

broken_ser:gcc7max:linux:
  extends: .test_extra
  tags:
    - saas-linux-small-amd64
  rules:
    - !reference [.max_never_auto_rule, rules]
    - !reference [.test_extra, rules]
  variables:
    IMAGE: centos7
    BUILD_NAME: "GCC7 maximal / broken serial"
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
    CTEST_OPTIONS: "-L broken"
  needs:
    - linux:gcc7max

# debug is compiled without openmp
no-slow_ser:gcc7max-debug:linux:
  extends: .test_extra
  <<: *test_no_slow
  tags:
    - saas-linux-small-amd64
  # overwrite rules & variables
  rules:
    - !reference [.max_never_auto_rule, rules]
    - !reference [.test_extra, rules]
  variables:
    IMAGE: centos7
    BUILD_NAME: "GCC7 maximal debug / no-slow serial"
    # debug is compiled without openmp, we could set the threads to anything and it would be ignored
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
    # this special test_no_slow does -LE "unstable|slow"
  needs:
    - linux:gcc7max-debug

unstable_par:intel:linux:
  extends: .test_extra
  tags:
    - saas-linux-small-amd64
  variables:
    IMAGE: ubuntu22.04
    BUILD_NAME: Intel2025 / unstable parallel
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=2
    CTEST_OPTIONS: "-L unstable"
  needs:
    - linux:intel

unstable_par:gcc14-musl:linux:
  extends: .test_extra
  tags:
    - saas-linux-small-amd64
  variables:
    IMAGE: ubuntu22.04
    BUILD_NAME: GCC14-MUSL / unstable parallel
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=2
    CTEST_OPTIONS: "-L unstable"
  needs:
    - linux:gcc14-musl

broken_ser:gcc14-musl:linux:
  extends: .test_extra
  tags:
    - saas-linux-small-amd64
  variables:
    IMAGE: ubuntu22.04
    BUILD_NAME: GCC14-MUSL / broken serial
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
    CTEST_OPTIONS: "-L broken"
  needs:
    - linux:gcc14-musl

broken_ser:intel:linux:
  extends: .test_extra
  tags:
    - saas-linux-small-amd64
  variables:
    IMAGE: ubuntu22.04
    BUILD_NAME: Intel2025 / broken serial
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
    CTEST_OPTIONS: "-L broken"
  needs:
    - linux:intel

broken_ser:MSVC2022-Ifort2021:windows:
  extends: .windows-shared-test
  stage: test_extra
  rules:
    - !reference [.test_extra, rules]
  variables:
    BUILD_NAME: MSVC2022-Ifort2021 / broken serial
    TEST_CONFIG_OPTIONS: -DTESTSUITE_THREADS=1
  script:
    - !reference [.windows-test_broken, script]
  needs:
    - windows:MSVC2022-Ifort2021

#######################################################################
# DOCS STAGE - Documentation jobs
#######################################################################

# build doxygen docu
doxygen:
  stage: docs
  image: $BUILD_ENVIRONMENT_REGISTRY/fedora32:$BUILD_ENVIRONMENT_TAG
  tags:
    - saas-linux-small-amd64
  variables:
    GIT_SUBMODULE_STRATEGY: none
  rules:
    - if: $CFS_PIPELINE_TYPE == "test"
    - if: $CFS_PIPELINE_TYPE == "release" && ( $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH )
    - if: $CFS_PIPELINE_TYPE == "manual"
      when: manual
  before_script:
    - mkdir -p build # create if it does not exist
    - cd build # descend in build
  script:
    # configure with correct generator
    - cmake ..
    # build docu
    - make doc-doxygen
    # pack
    - cd share/doc/developer/doxygen/html
    - tar -czf doxygen-html.tgz *
  after_script:
    - mv build/share/doc/developer/doxygen/html/doxygen-html.tgz doxygen-html.tgz
  artifacts:
    paths:
      - doxygen-html.tgz
    expire_in: 6 hours
  needs: []

#######################################################################
# DEPLOY STAGES
#######################################################################

cdash:report:
  stage: deploy
  tags: # add a tag since some runners refuse to run un-tagged jobsgit add .gi  
    - saas-linux-small-amd64
  # switch off cloning any code
  variables:
    GIT_SUBMODULE_STRATEGY: none
    GIT_STRATEGY: none
  rules:
    - if: $CFS_PIPELINE_TYPE == "test"
      allow_failure: true # only for info
    - if: $CFS_PIPELINE_TYPE == "manual"
      when: manual
      allow_failure: true # only for info
  cache: {}
  after_script: []
  before_script: []
  script:
    - echo "see failed tests for '${CI_COMMIT_REF_SLUG}' on http://movm.mi.uni-erlangen.de/cdash/queryTests.php?project=CFS&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=65&value1=${CI_COMMIT_REF_SLUG}&field2=status&compare2=61&value2=Failed"
  environment:
    name: CDash/$CI_COMMIT_REF_SLUG
    url: http://movm.mi.uni-erlangen.de/cdash/queryTests.php?project=CFS&filtercount=2&filtercombine=and&field1=buildname&compare1=65&value1=$CI_COMMIT_REF_SLUG&field2=status&compare2=61&value2=Failed
    auto_stop_in: 1 week
  dependencies: []

.deploy_rules: &deploy_rules
  only:
    refs:
      - master # only for refs pushed to master
    variables:
      # use variables to limit deploy jobs for mdmt to pipelines from the corresponding namespace
      # see the default variales https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables
      - $CI_PROJECT_NAMESPACE == "cfs"
  tags:
    - linux
    - mdmt
  stage: deploy
  cache: {}
  after_script: []
  before_script: []
  # switch off cloning any code
  variables:
    GIT_SUBMODULE_STRATEGY: none
    GIT_STRATEGY: none

pages:
  stage: deploy
  tags:
    - saas-linux-small-amd64
  # switch off cloning any code
  variables:
    GIT_SUBMODULE_STRATEGY: none
    GIT_STRATEGY: none
  rules:
    # only for release pipelines in our namespace
    - if: $CFS_PIPELINE_TYPE == "release" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_NAMESPACE == "openCFS"
  dependencies:
    - linux:gcc14-musl
    - doxygen
  script:
    - mkdir -p public # create public dir
    # publish XML scheme
    - tar -xzvf "build/CFS-$CI_COMMIT_REF_SLUG-Linux.tar.gz" # extract the build (for XML schema)
    - cp -r "CFS-$CI_COMMIT_SHA-Linux/share/xml" "public/." # publish XML scheme
    # publish the builds
    - mv "build/CFS-$CI_COMMIT_REF_SLUG-Linux.tar.gz" "public/." # move to public
    # - mv "build/CFS-$CI_COMMIT_REF_SLUG-Windows.zip" "public/." # windows is too large
    # publish doxygen
    - mkdir -p public/doxygen
    - tar -xzf doxygen-html.tgz -C public/doxygen
  artifacts:
    paths:
      - public
  cache: {}
  after_script: []
  before_script: []

.package-release_common: &package-release_common
  stage: deploy
  variables:
    # switch off cloning any code and add common variables
    GIT_SUBMODULE_STRATEGY: none
    GIT_STRATEGY: none
    # see https://docs.gitlab.com/ee/user/packages/generic_packages/index.html for PACKAGE_REGISTRY_URL format
    #                                                    projects/:id/packages/generic/:package_name/:package_version/:file_name
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/openCFS/${CI_COMMIT_TAG}"
    LINUX_ARCHIVE: "CFS-${CI_COMMIT_TAG}-Linux.tar.gz"
    WINDOWS_ARCHIVE: "CFS-${CI_COMMIT_TAG}-Windows.zip"
  rules:
    # Run this job when a tag is created
    - if: ( $CFS_PIPELINE_TYPE == "release" ) && $CI_COMMIT_TAG && ( $CI_PROJECT_NAMESPACE == "openCFS" )
  cache: {}
  after_script: []
  before_script: []
  needs:
    - linux:gcc14-musl
    - windows:MSVC2022-Ifort2021

repack-release: # publish release packages (when a tag is pushed)
  extends: .package-release_common
  image: alpine
  #rules:
  #  # repack only for tags
  #  - $CI_COMMIT_TAG && $CFS_PIPELINE_TYPE == "release" && $CI_PROJECT_NAMESPACE == "openCFS"
  script:
    # debug
    - echo "CI_COMMIT_TAG=$CI_COMMIT_TAG"
    - echo "CI_COMMIT_REF_SLUG=$CI_COMMIT_REF_SLUG"
    # linux
    - tar -xzvf "build/CFS-$CI_COMMIT_REF_SLUG-Linux.tar.gz" # extract the build
    - mv "CFS-$CI_COMMIT_SHA-Linux" "CFS-$CI_COMMIT_TAG-Linux" # rename
    - tar -czvf "build/${LINUX_ARCHIVE}" CFS-$CI_COMMIT_TAG-Linux # repack
    # windows
    - apk add --no-cache zip # install zip
    - unzip "build/CFS-$CI_COMMIT_REF_SLUG-Windows.zip" # extract
    - mv "CFS-$CI_COMMIT_SHA-win64" "CFS-$CI_COMMIT_TAG-Windows" # rename
    - zip -r -9 "build/${WINDOWS_ARCHIVE}" CFS-$CI_COMMIT_TAG-Windows # repack
  artifacts:
    paths:
      - build/$LINUX_ARCHIVE
      - build/$WINDOWS_ARCHIVE

package: # publish package for default branch
  extends: .package-release_common
  image: curlimages/curl:latest
  rules:
    # if it is a tag, we repack the archives such that the top-level-directory is called CFS-<TAG>-<platform>.<ext> 
    - if: ( $CFS_PIPELINE_TYPE == "release" ) && $CI_COMMIT_TAG && $CI_PROJECT_NAMESPACE == "openCFS"
      needs: ['repack-release']
    # otherwise we publish build artifacts directly (we edit the variable names to accept default artifacts)
    - if: ( $CFS_PIPELINE_TYPE == "release" ) && ( $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH )  
      variables:
        LINUX_ARCHIVE: "CFS-$CI_COMMIT_REF_SLUG-Linux.tar.gz"
        WINDOWS_ARCHIVE: "CFS-$CI_COMMIT_REF_SLUG-Windows.zip"
        PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/openCFS/${CI_COMMIT_REF_SLUG}"
  script:
    - echo "publishing ${LINUX_ARCHIVE} and ${WINDOWS_ARCHIVE} to ${PACKAGE_REGISTRY_URL}"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "build/${LINUX_ARCHIVE}" "${PACKAGE_REGISTRY_URL}/${LINUX_ARCHIVE}"
    - echo "download Linux build at ${PACKAGE_REGISTRY_URL}/${LINUX_ARCHIVE}"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "build/${WINDOWS_ARCHIVE}" "${PACKAGE_REGISTRY_URL}/${WINDOWS_ARCHIVE}"
    - echo "download Windows build at ${PACKAGE_REGISTRY_URL}/${WINDOWS_ARCHIVE}"

release:
  extends: .package-release_common
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - package
  script:
    - echo "${CI_COMMIT_TAG_MESSAGE}" > description.md
    - cat description.md
  release:  # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: './description.md'
    assets:
      # add links to downloads
      # format: https://gitlab.com/openCFS/cfs/-/releases/:release/downloads/:filepath
      # or permanent link to the latest version: https://gitlab.com/openCFS/cfs/-/releases/permalink/latest/downloads/:filepath
      links:
        - name: 'Linux binary (tar.gz)'
          url: "${PACKAGE_REGISTRY_URL}/${LINUX_ARCHIVE}" # uploaded by 'package' job before
          filepath: '/CFS-Linux.tar.gz' # optional, but required for 'latest', defines the URL (see https://docs.gitlab.com/ee/user/project/releases/release_fields.html#permanent-links-to-release-assets)
          link_type: 'package' # optional, defines the section and icon (see https://docs.gitlab.com/ee/user/project/releases/release_fields.html#link-types)
        - name: 'Windows binary (zip)'
          url: "${PACKAGE_REGISTRY_URL}/${WINDOWS_ARCHIVE}" # uploaded by 'package' job before
          filepath: '/CFS-Windows.zip' # optional, but required for 'latest', defines the URL (see https://docs.gitlab.com/ee/user/project/releases/release_fields.html#permanent-links-to-release-assets)
          link_type: 'package' # optional, defines the section and icon (see https://docs.gitlab.com/ee/user/project/releases/release_fields.html#link-types)
