# This file is used to define the CI pipeline for GitLab
# https://docs.gitlab.com/ee/ci/yaml
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build # config and build combined
  - test # we may have several test configs for one build
  - deploy

# this is run before/after every step
before_script:
  - mkdir -p build # make build dir
  - cd build
  - cat Testing/TAG || echo "no TAG"
  - rm -f CMakeCache.txt # clear old cache
  - cmake -DCTEST_GIT_UPDATE_CUSTOM:STRING="git;status" .. # configure with git update command
# after the before script we should be in the build dir and ready to run ctest
    
after_script:
  - cd build
  - cat Testing/TAG || echo "no TAG"
  - ctest -D ExperimentalSubmit --track Gitlab -V # this is in after to always submit a result, also it a sub-step failed
  # clean up for next build
  - rm CMakeCache.txt

# cache the build files see https://docs.gitlab.com/ee/ci/caching/index.html
# use the ref-name, e.g. `master` as key -> same for sucessive builds
# it is stored as a zip archive and extracted before each stage - this takes time,
# thus we combine the build and configure step
# the key is used to define which chache is used for which job.
cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - build/cfsdeps/cache
    - build/bin
    - build/lib*
    - build/Testing

#################################################
# BUILD STAGE
#################################################
# Here we define the build jobs, if one fails we do not need to test

.job_template: &config_build_ctest
  script:
    - ctest -D ExperimentalStart --track Gitlab -V
    - ctest -D ExperimentalUpdate --track Gitlab -V
    - ctest -D ExperimentalConfigure --track Gitlab -V
    - ctest -D ExperimentalSubmit --track Gitlab # intermittent submit to get live CDash results
    - ctest -D ExperimentalBuild --track Gitlab -V
    - ctest -D ExperimentalSubmit --track Gitlab
    - ctest -D ExperimentalTest -R Install --track Gitlab # only do the install testing
  artifacts:
    paths: # just an example
      - build/DartConfiguration.tcl
      - build/CFS-*-Linux.tar.gz # the packed binaries for distribution
    expire_in: 2h

build:gcc4: # eventually we should have one job for each required configuration
  stage: build
  tags:
    - gcc4
  <<: *config_build_ctest

build:gcc6:
  stage: build
  tags:
    - gcc6
  before_script:
    - mkdir build || cd build # descend in build
    - scl enable devtoolset-6 -- bash || gcc --version # try software collection, and if it fails use native gcc (and hope it's 6 - need correct tag on the runner)
    - cat Testing/TAG || echo "no TAG" # just debug
    - rm -f CMakeCache.txt # clear old cache
    - cmake -DCTEST_GIT_UPDATE_CUSTOM:STRING="git;status" .. # configure with git update command
  <<: *config_build_ctest

# re-build everything
complete-build:gcc4:
  stage: build
  tags:
    - gcc4
  when: manual
  before_script:
    - rm -rf build # clear
    - mkdir build
    - cd build
    - cmake -DCTEST_GIT_UPDATE_CUSTOM:STRING="git;status" ..
  <<: *config_build_ctest


#################################################
# TEST STAGE
#################################################
# the test stage might run on a different runner than the build, thus
# the binaries are shared via the gitlab server (artifacts/dependencies)

.job_template: &test_prepare
  before_script:
    - mkdir build || cd build # descend in build
    - ls # debug
    - tar -xzvf "CFS-"$CI_COMMIT_SHA"-Linux.tar.gz" --strip-components=1 # extract to correct location

test:gcc4:linux:
  tags:
    - linux
  stage: test
  <<: *test_prepare
  script:
    - cmake -DGITLAB_TEST_TAG:STRING=`date +%Y%m%d-%H%M` -DCFS_TESTSUITE_THREADS=1 -DCFS_TESTSUITE_CFSTOOL_MODE=relL2diff .. # re-configure with most robust test config
    - ctest -D ExperimentalTest -E "Instal|ElecTherm_ElTh_NMGtransient|Preisach|CFSdat_FFT_2D" --track Gitlab # exclude the install step and the failing tests
  dependencies:
    - build:gcc4

test:gcc4:linux:multicore: # if the machine has multiple
  tags:
    - linux
  stage: test
  when: manual
  <<: *test_prepare
  script:
    - cmake -DGITLAB_TEST_TAG:STRING=`date +%Y%m%d-%H%M` -DCFS_TESTSUITE_CFSTOOL_MODE=relL2diff .. # multicore
    - ctest -D ExperimentalTest -E Install --track Gitlab # exclude the install step
  dependencies:
    - build:gcc4

#################################################
# DEPLOY STAGES
#################################################

deploy:gcc4:mdmt:
  tags:
    - linux
    - mdmt
  stage:
    - deploy
  only:
    refs:
      - master # only for refs pushed to master
  dependencies:
    - build:gcc4
  script:
    - scp "CFS-$CI_COMMIT_SHA-Linux.tar.gz" "draco:/opt/programs/cfs_master/CFS-$CI_COMMIT_SHA-Linux.tar.gz"
    - ssh draco "tar -xzf /opt/programs/cfs_master/CFS-$CI_COMMIT_SHA-Linux.tar.gz --strip 1 -C /opt/programs/cfs_master"
