#------- Format for output results

format_output = unverg // gmv,unverg

#------- Library that is used for working with the mesh

mesh_library = cfsgrid // gridlib, cfsgrid, netgen 

#------- Material parameters for subdomains
#------ numsubdomain ------ material number --------
             1                 10000         
             2                 17889

#------- Parameters for acoustic equation

Acoustic PDE:
   adapttime = no  // Do you want use adaptivity in time ? (yes, no)
   epsilon = 1e-25         // a tolerance for own algebraic system

   ----- Parameters for CLA++ ---------------------------
   
   eps = 1e-6              // relative accuracy in the precond. energy
   dampiter = 0.7          // damping parameter for Jacobi, SSOR, ...
   maxnumit = 20           // max number of iterations

   solvertype = 2          // RICHARDSON = 1
                           // CG         = 2

   precondtype = 2         // ID    = 1
                           // MG    = 2

   numeqcoarse = 10000     // number equation for coarsing
   ----- Parameters for time-adaptivity ------------------

   tolrelerr = 0.05 // a tolerance of relative local error
   theta = 0.9     // factor introduced to avoid the new step being rejected
   coarsbeta = 0.9 // factor introduced for strategy of coarsing
   numrepeat = 5   // number of step for strategy of coarsing

#------- Parameters for thermal equation

Thermal PDE:
   formulation = 1 // 1 - effective mass formulation
                   // 2 - effective stiffness formulation   

   epsilon = 1e-26 // a tolerance for own algebraic system

   ----- Parameters for CLA++ ---------------------------- 

   eps =1e-6;              // relative accuracy in the precond. energy
   dampiter = 0.7;         // damping parameter for Jacobi, SSOR, ...
   maxnumiter = 20;        // max number of iterations

   solvertype = 2;         // RICHARDSON = 1
                           // CG         = 2

   precondtype = 2         // ID    = 1
                           // MG    = 2
   numeqcoarse = 10000     // number equation for coarsing
