#
# Makefile for Parameter Handling module
#
C_DIR = ../../..
src = PlainXMLParamHandler.cc XMLParserErrorHandler.cc XMLParamHandler.cc \
      ConfFile.cc SkeletonConf.cc XMLSkeletonConf.cc CFSOLASParams.cc
#
lib = paramhandling
libpath = libsrc/DataInOut/ParamHandling
CFLAGS3 =
#
include ../../makefile.inc
-include $(Dependencies)
# DO NOT DELETE


