#make the libs

driver:
	@cd $(LIBSRC_DIR)/Driver; $(MAKE) -f Makefile 

paramIdent:
	@cd $(LIBSRC_DIR)/ParamIdent; $(MAKE) -f Makefile 

domain:
	@cd $(LIBSRC_DIR)/Domain; $(MAKE) -f Makefile

gridcfs:
	@cd $(LIBSRC_DIR)/Domain/GridCFS; $(MAKE) -f Makefile

gridstruct:
	@cd $(LIBSRC_DIR)/Domain/GridStruct; $(MAKE) -f Makefile

gridadaption:
	@cd $(LIBSRC_DIR)/Domain/GridAdaption; $(MAKE) -f Makefile

estimator:
	@cd $(LIBSRC_DIR)/Estimator; $(MAKE) -f Makefile

toadaptgrid:
	@cd $(LIBSRC_DIR)/Domain/AdaptGrid; $(MAKE) -f Makefile

adaptgrid:
	@cd $(AdaptGrid); $(MAKE) -f Makefile

forms:
	@cd $(LIBSRC_DIR)/Forms; $(MAKE) -f Makefile

pde:
	@cd $(LIBSRC_DIR)/PDE; $(MAKE) -f Makefile

coupledpde:
	@cd $(LIBSRC_DIR)/CoupledPDE; $(MAKE) -f Makefile

elements:
	@cd $(LIBSRC_DIR)/Elements; $(MAKE) -f Makefile

elements1d:
	@cd $(LIBSRC_DIR)/Elements/1D; $(MAKE) -f Makefile

elements2d:
	@cd $(LIBSRC_DIR)/Elements/2D; $(MAKE) -f Makefile

elements3d:
	@cd $(LIBSRC_DIR)/Elements/3D; $(MAKE) -f Makefile

definefiles:
	@cd $(LIBSRC_DIR)/DataInOut/DefineFiles; $(MAKE) -f Makefile

datainout:
	@cd $(LIBSRC_DIR)/DataInOut; $(MAKE) -f Makefile

ansysfile:
	@cd $(LIBSRC_DIR)/DataInOut/AnsysFile; $(MAKE) -f Makefile

ansys-out:
	@cd $(LIBSRC_DIR)/DataInOut/AnsysOut; $(MAKE) -f Makefile

unverg:
	@cd $(LIBSRC_DIR)/DataInOut/Unverg; $(MAKE) -f Makefile

gmv:
	@cd $(LIBSRC_DIR)/DataInOut/GMV; $(MAKE) -f Makefile

database:
	@cd $(LIBSRC_DIR)/DataInOut/Database; $(MAKE) -f Makefile

gsi:
	@cd $(LIBSRC_DIR)/DataInOut/GSI; $(MAKE) -f Makefile

#algsys-own:
#	@cd $(LIBSRC_DIR)/AlgebraicSystem/LinAlg; $(MAKE) -f Makefile

utils:
	@cd $(LIBSRC_DIR)/Utils; $(MAKE) -f Makefile

matrix:
	@cd $(LIBSRC_DIR)/Matrix; $(MAKE) -f Makefile

general:
	@cd $(LIBSRC_DIR)/General; $(MAKE) -f Makefile

multigrid-las:
	@cd $(LibCLA)/multigrid; $(MAKE) -f Makefile

mpccicpl:
	@cd $(LIBSRC_DIR)/MpCCIcpl; $(MAKE) -f Makefile

paramhandling:
	@cd $(LIBSRC_DIR)/DataInOut/ParamHandling; $(MAKE) -f Makefile

odesolve:
	@cd $(LIBSRC_DIR)/ODESolve; $(MAKE) -f Makefile

odedescr:
	@cd $(LIBSRC_DIR)/ODEDescr; $(MAKE) -f Makefile
