SET( CGAL_CFG_NO_LIMITS 0 CACHE STRING Result FORCE)
SET( MPFR_RUN_RES__TRYRUN_OUTPUT
     "version=2.4.0"
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( MPFR_RUN_RES 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_WARNING_CPP_DIRECTIVE_BUG 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_MATCHING_BUG_5 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG 0 CACHE STRING Result FORCE)
SET( GMP_RUN_RES__TRYRUN_OUTPUT
     "version=4.2.4"
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( GMP_RUN_RES 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_USING_BASE_MEMBER_BUG_2 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_TMPL_IN_TMPL_PARAM 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_IEEE_754_BUG 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_MATCHING_BUG_6 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_TR1_TUPLE 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_STATEMENT_EXPRESSIONS 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_TR1_ARRAY 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG 0 CACHE STRING Result FORCE)
SET( ZLIB_RUN_RES__TRYRUN_OUTPUT
     "version=1.2.6"
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( ZLIB_RUN_RES 0 CACHE STRING Result FORCE)
SET( GCC_RUN_RES__TRYRUN_OUTPUT
     "version=4.5.3 20110428 (Fedora MinGW 4.5.3-2.el6)"
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( GCC_RUN_RES 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG
     "A's do_something
C's do_something
B's do_something
C's do_something
"
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_NEXTAFTER 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_LOGICAL_OPERATORS_ALTERNATIVES 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_CPP0X_DELETED_AND_DEFAULT_FUNCTIONS 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_MESSAGE_PRAGMA_BUG 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_DENORMALS_COMPILE_BUG 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_ISTREAM_INT_BUG__TRYRUN_OUTPUT
     "7812"
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( CGAL_CFG_ISTREAM_INT_BUG 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_STL 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_CPP0X_ISFINITE 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NO_CPP0X_LONG_LONG 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_NUMERIC_LIMITS_BUG 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_LONGNAME_BUG 0 CACHE STRING Result FORCE)
SET( CGAL_CFG_ARRAY_MEMBER_INITIALIZATION_BUG 0 CACHE STRING Result FORCE)