# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# GCC_RUN_RES
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set GCC_RUN_RES to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# GCC_RUN_RES__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set GCC_RUN_RES__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The GCC_COMPILE_RES variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/support/print_GCC_version.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec933278999-GCC_RUN_RES
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( GCC_RUN_RES 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( GCC_RUN_RES__TRYRUN_OUTPUT 
     "version=4.2.1 (Apple Inc. build 5646)"
     CACHE STRING "Output from TRY_RUN" FORCE)


# GMP_RUN_RES
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set GMP_RUN_RES to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# GMP_RUN_RES__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set GMP_RUN_RES__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The GMP_COMPILE_RES variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/support/print_GMP_version.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec3221488041-GMP_RUN_RES
# Run arguments : 
#    Called from: [2]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/cmake/modules/CGAL_SetupDependencies.cmake
#                 [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( GMP_RUN_RES 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( GMP_RUN_RES__TRYRUN_OUTPUT 
     "version=4.2.4"
     CACHE STRING "Output from TRY_RUN" FORCE)


# MPFR_RUN_RES
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set MPFR_RUN_RES to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# MPFR_RUN_RES__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set MPFR_RUN_RES__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The MPFR_COMPILE_RES variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/support/print_MPFR_version.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec749268670-MPFR_RUN_RES
# Run arguments : 
#    Called from: [2]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/cmake/modules/CGAL_SetupDependencies.cmake
#                 [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( MPFR_RUN_RES 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( MPFR_RUN_RES__TRYRUN_OUTPUT 
     "version=2.4.0"
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_DENORMALS_COMPILE_BUG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_DENORMALS_COMPILE_BUG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_DENORMALS_COMPILE_BUG__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_DENORMALS_COMPILE_BUG__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_DENORMALS_COMPILE_BUG_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_DENORMALS_COMPILE_BUG.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec2210889627-CGAL_CFG_DENORMALS_COMPILE_BUG
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_DENORMALS_COMPILE_BUG 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_DENORMALS_COMPILE_BUG__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec1373048546-CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_FPU_ROUNDING_MODE_UNWINDING_VC_BUG__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_IEEE_754_BUG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_IEEE_754_BUG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_IEEE_754_BUG__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_IEEE_754_BUG__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_IEEE_754_BUG_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_IEEE_754_BUG.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec2174176496-CGAL_CFG_IEEE_754_BUG
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_IEEE_754_BUG 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_IEEE_754_BUG__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_ISTREAM_INT_BUG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_ISTREAM_INT_BUG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_ISTREAM_INT_BUG__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_ISTREAM_INT_BUG__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_ISTREAM_INT_BUG_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_ISTREAM_INT_BUG.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec1949046932-CGAL_CFG_ISTREAM_INT_BUG
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_ISTREAM_INT_BUG 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_ISTREAM_INT_BUG__TRYRUN_OUTPUT 
     "7812"
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_MATCHING_BUG_5
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_MATCHING_BUG_5 to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_MATCHING_BUG_5__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_MATCHING_BUG_5__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_MATCHING_BUG_5_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_MATCHING_BUG_5.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec3482677807-CGAL_CFG_MATCHING_BUG_5
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_MATCHING_BUG_5 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_MATCHING_BUG_5__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_MATCHING_BUG_6
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_MATCHING_BUG_6 to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_MATCHING_BUG_6__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_MATCHING_BUG_6__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_MATCHING_BUG_6_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_MATCHING_BUG_6.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec3822229352-CGAL_CFG_MATCHING_BUG_6
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_MATCHING_BUG_6 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_MATCHING_BUG_6__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec535718095-CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_NESTED_CLASS_FRIEND_DECLARATION_BUG__TRYRUN_OUTPUT 
     "A's do_something;C's do_something;B's do_something;C's do_something"
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_NO_LIMITS
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_NO_LIMITS to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_NO_LIMITS__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_NO_LIMITS__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_NO_LIMITS_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_NO_LIMITS.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec720245518-CGAL_CFG_NO_LIMITS
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_NO_LIMITS 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_NO_LIMITS__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_NO_NEXTAFTER
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_NO_NEXTAFTER to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_NO_NEXTAFTER__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_NO_NEXTAFTER__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_NO_NEXTAFTER_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_NO_NEXTAFTER.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec3179046693-CGAL_CFG_NO_NEXTAFTER
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_NO_NEXTAFTER 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_NO_NEXTAFTER__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_NO_STL
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_NO_STL to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_NO_STL__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_NO_STL__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_NO_STL_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_NO_STL.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec3715950256-CGAL_CFG_NO_STL
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_NO_STL 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_NO_STL__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_NO_WARNING_CPP_DIRECTIVE_BUG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_NO_WARNING_CPP_DIRECTIVE_BUG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_NO_WARNING_CPP_DIRECTIVE_BUG__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_NO_WARNING_CPP_DIRECTIVE_BUG__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_NO_WARNING_CPP_DIRECTIVE_BUG_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_NO_WARNING_CPP_DIRECTIVE_BUG.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec2410228301-CGAL_CFG_NO_WARNING_CPP_DIRECTIVE_BUG
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_NO_WARNING_CPP_DIRECTIVE_BUG 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_NO_WARNING_CPP_DIRECTIVE_BUG__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_NUMERIC_LIMITS_BUG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_NUMERIC_LIMITS_BUG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_NUMERIC_LIMITS_BUG__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_NUMERIC_LIMITS_BUG__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_NUMERIC_LIMITS_BUG_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_NUMERIC_LIMITS_BUG.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec2151649956-CGAL_CFG_NUMERIC_LIMITS_BUG
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_NUMERIC_LIMITS_BUG 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_NUMERIC_LIMITS_BUG__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec1342780927-CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_OUTOFLINE_MEMBER_DEFINITION_BUG__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec4194474576-CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_TEMPLATE_IN_DEFAULT_PARAMETER_BUG__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec3832402053-CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_TYPENAME_BEFORE_DEFAULT_ARGUMENT_BUG__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# CGAL_CFG_USING_BASE_MEMBER_BUG_2
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CGAL_CFG_USING_BASE_MEMBER_BUG_2 to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CGAL_CFG_USING_BASE_MEMBER_BUG_2__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CGAL_CFG_USING_BASE_MEMBER_BUG_2__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The CGAL_CFG_USING_BASE_MEMBER_BUG_2_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/testfiles/CGAL_CFG_USING_BASE_MEMBER_BUG_2.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec3424686821-CGAL_CFG_USING_BASE_MEMBER_BUG_2
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/CMakeLists.txt

SET( CGAL_CFG_USING_BASE_MEMBER_BUG_2 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CGAL_CFG_USING_BASE_MEMBER_BUG_2__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# ZLIB_RUN_RES
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set ZLIB_RUN_RES to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# ZLIB_RUN_RES__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set ZLIB_RUN_RES__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The ZLIB_COMPILE_RES variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/config/support/print_ZLIB_version.cpp
# Executable    : /home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal-build/CMakeFiles/cmTryCompileExec1495609990-ZLIB_RUN_RES
# Run arguments : 
#    Called from: [1]	/home/strieben/Documents/dev/CFS_BUILD/FESPACE_MACOSX/cfsdeps/cgal/src/cgal/src/CGAL_ImageIO/CMakeLists.txt

SET( ZLIB_RUN_RES 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( ZLIB_RUN_RES__TRYRUN_OUTPUT 
     "version=1.2.7"
     CACHE STRING "Output from TRY_RUN" FORCE)

