baseDir='./';
fileName='directivity.csv';
 
% Read values from CSV file generated by ParaView
csv=csvread(strcat(baseDir, fileName), 1, 0);
 
% Assign x- and y-coordinate vectors
x=csv(:,3);
y=csv(:,5);
 
angles_rad=atan2(y, x);
angles_deg=angles_rad / pi * 180;
 
% Sort vector with ascending degree values before plotting!
% Also assign the necessary permutiations to an index vector
[angles2,perm]=sortrows(angles_deg);
values=csv(:,1);
 
% Calculate the dezibel values
% Reference pressure in air: 2e-5 Pa = 20 micropascals
% Reference pressure in water and other liquids: 1e-6 Pa = 1 micropascals
dbvalues=20*log10(values / 2e-5)
 
% Store x-, y-, angles(rad), angles(degree), values, values(dB)
% in matrix to save it in gnuplot format
matrix=zeros(length(angles2), 6)
matrix(:,1) = x(perm);
matrix(:,2) = y(perm);
matrix(:,3) = angles_rad(perm);
matrix(:,4) = angles_deg(perm);
matrix(:,5) = values(perm);
matrix(:,6) = dbvalues(perm);
save ("-ascii", "directivity.dat", "matrix")