SET(CTEST_PROJECT_NAME "CFS")
SET(CTEST_NIGHTLY_START_TIME "00:00:00 CET")

SET(CTEST_DROP_METHOD "http")
SET(CTEST_DROP_SITE "cfs.mdmt.tuwien.ac.at:1022")
SET(CTEST_DROP_LOCATION "/cdash/submit.php?project=CFS")
SET(CTEST_DROP_SITE_CDASH TRUE)
