# env -i HOME=/Users/simon PATH=/bin:/usr/bin:/sbin:/usr/sbin /Users/simon/Applications/CMake\ 2.8-8.app/Contents/bin/cmake -P Documents/dev/nightly_test.cmake
# vagrant ssh -c 'env -i HOME=/Users/simon PATH=/bin:/usr/bin:/sbin:/usr/sbin env && uname -a && /opt/pckg/cmake-2.8.10.2-Linux-i386/bin/cmake --version'
MESSAGE("CMAKE_COMMAND: ${CMAKE_COMMAND}")
MESSAGE("WIN32 ${WIN32}")
IF(WIN32)
SET(CMAKE_EXECUTABLE_SUFFIX ".exe")
ENDIF()
MESSAGE("CMAKE_EXECUTABLE_SUFFIX: ${CMAKE_EXECUTABLE_SUFFIX}")
STRING(REGEX REPLACE "/cmake${CMAKE_EXECUTABLE_SUFFIX}$" "/ctest${CMAKE_EXECUTABLE_SUFFIX}" CTEST_COMMAND "${CMAKE_COMMAND}")
MESSAGE("CTEST_COMMAND: ${CTEST_COMMAND}")
MESSAGE("CMAKE_CURRENT_LIST_FILE: ${CMAKE_CURRENT_LIST_FILE}")
GET_FILENAME_COMPONENT(SITE_BASE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
SET(SITE_BASE_DIR "${SITE_BASE_DIR}/sites")
MESSAGE("SITE_BASE_DIR: ${SITE_BASE_DIR}")

SITE_NAME(HOSTNAME)
STRING(REPLACE "." ";" HOSTNAME_LIST "${HOSTNAME}")
LIST(GET HOSTNAME_LIST 0 HOSTNAME) 
MESSAGE("HOSTNAME: ${HOSTNAME}")

SET(SITE_DIR "${SITE_BASE_DIR}/${HOSTNAME}")
MESSAGE("SITE_DIR: ${SITE_DIR}")

EXECUTE_PROCESS(
  COMMAND date "+%u"
  OUTPUT_VARIABLE DAYOFWEEK
  RESULT_VARIABLE RETVAL
  )
STRING(REPLACE "\n" "" DAYOFWEEK "${DAYOFWEEK}")
MESSAGE("DAYOFWEEK: ${DAYOFWEEK}")

MESSAGE(STATUS "Environment:")
EXECUTE_PROCESS(
  COMMAND "${CMAKE_COMMAND}" -E environment
#  WORKING_DIRECTORY "${BUILDDIR}"
  RESULT_VARIABLE RETVAL
  )
MESSAGE("HANS-GEORG")

MACRO(PERFORM_TEST TEST_NAME)
  IF(UNIX)
    STRING(REPLACE "_" ";" TARGET_ARCH_ENV_LIST "${TEST_NAME}")
    LIST(GET TARGET_ARCH_ENV_LIST 0 TARGET_ARCH) 
    
    IF(TARGET_ARCH MATCHES "linux[0-9][0-9]")
      EXECUTE_PROCESS(
        COMMAND ${TARGET_ARCH} ${CTEST_COMMAND} -V -S "${SITE_DIR}/${TEST_NAME}.ctest"
        WORKING_DIRECTORY "."
        RESULT_VARIABLE RETVAL
      )
    ELSE()
      EXECUTE_PROCESS(
        COMMAND ${CTEST_COMMAND} -V -S "${SITE_DIR}/${TEST_NAME}.ctest"
        WORKING_DIRECTORY "."
        RESULT_VARIABLE RETVAL
      )
    ENDIF()
  ELSE(UNIX)

  LIST(APPEND TEST_CMD "\\\"${CTEST_COMMAND}\\\"" -V -S "\\\"${SITE_DIR}/${TEST_NAME}.ctest\\\"")

  MESSAGE(STATUS "TEST_CMD: ${TEST_CMD}")

  EXECUTE_PROCESS(
    COMMAND ${CTEST_COMMAND} -V -S "${SITE_DIR}/${TEST_NAME}.ctest"
    WORKING_DIRECTORY "."
    RESULT_VARIABLE RETVAL
    )

  ENDIF(UNIX)
ENDMACRO()

MACRO(DEPLOY_TEST TEST_NAME)
  MESSAGE("DEPLOY_TEST() needs to be implemented")
ENDMACRO()

MACRO(CLEANUP_TEST TEST_NAME)
  MESSAGE("Cleaning up ${CTEST_BINARY_DIRECTORY}")

#  FILE(REMOVE_RECURSE "${CTEST_BINARY_DIRECTORY}")
ENDMACRO()

macro(temp_name fname)
  if(${ARGC} GREATER 1) # Have to escape ARGC to correctly compare
    set(_base ${ARGV1})
  else(${ARGC} GREATER 1)
    set(_base ".cmake-tmp")
  endif(${ARGC} GREATER 1)
  set(_counter 0)
  while(EXISTS "${_base}${_counter}")
    math(EXPR _counter "${_counter} + 1")
  endwhile(EXISTS "${_base}${_counter}")
  set(${fname} "${_base}${_counter}")
endmacro(temp_name)

# Evaluate expression
# Suggestion from the Wiki: http://cmake.org/Wiki/CMake/Language_Syntax
# Unfortunately, no built-in stuff for this: http://public.kitware.com/Bug/view.php?id=4034
macro(eval expr)
  temp_name(_fname)
  file(WRITE ${_fname} "${expr}")
  include(${_fname})
  file(REMOVE ${_fname})
endmacro(eval)


MACRO(GET_CTEST_BINARY_DIRECTORY TEST_NAME)
  FILE(STRINGS "${SITE_DIR}/${TEST_NAME}.ctest" FSTR)

  FOREACH(LINE IN LISTS FSTR)
    IF(LINE MATCHES "SET\\(CTEST_BINARY_DIRECTORY")
      SET(CTEST_BINARY_DIRECTORY_STR "${LINE}")
    ENDIF()
  ENDFOREACH()

#  EXECUTE_PROCESS(
#    COMMAND mktemp -t nightly_test_XXXX
#    WORKING_DIRECTORY "."
#    OUTPUT_VARIABLE TMPFILE
#    RESULT_VARIABLE RETVAL
#    )
#  STRING(REPLACE "\n" "" TMPFILE "${TMPFILE}")

#  MESSAGE("TMPFILE ${TMPFILE}")

#  FILE(WRITE "${TMPFILE}" "${CTEST_BINARY_DIRECTORY_STR}")

#  INCLUDE("${TMPFILE}")
  STRING(REPLACE "\$ENV{" "\\\$ENV{" CTEST_BINARY_DIRECTORY_STR "${CTEST_BINARY_DIRECTORY_STR}")
  MESSAGE(STATUS "CTEST_BINARY_DIRECTORY_STR ${CTEST_BINARY_DIRECTORY_STR}")
  EVAL("${CTEST_BINARY_DIRECTORY_STR}")
  file(TO_CMAKE_PATH "${CTEST_BINARY_DIRECTORY}" CTEST_BINARY_DIRECTORY)
  MESSAGE(STATUS "CTEST_BINARY_DIRECTORY ${CTEST_BINARY_DIRECTORY}")

#  FILE(REMOVE "${TMPFILE}")
ENDMACRO()

MESSAGE("FRANZ-FERDINAND")
FILE(GLOB TEST_FILES "${SITE_DIR}/*.ctest")
MESSAGE("WALBURGA ${TEST_FILES}")
FOREACH(F IN ITEMS "${TEST_FILES}")

  MESSAGE("BARBARA")
  GET_FILENAME_COMPONENT(TEST_NAME "${F}" NAME_WE)
  MESSAGE("Performing test: ${TEST_NAME}...")
  GET_CTEST_BINARY_DIRECTORY(${TEST_NAME})
  PERFORM_TEST(${TEST_NAME})
  DEPLOY_TEST(${TEST_NAME})
  CLEANUP_TEST(${TEST_NAME})

ENDFOREACH()

