#
C_DIR=../..
#
src = matrix.cc symmatrix.cc bandmatrix.cc sparsematrix.cc
#symbandmatrix.cc sparsematrix.cc symsparsematrixCRS.cc 
#
lib = matrix
libpath = libsrc/Matrix
CFLAGS3 =
#
include ../makefile.inc
