#!/usr/bin/env python3
"""Generate a tiny 3D hex block (openCFS HDF5) for the SmoothPrescribedFlap preCICE
test, plus the spec for the mock "Dummy" partner.

This exercises the SmoothPDE "prescribed displacement" mode fed via preCICE:
  * Dummy  : the C++ mock partner (mock_fluid). Provides a single-vertex mesh and
             writes a spatially-uniform, linearly-ramped displacement vector
             (DisplacementVolume).
  * Solid  : openCFS (SmoothPDE). Receives the value on its whole-volume NODE mesh
             via nearest-neighbour mapping (so every node gets the same vector) and
             injects it directly into SMOOTH_DISPLACEMENT (no solve), exporting it as
             smoothDisplacement.

The actual geometry is irrelevant (no solve), so we use a deliberately tiny block
to keep the reference well below 1 MB and the run well under a second. Serial-explicit
coupling (Dummy first) => fully deterministic => comparable against a committed .h5ref.

Outputs (written next to this script):
  * SmoothPrescribedFlap_mesh.h5 : openCFS HDF5 mesh (volume region "Solid")
  * mock_fluid.spec              : the Dummy partner's mesh + write data
"""
import os
import numpy as np
import h5py

# --- geometry / discretisation (tiny on purpose) ---
L, H, W = 0.01, 0.001, 0.001   # block dimensions [m]
NX, NY, NZ = 4, 1, 1           # elements per axis -> 4 HEXA8, 20 nodes

ET_HEXA8 = 11                  # source/Domain/ElemMapping/Elem.hh
HERE = os.path.dirname(os.path.abspath(__file__))


def node_id(i, j, k):
    """1-based node id of grid point (i in 0..NX, j in 0..NY, k in 0..NZ)."""
    return k * (NX + 1) * (NY + 1) + j * (NX + 1) + i + 1


def build():
    coords = []
    for k in range(NZ + 1):
        for j in range(NY + 1):
            for i in range(NX + 1):
                coords.append((i * (L / NX), j * (H / NY), k * (W / NZ)))
    coords = np.array(coords, dtype=np.float64)

    hexes = []
    for k in range(NZ):
        for j in range(NY):
            for i in range(NX):
                hexes.append((node_id(i, j, k),     node_id(i + 1, j, k),
                              node_id(i + 1, j + 1, k), node_id(i, j + 1, k),
                              node_id(i, j, k + 1),   node_id(i + 1, j, k + 1),
                              node_id(i + 1, j + 1, k + 1), node_id(i, j + 1, k + 1)))
    n_elem = len(hexes)
    conn = np.zeros((n_elem, 8), dtype=np.uint32)
    types = np.full((n_elem,), ET_HEXA8, dtype=np.int32)
    for e, h in enumerate(hexes):
        conn[e, :] = h

    solid_elems = np.arange(1, n_elem + 1, dtype=np.int32)
    solid_nodes = np.arange(1, coords.shape[0] + 1, dtype=np.uint32)

    mesh_path = os.path.join(HERE, "SmoothPrescribedFlap_mesh.h5")
    with h5py.File(mesh_path, "w") as f:
        fi = f.create_group("FileInfo")
        fi.create_dataset("Content", data=np.array([1, 2, 5], dtype=np.int32))
        sdt = h5py.string_dtype(encoding="utf-8")
        fi.create_dataset("Creator", data=np.array(["SmoothPrescribedFlap make_mesh.py"], dtype=object), dtype=sdt)
        fi.create_dataset("Date", data=np.array(["generated"], dtype=object), dtype=sdt)
        fi.create_dataset("Version", data=np.array(["0.9"], dtype=object), dtype=sdt)

        mesh = f.create_group("Mesh")
        mesh.attrs["Dimension"] = np.int32(3)
        nodes = mesh.create_group("Nodes")
        nodes.attrs["NumNodes"] = np.int32(coords.shape[0])
        nodes.create_dataset("Coordinates", data=coords)

        elems = mesh.create_group("Elements")
        elems.attrs["NumElems"] = np.int32(n_elem)
        elems.attrs["Num1DElems"] = np.int32(0)
        elems.attrs["Num2DElems"] = np.int32(0)
        elems.attrs["Num3DElems"] = np.int32(n_elem)
        elems.attrs["Num_HEXA8"] = np.int32(n_elem)
        elems.attrs["QuadraticElems"] = np.int32(0)
        elems.create_dataset("Connectivity", data=conn)
        elems.create_dataset("Types", data=types)

        mesh.create_group("Groups")
        regroup = mesh.create_group("Regions")
        g = regroup.create_group("Solid")
        g.attrs["Dimension"] = np.int32(3)
        g.create_dataset("Elements", data=solid_elems)
        g.create_dataset("Nodes", data=solid_nodes)

    # --- mock "Dummy" partner spec ---
    # Single vertex; with nearest-neighbour mapping every openCFS node receives the
    # same DisplacementVolume, so smoothDisplacement = u(t) everywhere -> easy to verify.
    # u(t) = loadVector * min(t / rampTime, 1), ramped over the first half of the run.
    spec_path = os.path.join(HERE, "mock_fluid.spec")
    with open(spec_path, "w") as s:
        s.write("# mock Dummy partner spec for SmoothPrescribedFlap (generated by make_mesh.py)\n")
        s.write("participant Dummy\n")
        s.write("dimensions 3\n")
        s.write("loadVector 1.0e-3 5.0e-4 0.0\n")
        s.write("rampTime 0.1\n")
        s.write("mesh Dummy-Mesh write DisplacementVolume\n1\n")
        s.write("0.0 0.0005 0.0\n")
        s.write("end\n")

    print(f"wrote {mesh_path}  ({coords.shape[0]} nodes, {n_elem} HEXA8)")
    print(f"wrote {spec_path}")


if __name__ == "__main__":
    build()
