# mock Dummy partner spec for SmoothPrescribedFlap (generated by make_mesh.py)
participant Dummy
dimensions 3
loadVector 1.0e-3 5.0e-4 0.0
rampTime 0.1
mesh Dummy-Mesh write DisplacementVolume
1
0.0 0.0005 0.0
end
