# test_macros.cmake is either called by nightly_test.cmake or by the site specific linux64_shared_opt_no_prec_gcc_release.cmake, ... scripts
if(NOT CTEST_SCRIPTS_DIR)
  # shall be /home/fwein/code/shared/ctest_scripts 
  # test for CMAKE_CURRENT_LIST_DIR=/home/fwein/code/shared/ctest_scripts/shared
  if(CMAKE_CURRENT_LIST_DIR)
    set(CTEST_SCRIPTS_DIR "${CMAKE_CURRENT_LIST_DIR}/..")
  else()
    message(FATAL_ERROR "neither CTEST_SCRIPTS_DIR nor CMAKE_CURRENT_LIST_DIR set")
  endif()  
endif()  

if(NOT CFS_macros)
  include("${CTEST_SCRIPTS_DIR}/../cmake_modules/CFS_macros.cmake")
  assert_set(CFS_macros)
endif()

# Include informations about development server.
include("${CTEST_SCRIPTS_DIR}/../cmake_modules/DevelopmentServer.cmake")

MACRO(SET_GLOBAL_VARS)
  # =========================================================================
  #
  #  Set some global variables.
  #
  #  Some global variables are set using this macro. E.g. the host name
  #  for this site gets determined and paths to the CMake/CTest binaries
  #  are set. Additionally we print out the current environment.
  #
  # =========================================================================

  IF(WIN32)
    SET(CMAKE_EXECUTABLE_SUFFIX ".exe")
  ENDIF()
  STRING(REGEX REPLACE "/cmake${CMAKE_EXECUTABLE_SUFFIX}$" "/ctest${CMAKE_EXECUTABLE_SUFFIX}" CTEST_COMMAND "${CMAKE_COMMAND}")
  GET_FILENAME_COMPONENT(SITE_BASE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
  SET(SITE_BASE_DIR "${SITE_BASE_DIR}/sites")
  SITE_NAME(HOSTNAME)
  STRING(STRIP ${HOSTNAME} HOSTNAME)
  STRING(REPLACE "." ";" HOSTNAME_LIST "${HOSTNAME}")
  LIST(GET HOSTNAME_LIST 0 HOSTNAME)
  STRING(TOLOWER ${HOSTNAME} HOSTNAME)
  SET(SITE_DIR "${SITE_BASE_DIR}/${HOSTNAME}")
  EXECUTE_PROCESS(
    COMMAND date "+%u"
    OUTPUT_VARIABLE DAYOFWEEK
    RESULT_VARIABLE RETVAL
    )
  STRING(REPLACE "\n" "" DAYOFWEEK "${DAYOFWEEK}")

  #---------------------------------------------------------------------------
  # Set destination directory for nightly built binaries
  #---------------------------------------------------------------------------
  SET(NIGHTLY_ARCHIVES_DIR "/opt/pckg/cfs_nightly/archives")
ENDMACRO()

MACRO(SET_SITE_SPECIFIC_VARS)

  # =========================================================================
  #
  #  Set some site-specific variables.
  #
  #  If the some special variables are required for a certain site, this
  #  can be achieved by setting them in ${SITE_DIR}/site_specific_vars.cmake
  #
  # =========================================================================

  IF(UNIX)
    # Set user name
    EXECUTE_PROCESS(
      COMMAND id -un
      OUTPUT_VARIABLE TESTUSER
      RESULT_VARIABLE RETVAL
    )
    STRING(STRIP ${TESTUSER} TESTUSER)

    # Set home directory
    EXECUTE_PROCESS(
      COMMAND getent passwd ${TESTUSER}
      OUTPUT_VARIABLE PWDLINE
      RESULT_VARIABLE RETVAL
    )
    STRING(REPLACE ":" ";" PWDLINE ${PWDLINE})

    LIST(GET PWDLINE 5 HOME)
  ENDIF()

  INCLUDE("${SITE_DIR}/site_specific_vars.cmake" OPTIONAL)

  # this would print all variables
  #EXECUTE_PROCESS(COMMAND "${CMAKE_COMMAND}" -E environment  RESULT_VARIABLE RETVAL)

ENDMACRO()



MACRO(GET_TEST_NAMES TEST_NAME_LIST)

  # =========================================================================
  #
  #  Generate list of test names.
  #
  #  By default the list of tests is generated by globbing all .ctest files
  #  in the site directory. On some machines, however, the order of tests is
  #  important.
  #  This can e.g. be the case, when nightly binaries for a network share
  #  should generated first and the more unimportant tests should be
  #  performed later on.
  #  Therefore, the creator of new tests can specify the order in which
  #  they will be performed in an additional generate_test_name_list.cmake
  #  file in which the macro GENERATE_TEST_NAME_LIST() has to be specified.
  #
  # =========================================================================

  SET(TEST_LIST_GEN_FN "${SITE_DIR}/generate_test_name_list.cmake")
  IF(NOT EXISTS "${TEST_LIST_GEN_FN}")
    FILE(GLOB TEST_FILES "${SITE_DIR}/*.ctest")

    FOREACH(TESTFN IN ITEMS ${TEST_FILES})

      GET_FILENAME_COMPONENT(TEST_NAME "${TESTFN}" NAME_WE)
      list(APPEND ${TEST_NAME_LIST} ${TEST_NAME})
    ENDFOREACH()
  ELSE()
    INCLUDE("${TEST_LIST_GEN_FN}")
    GENERATE_TEST_NAME_LIST(${TEST_NAME_LIST})
  ENDIF()
ENDMACRO()



MACRO(PERFORM_TEST TEST_NAME)

  # =========================================================================
  #
  #  Actually perform tests.
  #
  #  We distinguish if we are on UNIX (mainly Linux) or on Windows.
  #  For x86/amd64 Linux machines one can choose if the program should run
  #  in 32-bit or 64-bit environment by prefixing a command with linux32
  #  or linux64. This enables us to build 32-bit binaries on a x86_64
  #  machine. The type of environment for a test can therefore be chosen
  #  by prefixing the test file name with linux32_ or linux64_.
  #  
  # =========================================================================

  headline("Performing test: ${TEST_NAME}...")

  # this is unnecessary use: SET(CTEST_START_WITH_EMPTY_BINARY_DIRECTORY TRUE) instead
  #IF(EXISTS "${CTEST_BINARY_DIRECTORY}")
  #  MESSAGE("Removing previous build directory ${CTEST_BINARY_DIRECTORY}...")
  #  FILE(REMOVE_RECURSE "${CTEST_BINARY_DIRECTORY}")
  #ENDIF()

  if(UNIX)
    STRING(REPLACE "_" ";" TARGET_ARCH_ENV_LIST "${TEST_NAME}")
    LIST(GET TARGET_ARCH_ENV_LIST 0 TARGET_ARCH)

    IF(TARGET_ARCH MATCHES "linux[0-9][0-9]")
      EXECUTE_PROCESS(
        COMMAND ${TARGET_ARCH} ${CTEST_COMMAND} -V -S "${SITE_DIR}/${TEST_NAME}.ctest"
        WORKING_DIRECTORY "."
        RESULT_VARIABLE RETVAL)
    ELSE()
      EXECUTE_PROCESS(
        COMMAND ${CTEST_COMMAND} -V -S "${SITE_DIR}/${TEST_NAME}.ctest"
        WORKING_DIRECTORY "."
        RESULT_VARIABLE RETVAL)
    ENDIF()
  else()
    LIST(APPEND TEST_CMD "\\\"${CTEST_COMMAND}\\\"" -V -S "\\\"${SITE_DIR}/${TEST_NAME}.ctest\\\"")
    MESSAGE(STATUS "TEST_CMD: ${TEST_CMD}")
    EXECUTE_PROCESS(
      COMMAND ${CTEST_COMMAND} -V -S "${SITE_DIR}/${TEST_NAME}.ctest"
      WORKING_DIRECTORY "."
      RESULT_VARIABLE RETVAL)
  endif()

  # Copy nightly test logs of CTest over to ${SITE_DIR}/logs/${TEST_NAME}
  # so that they may be examined even if the corresponding VBox is already
  # deleted.
  IF(NOT EXISTS "${SITE_DIR}/logs")
    FILE(MAKE_DIRECTORY "${SITE_DIR}/logs")
  ENDIF()
  IF(EXISTS "${SITE_DIR}/logs/${TEST_NAME}")
    FILE(REMOVE_RECURSE "${SITE_DIR}/logs/${TEST_NAME}")
  ENDIF()
  FILE(MAKE_DIRECTORY "${SITE_DIR}/logs/${TEST_NAME}")

  EXECUTE_PROCESS(
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${CTEST_BINARY_DIRECTORY}/Testing"  "${SITE_DIR}/logs/${TEST_NAME}"
    RESULT_VARIABLE RETVAL)

  EXECUTE_PROCESS(
    COMMAND ${CMAKE_COMMAND} -E copy "${CTEST_BINARY_DIRECTORY}/CMakeCache.txt"  "${SITE_DIR}/logs/${TEST_NAME}/CMakeCache.txt"
    RESULT_VARIABLE RETVAL)

ENDMACRO()



#  Deploy built binaries.
#
#  For some tests, we do not want to throw away the built binaries but
#  rather make them available to others via a network share.
#  
#  This macro looks for a script ${SITE_DIR}/${TEST_NAME}_deploy.cmake
#  in which the actions for the deployment of the binaries can be carried
#  out. If the script can be found it will be exectued. If no such script
#  exists, nothing will happen.
MACRO(DEPLOY_TEST TEST_NAME)

  SET(DEPLOY_SCRIPT "${SITE_DIR}/${TEST_NAME}_deploy.cmake")
  IF(EXISTS "${DEPLOY_SCRIPT}")
    EXECUTE_PROCESS(
      COMMAND ${CTEST_COMMAND} -DCMAKE_COMMAND:FILEPATH=${CMAKE_COMMAND} -DNIGHTLY_ARCHIVES_DIR:PATH=${NIGHTLY_ARCHIVES_DIR} -DHOSTNAME:STRING=${HOSTNAME} -DTEST_NAME:STRING=${TEST_NAME} -S "${DEPLOY_SCRIPT}"
      WORKING_DIRECTORY "${SITE_DIR}"
      RESULT_VARIABLE RETVAL
      )
  ENDIF()
ENDMACRO()


#  Clean up after test has finished.
#
#  Does nothing at the moment...
MACRO(CLEANUP_TEST TEST_NAME)
  MESSAGE("Would cleaning up ${CTEST_BINARY_DIRECTORY} it there would be anything implemented...")
ENDMACRO()



MACRO(TEMP_NAME fname)

  # =========================================================================
  #
  #  Create temp file name.
  #
  # =========================================================================

  if(${ARGC} GREATER 1) # Have to escape ARGC to correctly compare
    set(_base ${ARGV1})
  else(${ARGC} GREATER 1)
    set(_base "cmake_tmp")
  endif(${ARGC} GREATER 1)

  SET(TMP_OK 0)

  IF(UNIX)
    SET(ENV{TMPDIR} "${SITE_DIR}/logs")

    # cf. http://content.hccfl.edu/pollock/ShScript/TempFile.htm
    EXECUTE_PROCESS(
      COMMAND mktemp
      WORKING_DIRECTORY "."
      OUTPUT_VARIABLE TMPFILE
      RESULT_VARIABLE RETVAL
      )

    UNSET(ENV{TMPDIR})
    # If RETVAL is zero everything went fine.
    IF(NOT RETVAL)
      STRING(REPLACE "\n" "" ${fname} "${TMPFILE}")
      SET(TMP_OK 1)
    ENDIF()
  ENDIF()

  IF(NOT TMP_OK)
    set(_counter 0)
    while(EXISTS "${SITE_DIR}/logs/${_base}${_counter}.cmake")
      math(EXPR _counter "${_counter} + 1")
    endwhile(EXISTS "${SITE_DIR}/logs/${_base}${_counter}.cmake")
    set(${fname} "${SITE_DIR}/logs/${_base}${_counter}.cmake")
    SET(TMP_OK 1)
  ENDIF()
endmacro()



MACRO(EVAL expr)

  # =========================================================================
  #
  #  Evaluate expression
  #  Suggestion from the Wiki: http://cmake.org/Wiki/CMake/Language_Syntax
  #  Unfortunately, no built-in stuff for this:
  #  http://public.kitware.com/Bug/view.php?id=4034
  #
  # =========================================================================

  temp_name(_fname eval)
  file(WRITE ${_fname} "${expr}")
  include(${_fname})
  file(REMOVE ${_fname})
endmacro()



MACRO(GET_CTEST_BINARY_DIRECTORY TEST_NAME)

  # =========================================================================
  #
  #  Determine location of binary directory of a test.
  #
  # =========================================================================

  FILE(STRINGS "${SITE_DIR}/${TEST_NAME}.ctest" FSTR)

  FOREACH(LINE IN LISTS FSTR)
    IF(LINE MATCHES "SET\\(CTEST_BINARY_DIRECTORY")
      SET(CTEST_BINARY_DIRECTORY_STR "${LINE}")
    ENDIF()
  ENDFOREACH()

  STRING(REPLACE "\$ENV{" "\\\$ENV{" CTEST_BINARY_DIRECTORY_STR "${CTEST_BINARY_DIRECTORY_STR}")
  # MESSAGE(STATUS "CTEST_BINARY_DIRECTORY_STR ${CTEST_BINARY_DIRECTORY_STR}")
  EVAL("${CTEST_BINARY_DIRECTORY_STR}")
  FILE(TO_CMAKE_PATH "${CTEST_BINARY_DIRECTORY}" CTEST_BINARY_DIRECTORY)
  MESSAGE(STATUS "CTEST_BINARY_DIRECTORY ${CTEST_BINARY_DIRECTORY}")

ENDMACRO()



#  Perform site-specific initialization before testing.
#
#  A site can provide ${SITE_DIR}/site_specific_init.cmake if certain 
#  tasks have to be carried out before testing can start (e.g. update 
#  working copies, kill/start virtual machines, etc.)
MACRO(SITE_SPECIFIC_INIT)
  INCLUDE("${SITE_DIR}/site_specific_init.cmake" OPTIONAL)
ENDMACRO()



#  Perform site-specific finalization after testing.
#
#  A site can provide ${SITE_DIR}/site_specific_finish.cmake if certain
#  tasks have to be carried out after testing has finished (e.g. put built
#  binaries into proper locations, etc.)
MACRO(SITE_SPECIFIC_FINISH)
  INCLUDE("${SITE_DIR}/site_specific_finish.cmake" OPTIONAL)
ENDMACRO()


MACRO(INIT_CACHE CACHE_VAR)
  # =========================================================================
  #
  #  Set parameters in initial cache for features which are required to work
  #  on all sites and tests, no matter what platform defaults have been set.
  #
  # =========================================================================
  SET(${CACHE_VAR}
    "BUILD_TESTING:BOOL=ON
     CMAKE_COLOR_MAKEFILE:BOOL=OFF
     CFSDAT:BOOL=ON
     CFSTOOL:BOOL=ON
     UNIT_TESTS:BOOL=OFF
    "
  )
ENDMACRO()


MACRO(IDENTIFY_DISTRO)
  #-----------------------------------------------------------------------------
  # Identify distro.
  #-----------------------------------------------------------------------------
  EXEC_PROGRAM("${CTEST_SOURCE_DIRECTORY}/share/scripts/distro.sh -c"
    ARGS
    OUTPUT_VARIABLE DISTRO_OUT
    RETURN_VALUE RETVAL)
  FILE(WRITE "${CTEST_BINARY_DIRECTORY}/CMakeFiles/distro_out.cmake" "${DISTRO_OUT}")
  INCLUDE("${CTEST_BINARY_DIRECTORY}/CMakeFiles/distro_out.cmake")
ENDMACRO()

# configures CTestConfig.cmake.in via CTestConfig.cmake.in which is first searched in ctest_scripts/sites/<HOST>/ then in test_scripts/shared/
MACRO(WRITE_CTEST_CONFIG)
  # copy over CTestConfig.cmake.in
  # puts it into the binary dir

  IF(NOT CFS_BUILD_HOST)
    SET(CFS_BUILD_HOST "${HOSTNAME}") # hostname is set in SET_GLOBAL_VARS()
  ENDIF()

  MESSAGE("Copy CTestConfig.cmake config, checking for host ${CFS_BUILD_HOST}")  
  SET(SITE_CTEST_CONFIG "${CTEST_SOURCE_DIRECTORY}/ctest_scripts/sites/${CFS_BUILD_HOST}/CTestConfig.cmake.in")
  MESSAGE("check for ${SITE_CTEST_CONFIG}")
  IF(EXISTS ${SITE_CTEST_CONFIG})
    MESSAGE("  ${SITE_CTEST_CONFIG} -> ${CTEST_BINARY_DIRECTORY}/CTestConfig.cmake")
    CONFIGURE_FILE(${SITE_CTEST_CONFIG} ${CTEST_BINARY_DIRECTORY}/CTestConfig.cmake @ONLY)
  ELSE()
    MESSAGE("  using ${CTEST_SOURCE_DIRECTORY}/ctest_scripts/shared/CTestConfig.cmake.in")
    CONFIGURE_FILE(${CTEST_SOURCE_DIRECTORY}/ctest_scripts/shared/CTestConfig.cmake.in ${CTEST_BINARY_DIRECTORY}/CTestConfig.cmake @ONLY)
  ENDIF()
ENDMACRO()




# define some common macros for this site
# this reduces excessive copy & paste


MACRO(DO_TESTING)
  #-----------------------------------------------------------------------------
  # Start the Update, Configure, Build and Testing
  #-----------------------------------------------------------------------------
  MESSAGE("Start dashboard...")
  SET(CTEST_CMAKE_GENERATOR "Unix Makefiles")
  # see http://www.vtk.org/Wiki/CTest:Nightly,_Experimental,_Continuous
  CTEST_START(Nightly)

  MESSAGE("  Configure")
  FILE(WRITE "${CTEST_BINARY_DIRECTORY}/CMakeCache.txt" ${CTEST_INITIAL_CACHE})
  # some configurations require to repeat the same ctest_configure() command
  CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}" RETURN_VALUE res)
  CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}" RETURN_VALUE res)

  MESSAGE("  Build")
  CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}" RETURN_VALUE res)

  MESSAGE("  Test")
  CTEST_TEST(BUILD "${CTEST_BINARY_DIRECTORY}" RETURN_VALUE res)

  MESSAGE("  Submit as ${CTEST_BUILD_NAME}")
  CTEST_SUBMIT(RETURN_VALUE res)
  MESSAGE("  All done") 
ENDMACRO()

MACRO(DO_CONFIG_AND_TEST)
  #-----------------------------------------------------------------------------
  # Configure and Testing
  #-----------------------------------------------------------------------------
  MESSAGE("Start dashboard...")
  SET(CTEST_CMAKE_GENERATOR "Unix Makefiles")
  CTEST_START(Nightly)
  MESSAGE("  Configure")
  FILE(WRITE "${CTEST_BINARY_DIRECTORY}/CMakeCache.txt" ${CTEST_INITIAL_CACHE})
  CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}" RETURN_VALUE res)
  CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}" RETURN_VALUE res)
  MESSAGE("  Test")
  CTEST_TEST(BUILD "${CTEST_BINARY_DIRECTORY}" RETURN_VALUE res)
  MESSAGE("  Submit as ${CTEST_BUILD_NAME}")
  CTEST_SUBMIT(RETURN_VALUE res)
  MESSAGE("  All done")
ENDMACRO()


MACRO(SET_COMPILER_ENV COMPILER_TYPE)
  MESSAGE("Setting environment for ${COMPILER_TYPE}")
  # =========================================================================
  #
  #  Set evironment for different compilers (gcc and intel)
  #
  # =========================================================================
  IF(${COMPILER_TYPE} STREQUAL "GCC")
    #-----------------------------------------------------------------------------
    # Set the following environment variables for the test run. This can be used
    # to specifiy the compilers and that all messages should be output in English
    # language, so that CTest may properly parse them.
    #-----------------------------------------------------------------------------
    SET(ENV{CC} "/usr/bin/gcc")
    SET(ENV{CXX} "/usr/bin/g++")
    SET(ENV{FC} "/usr/bin/gfortran")

  ELSEIF(${COMPILER_TYPE} STREQUAL "GCC-6")
    # search for compilers from software collections
    EXECUTE_PROCESS(COMMAND scl enable devtoolset-6 -- which gcc
                    OUTPUT_VARIABLE SCL_CC OUTPUT_STRIP_TRAILING_WHITESPACE)
    EXECUTE_PROCESS(COMMAND scl enable devtoolset-6 -- which g++
                    OUTPUT_VARIABLE SCL_CXX OUTPUT_STRIP_TRAILING_WHITESPACE)
    EXECUTE_PROCESS(COMMAND scl enable devtoolset-6 -- which gfortran
                    OUTPUT_VARIABLE SCL_FC OUTPUT_STRIP_TRAILING_WHITESPACE)
    SET(ENV{CC} "${SCL_CC}")
    SET(ENV{CXX} "${SCL_CXX}")
    SET(ENV{FC} "${SCL_FC}")

  ELSEIF(${COMPILER_TYPE} STREQUAL "GCC-7")
    # search for compilers from software collections
    EXECUTE_PROCESS(COMMAND scl enable devtoolset-7 -- which gcc
                    OUTPUT_VARIABLE SCL_CC OUTPUT_STRIP_TRAILING_WHITESPACE)
    EXECUTE_PROCESS(COMMAND scl enable devtoolset-7 -- which g++
                    OUTPUT_VARIABLE SCL_CXX OUTPUT_STRIP_TRAILING_WHITESPACE)
    EXECUTE_PROCESS(COMMAND scl enable devtoolset-7 -- which gfortran
                    OUTPUT_VARIABLE SCL_FC OUTPUT_STRIP_TRAILING_WHITESPACE)
    SET(ENV{CC} "${SCL_CC}")
    SET(ENV{CXX} "${SCL_CXX}")
    SET(ENV{FC} "${SCL_FC}")
    
  # we call this GCC8 insteaf of GCC-8 as we don't use the scl infrastructure as with GCC-6/7  
  elseif(${COMPILER_TYPE} STREQUAL "GCC8")
    set(ENV{CC} "gcc-8")
    set(ENV{CXX} "g++-8")
    set(ENV{FC} "gfortran-8")
    

  ELSEIF(${COMPILER_TYPE} STREQUAL "CLANG")
    SET(ENV{CC} "clang")
    SET(ENV{CXX} "clang++")
    SET(ENV{FC} "gfortran")

  ELSEIF(${COMPILER_TYPE} STREQUAL "ICC")

    # make sure to manuall source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64
    # automatic source removed, still present in revsion 16404

    SET(ENV{CC} "icc")
    SET(ENV{CXX} "icpc")
    SET(ENV{FC} "ifort")
    
  ELSEIF(${COMPILER_TYPE} STREQUAL "MPI")
    SET(ENV{CC} "mpicc")
    SET(ENV{CXX} "mpicxx")
    SET(ENV{FC} "mpif90")

  ELSE()
    MESSAGE("can only set compiler environment for GCC, GCC-6, GCC-7, GCC8, CLANG, ICC or MPI, not for ${COMPILER}!")
  ENDIF()

  SET(ENV{LC_MESSAGES} "C")
  SET(ENV{LC_ALL} "C")
  SET(ENV{LANG} "C")
  SET(ENV{LANGUAGE} "C")

  IDENTIFY_COMPILER()
ENDMACRO()

MACRO(IDENTIFY_COMPILER)
    SET(IDCOMP_TEMPL "${CTEST_SOURCE_DIRECTORY}/share/scripts/identify_compiler.cmake.in")
    SET(COMPILER_ID_FILE "${CTEST_BINARY_DIRECTORY}/CMakeFiles/out.cmake")
    SET(IDENTIFY_COMPILER_SRC "${CTEST_SOURCE_DIRECTORY}/share/scripts/IdentifyCXXCompiler.cpp")
    # determine compiler info
    SET(COMPILER "$ENV{CXX}")
    SET(ID_CXX "${CTEST_BINARY_DIRECTORY}/share/scripts/identify_cxx.cmake")
    CONFIGURE_FILE("${IDCOMP_TEMPL}" "${ID_CXX}" @ONLY)
    # create build/tmp directory
    EXECUTE_PROCESS(COMMAND "${CMAKE_COMMAND}" -E make_directory "${CTEST_BINARY_DIRECTORY}/tmp" WORKING_DIRECTORY "${CTEST_BINARY_DIRECTORY}" RESULT_VARIABLE RETVAL)
    # read ID_CXX
    EXECUTE_PROCESS(COMMAND "${CMAKE_COMMAND}" -P "${ID_CXX}" WORKING_DIRECTORY "${CTEST_BINARY_DIRECTORY}/tmp" RESULT_VARIABLE RETVAL)
    # include compiler info
    INCLUDE("${COMPILER_ID_FILE}")
ENDMACRO()

