#
C_DIR= ../..
include ../../main/Makefile.option
#
src = Optimization.cc SIMP.cc PiezoSIMP.cc DesignElement.cc DesignSpace.cc TransferFunction.cc IPOPT.cc
#
CFLAGS3 =
#
include ../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE
