#ifndef SNOPTBASE_HH_
#define SNOPTBASE_HH_

#include <string>
#include <vector>
#include <iostream>

#include "General/Enum.hh"

namespace CoupledField
{
using std::vector;
using std::string;

class SnOptBase
{
public:
  SnOptBase();

  virtual ~SnOptBase();

  // does the actual work
  virtual int Callback(int* Status, const int n, double* x, int* needF,
      int* nF, double* F, int* needG, int* nG, double* G, char* cu, int* lencu,
      int* iu, int* leniu, double* ru, int* lenru) = 0;
  
protected:

  virtual bool get_nlp_info(int& n, int& m, int& nnz_jac_g) = 0;

  /** overload this method to return the information about the bound
   *  on the variables and constraints. The value that indicates
   *  that a bound does not exist is specified in the parameters
   *  nlp_lower_bound_inf and nlp_upper_bound_inf.  By default,
   *  nlp_lower_bound_inf is -1e19 and nlp_upper_bound_inf is
   *  1e19. (see TNLPAdapter) */
  virtual bool get_bounds_info(int n, double* x_l, double* x_u,
      int m, double* g_l, double* g_u) = 0;

  /** overload this method to return the starting point. The bools
   *  init_x and init_lambda are both inputs and outputs. As inputs,
   *  they indicate whether or not the algorithm wants you to
   *  initialize x and lambda respectively. If, for some reason, the
   *  algorithm wants you to initialize these and you cannot, set
   *  the respective bool to false.
   */
  virtual bool get_starting_point(int n, double* x) = 0;

  /** overload this method to return the value of the objective function */
  virtual bool eval_f(int n, const double* x, double& obj_value) = 0;

  /** overload this method to return the vector of the gradient of
   *  the objective w.r.t. x */
  virtual bool eval_grad_f(int n, const double* x, double* grad_f) = 0;

  /** overload this method to return the vector of constraint values */
  virtual bool eval_g(int n, const double* x, int m, double* g) = 0;

  /** overload this method to return the jacobian of the
   *  constraints. */
  virtual bool eval_jac_g(int n, const double* x, 
      int m, int nele_jac, double* values) = 0;

  /** Generates an message out of the last status (ierr). */
  std::string ToString(int ierr);

  /** Dumps the info block (info and rinfo). For debugging */
  void PrintInfo(std::ostream& os);
  
  /** Helper function for setting an integer option
   *  currently known options are:
   *  minor_iterations_limit: maximum (total!) number of iterations of the simplex method or the QP algo
   *  superbasics_limit: default min{500, #nonlin-vars + 1}, limit of storage allocated for suberbasics variables
   *  timing_level: default = 3, 0 suppresses output
   *  verify_level: \in [-1,.., 3], finite difference checks for gradients
   *  major_print_level: \in {0, 1, 11, 111, 1111, 11111}, controls amount of output
   *  minor_print_level: \in {0, 1, 11}, controls amount of output for QP subproblem
   */
  void SetIntegerValue(const std::string& key, int value);
  
  /** Helper function for setting a real valued option
   *  currently known options are:
   *  major_optimality_tolerance: final accuracy of dual variables
   *  major_feasibility_tolerance: how accurately should the nonlin constraints be fulfilled
   *  minor_feasibility_tolerance: tolerance with which all variables satisfy upper/lower bounds
   *  linesearch_tolerance: \in [0, 1], default 0.9, higher is less accurate
   */
  void SetNumericValue(const std::string& key, double value);

  /** number of function evaluations */
  int f_evals;

  /** number of function evaluations */
  int g_evals;
  
  /** indicates the usage of names for F rows and cols, value of 1 indicates default names generated by snopt */
  int nxname;
  int nFname;
    
  /** snopt variables for output */
  int iSumm;
  int iPrint;
  int iSpecs;
  int DerOpt;
  
  /** some variables that snopt needs for info passing
   *  they must all have size at least 500 */
  int minrw;
  int miniw;
  int mincw;
  int lenrw;
  int leniw;
  int lencw;
  vector<double> rw;
  vector<int> iw;
  vector<char> cw; // must be 8 times larger than lencw!!!
  
  int n; // number of variables
  int nF; // is the number of problem functions (objective and constraints, linear and nonlinear)
  int nG; // number of nonzero nonlinear gradient values
  int lenG; // dimension of the coordinate arrays iGfun, jGvar
  int nA; // number of nonzero linear gradient values
  int lenA;
  
  int nS; // number of superbasic variables
  int nInf;
  double sInf;
  
  // 0 = cold start
  // 1 = same as 0 but more meaningful when a basis file is given
  // 2 = warm start: xstate and Fstate define a valid starting point
  int Start;
  
  /** SnOpt is hard to kill, so if we get the request to stop the optimization, we set this trigger
   *  to really end the optimization! */
  bool stop;
 
  /** reports the result of the call to snOptA. Here is a summary of possible values:
  0  - Optimal solution found, i.e., the primal and dual infeasibilities are negligible.
  1  - The problem is infeasible.
  2  - The problem is unbounded (or badly scaled).
  3  - Too many iterations.
  4  - Feasible solution, but the requested accuracy in the dual infeasibilities could
       not be achieved.
  5  - The Superbasics limit is too small.
  6  - Termination has been requested by the user.
  7  - usrfun seems to be giving incorrect objective derivatives.
  8  - usrfun seems to be giving incorrect constraint derivatives.
  9  - The current point cannot be improved.
  10 - Numerical error in trying to satisfy the linear constraints (or the linearized
       nonlinear constraints). The basis is very ill-conditioned.
  11 - The user signaled undeﬁned functions, but no recovery was possible.
  20 - Not enough storage for the basis factorization.
  21 - Error in basis package.
  22 - The basis is singular after several attempts to factorize it (and add slacks
       where necessary).
  30 - An OLD BASIS ﬁle had dimensions that did not match the current problem.
  32 - System error. Wrong number of basic variables.
  40 - Some input arguments have invalid values.
  41 - The work arrays each must have at least 500 elements.
  42 - Not enough 8-character workspace to solve the problem.
  43 - Not enough integer workspace to solve the problem.
  44 - Not enough real workspace to solve the problem.
  */
  int INFO;
  
  const int ObjRow; // which row of F do we use as objective? -> by definition, it will be 1! NOTE: Me must add one to mesh with fortran
  double ObjAdd; // add this value to objective when outputting
  
  vector<double> x;     // start values
  vector<double> xlow;  // holds the lower bounds on x
  vector<double> xupp;   // holds the upper bounds on x
  vector<double> xmul;
  vector<int> xstate; // is a set of initial states for each x  (0,1,2,3,4,5)
  
  vector<double> F;     // nonlinear objective and constraint terms
  vector<double> Flow;  // holds the lower bounds on F
  vector<double> Fupp;   // holds the upper bounds on F
  vector<double> Fmul;   // set of initial values for the dual variables
  vector<int> Fstate;
  
  vector<double> G;     // nonlinear objective and constraint gradient terms
  vector<int> iGfun; // (iGfun(k),jGvar(k)), k = 1,2,...,nG, define the 
  vector<int> jGvar; // coordinates of the nonzero nonlinear problem derivatives
  
  vector<double> A;     // linear objective and constraint gradient terms
  vector<int> iAfun; // (iAfun(k),jAvar(k)), k = 1,2,...,nA, define the 
  vector<int> jAvar; // coordinates of the nonzero linear problem derivatives
};

} // namespace

#endif
