#-------------------------------------------------------------------------------
# SNOPT (sparse nonlinear optimizer) is a commercial general purpose optimizer
# which can be used efficiently for structural optimization.
#
# The chair applied mathematics 2 (FAU) has a license for the code.
#
# You need to request the encrypted file snopt-7.2.8-cfsdeps.zip with the source 
# from the optimization group. 
# Place snopt-7.2.8-cfsdeps.zip to the cfsdepscache source/snopt directory
# and set the password for the file to CFS_KEY_SNOPT (e.g. in .cfs_platform_defaults.cmake)
#-------------------------------------------------------------------------------

set(SNOPT_PREFIX  "${CMAKE_CURRENT_BINARY_DIR}/cfsdeps/snopt")
set(SNOPT_SOURCE  "${SNOPT_PREFIX}/src/snopt")
# we use this as temporary install directory to alllow packing for precompiled cfsdeps
# for snopt we also need to remove the libblas.a generated by snopt as we have an own one in cfs!
set(SNOPT_INSTALL  "${SNOPT_PREFIX}/install")

# snopt is build by configure, therefore no cmake args needed

# no patches are required

# we do not download but assume the file to magically exist there. It is encrypted!
SET(LOCAL_FILE "${CFS_DEPS_CACHE_DIR}/sources/snopt/${SNOPT_ZIP}")
# we don't check the md5 here

if(NOT EXISTS "${LOCAL_FILE}")
  message(FATAL_ERROR "Please provide the encypted snopt source in ${LOCAL_FILE}") 
endif()

if(NOT CFS_KEY_SNOPT)
  message(FATAL_ERROR "Key for encrypted ${SNOPT_ZIP} required in CFS_KEY_SNOPT. Set e.g. in your ~/.cfs_platform_defaults.cmake")
endif()    

#-------------------------------------------------------------------------------
# After the installation we remove libblas.a, remove the confidental source and
# copy to cfs
#-------------------------------------------------------------------------------
SET(PI_TEMPL "${CFS_SOURCE_DIR}/cfsdeps/snopt/snopt-post_install.cmake.in")
SET(PI "${SNOPT_PREFIX}/snopt-post_install.cmake")
CONFIGURE_FILE("${PI_TEMPL}" "${PI}" @ONLY) 

PRECOMPILED_ZIP_FOR_NOBUILD(PRECOMPILED_PCKG_FILE "snopt" "${SNOPT_VER}")
  
# This should be either PREFIX_DIR/src (install manifest is used for zipping)
# or PREFIX_DIR/install (install directory will be zipped)
SET(TMP_DIR "${SNOPT_PREFIX}/src")

SET(ZIPFROMCACHE "${SNOPT_PREFIX}/snopt-zipFromCache.cmake")
CONFIGURE_FILE("${CFS_SOURCE_DIR}/cmake_modules/cfsdeps_zipFromCache.cmake.in" "${ZIPFROMCACHE}" @ONLY)

SET(ZIPTOCACHE "${SNOPT_PREFIX}/snopt-zipToCache.cmake")
CONFIGURE_FILE("${CFS_SOURCE_DIR}/cmake_modules/cfsdeps_zipToCache.cmake.in" "${ZIPTOCACHE}" @ONLY)

#-------------------------------------------------------------------------------
# The snopt external project
#-------------------------------------------------------------------------------
IF("${CFS_DEPS_PRECOMPILED}" STREQUAL "ON" AND EXISTS "${PRECOMPILED_PCKG_FILE}")
  #-------------------------------------------------------------------------------
  # If precompiled package exists copy files from cache
  #-------------------------------------------------------------------------------
  ExternalProject_Add(snopt
    PREFIX "${SNOPT_PREFIX}"
    DOWNLOAD_COMMAND ${CMAKE_COMMAND} -P "${ZIPFROMCACHE}"
    PATCH_COMMAND ""
    UPDATE_COMMAND ""
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND ""
  )
ELSE("${CFS_DEPS_PRECOMPILED}" STREQUAL "ON" AND EXISTS "${PRECOMPILED_PCKG_FILE}")
  #-------------------------------------------------------------------------------
  # If precompiled package does not exist build external project
  #-------------------------------------------------------------------------------
  ExternalProject_Add(snopt
    PREFIX "${SNOPT_PREFIX}"
    SOURCE_DIR "${SNOPT_SOURCE}"
    # all in the zip is below snopt7
    BINARY_DIR "${SNOPT_SOURCE}/snopt7"
    # don't dowload but simply copy w/o md5 check
    DOWNLOAD_COMMAND ${CMAKE_COMMAND} -E copy ${LOCAL_FILE} ${SNOPT_SOURCE}
    # the zip file is encrypted!
    PATCH_COMMAND unzip -q -u -P ${CFS_KEY_SNOPT} ${SNOPT_ZIP}
    # let it install to the temporay directory where we can remove libblas.a and prepare to copy to precompiled cfsdeps
    # the libs will be created in install/lib64 and we manually copy them to lib64/CFS_ARCH_STR
    CONFIGURE_COMMAND ${SNOPT_SOURCE}/snopt7/configure --prefix=${SNOPT_INSTALL} --libdir=${SNOPT_INSTALL}/lib64/${CFS_ARCH_STR} --disable-shared --enable-static --without-f2c F77=${CMAKE_Fortran_COMPILER} FFLAGS=-O3 
  )
  
  #-------------------------------------------------------------------------------
  # Execute the stuff from snopt-post_install.cmake after installation
  #-------------------------------------------------------------------------------
  ExternalProject_Add_Step(snopt post_install
    COMMAND ${CMAKE_COMMAND} -P "${PI}"
    DEPENDEES install
  )
  
  IF("${CFS_DEPS_PRECOMPILED}" STREQUAL "ON")
    #-------------------------------------------------------------------------------
    # Add custom step to zip a precompiled package to the cache.
    #-------------------------------------------------------------------------------
    ExternalProject_Add_Step(snopt cfsdeps_zipToCache
      COMMAND ${CMAKE_COMMAND} -P "${ZIPTOCACHE}"
      DEPENDEES post_install
      DEPENDS "${ZIPTOCACHE}"
      WORKING_DIRECTORY ${CFS_BINARY_DIR}
    )
  ENDIF()
ENDIF("${CFS_DEPS_PRECOMPILED}" STREQUAL "ON" AND EXISTS "${PRECOMPILED_PCKG_FILE}")

# Add project to global list of CFSDEPS, this allows "make snopt"
SET(CFSDEPS ${CFSDEPS} snopt)

# Determine paths of SNOPT libraries. We have only libs and nothing to include
SET(LD "${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}")
SET(SNOPT_LIBRARY "${LD}/libsnopt.a;${LD}/libsnprint.a" CACHE FILEPATH "SNOPT library.")

MARK_AS_ADVANCED(SNOPT_LIBRARY)
