#-------------------------------------------------------------------------------
# SNOPT (sparse nonlinear optimizer) is a commercial general purpose optimizer
# which can be used efficiently for structural optimization.
#
# The chair applied mathematics 2 (FAU) has a license for the code.
#
# You need to request the encrypted file snopt-7.2.8-cfsdeps.zip with the source 
# from the optimization group. 
# Place snopt-7.2.8-cfsdeps.zip to the cfsdepscache source/snopt directory
# and set the password for the file to CFS_KEY_SNOPT (e.g. in .cfs_platform_defaults.cmake)
#-------------------------------------------------------------------------------

set(SNOPT_PREFIX  "${CMAKE_CURRENT_BINARY_DIR}/cfsdeps/snopt")
set(SNOPT_SOURCE  "${SNOPT_PREFIX}/src/snopt")
# we use this as temporary install directory to alllow packing for precompiled cfsdeps
# for snopt we also need to remove the libblas.a generated by snopt as we have an own one in cfs!
set(SNOPT_INSTALL  "${SNOPT_PREFIX}/install")

# snopt is build by configure, therefore no cmake args needed

# no patches are required

# we do not download but assume the file to magically exist there. It is encrypted!
SET(LOCAL_FILE "${CFS_DEPS_CACHE_DIR}/sources/snopt/${SNOPT_ZIP}")
# we don't check the md5 here

if(NOT EXISTS "${LOCAL_FILE}")
  message(FATAL_ERROR "Please privide the encypted snopt source in ${LOCAL_FILE}") 
endif()

if(NOT CFS_KEY_SNOPT)
  message(FATAL_ERROR "Key for encrypted ${SNOPT_ZIP} required in CFS_KEY_SNOPT. Set e.g. in your ~/.cfs_platform_defaults.cmake")
endif()    

# precompiled cfsdeps not yet implemented!

# the whole build project
ExternalProject_Add(snopt
  PREFIX "${SNOPT_PREFIX}"
  SOURCE_DIR "${SNOPT_SOURCE}"
  # all in the zip is below snopt7
  BINARY_DIR "${SNOPT_SOURCE}/snopt7"
  # don't dowload but simply copy w/o md5 check
  DOWNLOAD_COMMAND ${CMAKE_COMMAND} -E copy ${LOCAL_FILE} ${SNOPT_SOURCE}
  # the zip file is encrypted!
  PATCH_COMMAND unzip -u -P ${CFS_KEY_SNOPT} ${SNOPT_ZIP}
  # let it install to the temporay directory where we can remove libblas.a and prepare to copy to precompiled cfsdeps
  # the libs will be created in install/lib64 and we manually copy them to lib64/CFS_ARCH_STR
  CONFIGURE_COMMAND ${SNOPT_SOURCE}/snopt7/configure --prefix=${SNOPT_INSTALL} --libdir=${SNOPT_INSTALL}/lib64/${CFS_ARCH_STR} --disable-shared --enable-static --without-f2c
)

# after the installation we remove libblas.a, remove the confidental source, copy to cfs and might copy to precompiled cfsdeps
SET(PI_TEMPL "${CFS_SOURCE_DIR}/cfsdeps/snopt/snopt-post_install.cmake.in")
SET(PI "${SNOPT_PREFIX}/snopt-post_install.cmake")
CONFIGURE_FILE("${PI_TEMPL}" "${PI}" @ONLY) 

# execute the stuff from snopt-post_install.cmake after installation
ExternalProject_Add_Step(snopt post_install COMMAND ${CMAKE_COMMAND} -P "${PI}" DEPENDEES install)

# Add project to global list of CFSDEPS, this allows "make snopt"
SET(CFSDEPS ${CFSDEPS} snopt)

# Determine paths of SNOPT libraries. We have only libs and nothing to include
SET(LD "${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}")
SET(SNOPT_LIBRARY "${LD}/libsnopt.a;${LD}/libsnprint.a" CACHE FILEPATH "SNOPT library.")

MARK_AS_ADVANCED(SNOPT_LIBRARY)

