#-------------------------------------------------------------------------------
# SNOPT (sparse nonlinear optimizer) is a commercial general purpose optimizer
# which can be used efficiently for structural optimization.
#
# The chair applied mathematics 2 (FAU) has a license for the code.
#
# You need to request the encrypted file snopt-7.2.8-cfsdeps.zip with the source 
# from the optimization group. 
# Place snopt-7.2.8-cfsdeps.zip to the cfsdepscache source/snopt directory
# and set the password for the file to CFS_KEY_SNOPT (e.g. in .cfs_platform_defaults.cmake)
#-------------------------------------------------------------------------------

set(SNOPT_PREFIX  "${CMAKE_CURRENT_BINARY_DIR}/cfsdeps/snopt")
set(SNOPT_SOURCE  "${SNOPT_PREFIX}/src/snopt")
# we use this as temporary install directory to alllow packing for precompiled cfsdeps
# for snopt we also need to remove the libblas.a generated by snopt as we have an own one in cfs!
set(SNOPT_INSTALL  "${SNOPT_PREFIX}/install")

# snopt is build by configure, therefore no cmake args needed

# no patches are required

SET(MIRRORS 
  "/share/programs/cfsdeps/snopt-7.2.8.zip")

SET(LOCAL_FILE "${CFS_DEPS_CACHE_DIR}/sources/snopt/${SNOPT_ZIP}")
SET(MD5_SUM ${SNOPT_MD5})

SET(DLFN "${SNOPT_PREFIX}/snopt-download.cmake")

CONFIGURE_FILE("${CFS_SOURCE_DIR}/cmake_modules/cfsdeps_download.cmake.in" "${DLFN}" @ONLY)

# we do not download but assume the file to magically exist there. It is encrypted!
SET(LOCAL_FILE1 "${CFS_DEPS_CACHE_DIR}/sources/snopt/${SNOPT_ZIP}") # needs to be replaced because LOCAL_FILE->SNOPT_LOCAL_FILE
# we don't check the md5 here

if(NOT CFS_KEY_SNOPT)
  message(FATAL_ERROR "Key for encrypted ${SNOPT_ZIP} required in CFS_KEY_SNOPT. Set e.g. in your ~/.cfs_platform_defaults.cmake")
endif()    

#-------------------------------------------------------------------------------
# After the installation we remove libblas.a, remove the confidental source and
# copy to cfs
#-------------------------------------------------------------------------------
SET(PI_TEMPL "${CFS_SOURCE_DIR}/cfsdeps/snopt/snopt-post_install.cmake.in")
SET(PI "${SNOPT_PREFIX}/snopt-post_install.cmake")
CONFIGURE_FILE("${PI_TEMPL}" "${PI}" @ONLY) 

#PRECOMPILED_ZIP(PRECOMPILED_PCKG_FILE "snopt" "${SNOPT_VER}") 

PRECOMPILED_ZIP_NOBUILD(PRECOMPILED_PCKG_FILE "snopt" "${SNOPT_VER}")
  
# This should be either PREFIX_DIR (install manifest is used for zipping)
# or INSTALL_DIR (install directory will be zipped)
SET(TMP_DIR "${SNOPT_INSTALL}")

SET(ZIPFROMCACHE "${SNOPT_PREFIX}/snopt-zipFromCache.cmake")
CONFIGURE_FILE("${CFS_SOURCE_DIR}/cmake_modules/cfsdeps_zipFromCache.cmake.in" "${ZIPFROMCACHE}" @ONLY)

SET(ZIPTOCACHE "${SNOPT_PREFIX}/snopt-zipToCache.cmake")
CONFIGURE_FILE("${CFS_SOURCE_DIR}/cmake_modules/cfsdeps_zipToCache.cmake.in" "${ZIPTOCACHE}" @ONLY)

IF(WIN32)
  #-------------------------------------------------------------------------------
  # Configure SNOPT by copying the config file.
  #-------------------------------------------------------------------------------
  SET(PFN_TEMPL "${CFS_SOURCE_DIR}/cfsdeps/snopt/snopt-win-patch.cmake.in")
  SET(PFN "${SNOPT_PREFIX}/snopt-win-patch.cmake")
  CONFIGURE_FILE("${PFN_TEMPL}" "${PFN}" @ONLY)

  #-------------------------------------------------------------------------------
  # CMAKE Args
  #-------------------------------------------------------------------------------
  SET(CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX:PATH=${SNOPT_INSTALL}
    -DCMAKE_BUILD_TYPE:STRING=Release
    -DLIB_SUFFIX:STRING=${LIB_SUFFIX}
  )

  IF(CMAKE_TOOLCHAIN_FILE)
    LIST(APPEND CMAKE_ARGS
      -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${CMAKE_TOOLCHAIN_FILE}
    )
  ENDIF()
ENDIF()

#-------------------------------------------------------------------------------
# The snopt external project
#-------------------------------------------------------------------------------
IF("${CFS_DEPS_PRECOMPILED}" STREQUAL "ON" AND EXISTS "${PRECOMPILED_PCKG_FILE}")
  #-------------------------------------------------------------------------------
  # If precompiled package exists copy files from cache
  #-------------------------------------------------------------------------------
  ExternalProject_Add(snopt
    PREFIX "${SNOPT_PREFIX}"
    DOWNLOAD_COMMAND ${CMAKE_COMMAND} -P "${ZIPFROMCACHE}"
    PATCH_COMMAND ""
    UPDATE_COMMAND ""
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND ""
  )
ELSE()
  #-------------------------------------------------------------------------------
  # If precompiled package does not exist build external project
  #-------------------------------------------------------------------------------
  IF(UNIX)
    ExternalProject_Add(snopt
      PREFIX "${SNOPT_PREFIX}"
      SOURCE_DIR "${SNOPT_SOURCE}"
      URL ${LOCAL_FILE}
      URL_MD5 ${SNOPT_MD5}
      CMAKE_ARGS ${CMAKE_ARGS}
      # all in the zip is below snopt7
      BINARY_DIR "${SNOPT_SOURCE}/snopt7"
      # don't dowload but simply copy w/o md5 check
      DOWNLOAD_COMMAND ${CMAKE_COMMAND} -E copy ${LOCAL_FILE1} ${SNOPT_SOURCE}
      # the zip file is encrypted!
      PATCH_COMMAND unzip -q -u -P ${CFS_KEY_SNOPT} ${SNOPT_ZIP}
      # let it install to the temporay directory where we can remove libblas.a and prepare to copy to precompiled cfsdeps
      # the libs will be created in install/lib64 and we manually copy them to lib64/CFS_ARCH_STR
      CONFIGURE_COMMAND ${SNOPT_SOURCE}/snopt7/configure --prefix=${SNOPT_INSTALL} --libdir=${SNOPT_INSTALL}/lib64/${CFS_ARCH_STR} --disable-shared --enable-static --without-f2c F77=${CMAKE_Fortran_COMPILER} FFLAGS=-O3 
    )
  ELSE()
    ExternalProject_Add(snopt
      PREFIX "${SNOPT_PREFIX}"
      URL ${LOCAL_FILE}
      URL_MD5 ${SNOPT_MD5}
      SOURCE_DIR "${SNOPT_SOURCE}"
      CMAKE_ARGS ${CMAKE_ARGS}
      # all in the zip is below snopt7
      #BINARY_DIR "${SNOPT_SOURCE}/snopt7"
      # don't dowload but simply copy w/o md5 check
      DOWNLOAD_COMMAND ${CMAKE_COMMAND} -E copy ${LOCAL_FILE1} ${SNOPT_SOURCE}
      # the zip file is encrypted!
      PATCH_COMMAND unzip -q -u -P ${CFS_KEY_SNOPT} ${SNOPT_ZIP}
      LOG_CONFIGURE 1
      LOG_BUILD 1
      LOG_INSTALL 1
    )
    #-------------------------------------------------------------------------------
    # Add custom patch step, needed for windows
    #-------------------------------------------------------------------------------
    ExternalProject_Add_Step(snopt winpatch
      COMMAND ${CMAKE_COMMAND} -P "${PFN}"
      DEPENDERS build
      DEPENDEES patch 
      DEPENDS "${PFN}"
    )
  ENDIF()

  #-------------------------------------------------------------------------------
  # Add custom download step to be able to download from a list of mirrors
  # instead of just a single URL.
  #-------------------------------------------------------------------------------
  ExternalProject_Add_Step(snopt cfsdeps_download
    COMMAND ${CMAKE_COMMAND} -P "${DLFN}"
    DEPENDERS download
    DEPENDS "${DLFN}"
    WORKING_DIRECTORY ${SNOPT_prefix}
  )
 
  #-------------------------------------------------------------------------------
  # Execute the stuff from snopt-post_install.cmake after installation
  #-------------------------------------------------------------------------------
  ExternalProject_Add_Step(snopt post_install
    COMMAND ${CMAKE_COMMAND} -P "${PI}"
    DEPENDEES install
  )
  
  IF("${CFS_DEPS_PRECOMPILED}" STREQUAL "ON")
    #-------------------------------------------------------------------------------
    # Add custom step to zip a precompiled package to the cache.
    #-------------------------------------------------------------------------------
    ExternalProject_Add_Step(snopt cfsdeps_zipToCache
      COMMAND ${CMAKE_COMMAND} -P "${ZIPTOCACHE}"
      DEPENDEES post_install
      DEPENDS "${ZIPTOCACHE}"
      WORKING_DIRECTORY ${CFS_BINARY_DIR}
    )
  ENDIF()
ENDIF("${CFS_DEPS_PRECOMPILED}" STREQUAL "ON" AND EXISTS "${PRECOMPILED_PCKG_FILE}")

# Add project to global list of CFSDEPS, this allows "make snopt"
SET(CFSDEPS ${CFSDEPS} snopt)

# Determine paths of SNOPT libraries. We have only libs and nothing to include
SET(LD "${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}")
IF(UNIX)
  SET(SNOPT_LIBRARY "${LD}/libsnopt.a;${LD}/libsnprint.a" CACHE FILEPATH "SNOPT library.")
ELSE()
  SET(SNOPT_LIBRARY "${LD}/snopt.lib;${LD}/snprint.lib" CACHE FILEPATH "SNOPT library.")
ENDIF()

MARK_AS_ADVANCED(SNOPT_LIBRARY)
