////////////////////////////////////////
// Define here possbile coupling pdes //
////////////////////////////////////////

Definition * CoupledPDE;

// Define here the right ordering of 
// the single PDEs.
//
// A Basic definition looks like this:
//
// **********************************
// CoupledPDE = new Definition();
// CoupledPDE->AddPDE("<PDENAME>");
// CoupledPDE->AddPDE("<PDENAME>");
// ....
// CoupledPDE->AddInputCoupling("<PDENAME>", <InputCouplingType>, "<QuantityName>");
// CoupledPDE->AddInputCoupling("<PDENAME>", <InputCouplingType>, "<QuantityName>");
// ...
// CoupledPDEs_.push_back(CoupledPDE);
// **********************************
//
// Note: <InputCouplingType> is defined in environment.hh


// Coupling Electrostatic-Mechanic (without grid smoothing)
CoupledPDE = new Definition();
CoupledPDE->AddPDE("electrostatic");
CoupledPDE->AddPDE("mechanic");
CoupledPDE->AddInputCoupling("mechanic", RHS, "elecforce", TRUE);
CoupledPDE->AddInputCoupling("mechanic", RHS, "interfaceForce",TRUE);    //TRUE means: optional coupling!
CoupledPDE->AddInputCoupling("electrostatic", COORD, "mechdisplacement");
CoupledPDEs_.push_back(CoupledPDE);


// Coupling Mechanic-Smooth
CoupledPDE = new Definition();
CoupledPDE->AddPDE("mechanic");
CoupledPDE->AddPDE("smooth");
CoupledPDE->AddInputCoupling("smooth", ID_BC, "mechdisplacement");
CoupledPDEs_.push_back(CoupledPDE);


// Coupling Electrostatic-Mechanic-Smoothing
CoupledPDE = new Definition();
CoupledPDE->AddPDE("electrostatic");
CoupledPDE->AddPDE("mechanic");
CoupledPDE->AddPDE("smooth");
CoupledPDE->AddInputCoupling("electrostatic", COORD, "smoothdisplacement");
CoupledPDE->AddInputCoupling("mechanic", RHS, "elecforce");
CoupledPDE->AddInputCoupling("mechanic", RHS, "interfaceForce");
CoupledPDE->AddInputCoupling("smooth", ID_BC, "mechdisplacement");
CoupledPDEs_.push_back(CoupledPDE);

// Coupling Electrostatic-Mechanic-LaplaceSmoothing
CoupledPDE = new Definition();
CoupledPDE->AddPDE("electrostatic");
CoupledPDE->AddPDE("mechanic");
CoupledPDE->AddPDE("laplacesmooth");
CoupledPDE->AddInputCoupling("electrostatic", COORD, "smoothdisplacement");
CoupledPDE->AddInputCoupling("mechanic", RHS, "elecforce");
CoupledPDE->AddInputCoupling("laplacesmooth", ID_BC, "mechdisplacement");
CoupledPDEs_.push_back(CoupledPDE);



// Coupling Mechanic-Acoustic
CoupledPDE = new Definition();
CoupledPDE->AddPDE("mechanic");
CoupledPDE->AddPDE("acoustic");
CoupledPDE->AddInputCoupling("mechanic", RHS, "acousticforce");
CoupledPDE->AddInputCoupling("acoustic", RHS, "mechforce");
CoupledPDEs_.push_back(CoupledPDE);


// Coupling Electrostatic-Mechanic-Acoustic
CoupledPDE = new Definition();
CoupledPDE->AddPDE("electrostatic");
CoupledPDE->AddPDE("mechanic");
CoupledPDE->AddPDE("acoustic");
CoupledPDE->AddInputCoupling("mechanic", RHS, "elecforce");
CoupledPDE->AddInputCoupling("electrostatic", COORD, "mechdisplacement");
CoupledPDE->AddInputCoupling("mechanic", RHS, "acousticforce");
CoupledPDE->AddInputCoupling("acoustic", RHS, "mechforce");
CoupledPDEs_.push_back(CoupledPDE);


