////////////////////////////////////////
// Define here possbile coupling pdes //
////////////////////////////////////////

Definition * CoupledPDE;
// Coupling Electrostatic-Mechanic
CoupledPDE = new Definition();
CoupledPDE->AddPDE("electrostatic");
CoupledPDE->AddPDE("mechanic");
CoupledPDE->AddInputCoupling("electrostatic", COORD, "mechdisplacement");
CoupledPDE->AddInputCoupling("mechanic", RHS, "elecforce");
CoupledPDEs_.push_back(CoupledPDE);


// Coupling Mechanic-Smooth
CoupledPDE = new Definition();
CoupledPDE->AddPDE("mechanic");
CoupledPDE->AddPDE("smooth");
CoupledPDE->AddInputCoupling("smooth", ID_BC, "mechdisplacement");
CoupledPDEs_.push_back(CoupledPDE);


// Coupling Electrostatic-Mechanic-Smoothing
CoupledPDE = new Definition();
CoupledPDE->AddPDE("electrostatic");
CoupledPDE->AddPDE("mechanic");
CoupledPDE->AddPDE("smooth");
CoupledPDE->AddInputCoupling("electrostatic", COORD, "smoothdisplacement");
CoupledPDE->AddInputCoupling("mechanic", RHS, "elecforce");
CoupledPDE->AddInputCoupling("smooth", ID_BC, "mechdisplacement");
CoupledPDEs_.push_back(CoupledPDE);






