#
C_DIR= ../..
#
src = basecoupledpde.cc itercoupledpde.cc coupledpdedef.cc pdecoupling.cc couplingmemento.cc
#
lib = coupledpde
libpath = libsrc/CoupledPDE
CFLAGS3 =
#
include ../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE


