#
C_DIR= ../..
#
src = itercoupledpde.cc coupledpdedef.cc pdecoupling.cc couplingmemento.cc\
	DirectCoupledPDE.cc
#
lib = coupledpde
libpath = libsrc/CoupledPDE
CFLAGS3 =
#
include ../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE


