#
C_DIR= ../..
#
src = itercoupledpde.cc coupledpdedef.cc pdecoupling.cc couplingmemento.cc\
	DirectCoupledPDE.cc BasePairCoupling.cc PiezoCoupling.cc\
	AcouMechCoupling.cc
#
CFLAGS3 =
#
include ../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE


