// -*- mode: c++; coding: utf-8; indent-tabs-mode: nil; -*-
// kate: space-indent on; indent-width 2; encoding utf-8;
// kate: auto-brackets on; mixedindent off; indent-mode cstyle;

/*! \file environment.hh
    Contains general typedefs and enum-types for solver specification, matrix
    classes and preconditioner types.
*/
#ifndef OLAS_ENVIRONMENT_HH
#define OLAS_ENVIRONMENT_HH

#include <sstream>
#include <limits.h>

// Include build type options header containing the #defines
#include <def_build_type_options.hh>

//! Namespace for filestreams used by both OLAS and CFS++

//! The %OutInfo namespace contains the various output streams that are used
//! by both OLAS and CFS++. The filestreams are included into the OLAS and
//! CoupledField namespaces for convenience.
namespace OutInfo{

  //! Pointer to OLAS logfile (must be generated by driver)
  extern std::ostream *cla;

  //! Global pointer to a stringstream used for generating error messages

  //! This is a global pointer to a stringstream object used for generating
  //! error messages. The object itself must be generated by the application
  //! making use of the OLAS library.
  extern std::stringstream *error;

  //! Global pointer to a stringstream used for generating warning messages

  //! This is a global pointer to a stringstream object used for generating
  //! warning messages. The object itself must be generated by the
  //! application making use of the OLAS library.
  extern std::stringstream *warning;
}



//! Namespace for OLAS project

//! All classes, data types and the like of the OLAS package belong to this
//! namespace.
namespace OLAS {

  // Forward declaration
  class OLAS_Params;
  class OLAS_Report;

  // Import stuff from OutInfo namespace into OLAS namespace for convenience
  using OutInfo::cla;
  using OutInfo::error;
  using OutInfo::warning;

  //! Standard type for identifiying a Pde in the algebraic system
  //! \note This type is guaranteed to be of an Integer or
  //! enumeration typem, so it can be used as array index
  typedef unsigned short PdeIdType;

  //! Standard type for identifiying a sparsity pattern of a matrix object
  //! in combination with the PatternPool class.
  typedef unsigned char PatternIdType;

  //! Macro to allow consistent storage of unavailable pattern identifier
#define NO_PATTERN_ID 0

  //! Standard default identifier
#define NO_PDE_ID 0

  // ---- Enumerations for general algebraic system information ----

  //! Type of re-ordering for the graph

  //! This enumeration data type describes the type of re-ordering that is to
  //! be applied to the graph. The enumeration contains the following values:
  //! - NOREORDERING
  //! - METIS
  //! - SLOAN
  //! - MINIMUM_DEGREE
  //! - NESTED_DISSECTION
  typedef enum { NOREORDERING, METIS, SLOAN, NESTED_DISSECTION,
                 MINIMUM_DEGREE } ReorderingType;

  //! Type of finite element matrix

  //! This enumeration data type describes the type of FE-matrices which
  //! are used to assemble an effective system matrix.
  //! The enumeration contains the following values:
  //! - NOTYPE
  //! - SYSTEM
  //! - STIFFNESS
  //! - DAMPING
  //! - CONVECTION
  //! - MASS
  //! - AUXILIARY - e.g. for radiation optimization used in SurfaceNormalInt               
  typedef enum {NOTYPE, SYSTEM = 1, STIFFNESS, DAMPING, CONVECTION, MASS, AUXILIARY}
  FEMatrixType;

  //! Maximal number of different FE matrix types

  //! This macro specifies the maximal number
  //! of different types of Finite-Element matrices that can occur in a
  //! CFS++/OLAS run, i.e. the number of possible choices from FEMatrixType
  //! besides the NOTYPE value.
#define MAX_NUM_FE_MATRICES 6  

  
  //! Type of algebraic system

  //! This enumeration data type describes the type of the algebraic system.
  //! To be more precise is describes the type of linear system objects that
  //! are assembled and managed by the linear system. These can either be
  //! StdMatrix / StdVector objects or SBM_Matrix / SBM_Vector objects. Thus,
  //! the current value are:
  //! - NOALGSYSTYPE
  //! - SBM_SYSTEM
  //! - STANDARD_SYSTEM
  typedef enum { NOALGSYSTYPE, SBM_SYSTEM, STANDARD_SYSTEM } AlgSysType;


  //! Type of preconditioner

  //! This enumeration data type describes the type of Preconditioner which
  //! is applied before solving the algebraic system.
  //! The enumeration contains the following values:
  //! - NOPRECOND
  //! - ID
  //! - MG
  //! - JACOBI
  //! - SSOR
  //! - ILU0
  //! - ILUTP
  //! - ILUK
  //! - ILDLK
  //! - ILDLTP
  //! - ILDLCN
  typedef enum {NOPRECOND, ID, MG, JACOBI, SSOR, ILU0,ILUTP, ILUK, ILDL0, ILDLK, ILDLTP,
                ILDLCN, IC0} PrecondType;

  //! Type of solver

  //! This enumeration data type describes the type of solver which
  //! is applied to solve the system. Note that not all solvers can handle
  //! all types of matrices. The enumeration contains the following values:
  //! - NOSOLVER
  //! - DIRECT
  //! - RICHARDSON
  //! - CG
  //! - LANCZOS
  //! - QMR
  //! - GMRES
  //! - MINRES
  //! - LAPACK_LU
  //! - LAPACK_LL
  //! - PARDISO
  //! - ILUPACK_SOLVER
  //! - LU_SOLVER
  //! - LDL_SOLVER
  //! - LDL_SOLVER2
  typedef enum {NOSOLVER, DIRECT, RICHARDSON, CG, LANCZOS, QMR, GMRES,
                MINRES, SYMMLQ, LAPACK_LU, LAPACK_LL, PARDISO,  ILUPACK_SOLVER, LU_SOLVER,
		LDL_SOLVER, LDL_SOLVER2, DIAGSOLVER } SolverType;

  //! Type of EigenSolver

  //! This enumeration data type describes the type of eigensolver which is 
  //! applied to solve a generalized eigenvalue problem. The enumeration
  //! contains the following:
  //! - NOEIGENSOLVER
  //! - ARPACK
  //! - SUBSPACE  
  typedef enum {NOEIGENSOLVER, ARPACK, SUBSPACE} EigenSolverType;

  //! Type of cycle used for algebraic multigrid preconditioner

  //! This enumeration data type describes the type of solutions
  //! cycle which is used by the AMG(algebraic multigrid) preconditioner.
  //! It can take one of the following values:
  //! - NOCYCLE
  //! - VCYCLE
  //! - WCYCLE
  typedef enum {NOCYCLE, VCYCLE, WCYCLE} CycleType;
  

  // ---- Enumerations for dynamic Matrix information ----

  //! Structural type of the matrix.
  
  //! This enumeration data type describes the structural type of the matrix.
  //! This is used to distinguish e.g. SBM_Matrices from StdMatrices and so
  //! on. It can take one of the following values:
  //! - NOSTRUCTURETYPE
  //! - SBM_MATRIX
  //! - STDMATRIX
  typedef enum { NOSTRUCTURETYPE, SBM_MATRIX, STDMATRIX } MatrixStructureType;

  //! Entry type of the matrix.
  
  //! This enumeration data type describes the entry type of the matrix.
  //! The entry type describes the scalar type of the entries e.g. Integer,
  //! Double or Complex. It can take one of the following values:
  //! - NOENTRYTYPE
  //! - INTEGER
  //! - DOUBLE
  //! - COMPLEX
  //! - F77REAL8
  //! - F77COMPLEX16
  typedef enum { NOENTRYTYPE, INTEGER, DOUBLE, COMPLEX, F77REAL8,
		 F77COMPLEX16 } MatrixEntryType;

  //! Storage type of the matrix.

  //! This enumeration data type describes the storage format of a sparse
  //! matrix. It can take one of the following values
  //! - NOSTORAGETYPE
  //! - SPARSE_SYM
  //! - SPARSE_NONSYM
  //! - SKYLINE_SYM
  //! - SKYLINE_NONSYM
  //! - LAPACK_GBMATRIX
  typedef enum { NOSTORAGETYPE, SPARSE_SYM, SPARSE_NONSYM,
		 SKYLINE_SYM, SKYLINE_NONSYM, 
		 LAPACK_GBMATRIX, DIAG } MatrixStorageType;


  //! Type of stopping criterion used by iterative solvers

  //! This enumeration data type describes the different stopping criteria
  //! supported by the iterative solvers. It can take one of the following
  //! values
  //! - NOSTOPCRIT
  //! - ABSNORM
  //! - RELNORM_RHS
  //! - RELNORM_RES0
  typedef enum { NOSTOPCRITTYPE, ABSNORM, RELNORM_RHS,
		 RELNORM_RES0 } StopCritType;

  //! Parallel type of the matrix.

  //! This enumeration data type describes the parallelisation type of the
  //! matrix.
  //! <center>
  //! <table border="1" cellpadding="10">
  //! <tr>
  //!   <td align="center"><b>Enumeration value</b></td>
  //!   <td align="center"><b>Description</b></td>
  //! </tr>
  //! <tr><td>NOPARMATRIXTYPE</td><td>No type was specified.</td></tr>
  //! <tr><td>SEQMATRIX</td><td>This is a sequential matrix object.</td></tr>
  //! <tr><td>PARMATRIX</td><td>This is a ParMatrix object. The type of the
  //! submatrices used for storing the internal and coupling parts can be
  //! obtained from MatrixStorageType.</td></tr>
  //! <tr><td>PARCRSMATRIX</td><td>This is a ParCRS_Matrix object.</td></tr>
  //! </table>
  //! </center>
  typedef enum { NOPARMATRIXTYPE, SEQMATRIX, PARMATRIX, PARCRSMATRIX
               } ParMatrixType;

  //! \name enumeration types for (parallel) AMG
  //@{
  //! interpolation type
  typedef enum { AMG_INTERPOLATION_CONSTANT,
                 AMG_INTERPOLATION_SIMPLE_WEIGHTED,
                 AMG_INTERPOLATION_SMOOTHED_SCALING,
                 AMG_INTERPOLATION_DEVELOP
               } AMGInterpolationType;
  //! smoother type
  typedef enum { AMG_SMOOTHER_GAUSSSEIDEL,
                 AMG_SMOOTHER_DAMPED_JACOBI
               } AMGSmootherType;
  //@}

  //! Type of treatment of inhomogeneous Dirichlet boundary conditions

  //! Enumeration data type describing the approach used for the treatment
  //! of inhomogeneous Dirichlet boundary conditions. Can currently take one
  //! of the following values
  //! - IDBC_NOTYPE
  //! - IDBC_ELIMINATION
  //! - IDBC_PENALTY
  typedef enum { IDBC_NOTYPE, IDBC_ELIMINATION, IDBC_PENALTY } IDBCType;

  //! Convert a string to an enumeration value

  //! This auxiliary function can be used to convert a string to an
  //! enumeration value. If the input string contains a value value of the
  //! enumeration data type ENUMTYPE, then that value will be assigned to
  //! the parameter out. If the value is not valid an error message will be
  //! issued and program execution terminated.
  template <class ENUMTYPE>
  void String2Enum( const std::string &in, ENUMTYPE &out );

  //! Convert an enumeration value to a string

  //! This auxiliary function can be used to convert the value of the
  //! enumeration data type ENUMTYPE contained in the input parameter in
  //! into a corresponding string representation. The string representations
  //! are chosen to be identical to the identifiers used in the Schema
  //! definitions for the XML parameter file.
  //! \return string representation of enumeration value
  template<class ENUMTYPE>
  std::string Enum2String( const ENUMTYPE &in );

}  // namespace

#endif // OLAS_ENVIRONMENT_HH

