/* -*- mode: c++; coding: utf-8; indent-tabs-mode: nil; -*-
   kate: space-indent on; indent-width 2; encoding utf-8;
   kate: auto-brackets on; mixedindent off; indent-mode cstyle; */


#ifndef FILE_SCFE_MYDEFS_2001
#define FILE_SCFE_MYDEFS_2001

#include <cfloat>
#include <cmath>
#include <iostream>
#include <typeinfo>
#include <vector>
#include "General/defs.hh"
#include "General/Enum.hh"
// includes for the C99 standard datatypes (e.g. uint32_t, long double)
#include "boost/cstdint.hpp"
#include "boost/shared_ptr.hpp"

//! \file environment.hh
//! This file contains some global macro, class and enumeration data type
//! definitions for CFS++.

//! Namespace for filestreams used by both OLAS and CFS++

//! The %OutInfo namespace contains the various output streams that are used
//! by both OLAS and CFS++. The filestreams are included into the OLAS and
//! CoupledField namespaces for convenience.
namespace OutInfo{

  //! Pointer to OLAS logfile (must be generated by driver)
  extern std::ostream *cla;

  // ------------------- Files for debug, trace and information -------------
  extern std::ostream * debug;     // basename.deb
  extern std::ostream * memtrace;  // basename.mem
  extern std::ostream * data;      // basename.data

#ifdef MEMTRACE
  extern double sumdmem;
  extern double sumimem;
#endif

}


namespace CoupledField {

  // Import Boost's namespace as using namespace boost is evil. It breaks with gcc 4.8
  using boost::shared_ptr;
  using boost::lexical_cast;

  class CFSMessenger;
  // forward class declaration
  class Domain;
  class LogConfigurator;
  

  // Type definitions for regions
  typedef Integer RegionIdType;
  static const RegionIdType NO_REGION_ID = -1;
  static const RegionIdType ALL_REGIONS = -2;

  typedef Double (*pFncWith1Var)(const Double);

  static const Double PI = acos(-1.0);
  static const Double NORM_EPS = 1e-6;  // needed e.g. for lower bounds of norms in iteration loops
  static const Double EPS = 1e-12;     // value for absolute precision (needed e.g. for lower bounds of norms in iteration loops)

  //! specifications of Lapack routines for different types of system matrices in
  //! matrix.solveWithLapack
  //! Z - Complex valued matrix
  //! SY - symmetric matrix
  //! GE - general matrix
  //! HE - hermitian matrix
  typedef enum {ZSYSV, ZGESV, ZHESV} lapackSysMatType;


  //! logging configurator

  extern LogConfigurator * logConf;

  //! Global pointer to domain object
  extern Domain *domain;

#ifdef USE_SCRIPTING
  //! Global pointer to messenger object
  extern CFSMessenger * messenger;
#endif





  /** enumeration with integration types - to be renamed into IntegrationType
   * ECONOMICAL are the "efficient" gaussian quadrature weights
   *            (->Solin, Segeth, Dolezel, Higher-Order Finite Element Methods) -> see also Elements/BaseFE
   * CLASSICAL either the "original" implementation before ECONOMICAL refactoring or fixed product rule (wedge)
   * EXPERIMENTAL is only for developer/debugging use -> one does not need to modify "real" data
   * CARTESIAN is only for developer/debugging -> x1 =0-9, x2 = 1x-9x, x3 = 1xx-9xx
   * UNDEFINED only internal use!
   * LOBATTO and CHEBYSHEV are special line intgration methods (->Solin, Segeth, Dolezel, Higher-Order Finite Element Methods)*/
  enum IntegrationMethod {ECONOMICAL, CLASSICAL, LOBATTO, CHEBYSHEV, EXPERIMENTAL, CARTESIAN, SPECIAL, UNDEFINED};

  //! Damping type
  enum DampingType{NONE=0, RAYLEIGH=1, ABCDAMP=2, THERMOVISCOUS=3,
                   FRACTIONAL=4, FRACTIONAL_GL=5, FRACTIONAL_BLANK=6,
                   FRACTIONAL_GL_INT=7, FRACTIONAL_BLANK_INT=8,
                   PML, DAMPLAYER};

  //! Interpolation type used in fractional damping model
  enum InterpolType{NOTUSED=0, trueVAL=1, LIN1PT=2};

  //! Type of nonlinearity for certain pdes
  typedef enum { NO_NONLINEARITY, WESTERVELT, KUZNETSOV, VARIABLE_SOS_CN1,
                 VARIABLE_SOS_CN2, VARIABLE_SOS_CN2Mean,
                 GEOMETRIC, HYSTERESIS, PIEZO_MICRO_HF, PERMEABILITY,
                 NLHEAT_CONDUCTIVITY, NLHEAT_CAPACITY} NonLinType;


   //! Describes all possible solution types in a CFS simulation
   typedef enum{
    NO_SOLUTION_TYPE, 
    // === Mechanic results ===    
    MECH_DISPLACEMENT,
    LUMPED_MECH_DISPLACEMENT, MECH_ACCELERATION,
    MECH_VELOCITY, MECH_FORCE, MECH_STRESS, MECH_STRAIN, MECH_STRAIN_IRR, 
    VON_MISES_STRESS, VON_MISES_STRAIN,
    MECH_ENERGY, MECH_DEF_VOLUME, MECH_RHS_LOAD, MECH_PRESSURE,
    MECH_PSEUDO_DENSITY, PHYSICAL_PSEUDO_DENSITY, MECH_SHAPE, MECH_REL_DILATATION, MECH_TENSOR_TRACE, MECH_TENSOR,
    
    // === Electrostatic results ===
    ELEC_POTENTIAL, ELEC_FIELD_INTENSITY, ELEC_FORCE_VWP,
    ELEC_INTERFACE_FORCE, ELEC_CHARGE, ELEC_FLUX_DENSITY,
    ELEC_ENERGY, ELEC_POLARIZATION,ELEC_RHS_LOAD,ELEC_PSEUDO_POLARIZATION,
    ELEC_PHYSICAL_PSEUDO_DENSITY, ELEC_TENSOR_TRACE, ELEC_TENSOR,
    
    // === Pseudo mechanic smoothing results ===
    SMOOTH_DISPLACEMENT, SMOOTH_VELOCITY, GRID_VELOCITY, SMOOTH_STRAIN,  
    
    // === Acoustic results ===
    ACOU_POTENTIAL, ACOU_PRESSURE, ACOU_PRESSURE_DERIV_1,
    ACOU_PRESSURE_DERIV_2,ACOU_VELOCITY,ACOU_ACCELERATION, ACOU_FORCE, 
    ACOU_PSEUDO_DENSITY, ACOU_POWERDENSITY, ACOU_POWER, ACOU_INTENSITY, ACOU_ENERGY,
    ACOU_POTENTIAL_DERIV_1, ACOU_POTENTIAL_DERIV_2, ACOU_RHS_LOAD, ACOU_RHS_LOAD_DENSITY,
    ACOU_RHSVAL, ACOUSURF_RHSVAL,
    ACOU_BUBBLE_RHS_VAL, ACOU_SURFINTENSITY, ACOU_DIV_LH_TENSOR, ACOU_DIV_LH_TENSOR_NODAL,
    ACOU_PMLAUXVEC, ACOU_PMLAUXSCALAR,
    ACOU_ELEM_SPEED_OF_SOUND,
    ACOU_LAMB_RHS, ACOU_LAMB_VEC, ACOUMIXED_MASS_LOAD,
    AERO_ACOU_SRC_RHS,AERO_ACOU_D_LH_TENSOR,AERO_ACOU_LAPLACE_P_RHS,AERO_ACOU_DIV_LAMB_RHS,
    
    // === Magnetic results ===
    MAG_POTENTIAL, MAG_SCALAR_POTENTIAL, MAG_FLUX_DENSITY, MAG_HFIELD, MAG_EDDY_CURRENT,
    MAG_POTENTIAL_DIV, MAG_SURF_CURRENT,
    MAG_FORCE_VWP, MAG_FORCE_LORENTZ, MAG_ENERGY,
    MAG_EDDY_POWER, MAG_RHS_LOAD, MAG_ELEM_PERMEABILITY,
    
    // === Heat results ===
    HEAT_TEMPERATURE, HEAT_RHS_LOAD,

    // === unqualified results ===
    MPCCI, FLUID_FORCE, PIEZO_COUPL_TENSOR,
    ACOU_PRESSUREXYZ,

    // === Flow results ===
    LAMBDA_K, MEAN_FLUIDMECH_VELOCITY, MEAN_FLUIDMECH_PRESSURE,
    FLUIDMECH_VELOCITY, FLUIDMECH_PRESSURE,
    FLUIDMECH_VELOCITY_DERIV_1, FLUIDMECH_PRESSURE_DERIV_1,
    FLUIDMECH_VELOCITY_DERIV_2, FLUIDMECH_PRESSURE_DERIV_2,
    FLUIDMECH_PRESSURE_TIME_DERIV_2,
    FLUIDMECH_DENSITY, FLUIDMECH_FORCE, FLUIDMECH_TKE, 
    FLUIDMECH_STRESS, FLUIDMECH_STRAINRATE, FLUIDMECH_ENERGY, FLUIDMECH_STABILPARAM,
    FLUIDMECH_SKINFRICTION, FLUIDMECH_DIV_LH_T, FLUIDMECH_DIV_LAMBVEC,

    // === Exteranl LBM results ===
    LBM_PROBABILITY_DISTRIBUTION, LBM_VELOCITY, LBM_DENSITY, LBM_PRESSURE, LBM_PHYSICAL_PSEUDO_DENSITY,

    // === Various results ===
    HOMOGENIZED_TENSOR = 200,
    BUBBLE_RADIUS, BUBBLE_RADIUS_DERIV_1, BUBBLE_VOLUME_FRAC,
    OPT_RESULT_1, OPT_RESULT_2, OPT_RESULT_3,
    OPT_RESULT_4, OPT_RESULT_5, OPT_RESULT_6,
    OPT_RESULT_7, OPT_RESULT_8, OPT_RESULT_9,
    OPT_RESULT_10, OPT_RESULT_11, OPT_RESULT_12,
    LAGRANGE_MULT, THERMOMECH_FORCE, THERMOELEC_FORCE,
    GRAD_ACOU_SOLUTION, GRAD_ELEC_POTENTIAL,
    GRAD_X_DISPLACEMENT, GRAD_Y_DISPLACEMENT, GRAD_Z_DISPLACEMENT, // nodal gradients
    ELEM_LOC_DIR, JACOBIAN
  } SolutionType;

  extern Enum<SolutionType> SolutionTypeEnum;
  
  //! describes the possible material types
  typedef enum{NO_MATERIAL, MAG_PERMEABILITY, MAG_RELUCTIVITY, MAG_CONDUCTIVITY,
               MAG_PERMEABILITY_1, MAG_PERMEABILITY_2, MAG_PERMEABILITY_3,
               MAG_PERMEABILITYCURVES, ELEC_PERMITTIVITY, MECH_STIFFNESS_TENSOR, MECH_EMODULUS,
               MECH_POISSON, MECH_KMODULUS, MECH_GMODULUS,
               MECH_LAME_MU, MECH_LAME_LAMBDA, COEFF_STRAIN_IRREVERSIBLE,
               MECH_EMODULUS_X, MECH_EMODULUS_Y, MECH_EMODULUS_Z,
               MECH_POISSON_XY, MECH_POISSON_YZ, MECH_POISSON_XZ,
               MECH_GMODULUS_YZ, MECH_GMODULUS_ZX, MECH_GMODULUS_XY,
               RAYLEIGH_ALPHA, RAYLEIGH_BETA, RAYLEIGH_FREQUENCY, RAYLEIGH_DELTA_FREQ,
               BOVERA, LOSS_TANGENS_DELTA,
               DENSITY, ACOU_BULK_MODULUS, ACOU_SOUND_SPEED,
               ACOU_ALPHA, FRACTIONAL_ALG, FRACTIONAL_MEMORY, FRACTIONAL_INTERPOL,
               FRACTIONAL_EXPONENT,
               HEAT_CONDUCTIVITY, HEAT_CAPACITY, PIEZO_TENSOR, HEAT_CONDUCTIVITY_TENSOR,
               MAGNETOSTRICTION_TENSOR, MAGNETOSTRICTION_NLCURVES,
               X_SATURATION, Y_SATURATION, Y_REMANENCE, PREISACH_WEIGHTS, A_JILES,
               ALPHA_JILES, K_JILES, C_JILES, P_DIRECTION, HYST_MODEL,
               NONLIN_COEFFICIENT, NONLIN_DEPENDENCY, NONLIN_APPROXIMATION_TYPE,
               NONLIN_DATA_NAME, DYNAMIC_VISCOSITY, KINEMATIC_VISCOSITY,
               DATA_ACCURACY, MAX_APPROX_VAL,
               THERMAL_EXPANSION_TENSOR, PYROCOEFFICIENT_TENSOR,
               MEAN_TEMPERATURE, SPON_POLARIZATION, SPON_STRAIN, DRIVING_FORCE_90,
               DRIVING_FORCE_180, RATE_CONSTANT, VISCO_PLASTIC_INDEX, SATURATION_INDEX,
               VOLUME_FRAC_INIT, EFIELD0, STRESS0, DCOUPLE0,
               SCALE_FORCE_ELEC, SCALE_FORCE_MECH, SCALE_FORCE_COUPLE,
               LBM_MATERIAL
  } MaterialType;
  extern Enum<MaterialType> MaterialTypeEnum;
               
  typedef enum{NO_TENSOR = -1, FULL, PLANE_STRAIN, PLANE_STRESS, PLANE, AXI} SubTensorType;

  typedef enum{ NO_CLASS, ELECTROMAGNETIC, ELECTROSTATIC, FLUID, FLOW,
                MECHANIC, PIEZO, THERMIC, PYROELECTRIC, THERMOELASTIC,
                MAGNETOSTRICTIVE } MaterialClass;


  // type of approximation / interpolation
  typedef enum{ NO_APPROX_TYPE, LIN_INTERPOLATE, CUBIC_SPLINES, SMOOTH_SPLINES, ANALYTIC } ApproxCurveType;

  //! material parameter to be approximated / interpolated
  typedef enum{ GENERIC, MAGNETIC_MAT_BH, HEAT_MAT_CONDUCTIVITY, HEAT_MAT_CAPACITY }  ApproxMaterialCurves;

  //! Enumberation for coupling method\n
  //! NO_COUPLING          = No coupling at all
  //! DIRECT_COUPLING      = Direct Coupling via matrix \n
  //! ITER_RHS_COUPLING    = Iterative via RHS \n
  //! ITER_MATRIX_COUPLING = Iterative via matrix
  typedef enum{NO_COUPLING, DIRECT_COUPLING, ITER_RHS_COUPLING,
                 ITER_MATRIX_COUPLING} CouplingMethod;

  //! Enumeration for Input Coupling types \n
  //! COORD = Coupling via coordinate displacement \n
  //! RHS   = Coupling via Right hand side \n
  //! ID_BC = Coupling via inhomogenous dirichlet bc \n
  //! MAT   = Coupling via material change \n
  typedef enum {COORD, RHS, ID_BC, MAT, GRID_VEL} CouplingInputType;

  //! Enumeration for Output Coupling types\n
  //! ELEM = Coupling via element quantities\n
  //! NODE = Coupling via node quantities\n
  typedef enum {NODE, ELEM} CouplingOutputType;

  //! Enumeration for types of coupling regions\n
  //! REGION = Coupling region is whole Subdomain\n
  //! NODES = Coupling region is specified as nodes in .conf file\n
  //! SURFACE = Coupling region is specified as 1D/2D surface elements
  typedef enum {REGION, NODES, SURFACE} CouplingRegionType;

  //! Enumeration for types of norms
  //! L2ABS = absolute L2-norm
  //! L2REL = relative L2 norm: (|val| - |oldval|) / |val|
  typedef enum {NO_NORM, L2ABS, L2REL} NormType;

  //! Enumeration for directions
  //! direction of various fields
  //! "Rad" means readial, following two letters indicate the stress-plane
  enum  Directions {X=0, Y=1, Z=2, radXY=3, radXZ=4, radYZ=5};

  //! orientation of calculation plane in 2D
  //! (especially important for anisotropic simulations)
  enum orientation2D {xy, xz, yz};

  //! nonlinear method definition
  typedef enum {FIXEDPOINT=1, NEWTON=2} NonLinMethodType ; 
  extern Enum<NonLinMethodType> NonLinMethodTypeEnum;

  //! output format for complex numbers
  typedef enum {REAL_IMAG, AMPLITUDE_PHASE} ComplexFormat;


  //! type of data
  struct Global {
    typedef enum {INTEGER, REAL, IMAG, COMPLEX} ComplexPart;
    static Enum<ComplexPart> complexPart;
  };

  //! Data type for specification of frequency sampling approach

  //! This enumeration data type is used for distinguishing the different
  //! approaches for sampling the frequency domain when performing a
  //! harmonic analysis with CFS++. The type currently allows the following
  //! values
  //! - NO_SAMPLING_TYPE
  //! - LINEAR_SAMPLING
  //! - LOG_SAMPLING
  //! - REVERSE_LOG_SAMPLING
  typedef enum { NO_SAMPLING_TYPE, LINEAR_SAMPLING, LOG_SAMPLING,
                 REVERSE_LOG_SAMPLING } FreqSamplingType;


  //--------------------- Stuff for handling different IO files -------------

  typedef enum {MEMTRACE_FILE, OLAS_FILE} AuxFileType;


  //------------------------ Stuff for bubble simulation --------------------

  typedef enum {NOBUBBLETYPE, KELLERMIKSIS, GILMORE} BubbleDynType;

  extern BubbleDynType bubbleDyn;




  //------------------------ Files for debug and information ---------

  // NOTE: OLAS uses the namespace 'OutInfo' for writing out data into the
  // different filestreams such as (*cla) etc. Therefore they are
  // explicitely imported into namespace CoupledField at this point
  using OutInfo::cla;
  using OutInfo::memtrace;

#ifdef MEMTRACE
  using OutInfo::sumdmem;
  using OutInfo::sumimem;
#endif

  // Forward declaration of class
  class WriteInfo;

  //! Global pointer to class performing logging to info file
  extern WriteInfo *Info;

  class BaseFE;

  //! Pointers to derived classes of BaseElem. Initialized in grid.hh/grid.cc.
  //! They are used, when we read information about elements from mesh and
  //! create a pointer to the class containing the description of the Finite
  //! Element.
  extern BaseFE *ptQ1, *ptQ2, *ptQ9, *ptL1, *ptL2, *ptTet1, *ptTet2, *ptTr1, 
	*ptTr2, *ptHexa1, *ptHexa2, *ptHexa27, *ptPyra1, *ptPyra2, *ptWedge1, *ptWedge2;

  //! conversion from strings to enum types
  template <class TYPE>
  void String2Enum(const std::string &in, TYPE &out);

  //! conversion from enum types to strings
  template<class TYPE>
  void Enum2String(const TYPE &in, std::string &out);

  // ****************************************************************
  // ****************************************************************
  //              THE OLAS ENVIRONMENT STARTS HERE
  // ****************************************************************
  // ****************************************************************

  //! Standard type for identifiying a Pde in the algebraic system
  //! \note This type is guaranteed to be of an Integer or
  //! enumeration typem, so it can be used as array index
  typedef Integer PdeIdType;
  //! Standard default identifier
  static const PdeIdType NO_PDE_ID = -1;

  //! Standard type for identifiying a sparsity pattern of a matrix object
  //! in combination with the PatternPool class.
  typedef UInt PatternIdType;
  //! Value to allow consistent storage of unavailable pattern identifier
  static const PatternIdType NO_PATTERN_ID = 0;


  // ---- Enumerations for general algebraic system information ----

  //! Type of finite element matrix

  //! This enumeration data type describes the type of FE-matrices which
  //! are used to assemble an effective system matrix.
  //! The enumeration contains the following values:
  //! - NOTYPE
  //! - SYSTEM
  //! - STIFFNESS
  //! - DAMPING
  //! - CONVECTION
  //! - MASS
  //! - AUXILIARY - e.g. for radiation optimization used in SurfaceNormalInt
  typedef enum {NOTYPE, SYSTEM = 1, STIFFNESS, DAMPING, CONVECTION, MASS, AUXILIARY}
  FEMatrixType;
  extern Enum<FEMatrixType> feMatrixType;

  //! Maximal number of different FE matrix types

  //! This macro specifies the maximal number
  //! of different types of Finite-Element matrices that can occur in a
  //! CFS++/OLAS run, i.e. the number of possible choices from FEMatrixType
  //! besides the NOTYPE value.
  extern UInt MAX_NUM_FE_MATRICES;

  //! Type of algebraic system

  //! This enumeration data type describes the type of the algebraic system.
  //! To be more precise is describes the type of linear system objects that
  //! are assembled and managed by the linear system. These can either be
  //! StdMatrix / StdVector objects or SBM_Matrix / SBM_Vector objects. Thus,
  //! the current value are:
  //! - NOALGSYSTYPE
  //! - SBM_SYSTEM
  //! - STANDARD_SYSTEM
  typedef enum { NOALGSYSTYPE, SBM_SYSTEM, STANDARD_SYSTEM } AlgSysType;


  //! Type of cycle used for algebraic multigrid preconditioner

  //! This enumeration data type describes the type of solutions
  //! cycle which is used by the AMG(algebraic multigrid) preconditioner.
  //! It can take one of the following values:
  //! - NOCYCLE
  //! - VCYCLE
  //! - WCYCLE
  typedef enum {NOCYCLE, VCYCLE, WCYCLE} CycleType;


  //! Type of stopping criterion used by iterative solvers

  //! This enumeration data type describes the different stopping criteria
  //! supported by the iterative solvers. It can take one of the following
  //! values
  //! - NOSTOPCRIT
  //! - ABSNORM
  //! - RELNORM_RHS
  //! - RELNORM_RES0
  typedef enum { NOSTOPCRITTYPE, ABSNORM, RELNORM_RHS,
                 RELNORM_RES0 } StopCritType;

  //! Parallel type of the matrix.

  //! This enumeration data type describes the parallelisation type of the
  //! matrix.
  //! <center>
  //! <table border="1" cellpadding="10">
  //! <tr>
  //!   <td align="center"><b>Enumeration value</b></td>
  //!   <td align="center"><b>Description</b></td>
  //! </tr>
  //! <tr><td>NOPARMATRIXTYPE</td><td>No type was specified.</td></tr>
  //! <tr><td>SEQMATRIX</td><td>This is a sequential matrix object.</td></tr>
  //! <tr><td>PARMATRIX</td><td>This is a ParMatrix object. The type of the
  //! submatrices used for storing the internal and coupling parts can be
  //! obtained from MatrixStorageType.</td></tr>
  //! <tr><td>PARCRSMATRIX</td><td>This is a ParCRS_Matrix object.</td></tr>
  //! </table>
  //! </center>
  typedef enum { NOPARMATRIXTYPE, SEQMATRIX, PARMATRIX, PARCRSMATRIX
               } ParMatrixType;

  //! \name enumeration types for (parallel) AMG
  //@{
  //! interpolation type
  typedef enum { AMG_INTERPOLATION_CONSTANT,
                 AMG_INTERPOLATION_SIMPLE_WEIGHTED,
                 AMG_INTERPOLATION_SMOOTHED_SCALING,
                 AMG_INTERPOLATION_DEVELOP
               } AMGInterpolationType;
  //! smoother type
  typedef enum { AMG_SMOOTHER_GAUSSSEIDEL,
                 AMG_SMOOTHER_DAMPED_JACOBI
               } AMGSmootherType;
  //@}

  //! Type of treatment of inhomogeneous Dirichlet boundary conditions

  //! Enumeration data type describing the approach used for the treatment
  //! of inhomogeneous Dirichlet boundary conditions. Can currently take one
  //! of the following values
  //! - IDBC_NOTYPE
  //! - IDBC_ELIMINATION
  //! - IDBC_PENALTY
  typedef enum { IDBC_NOTYPE, IDBC_ELIMINATION, IDBC_PENALTY } IDBCType;

  // Instantiation for all known enum types;
#define DEFINE_ENUM_CONVERSION(TYPE)                                  \
  template<typename TYPE> void String2Enum(const std::string &in, TYPE &out); \
  template<typename TYPE> void Enum2String(const TYPE &in, std::string &out);

  DEFINE_ENUM_CONVERSION(FreqSamplingType)
  DEFINE_ENUM_CONVERSION(CouplingInputType)
  DEFINE_ENUM_CONVERSION(CouplingOutputType)
  DEFINE_ENUM_CONVERSION(CouplingRegionType)
  DEFINE_ENUM_CONVERSION(NormType)
  DEFINE_ENUM_CONVERSION(ComplexFormat)
  DEFINE_ENUM_CONVERSION(EQNType)
  DEFINE_ENUM_CONVERSION(MaterialClass)
  DEFINE_ENUM_CONVERSION(IntegrationMethod)
  DEFINE_ENUM_CONVERSION(NonLinType)
  DEFINE_ENUM_CONVERSION(DampingType)
  DEFINE_ENUM_CONVERSION(StopCritType)
  DEFINE_ENUM_CONVERSION(FEMatrixType)
  DEFINE_ENUM_CONVERSION(IDBCType)


#undef DEFINE_ENUM_CONVERSION

  std::string MapSolTypeToUnit(SolutionType solType);

#ifdef INTEGLIB
  typedef enum {NOTYPE, SYSTEM, STIFFNESS, DAMPING, CONVECTION, MASS}
  FEMatrixType;

#endif
  
  void SetEnvironmentEnums();

} // end of namespace

#endif // FILE_SCFE_MYDEFS
