#
C_DIR= ../../..
include ../../../main/Makefile.option
#
src = mathParser.cc muParserBase.cpp muParser.cpp muParserBytecode.cpp \
      muParserCallback.cpp muParserError.cpp muParserTokenReader.cpp \
      muParserInt.cpp
#
CFLAGS3 =
#
include ../../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE this line



