/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the files COPYING and Copyright.html.  COPYING can be found at the root   *
 * of the source code distribution tree; Copyright.html can be found at the  *
 * root level of an installed copy of the electronic HDF5 document set and   *
 * is linked from the top-level documents page.  It can also be found at     *
 * http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have          *
 * access to either file, you may request a copy from help@hdfgroup.org.     *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Nov 21, 2012
 *			
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"      SUMMARY OF THE HDF5 CONFIGURATION\n"
	"      =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.8.8\n"
	"                  Configured on: \n"
	"                  Configured by: Unix Makefiles\n"
	"                 Configure mode: CMAKE 2.8.9\n"
	"                    Host system: Linux-2.6.32-279.11.1.el6.x86_64\n"
	"              Uname information: Windows\n"
	"                       Byte sex: little-endian\n"
	"                      Libraries: STATIC\n"
	"             Installation point: /home/strieben/Documents/dev/CFS_BUILD/FESPACE_WIN64\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"               Compilation Mode: DEBUG\n"
	"                     C Compiler: /usr/bin/x86_64-w64-mingw32-gcc\n"
	"                         CFLAGS:  -w -std=c99 -fomit-frame-pointer -finline-functions -fno-common -fmessage-length=0\n"
	"                      H5_CFLAGS: \n"
	"                      AM_CFLAGS: \n"
	"                       CPPFLAGS: -w -fmessage-length=0\n"
	"                    H5_CPPFLAGS: \n"
	"                    AM_CPPFLAGS: \n"
	"               Shared Libraries: NO\n"
	"               Static Libraries: YES\n"
	"  Statically Linked Executables: OFF\n"
	"                        LDFLAGS:  \n"
	"                     AM_LDFLAGS: \n"
	"                Extra libraries: ws2_32;wsock32;/home/strieben/Documents/dev/CFS_BUILD/FESPACE_WIN64/lib64/RHEL_6_X86_64/libz.a\n"
	"                       Archiver: /usr/bin/x86_64-w64-mingw32-ar\n"
	"                         Ranlib: /usr/bin/x86_64-w64-mingw32-ranlib\n"
	"              Debugged Packages: \n"
	"                    API Tracing: OFF\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                        Fortran: OFF\n"
	"               Fortran Compiler: /usr/bin/x86_64-w64-mingw32-gfortran\n"
	"          Fortran 2003 Compiler: \n"
	"                  Fortran Flags: \n"
	"               H5 Fortran Flags: \n"
	"               AM Fortran Flags: \n"
	"                            C++: ON\n"
	"                   C++ Compiler: /usr/bin/x86_64-w64-mingw32-g++\n"
	"                      C++ Flags: -w -fmessage-length=0\n"
	"                   H5 C++ Flags: \n"
	"                   AM C++ Flags: \n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: OFF\n"
	"             High Level library: ON\n"
	"                   Threadsafety: OFF\n"
	"            Default API Mapping: \n"
	" With Deprecated Public Symbols: ON\n"
	"         I/O filters (external):  DEFLATE\n"
	"         I/O filters (internal):  SHUFFLE FLETCHER32 NBIT SCALEOFFSET\n"
	"                            MPE: \n"
	"                     Direct VFD: \n"
	"                        dmalloc: \n"
	"Clear file buffers before write: ON\n"
	"           Using memory checker: OFF\n"
	"         Function Stack Tracing: OFF\n"
	"                           GPFS: OFF\n"
	"      Strict File Format Checks: OFF\n"
	"   Optimization Instrumentation: OFF\n"
	"       Large File Support (LFS): ON\n"
;

