# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# TEST_LFS_WORKS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set TEST_LFS_WORKS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# TEST_LFS_WORKS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set TEST_LFS_WORKS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The TEST_LFS_WORKS_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/HDF5Tests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec3494696799-TEST_LFS_WORKS_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( TEST_LFS_WORKS_RUN 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( TEST_LFS_WORKS_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# HDF5_PRINTF_LL_TEST_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HDF5_PRINTF_LL_TEST_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HDF5_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set HDF5_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HDF5_PRINTF_LL_TEST_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/HDF5Tests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec594295720-HDF5_PRINTF_LL_TEST_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( HDF5_PRINTF_LL_TEST_RUN 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HDF5_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT 
     "PRINTF_LL_WIDTH=[q]"
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LDOUBLE_TO_INTEGER_WORKS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LDOUBLE_TO_INTEGER_WORKS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LDOUBLE_TO_INTEGER_WORKS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LDOUBLE_TO_INTEGER_WORKS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LDOUBLE_TO_INTEGER_WORKS_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/ConversionTests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec1696645044-H5_LDOUBLE_TO_INTEGER_WORKS_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( H5_LDOUBLE_TO_INTEGER_WORKS_RUN 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_LDOUBLE_TO_INTEGER_WORKS_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_ULONG_TO_FLOAT_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_ULONG_TO_FLOAT_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_ULONG_TO_FLOAT_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_ULONG_TO_FLOAT_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_ULONG_TO_FLOAT_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/ConversionTests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec3190958351-H5_ULONG_TO_FLOAT_ACCURATE_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( H5_ULONG_TO_FLOAT_ACCURATE_RUN 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_ULONG_TO_FLOAT_ACCURATE_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/ConversionTests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec1128576126-H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_FP_TO_ULLONG_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_FP_TO_ULLONG_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_FP_TO_ULLONG_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_FP_TO_ULLONG_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_FP_TO_ULLONG_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/ConversionTests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec1926078024-H5_FP_TO_ULLONG_ACCURATE_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( H5_FP_TO_ULLONG_ACCURATE_RUN 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_FP_TO_ULLONG_ACCURATE_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_FP_TO_ULLONG_RIGHT_MAXIMUM_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/ConversionTests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec495437719-H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LDOUBLE_TO_UINT_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LDOUBLE_TO_UINT_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LDOUBLE_TO_UINT_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LDOUBLE_TO_UINT_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LDOUBLE_TO_UINT_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/ConversionTests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec2767825674-H5_LDOUBLE_TO_UINT_ACCURATE_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( H5_LDOUBLE_TO_UINT_ACCURATE_RUN 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_LDOUBLE_TO_UINT_ACCURATE_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_ULLONG_TO_LDOUBLE_PRECISION_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_ULLONG_TO_LDOUBLE_PRECISION_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_ULLONG_TO_LDOUBLE_PRECISION_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_ULLONG_TO_LDOUBLE_PRECISION_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_ULLONG_TO_LDOUBLE_PRECISION_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/ConversionTests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec39794711-H5_ULLONG_TO_LDOUBLE_PRECISION_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( H5_ULLONG_TO_LDOUBLE_PRECISION_RUN 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_ULLONG_TO_LDOUBLE_PRECISION_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_FP_TO_INTEGER_OVERFLOW_WORKS_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/ConversionTests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec3317117288-H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LDOUBLE_TO_LLONG_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LDOUBLE_TO_LLONG_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LDOUBLE_TO_LLONG_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/ConversionTests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec352390050-H5_LDOUBLE_TO_LLONG_ACCURATE_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( H5_LDOUBLE_TO_LLONG_ACCURATE_RUN 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LLONG_TO_LDOUBLE_CORRECT_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LLONG_TO_LDOUBLE_CORRECT_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LLONG_TO_LDOUBLE_CORRECT_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/ConversionTests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec1545317816-H5_LLONG_TO_LDOUBLE_CORRECT_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( H5_LLONG_TO_LDOUBLE_CORRECT_RUN 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_NO_ALIGNMENT_RESTRICTIONS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_NO_ALIGNMENT_RESTRICTIONS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_NO_ALIGNMENT_RESTRICTIONS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_NO_ALIGNMENT_RESTRICTIONS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_NO_ALIGNMENT_RESTRICTIONS_COMPILE variable holds the build result for this TRY_RUN().
# 
# Source file   : hdf5/config/cmake/ConversionTests.c
# Executable    : hdf5-static-build/CMakeFiles/cmTryCompileExec53468950-H5_NO_ALIGNMENT_RESTRICTIONS_RUN
# Run arguments : 
#    Called from: [2]	hdf5/config/cmake/ConfigureChecks.cmake
#                 [1]	hdf5/CMakeLists.txt

SET( H5_NO_ALIGNMENT_RESTRICTIONS_RUN 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_NO_ALIGNMENT_RESTRICTIONS_RUN__TRYRUN_OUTPUT 
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)

