#
C_DIR = ../../..
#
include $(C_DIR)/main/Makefile.option
#
src = outGSI.cc GSIBaseIO.cc GSIXDRIO.cc GSISocket.cc
#
lib = gsi
libpath = libsrc/DataInOut/GSI
CFLAGS3 =
#
include ../../makefile.inc
-include Makefile.depend
#
# DO NOT DELETE


