#
C_DIR = ../../..
#
include $(C_DIR)/main/Makefile.option
#
src = outGSI.cc GSIBaseIO.cc GSIXDRIO.cc GSIRawIO.cc GSIIOException.cc GSIEndianConverter.cc GSISocket.cc
#
CFLAGS3 =
#
include ../../makefile.inc
-include Makefile.depend
#
# DO NOT DELETE


