#
# Makefile for discretization
C_DIR=../..
#
src = baseForm.cc laplaceInt.cc bdbInt.cc linElastInt.cc nLinElastInt.cc massInt.cc baseoperator.cc \
	elecfieldop.cc elecforceop.cc curlCurlEdgeInt.cc massEdgeInt.cc linearForm.cc  smoothInt.cc curlCurlNodeInt.cc linPiezoInt.cc nLincurlCurlNodeInt.cc
#
lib = forms
libpath = libsrc/Forms
CFLAGS3 =
#
include ../makefile.inc

# DO NOT DELETE


