#
# Makefile for physical system
C_DIR=../..
#
#src = timeerror.cc actimeerror.cc spaceerror.cc
src = 
#
lib = estimator
libpath = libsrc/Estimator
CFLAGS3 =
#
include ../makefile.inc

# DO NOT DELETE


