#-------------------------------------------------------------------------------
# SGPP (sparse nonlinear optimizer) is a commercial general purpose optimizer
# which can be used efficiently for structural optimization.
#
# The chair applied mathematics 2 (FAU) has a license for the code.
#
# You need to request the encrypted file sgopt.zip with the source 
# from the optimization group. 
# Place sgopt.zip to the cfsdepscache source/sgpp directory
# and set the password for the file to CFS_KEY_SGPP (e.g. in .cfs_platform_defaults.cmake)
#-------------------------------------------------------------------------------

set(SGPP_PREFIX  "${CMAKE_CURRENT_BINARY_DIR}/cfsdeps/sgpp")
set(SGPP_SOURCE  "${SGPP_PREFIX}/src/sgpp")
# we use this as temporary install directory to alllow packing for precompiled cfsdeps
# for sgpp we also need to remove the libblas.a generated by sgpp as we have an own one in cfs!
set(SGPP_INSTALL  "${SGPP_PREFIX}/src/sgpp/SGpp_0.9.3")

# sgpp is build by configure, therefore no cmake args needed

# no patches are required

# we do not download but assume the file to magically exist there. It is encrypted!
SET(LOCAL_FILE "${CFS_DEPS_CACHE_DIR}/sources/sgpp/${SGPP_ZIP}")
# we don't check the md5 here

if(NOT EXISTS "${LOCAL_FILE}")
  message(FATAL_ERROR "Please provide the encypted sgpp source in ${LOCAL_FILE}") 
endif()

#if(NOT CFS_KEY_SGPP)
#  message(FATAL_ERROR "Key for encrypted ${SGPP_ZIP} required in CFS_KEY_SGPP. Set e.g. in your ~/.cfs_platform_defaults.cmake")
#endif()    

# precompiled cfsdeps not yet implemented!

# the whole build project
ExternalProject_Add(sgpp
  PREFIX "${SGPP_PREFIX}"
  SOURCE_DIR "${SGPP_SOURCE}"
  # all in the zip is below sgopt
  BINARY_DIR "${SGPP_SOURCE}/SGpp_0.9.3"
  # don't dowload but simply copy w/o md5 check
  DOWNLOAD_COMMAND ${CMAKE_COMMAND} -E copy ${LOCAL_FILE} ${SGPP_SOURCE}
  # the zip file is encrypted!
  #PATCH_COMMAND unzip -q -u -P ${CFS_KEY_SGPP} ${SGPP_ZIP}
  PATCH_COMMAND unzip -q -u ${SGPP_ZIP}
  INSTALL_COMMAND ""
  CONFIGURE_COMMAND ""
  # let it install inplace where we can prepare to copy to precompiled cfsdeps
  # the libs will be created in lib/sgpp and we manually copy them to lib64/CFS_ARCH_STR
  BUILD_COMMAND scons -j 4 -s SG_OPT=yes OMP=yes UMFPACK=yes EIGEN=yes ARMADILLO=yes GMMPP=yes
)

# after the installation we remove libblas.a, remove the confidental source, copy to cfs and might copy to precompiled cfsdeps
SET(PI_TEMPL "${CFS_SOURCE_DIR}/cfsdeps/sgpp/sgpp-post_install.cmake.in")
SET(PI "${SGPP_PREFIX}/sgpp-post_install.cmake")
CONFIGURE_FILE("${PI_TEMPL}" "${PI}" @ONLY) 

# execute the stuff from sgpp-post_install.cmake after installation
ExternalProject_Add_Step(sgpp post_install COMMAND ${CMAKE_COMMAND} -P "${PI}" DEPENDEES install)

# Add project to global list of CFSDEPS, this allows "make sgpp"
SET(CFSDEPS ${CFSDEPS} sgpp)

# Determine paths of SGPP libraries.
SET(LD "${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}")
#SET(SGPP_LIBRARY "${LD}/libsgppopt.a;${LD}/libumfpack4sgpp.a;${LD}/libsuitesparseconfig4sgpp.a;${LD}/libarmadillo4sgpp.a;${LD}/libsgppbase.a;${LD}/libsgpppde.a;${LD}/libsgppsolver.a" CACHE FILEPATH "SGPP library.")
SET(SGPP_LIBRARY "${LD}/libsgppopt.a;${LD}/libumfpack4sgpp.a;${LD}/libsuitesparseconfig4sgpp.a;${LD}/libarmadillo4sgpp.a;${LD}/libsgppbase.a;${LD}/libsgpppde.a;${LD}/libsgppsolver.a;${LD}/libamd_dlong.a;${LD}/libcholmod_dlong.a;${LD}/libcolamd_dlong.a;${LD}/libccolamd_dlong.a;${LD}/libcamd_dlong.a;${LD}/libarpack.a" CACHE FILEPATH "SGPP library.")

MARK_AS_ADVANCED(SGPP_LIBRARY)
