# env -i HOME=/Users/simon PATH=/bin:/usr/bin:/sbin:/usr/sbin /Users/simon/Applications/CMake\ 2.8-8.app/Contents/bin/cmake -P Documents/dev/nightly_test.cmake
# vagrant ssh -c 'env -i HOME=/Users/simon PATH=/bin:/usr/bin:/sbin:/usr/sbin env && uname -a && /opt/pckg/cmake-2.8.10.2-Linux-i386/bin/cmake --version'

GET_FILENAME_COMPONENT(CTEST_SCRIPTS_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
INCLUDE("${CTEST_SCRIPTS_DIR}/test_macros.cmake")

SET_GLOBAL_VARS()
SET_SITE_SPECIFIC_VARS()

MESSAGE("CMAKE_COMMAND: ${CMAKE_COMMAND}")
MESSAGE("CMAKE_EXECUTABLE_SUFFIX: ${CMAKE_EXECUTABLE_SUFFIX}")
MESSAGE("CTEST_COMMAND: ${CTEST_COMMAND}")
MESSAGE("CMAKE_CURRENT_LIST_FILE: ${CMAKE_CURRENT_LIST_FILE}")
MESSAGE("SITE_BASE_DIR: ${SITE_BASE_DIR}")
MESSAGE("HOSTNAME: ${HOSTNAME}")
MESSAGE("SITE_DIR: ${SITE_DIR}")
MESSAGE("TESTUSER: ${TESTUSER}")
MESSAGE("HOME: ${HOME}")
MESSAGE("DAYOFWEEK: ${DAYOFWEEK}")

SITE_SPECIFIC_INIT()

FILE(GLOB TEST_FILES "${SITE_DIR}/*.ctest")

FOREACH(F IN ITEMS ${TEST_FILES})

  MESSAGE("BARBARA")
  GET_FILENAME_COMPONENT(TEST_NAME "${F}" NAME_WE)
  MESSAGE("Performing test: ${TEST_NAME}...")
  GET_CTEST_BINARY_DIRECTORY(${TEST_NAME})
  PERFORM_TEST(${TEST_NAME})
  DEPLOY_TEST(${TEST_NAME})
  CLEANUP_TEST(${TEST_NAME})

ENDFOREACH()

SITE_SPECIFIC_FINISH()

