
MACRO(SET_GLOBAL_VARS)

  # =========================================================================
  #
  #  Set some global variables.
  #
  #  Some global variables are set using this macro. E.g. the host name
  #  for this site gets determined and paths to the CMake/CTest binaries
  #  are set. Additionally we print out the current environment.
  #
  # =========================================================================

  IF(WIN32)
    SET(CMAKE_EXECUTABLE_SUFFIX ".exe")
  ENDIF()
  STRING(REGEX REPLACE "/cmake${CMAKE_EXECUTABLE_SUFFIX}$" "/ctest${CMAKE_EXECUTABLE_SUFFIX}" CTEST_COMMAND "${CMAKE_COMMAND}")
  GET_FILENAME_COMPONENT(SITE_BASE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
  SET(SITE_BASE_DIR "${SITE_BASE_DIR}/sites")
  SITE_NAME(HOSTNAME)
  STRING(REPLACE "." ";" HOSTNAME_LIST "${HOSTNAME}")
  LIST(GET HOSTNAME_LIST 0 HOSTNAME)
  SET(SITE_DIR "${SITE_BASE_DIR}/${HOSTNAME}")
  EXECUTE_PROCESS(
    COMMAND date "+%u"
    OUTPUT_VARIABLE DAYOFWEEK
    RESULT_VARIABLE RETVAL
    )
  STRING(REPLACE "\n" "" DAYOFWEEK "${DAYOFWEEK}")

  #---------------------------------------------------------------------------
  # Set destination directory for nightly built binaries
  #---------------------------------------------------------------------------
  SET(NIGHTLY_ARCHIVES_DIR "/opt/pckg/cfs_nightly/archives")

  MESSAGE(
  "
=============================================================================
 Environment:
=============================================================================
  "
  )
  EXECUTE_PROCESS(
    COMMAND "${CMAKE_COMMAND}" -E environment
  #  WORKING_DIRECTORY "${BUILDDIR}"
    RESULT_VARIABLE RETVAL
    )
ENDMACRO()



MACRO(SET_SITE_SPECIFIC_VARS)

  # =========================================================================
  #
  #  Set some site-specific variables.
  #
  #  If the some special variables are required for a certain site, this
  #  can be achieved by setting them in ${SITE_DIR}/site_specific_vars.cmake
  #
  # =========================================================================

  IF(UNIX)
    # Set user name
    EXECUTE_PROCESS(
      COMMAND id -un
      OUTPUT_VARIABLE TESTUSER
      RESULT_VARIABLE RETVAL
    )
    STRING(STRIP ${TESTUSER} TESTUSER)

    # Set home directory
    EXECUTE_PROCESS(
      COMMAND getent passwd ${TESTUSER}
      OUTPUT_VARIABLE PWDLINE
      RESULT_VARIABLE RETVAL
    )
    STRING(REPLACE ":" ";" PWDLINE ${PWDLINE})

    LIST(GET PWDLINE 5 HOME)
  ENDIF()

#  MESSAGE("Entering SET_SITE_SPECIFIC_VARS...")
  INCLUDE("${SITE_DIR}/site_specific_vars.cmake" OPTIONAL)
#  MESSAGE("Leaving SET_SITE_SPECIFIC_VARS...")
ENDMACRO()



MACRO(GET_TEST_NAMES TEST_NAME_LIST)

  # =========================================================================
  #
  #  Generate list of test names.
  #
  #  By default the list of tests is generated by globbing all .ctest files
  #  in the site directory. On some machines, however, the order of tests is
  #  important.
  #  This can e.g. be the case, when nightly binaries for a network share
  #  should generated first and the more unimportant tests should be
  #  performed later on.
  #  Therefore, the creator of new tests can specify the order in which
  #  they will be performed in an additional generate_test_name_list.cmake
  #  file in which the macro GENERATE_TEST_NAME_LIST() has to be specified.
  #
  # =========================================================================

  SET(TEST_LIST_GEN_FN "${SITE_DIR}/generate_test_name_list.cmake")
  IF(NOT EXISTS "${TEST_LIST_GEN_FN}")
    FILE(GLOB TEST_FILES "${SITE_DIR}/*.ctest")

    FOREACH(TESTFN IN ITEMS ${TEST_FILES})

      GET_FILENAME_COMPONENT(TEST_NAME "${TESTFN}" NAME_WE)
      list(APPEND ${TEST_NAME_LIST} ${TEST_NAME})
    ENDFOREACH()
  ELSE()
    INCLUDE("${TEST_LIST_GEN_FN}")
    GENERATE_TEST_NAME_LIST(${TEST_NAME_LIST})
  ENDIF()
ENDMACRO()



MACRO(PERFORM_TEST TEST_NAME)

  # =========================================================================
  #
  #  Actually perform tests.
  #
  #  We distinguish if we are on UNIX (mainly Linux) or on Windows.
  #  For x86/amd64 Linux machines one can choose if the program should run
  #  in 32-bit or 64-bit environment by prefixing a command with linux32
  #  or linux64. This enables us to build 32-bit binaries on a x86_64
  #  machine. The type of environment for a test can therefore be chosen
  #  by prefixing the test file name with linux32_ or linux64_.
  #  
  # =========================================================================

  MESSAGE(
"
=============================================================================
 Performing test: ${TEST_NAME}...
=============================================================================
"
  )

  IF(EXISTS "${CTEST_BINARY_DIRECTORY}")
    MESSAGE("Removing previous build directory ${CTEST_BINARY_DIRECTORY}...")
    FILE(REMOVE_RECURSE "${CTEST_BINARY_DIRECTORY}")
  ENDIF()

  IF(UNIX)
    STRING(REPLACE "_" ";" TARGET_ARCH_ENV_LIST "${TEST_NAME}")
    LIST(GET TARGET_ARCH_ENV_LIST 0 TARGET_ARCH)

    IF(TARGET_ARCH MATCHES "linux[0-9][0-9]")
      EXECUTE_PROCESS(
        COMMAND ${TARGET_ARCH} ${CTEST_COMMAND} -V --build-two-config -S "${SITE_DIR}/${TEST_NAME}.ctest"
        WORKING_DIRECTORY "."
        RESULT_VARIABLE RETVAL
      )
    ELSE()
      EXECUTE_PROCESS(
        COMMAND ${CTEST_COMMAND} -V --build-two-config -S "${SITE_DIR}/${TEST_NAME}.ctest"
        WORKING_DIRECTORY "."
        RESULT_VARIABLE RETVAL
      )
    ENDIF()
  ELSE(UNIX)

    LIST(APPEND TEST_CMD "\\\"${CTEST_COMMAND}\\\"" -V --build-two-config -S "\\\"${SITE_DIR}/${TEST_NAME}.ctest\\\"")

    MESSAGE(STATUS "TEST_CMD: ${TEST_CMD}")

    EXECUTE_PROCESS(
      COMMAND ${CTEST_COMMAND} -V --build-two-config -S "${SITE_DIR}/${TEST_NAME}.ctest"
      WORKING_DIRECTORY "."
      RESULT_VARIABLE RETVAL
      )

  ENDIF(UNIX)

  IF(NOT EXISTS "${SITE_DIR}/logs")
    FILE(MAKE_DIRECTORY "${SITE_DIR}/logs")
  ENDIF()
  FILE(MAKE_DIRECTORY "${SITE_DIR}/logs/${TEST_NAME}")
EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory "${CTEST_BINARY_DIRECTORY}/Testing"  "${SITE_DIR}/logs/${TEST_NAME}"
  RESULT_VARIABLE RETVAL)


ENDMACRO()



MACRO(DEPLOY_TEST TEST_NAME)

  # =========================================================================
  #
  #  Deploy built binaries.
  #
  #  For some tests, we do not want to throw away the built binaries but
  #  rather make them available to others via a network share.
  #  
  #  This macro looks for a script ${SITE_DIR}/${TEST_NAME}_deploy.cmake
  #  in which the actions for the deployment of the binaries can be carried
  #  out. If the script can be found it will be exectued. If no such script
  #  exists, nothing will happen.
  #  
  # =========================================================================

  SET(DEPLOY_SCRIPT "${SITE_DIR}/${TEST_NAME}_deploy.cmake")
  IF(EXISTS "${DEPLOY_SCRIPT}")
    EXECUTE_PROCESS(
      COMMAND ${CTEST_COMMAND} -DCMAKE_COMMAND:FILEPATH=${CMAKE_COMMAND} -DNIGHTLY_ARCHIVES_DIR:PATH=${NIGHTLY_ARCHIVES_DIR} -DHOSTNAME:STRING=${HOSTNAME} -DTEST_NAME:STRING=${TEST_NAME} -S "${DEPLOY_SCRIPT}"
      WORKING_DIRECTORY "${SITE_DIR}"
      RESULT_VARIABLE RETVAL
      )
  ENDIF()
ENDMACRO()



MACRO(CLEANUP_TEST TEST_NAME)

  # =========================================================================
  #
  #  Clean up after test has finished.
  #
  #  Does nothing at the moment...
  #
  # =========================================================================

  MESSAGE("Cleaning up ${CTEST_BINARY_DIRECTORY}")

#  FILE(REMOVE_RECURSE "${CTEST_BINARY_DIRECTORY}")
ENDMACRO()



MACRO(TEMP_NAME fname)

  # =========================================================================
  #
  #  Create temp file name.
  #
  # =========================================================================

  if(${ARGC} GREATER 1) # Have to escape ARGC to correctly compare
    set(_base ${ARGV1})
  else(${ARGC} GREATER 1)
    set(_base ".cmake-tmp")
  endif(${ARGC} GREATER 1)
  set(_counter 0)
  while(EXISTS "${_base}${_counter}")
    math(EXPR _counter "${_counter} + 1")
  endwhile(EXISTS "${_base}${_counter}")
  set(${fname} "${_base}${_counter}")
endmacro()



MACRO(EVAL expr)

  # =========================================================================
  #
  #  Evaluate expression
  #  Suggestion from the Wiki: http://cmake.org/Wiki/CMake/Language_Syntax
  #  Unfortunately, no built-in stuff for this:
  #  http://public.kitware.com/Bug/view.php?id=4034
  #
  # =========================================================================

  temp_name(_fname)
  file(WRITE ${_fname} "${expr}")
  include(${_fname})
  file(REMOVE ${_fname})
endmacro()



MACRO(GET_CTEST_BINARY_DIRECTORY TEST_NAME)

  # =========================================================================
  #
  #  Determine location of binary directory of a test.
  #
  # =========================================================================

  FILE(STRINGS "${SITE_DIR}/${TEST_NAME}.ctest" FSTR)

  FOREACH(LINE IN LISTS FSTR)
    IF(LINE MATCHES "SET\\(CTEST_BINARY_DIRECTORY")
      SET(CTEST_BINARY_DIRECTORY_STR "${LINE}")
    ENDIF()
  ENDFOREACH()

#  EXECUTE_PROCESS(
#    COMMAND mktemp -t nightly_test_XXXX
#    WORKING_DIRECTORY "."
#    OUTPUT_VARIABLE TMPFILE
#    RESULT_VARIABLE RETVAL
#    )
#  STRING(REPLACE "\n" "" TMPFILE "${TMPFILE}")

#  MESSAGE("TMPFILE ${TMPFILE}")

#  FILE(WRITE "${TMPFILE}" "${CTEST_BINARY_DIRECTORY_STR}")

#  INCLUDE("${TMPFILE}")
  STRING(REPLACE "\$ENV{" "\\\$ENV{" CTEST_BINARY_DIRECTORY_STR "${CTEST_BINARY_DIRECTORY_STR}")
  MESSAGE(STATUS "CTEST_BINARY_DIRECTORY_STR ${CTEST_BINARY_DIRECTORY_STR}")
  EVAL("${CTEST_BINARY_DIRECTORY_STR}")
  FILE(TO_CMAKE_PATH "${CTEST_BINARY_DIRECTORY}" CTEST_BINARY_DIRECTORY)
  MESSAGE(STATUS "CTEST_BINARY_DIRECTORY ${CTEST_BINARY_DIRECTORY}")

#  FILE(REMOVE "${TMPFILE}")
ENDMACRO()



MACRO(SITE_SPECIFIC_INIT)

  # =========================================================================
  #
  #  Perform site-specific initialization before testing.
  #
  #  A site can provide ${SITE_DIR}/site_specific_init.cmake if certain 
  #  tasks have to be carried out before testing can start (e.g. update 
  #  working copies, kill/start virtual machines, etc.)
  #
  # =========================================================================

#  MESSAGE("Entering SITE_SPECIFIC_INIT...")
  INCLUDE("${SITE_DIR}/site_specific_init.cmake" OPTIONAL)
#  MESSAGE("Leaving SITE_SPECIFIC_INIT...")
ENDMACRO()



MACRO(SITE_SPECIFIC_FINISH)

  # =========================================================================
  #
  #  Perform site-specific finalization after testing.
  #
  #  A site can provide ${SITE_DIR}/site_specific_finish.cmake if certain
  #  tasks have to be carried out after testing has finished (e.g. put built
  #  binaries into proper locations, etc.)
  #
  # =========================================================================

#  MESSAGE("Entering SITE_SPECIFIC_FINISH...")
  INCLUDE("${SITE_DIR}/site_specific_finish.cmake" OPTIONAL)
#  MESSAGE("Leaving SITE_SPECIFIC_FINISH...")
ENDMACRO()

