INST_BIN_DIR=/home/data/proj/bin
INST_MAC_DIR=/ansys_inc/local
INST_BASE_HOST=lse10

inst:
	scp -pr mkmesh root@$(INST_BASE_HOST):$(INST_BIN_DIR)
	scp -pr mkmesh.mlib root@$(INST_BASE_HOST):$(INST_MAC_DIR)
