#!/usr/bin/gawk -f
# Make .mesh-file from .nodes, .elements, .nodebc, .savenode and .saveelem files.
# Peipp, 2002-07-31


BEGIN {
   if (ARGC >= 2) {
      # rework around an error of ANSYS 6.1 which calls external programs
      # with the "/syp" command with additional "0" arguments
      for (i=ARGC-1; i>=1; i--) {
	 if (ARGV[i] == "0") ARGC=i;
	 else break;
      }
     
      Filename = ARGV[ARGC-1];
      for(i=1; i<ARGC-1; i++) {
         if (substr(ARGV[i],1,1) != "-") {
            printf("ERROR: %s -- unknown option\n", ARGV[i]) > "/dev/stderr";
            exit 1;
         } else if (substr(ARGV[i],2) == "d") {
            DEBUG = 1; # print debug information
         } else if (substr(ARGV[i],2) == "D") {
            DEGEN = 1; # allow degenerated elements
         } else {
            printf("ERROR: %s -- unknown option\n", ARGV[i]) > "/dev/stderr";
            exit 1;
         }
      }
      ARGC = 1;
   } else {
      print "mkmesh" > "/dev/stderr";
      print "USAGE: mkmesh [-d] modelName" > "/dev/stderr";
      print "       modelName must be specified without file extension! "\
         > "/dev/stderr";
      print "       -d: print debug info" > "/dev/stderr";
      print "       -D: allow degenerated elements" > "/dev/stderr";
      exit 1;
   }

   # define numerical precision
   CONVFMT = "%.16g";

   NodesInFile = Filename ".nodes";
   NodesOutFile = Filename ".nodes###";

   NodeBCInFile = Filename ".nodebc";
   NodeBCOutFile = Filename ".nodebc###";
   
   ElementsInFile = Filename ".elements";
   Elements3DOutFile = Filename ".elements3D###";
   Elements2DOutFile = Filename ".elements2D###";
   Elements1DOutFile = Filename ".elements1D###";

   SaveNodesInFile = Filename ".savenode";
   SaveNodesOutFile = Filename ".savenode###";
   SaveElementsInFile = Filename ".saveelem";
   SaveElementsOutFile = Filename ".saveelem###";

   MeshFile = Filename ".mesh";

   system("rm -f " NodesOutFile " " NodeBCOutFile " " Elements3DOutFile " "\
          Elements2DOutFile " " Elements1DOutFile " " SaveNodesOutFile " "\
          SaveElementsOutFile " "MeshFile);

   Version = 1;
   Dimension = 0
   NumNodes = 0;
   Num3DElements = 0;
   Num2DElements = 0;
   Num1DElements = 0;
   NumNodeBC = 0;
   NumSaveNodes = 0;
   NumSaveElements = 0;

   if (DEBUG) print "processing .nodes ..." > "/dev/stderr";

   # parse .nodes file
   while((getline < NodesInFile) == 1) {
#     print $1, $2, $3, $4 >> NodesOutFile;
      x = substr($0,9,28)+0;
      y = substr($0,29,48)+0;
      z = substr($0,49,68)+0;
      if (Dimension < 3 && z != 0) Dimension = 3;
      else if (Dimension < 2 && y != 0) Dimension = 2;
      else if (Dimension < 1 && x != 0) Dimension = 2;
      printf("%8d % .13e % .13e % .13e\n",\
             substr($0, 1, 8)+0, x, y, z) >> NodesOutFile;
      NumNodes++;
   }
   if (NumNodes == 0) {
      print "ERROR: no nodes found" > "/dev/stderr";
      print "       please check the " NodesInFile " file" > "/dev/stderr";
      exit 2;
   }
   close(NodesInFile);
   close(NodesOutFile);

   if (DEBUG) print "processing .elements ..." > "/dev/stderr";

   # parse .elements file
   level = "";
   while((getline < ElementsInFile) == 1) {
      if ($0 ~ /^\[/) { # level record

         # write out old ElemRecord
         WriteElementRecord();

         ElemLevel = $1;
         gsub(/[\[\]]/, "", ElemLevel);
         if (DEBUG) print " current level: " ElemLevel > "/dev/stderr";

      } else if (NF == 14) { # first line of element record

         # write out old ElemRecord
         WriteElementRecord();

         # parameters of new ElemRecord
         mat = $9;
         ElemType = $10;
         BaseElemType = ElemType;
         real = $11;
         secnum = $12;
         esys = $13;
         ElemNumber = $14;

         # element nodes
         ElemNodes = $1; # first node;
         delete ElemNodeList;
         ElemNodeList[$1] = 1;
         i = 2;
         NrOfNodes = 1;
         while (($i > 0) && (i <= 8)) {
            if (DEGEN || ElemNodeList[$i] != 1) { # no double nodes
               ElemNodes = ElemNodes " " $i;
               NrOfNodes++;
               ElemNodeList[$i] = 1;
            }
            i++;
         }

         if (!DEGEN) {
            # find new element type for degenerated elements
            #   rectangle to triangle
            if (ElemType == 6 && NrOfNodes == 3) BaseElemType = 4;
            #   quad rectangle to triangle
            if (ElemType == 7 && NrOfNodes == 6) BaseElemType = 5;
            #   brick to tetrahedron
            if (ElemType == 10 && NrOfNodes == 4) BaseElemType = 8;
            #   brick to pyramid
            if (ElemType == 10 && NrOfNodes == 5) BaseElemType = 12;
            #   brick to wedge
            if (ElemType == 10 && NrOfNodes == 6) BaseElemType = 13;
            #   quad brick to tetrahedron
            if (ElemType == 11 && NrOfNodes == 10) BaseElemType = 9;
            #   quad brick to pyramid
            if (ElemType == 11 && NrOfNodes == 13) BaseElemType = 14;
            #   quad brick to wedge
            if (ElemType == 11 && NrOfNodes == 15) BaseElemType = 15;
         }
         
      } else { # second line of element record
         for (i = 1; i<=NF; i++){
            if (DEGEN || ElemNodeList[$i] != 1) { # no double nodes
               ElemNodes = ElemNodes " " $i;
               NrOfNodes++;
            }
         }
      }
   }
   # write out last ElemRecord
   WriteElementRecord();

   if (Num1DElements + Num2DElements + Num3DElements == 0){
      print "ERROR: no elements found" > "/dev/stderr";
      print "       please check the " ElementsInFile " file" > "/dev/stderr";
      exit 2;
   }
   close(ElementsInFile);
   close(Elements1DOutFile);
   close(Elements2DOutFile);
   close(Elements3DOutFile);

   if (DEBUG) print "processing .nodesbc ..." > "/dev/stderr";

   # parse .nodesbc file
   level = "";
   while((getline < NodeBCInFile) == 1) {
      if ($0 ~ /^\[/) { # level record
         level = $1;
         gsub(/[\[\]]/, "", level);
         if (DEBUG) print " current level: " level > "/dev/stderr";
      } else {
         print substr($0, 1, 8), level >> NodeBCOutFile;
         NumNodeBC++;
      }
   }
   close(NodeBCInFile);
   close(NodeBCOutFile);

   if (DEBUG) print "processing .savenode ..." > "/dev/stderr";

   # parse .savenode file
   level = "";
   while((getline < SaveNodesInFile) == 1) {
      if ($0 ~ /^\[/) { # level record
         level = $1;
         gsub(/[\[\]]/, "", level);
         if (DEBUG) print " current level: " level > "/dev/stderr";
      } else {
         print substr($0, 1, 8), level >> SaveNodesOutFile;
         NumSaveNodes++;
      }
   }
   close(SaveNodesInFile);
   close(SaveNodesOutFile);

   if (DEBUG) print "processing .saveelem ..." > "/dev/stderr";

   # parse .saveelem file
   level = "";
   while((getline < SaveElementsInFile) == 1) {
      if ($0 ~ /^\[/) { # level record
         level = $1;
         gsub(/[\[\]]/, "", level);
         if (DEBUG) print " current level: " level > "/dev/stderr";
      } else {
         print $14, level >> SaveElementsOutFile;
         NumSaveElements++;
      }
   }
   close(SaveElementsInFile);
   close(SaveElementsOutFile);

   # ================ write mesh file ===================

   if (DEBUG) print "writing .mesh ..." > "/dev/stderr";

   # write [info] section
   print "[Info]" > MeshFile;
   print "Version " Version >> MeshFile;
   print "Dimension " Dimension >> MeshFile;
   print "NumNodes " NumNodes >> MeshFile;
   print "Num3DElements " Num3DElements >> MeshFile;
   print "Num2DElements " Num2DElements >> MeshFile;
   print "Num1DElements " Num1DElements >> MeshFile;
   print "NumNodeBC " NumNodeBC >> MeshFile;
   print "NumSaveNodes " NumSaveNodes >> MeshFile;
   print "NumSaveElements " NumSaveElements >> MeshFile;
   for(i = 0; i <= 11; i++)
      print "NumElemType" i " " NumElemType[i]+0 >> MeshFile;
   for(i = 0; i <= 15; i++)
      print "NumBaseElemType" i " " NumBaseElemType[i]+0 >> MeshFile;
   print "" >> MeshFile;
   if (DEBUG) system("cat " MeshFile);

   # write [Nodes] section
   print "[Nodes]" >> MeshFile;
   print "#NodeNr x-coord y-coord z-coord" >> MeshFile;
   close(MeshFile);
   system("cat -s " NodesOutFile " >> " MeshFile);
   print "" >> MeshFile;

   # write [3D Elements] section
   print "[3D Elements]" >> MeshFile;
   print "#ElemNr  ElemType  NrOfNodes  Level" >> MeshFile;
   print "#Node1 Node2 ... NodeNrOfNodes" >> MeshFile;
   close(MeshFile);
   system("cat -s " Elements3DOutFile " >> " MeshFile);
   print "" >> MeshFile;
   
   # write [2D Elements] section
   print "[2D Elements]" >> MeshFile;
   print "#ElemNr  ElemType  NrOfNodes  Level" >> MeshFile;
   print "#Node1 Node2 ... NodeNrOfNodes" >> MeshFile;
   close(MeshFile);
   system("cat -s " Elements2DOutFile " >> " MeshFile);
   print "" >> MeshFile;
   
   # write [1D Elements] section
   print "[1D Elements]" >> MeshFile;
   print "#ElemNr  ElemType  NrOfNodes  Level" >> MeshFile;
   print "#Node1 Node2 ... NodeNrOfNodes" >> MeshFile;
   close(MeshFile);
   system("cat -s " Elements1DOutFile " >> " MeshFile);
   print "" >> MeshFile;
   
   # write [Node BC] section
   print "[Node BC]" >> MeshFile;
   print "#NodeNr Level" >> MeshFile;
   close(MeshFile);
   system("cat -s " NodeBCOutFile " >> " MeshFile);
   print "" >> MeshFile;

   # write [Save Nodes] section
   print "[Save Nodes]" >> MeshFile;
   print "#NodeNr Level" >> MeshFile;
   close(MeshFile);
   system("cat -s " SaveNodesOutFile " >> " MeshFile);
   print "" >> MeshFile;

   # write [Save Elements] section
   print "[Save Elements]" >> MeshFile;
   print "#ElemNr Level" >> MeshFile;
   close(MeshFile);
   system("cat -s " SaveElementsOutFile " >> " MeshFile);
   print "" >> MeshFile;

   system("rm -f " NodesOutFile " " NodeBCOutFile " " Elements3DOutFile " "\
          Elements2DOutFile " " Elements1DOutFile " " SaveNodesOutFile " "\
          SaveElementsOutFile);

}

function WriteElementRecord() {
   # write out old ElemRecord
   if (ElemNodes != "") {
   # build new ElemRecord
	  ElemRecord = ElemNumber " " BaseElemType " " NrOfNodes\
		 " " ElemLevel "\n" ElemNodes;
	  if (ElemType <= 3) {
		 print ElemRecord >> Elements1DOutFile;
		 Num1DElements++;
	  } else if (ElemType <= 7) {
		 print ElemRecord >> Elements2DOutFile;
		 Num2DElements++;
	  } else {
		 print ElemRecord >> Elements3DOutFile;
		 Num3DElements++;
	  }
	  NumElemType[ElemType]++;
	  NumBaseElemType[BaseElemType]++;
   }
   ElemNodes = "";
   return;
}
