#
# Makefile for discretization
C_DIR=../../..
#
src = tetraFE.cc tetra1FE.cc hexaFE.cc hexa1FE.cc pyraFE.cc pyra1FE.cc wedgeFE.cc wedge1FE.cc
#
lib = elements3d
libpath = libsrc/Elements/3D
CFLAGS3 =
#
include ../../makefile.inc
-include $(Dependencies)
# DO NOT DELETE


