#
# Makefile for discretization
C_DIR=../../..
#
src = getetrahedral.cc tetrahedral1.cc gehexahedral.cc hexahedral1.cc
#
lib = elements3d
libpath = libsrc/Elements/3D
CFLAGS3 =
#
include ../../makefile.inc

# DO NOT DELETE


