#
# Makefile for discretization
C_DIR=../../..
#
src = tetraFE.cc tetra1FE.cc tetra2FE.cc hexaFE.cc hexa1FE.cc pyraFE.cc pyra1FE.cc pyra2FE.cc wedgeFE.cc wedge1FE.cc hexa2FE.cc wedge2FE.cc
#
CFLAGS3 =
#
include ../../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE


