#
C_DIR = ../../..
src = cfsmessenger.cc tcl-messenger.cc scriptable.cc
#
lib = scripting
libpath = libsrc/DataInOut/Scripting
CFLAGS3 =
#
include ../../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE


