#
# Makefile for discretization
#
C_DIR=../../..
src = definefiles.cc 
#
lib = definefiles
libpath = libsrc/DataInOut/DefineFiles
CFLAGS3 =
#
include ../../makefile.inc
-include $(Dependencies)
# DO NOT DELETE


