#
# Makefile for discretization
#
C_DIR=../../..
src = grid_struct.cc 
#
lib = gridstruct
libpath = libsrc/Domain/GridStruct
CFLAGS3 =
#
include ../../makefile.inc
-include $(Dependencies)
# DO NOT DELETE


