#
C_DIR=../..
#
src = acousticMaterial.cc baseMaterial.cc electroMagneticMaterial.cc \
      electrostaticMaterial.cc flowMaterial.cc heatMaterial.cc \
      MaterialData.cc mechanicMaterial.cc MHMaterialData.cc \
      piezoMaterial.cc
#
CFLAGS3 =
#
include ../makefile.inc
-include $(DEPEND_FILE)

