// -*- mode: c++; coding: utf-8; indent-tabs-mode: nil; -*-
// kate: space-indent on; indent-width 2; encoding utf-8;
// kate: auto-brackets on; mixedindent off; indent-mode cstyle;

#ifndef FILE_EXTLBMPDE
#define FILE_EXTLBMPDE

#include <string>

#include "DataInOut/ParamHandling/ParamNode.hh"
#include "General/Enum.hh"
#include "General/defs.hh"
#include "General/environment.hh"
#include "MatVec/matrix.hh"
#include "MatVec/vector.hh"
#include "SinglePDE.hh"
#include "Utils/nodestoresol.hh"


namespace CoupledField {
class BaseResult;
class Grid;
class PDECoupling;
class DesignElement;
class Function;
}  // namespace CoupledField
 
namespace CoupledField
{

  //! Class for mechanic equation (no adaptivity)
  class ExtLBMPDE: public SinglePDE
  {

  public:
    typedef enum { INTERNAL, EXT_MATLAB, EXT_CFSxLBM } Iface;

    //!  Constructor. here we read integration parameters
    /*!
      \param aGrid pointer to grid
    */
    ExtLBMPDE(Grid* grid, PtrParamNode pn);

//    //!  Deconstructor
//    virtual ~ExtLBMPDE() {;};

    //! define all (bilinearform) integrators needed for this pde
    virtual void DefineIntegrators();

    //! define the SoltionStep-Driver
    virtual void DefineSolveStep();

    //! initalize PDE coupling
    virtual void InitCoupling(PDECoupling * Coupling);

    //! initialize time stepping: nothing to do in smoother!
    void InitTimeStepping();

    //! set time step
    //! \param dt Current time step
    virtual void SetTimeStep(const Double dt){};
  
    //! calculate coupling terms
    virtual void CalcOutputCoupling();

    /** handle the dirty flag -> CalcResults() and Solve() */
    void SetDirty(bool dirty) { dirty_ = dirty; }

    /** actually calls LBM.
     * Triggered also by CalcResults() if dirty_ is set */
    void Solve();

    /** For the olt multi-file interface, reads the files x_pardiso2.dat and dRdp.mtx and computes the gradient */
    void SetPrecalculatedGradient(StdVector<DesignElement*>& design, Function* f);

    /** Üerform postprocessing on data. Conditionally calls Solve() if dirty is set */
    void CalcResults( shared_ptr<BaseResult> result );

    /** implementation of objective function */
    double CalcPressureDrop();

    //! returns if PDE can compute the quantity
    virtual bool HasOutput(SolutionType output);

    virtual void ReadSpecialResults();

    Iface GetIface() const { return iface_; }

    //! Contains LBM velocity
    NodeStoreSol<Double> solDeriv1_;
    
    Matrix<Double> couplingNodes_;

  private:

    /** part of the constructor */
    void InitRegions(PtrParamNode pn, Grid* grid);

    /** setup elemen mapping
     * @see elem_to_idx
     * @see ids_to_elem */
     void SetupElementMapping(Grid* grid);

    //! Define available result types
    void DefineAvailResults();

    /** Calculate the LBM Density of an element idx */
    inline double CalcLBMDensity(unsigned int idx) const;

    inline double CalcVelocityX(unsigned int idx, double density) const;

    inline double CalcVelocityY(unsigned int idx, double density) const;

    inline double CalcPressure(unsigned int idx) const;

    double pdf(unsigned int idx, int dir) const  {
      return pdfs[idx * 9 + dir];
    };

    double& pdf(unsigned int idx, int dir) {
      return pdfs.GetPointer()[idx * 9 + dir];
    };


    //! Calculate macroscopic velocities
    void CalcVelocities(shared_ptr<BaseResult> res);

    //! Calculate densities
    void CalcDensities(shared_ptr<BaseResult> res);

    void CalcPressures(shared_ptr<BaseResult> res);

    // reads discrete velocities from extern LBM simulation
    void ReadProbabilityDistribution(const std::string& file);

    /** export file(s) for external LBM communication. Checks iface_ */
    void ExportExternalSolverFiles();

    /** write the single CFS2LBM.dat dat (new interface) */
    void ExportCFS2LBM(const StdVector<double>& elements);

    /** write the files for the old interface: data.dat, obst.dat, por.dat, non_sing_dat. These are e.g. generated by thomas guess's matlab optimization */
    void ExportMultipleFiles(const StdVector<double>& elements);

    /** This method computes the indices of the adjoint system which avoid a singular Jacobian. Based on Georg Pingen and Thomas Guess, see non_singularities_new.m */
    void IdentifyNonSingualrityIndices(Matrix<int>& obst, StdVector<unsigned int>& indices);

    /** ist solved for current "data". Cleared by Solve(). checked by CalcResults() to handle simulation w/o optimization.
     * @see SetDirty() */
    bool dirty_;

    //! Method of smoothing
    std::string method_;

    //! Flag indicating if PDE is assembled for first time
    bool firstTurn_;

    //! Vector storing factors for adapted pseudo mechanic bulk modulus
    Vector<Double> factor_;

    /** this stores the boundary region id */
    RegionIdType boundary_reg_;

    /** this stores the design region */
    StdVector<RegionIdType> design_reg_;

    /** LBM requires the data do be ordered in a defined way (lexicographic). The LBM data covers all regions (design and boundary).
     * To allow access by region (CalcResults()) this does the mapping from CFS elemNum to lbm idx and lbm idx to elemNum. lbm idx is 0-based
     * elem_to_idx has the size of the larges elem_num and contains the idx or -1 where there is no mapping.
     * @see SetupElemMapping() */
    StdVector<int> elem_to_idx;

    /** size n_elems and contains the CFS elemNr
     * @see elem_to_idx */
    StdVector<int> idx_to_elem;

    /** extents of computational grid */
    unsigned int n_x_, n_y_, n_z_;

    /** total number of elements */
    unsigned int n_elems;

    /** storage for PDFs */
    StdVector<double> pdfs;

    /** this are the indices of the inlet elements */
    StdVector<unsigned int> inlet;

    /** this are the indices of the outlet elements */
    StdVector<unsigned int> outlet;

    double omega_;
    double maxWallTime_;
    unsigned int maxIter_;
    double convergence_;

    // inlet velocities
    double u_x_;
    double u_y_;
    double u_z_;

    std::string executable;

    /** type of interface */
    Iface iface_;
    Enum<Iface> iface;
  };

} // end of namespace
#endif
