#
# Makefile for discretization
#
C_DIR=../../..
src = interface_gridlib.cc 
#
lib = togridlib
libpath = libsrc/Domain/Gridlib 
CFLAGS3 =
#
include ../../makefile.inc
-include $(Dependencies)
# DO NOT DELETE


