# ===========================================================================
#  Include macros for starting/stopping VBoxes on wiki.
# ===========================================================================
INCLUDE("${SITE_DIR}/macros_for_wiki.cmake")

# ===========================================================================
#  Wait until it is 7:30 and then deploy binaries generated by nightly
#  builds to HTTP server and /opt/pckg/cfs_nightly.
# ===========================================================================

# Find out seconds of current time                                                                                                     
GET_SECONDS(NOW_SEC "now")

# Find out seconds at 7:30
GET_SECONDS(SEVEN_THIRTY_SEC "today 7:30")

MESSAGE("NOW_SEC ${NOW_SEC}")
MESSAGE("SEVEN_THIRTY_SEC ${SEVEN_THIRTY_SEC}")

# Determine how many seconds to wait until 7:30
MATH(EXPR SLEEP_SEC "${SEVEN_THIRTY_SEC}-${NOW_SEC}")
MESSAGE("SLEEP_SEC ${SLEEP_SEC}")

# If it is still before 7:30 sleep until then
IF(SLEEP_SEC GREATER 0)
  CTEST_SLEEP(${SLEEP_SEC})
ENDIF()

# Print current date and time for debug purposes
EXECUTE_PROCESS(
  COMMAND date
  RESULT_VARIABLE RETVAL)


# ===========================================================================
#  Make nightly binaries available via Apache server.
# ===========================================================================
EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory archives ${APACHE_NIGHTLY_DIR}
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)


# ===========================================================================
#  Unpack nightly binaries to /opt/pckg/cfs_nightly.
# ===========================================================================

# Unpack FeSpace binaries
IF(NOT EXISTS "${CFS_NIGHTLY_DIR}/fespace_gcc")
  FILE(MAKE_DIRECTORY "${CFS_NIGHTLY_DIR}/fespace_gcc")
ENDIF()
IF(NOT EXISTS "${CFS_NIGHTLY_DIR}/fespace_icc")
  FILE(MAKE_DIRECTORY "${CFS_NIGHTLY_DIR}/fespace_icc")
ENDIF()


EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E tar xvf archives/oracle6_linux64_fespace_gcc_release.zip
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory CFS_BUILD_NIGHTLY fespace_gcc
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

FILE(REMOVE_RECURSE "${CFS_NIGHTLY_DIR}/CFS_BUILD_NIGHTLY")


EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E tar xvf archives/precise_linux64_fespace_gcc_release.zip
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory CFS_BUILD_NIGHTLY fespace_gcc
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

FILE(REMOVE_RECURSE "${CFS_NIGHTLY_DIR}/CFS_BUILD_NIGHTLY")

EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E tar xvf archives/wiki_linux64_fespace_icc12_release.zip
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory CFS_BUILD_NIGHTLY fespace_icc
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

FILE(REMOVE_RECURSE "${CFS_NIGHTLY_DIR}/CFS_BUILD_NIGHTLY")


# Unpack Trunk binaries
IF(NOT EXISTS "${CFS_NIGHTLY_DIR}/trunk_gcc")
  FILE(MAKE_DIRECTORY "${CFS_NIGHTLY_DIR}/trunk_gcc")
ENDIF()

EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E tar xvf archives/oracle6_linux64_trunk_gcc_release.zip
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

# Remove symlinks pointing to nirvana. Otherwise cmake -E copy_directory
# will return an error.
EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E remove bzcmp bzegrep bzfgrep bzless
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}/CFS_BUILD_NIGHTLY/bin/RHEL_6_X86_64"
  RESULT_VARIABLE RETVAL)

EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory CFS_BUILD_NIGHTLY trunk_gcc
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

FILE(REMOVE_RECURSE "${CFS_NIGHTLY_DIR}/CFS_BUILD_NIGHTLY")


EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E tar xvf archives/precise_linux64_trunk_gcc_release.zip
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

# Remove symlinks pointing to nirvana. Otherwise cmake -E copy_directory
# will return an error.
EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E remove bzcmp bzegrep bzfgrep bzless
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}/CFS_BUILD_NIGHTLY/bin/UBUNTU_12.04_X86_64"
  RESULT_VARIABLE RETVAL)

EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory CFS_BUILD_NIGHTLY trunk_gcc
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

FILE(REMOVE_RECURSE "${CFS_NIGHTLY_DIR}/CFS_BUILD_NIGHTLY")

# ===========================================================================
#  Copy over CFSDEPS and CFSDEPSCACHE to /opt/pckg.
# ===========================================================================

FILE(GLOB CFSDEPSCACHE_FILES "/opt/pckg/CFSDEPSCACHE/*")
IF(NOT CFSDEPSCACHE_FILES STREQUAL "")
  FILE(REMOVE_RECURSE ${CFSDEPSCACHE_FILES})
ENDIF()

FILE(GLOB CFSDEPS_FILES "/opt/pckg/CFSDEPS/*")
IF(NOT CFSDEPS_FILES STREQUAL "")
  FILE(REMOVE_RECURSE ${CFSDEPS_FILES})
ENDIF()

EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory CFSDEPS_TRUNK_NIGHTLY /opt/pckg/CFSDEPS
  WORKING_DIRECTORY "${HOME}/Documents/dev/NIGHTLY"
  RESULT_VARIABLE RETVAL)

EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory CFSDEPSCACHE /opt/pckg/CFSDEPSCACHE
  WORKING_DIRECTORY "${HOME}/Documents/dev/NIGHTLY"
  RESULT_VARIABLE RETVAL)

# ===========================================================================
#  Kill still running VMs...
# ===========================================================================
POWER_OFF_RUNNING_VBOXES()

# ===========================================================================
#  Clean up Virtual Box directories
# ===========================================================================
CLEANUP_VBOX_DIRS()

# ===========================================================================
#  Clean up local nightly build directory
# ===========================================================================
FILE(REMOVE_RECURSE "${HOME}/Documents/dev/NIGHTLY/CFS_BUILD_NIGHTLY")

# ===========================================================================
#  Start Virtual Boxes. After 7:30 we start the other VBoxes depending on 
#  DAYOFWEEK. The Windows XP 32-bit box should be started every day.
#  Since we are low on hdd space, we don't start N boxes at the same time
#  but we just start one box at a time and then wait for 4h.
# ===========================================================================
SET(VBOXES "winxp32")

MATH(EXPR DAY "${DAYOFWEEK} % 3")

START_VBOXES(${VBOXES})

# ===========================================================================
#  Wait for 4h
# ===========================================================================
CTEST_SLEEP(14400)

# ===========================================================================
#  Make nightly binaries available via Apache server (again).
# ===========================================================================
EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory archives ${APACHE_NIGHTLY_DIR}
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)



# ===========================================================================
#  At the moment we do not go on with the other VBoxes and just stop here.
# ===========================================================================
MESSAGE(FATAL_ERROR "We just stop here. Nothing wrong. Don't worry!")




# ===========================================================================
#  Kill still running VMs...
# ===========================================================================
POWER_OFF_RUNNING_VBOXES()

# ===========================================================================
#  Clean up Virtual Box directories
# ===========================================================================
CLEANUP_VBOX_DIRS()

IF(DAY EQUAL 0)
  SET(VBOXES "sles10")
ENDIF()
IF(DAY EQUAL 1)
  SET(VBOXES "oracle5")
ENDIF()
IF(DAY EQUAL 2)
  SET(VBOXES "hardy")
ENDIF()

# ===========================================================================
#  Wait for 4h
# ===========================================================================
CTEST_SLEEP(14400)

# ===========================================================================
#  Kill still running VMs...
# ===========================================================================
POWER_OFF_RUNNING_VBOXES()

# ===========================================================================
#  Clean up Virtual Box directories
# ===========================================================================
CLEANUP_VBOX_DIRS()

IF(DAY EQUAL 0)
  SET(VBOXES "sles11")
ENDIF()
IF(DAY EQUAL 1)
  SET(VBOXES "fedora18")
ENDIF()
IF(DAY EQUAL 2)
  SET(VBOXES "lucid")
ENDIF()

# ===========================================================================
#  Wait for 4h
# ===========================================================================
CTEST_SLEEP(14400)

# ===========================================================================
#  Kill still running VMs...
# ===========================================================================
POWER_OFF_RUNNING_VBOXES()

# ===========================================================================
#  Clean up Virtual Box directories
# ===========================================================================
CLEANUP_VBOX_DIRS()

IF(DAY EQUAL 0)
  SET(VBOXES "opensuse123")
ENDIF()
IF(DAY EQUAL 2)
  SET(VBOXES "lmde201303")
ENDIF()

# ===========================================================================
#  Make nightly binaries available via Apache server (once more).
# ===========================================================================
EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory archives ${APACHE_NIGHTLY_DIR}
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)
