# Wait until it is 7:30 and then deploy binaries generated by nightly builds
# to HTTP server and /opt/pckg.
EXECUTE_PROCESS(
  COMMAND ${CTEST_COMMAND} -DCMAKE_COMMAND:FILEPATH=${CMAKE_COMMAND} -S ${SITE_DIR}/wait_until_seven_thirty_then_deploy_binaries.cmake 
  RESULT_VARIABLE RETVAL)

