# Find out seconds of current time
EXECUTE_PROCESS(
  COMMAND date +%s
  OUTPUT_VARIABLE NOW_SEC
  RESULT_VARIABLE RETVAL)
STRING(STRIP ${NOW_SEC} NOW_SEC)

# Find out seconds at 7:30
EXECUTE_PROCESS(
  COMMAND date -d "today 7:30" +%s
  OUTPUT_VARIABLE SEVEN_THIRTY_SEC
  RESULT_VARIABLE RETVAL)
STRING(STRIP ${SEVEN_THIRTY_SEC} SEVEN_THIRTY_SEC)

MESSAGE("NOW_SEC ${NOW_SEC}")
MESSAGE("SEVEN_THIRTY_SEC ${SEVEN_THIRTY_SEC}")

# Determine how many seconds to wait until 7:30
MATH(EXPR SLEEP_SEC "${SEVEN_THIRTY_SEC}-${NOW_SEC}")
MESSAGE("SLEEP_SEC ${SLEEP_SEC}")

# If it is still before 7:30 sleep until then
IF(SLEEP_SEC GREATER 0)
  CTEST_SLEEP(${SLEEP_SEC})
ENDIF()

# Print current date and time for debug purposes
EXECUTE_PROCESS(
  COMMAND date
  RESULT_VARIABLE RETVAL)



SET(CFS_NIGHTLY_DIR "/opt/pckg/cfs_nightly")

IF(NOT EXISTS "${CFS_NIGHTLY_DIR}/fespace_gcc")
  FILE(MAKE_DIRECTORY "${CFS_NIGHTLY_DIR}/fespace_gcc")
ENDIF()

EXECUTE_PROCESS(
  COMMAND unzip archives/oracle6_linux64_fespace_gcc_release.zip
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory CFS_BUILD_NIGHTLY fespace_gcc
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

FILE(REMOVE_RECURSE "${CFS_NIGHTLY_DIR}/CFS_BUILD_NIGHTLY")


EXECUTE_PROCESS(
  COMMAND unzip archives/precise_linux64_fespace_gcc_release.zip
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

EXECUTE_PROCESS(
  COMMAND ${CMAKE_COMMAND} -E copy_directory CFS_BUILD_NIGHTLY fespace_gcc
  WORKING_DIRECTORY "${CFS_NIGHTLY_DIR}"
  RESULT_VARIABLE RETVAL)

FILE(REMOVE_RECURSE "${CFS_NIGHTLY_DIR}/CFS_BUILD_NIGHTLY")
