#
# Makefile for discretization
#
C_DIR=../../..
src = GridAdaption.cc
#
lib = gridadaption
libpath = libsrc/Domain/GridAdaption
CFLAGS3 =
#
include ../../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE


