#
# Makefile for discretization
#
C_DIR=../..
#
src = filetype.cc timefunc.cc writeresults.cc MaterialData.cc \
      LoadMaterialData.cc WriteInfo.cc
#
lib = datainout
libpath = libsrc/DataInOut
CFLAGS3 =
#
include ../makefile.inc

# DO NOT DELETE


