#
# Makefile for discretization
#
C_DIR=../..
#
src = conffile.cc filetype.cc timefunc.cc writeresults.cc MaterialData.cc LoadMaterialData.cc WriteInfo.cc \
      SkeletonConf.cc
#
lib = datainout
libpath = libsrc/DataInOut
CFLAGS3 =
#
include ../makefile.inc

# DO NOT DELETE


