# Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.
# https://eigen.tuxfamily.org/index.php?title=Main_Page#Documentation
#
clear_depencency_variables()

# set mandatory variables for the macros in DependencyTools.cmake.
set(PACKAGE_NAME "eigen")
set(PACKAGE_VER "3.4.0")
set(PACKAGE_FILE "eigen-${PACKAGE_VER}.tar.bz2")
set(PACKAGE_MD5 "132dde48fe2b563211675626d29f1707")
set(DEPS_VER "-a") # set to "-a", "-b", when dependency changed with same PACKAGE_VER. Reset to "" with new PACKAGE_VER.

# the mirrors can point to arbitrary file names. 
set(PACKAGE_MIRRORS "https://gitlab.com/libeigen/eigen/-/archive/${PACKAGE_VER}/${PACKAGE_FILE}") 
# add default mirrors to PACKAGE_MIRRORS or replace all with LOCAL_PACKAGE_FILE if we already have it
add_standard_mirrors_or_set_local()

 # we do not compile as eigen is header only
use_c_and_fortran(OFF OFF)

# sets PRECOMPILED_PCKG_FILE to the full precompiled name including path
set_precompiled_pckg_file()

# cmake package building directly to cfs build. precompiled package via manifest
set(DEPS_PREFIX  "${CMAKE_BINARY_DIR}/cfsdeps/${PACKAGE_NAME}")
set(DEPS_SOURCE  "${DEPS_PREFIX}/src/${PACKAGE_NAME}")

# the clean-<package> target deletes everything to allow a clean make <package>
add_clean_target()

# Don't use use install_manifest.txt
set(DEPS_INSTALL "${DEPS_PREFIX}/install")

# set DEPS_ARG with defaults for a cmake project
set_deps_args_default(ON)

# add flag for using only MPL2 or weaker-licenced parts of eigen
set(EIGEN_CXX_FLAGS "${CFSDEPS_CXX_FLAGS} -DEIGEN_MPL2_ONLY")

# add the specific settings for the packge which comes in cmake style
set(DEPS_ARGS ${DEPS_ARGS} -DBUILD_TESTING:BOOL=OFF -DINCLUDE_INSTALL_DIR:PATH=${DEPS_INSTALL}/include/ -DCMAKE_CXX_FLAGS:STRING=${EIGEN_CXX_FLAGS})

# --- it follows generic final block for cmake packages with no patch and no postinstall ---

# copy "static" license as we configure this dependency. Check if license is still valid!
file(COPY "${CMAKE_SOURCE_DIR}/cfsdeps/${PACKAGE_NAME}/license/" DESTINATION "${CMAKE_BINARY_DIR}/license/${PACKAGE_NAME}" )

assert_unset(PATCHES_SCRIPT)

# filter from DEPS_INSTALL, zip and copy to binary dir 
generate_packing_script_install_dir()

# we have no postinstall, so don't call generate_postinstall_script()
assert_unset(POSTINSTALL_SCRIPT)

# dump_depencency_variables()

# do we want to use precompiled and do we already have the package?
if(${CFS_DEPS_PRECOMPILED} AND EXISTS "${PRECOMPILED_PCKG_FILE}")
  # copy files from cache
  create_external_unpack_precompiled()

# if not, build newly and possibly pack the stuff
else()
  create_external_cmake()  

  # new data just built: shall we pack and store as precompiled?
  if(${CFS_DEPS_PRECOMPILED})
    # add custom step to zip a precompiled package to the cache.
    add_external_storage_step()
  else()
    # without manifest (installs directly to binary dir) an without packing, we need to copy manually  
    add_install_dir_to_binary_step()  
  endif()  
endif()

# --- relocatable CMake package config for find_package(Eigen3 CONFIG) consumers ---
# Eigen is header-only: openCFS consumes it via its include dir, but preCICE (and
# any other find_package(Eigen3 3.4 CONFIG) consumer) needs an Eigen3Config.cmake.
# Eigen's OWN config installs to share/eigen3/cmake and is NOT shipped in the
# cfsdeps precompiled zip (DepsPackagingInstallDir.cmake.in packs only include/ and
# lib/cmake for *dynamic* deps; eigen is static). Worse, eigen's build-tree
# export(PACKAGE Eigen3) registry entry exists ONLY after a fresh build - so a
# cache-restored eigen has no discoverable config at all and preCICE fails with
# "Could not find a package configuration file provided by Eigen3". Generate a
# minimal, self-contained config next to the (always-present, both fresh and
# precompiled) headers so discovery is identical in both cases. Path is computed
# from CMAKE_CURRENT_LIST_DIR so it survives the pack/unpack prefix relocation.
# Only preCICE needs config mode, so gate on CFS_BUILD_PRECICE.
if(CFS_BUILD_PRECICE)
  set(_EIGEN_CMAKE_DIR "${CMAKE_BINARY_DIR}/lib/cmake/eigen3")
  file(WRITE "${_EIGEN_CMAKE_DIR}/Eigen3Config.cmake"
"# generated by cfsdeps/eigen/External_EIGEN.cmake - do not edit
get_filename_component(_eigen3_prefix \"\${CMAKE_CURRENT_LIST_DIR}/../../..\" ABSOLUTE)
set(EIGEN3_VERSION_STRING \"${PACKAGE_VER}\")
set(EIGEN3_INCLUDE_DIR \"\${_eigen3_prefix}/include\")
set(EIGEN3_INCLUDE_DIRS \"\${EIGEN3_INCLUDE_DIR}\")
set(EIGEN3_ROOT_DIR \"\${_eigen3_prefix}\")
if(NOT TARGET Eigen3::Eigen)
  add_library(Eigen3::Eigen INTERFACE IMPORTED)
  set_target_properties(Eigen3::Eigen PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES \"\${EIGEN3_INCLUDE_DIR}\")
endif()
")
  file(WRITE "${_EIGEN_CMAKE_DIR}/Eigen3ConfigVersion.cmake"
"set(PACKAGE_VERSION \"${PACKAGE_VER}\")
if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  if(PACKAGE_VERSION VERSION_EQUAL PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
")
endif()

# add project to global list of CFSDEPS
set(CFSDEPS ${CFSDEPS} ${PACKAGE_NAME})
