#!/bin/sh

# This script facilitates to run CFS with various profiling / debbuging tools:
# 
#  - gdb
#  - valgrind-memcheck (memory leak detection)
#  - valgrind-callgrind (generation of call graph)
#  - valgrind-massif (detailed heap-profiling)
#  - gperftools-cpu (generation of call graph, FAST)


# print usage of script
PrintUsage() {
    echo -e "This is the CFS debugging / profiling script.";
    echo -e "The following usage modes are available:\n"
    
    echo -e "1) GDB-run"
    echo -e "----------"
    echo -e "Run the cfs binary with the gnu debugger.\n"
    echo -e "Usage:"
    echo -e "\t cfs-debug gdb [cfs-arguments]\n\n"

    echo -e "2) Valgrind-memcheck run"
    echo -e "------------------------"
    echo -e "Check the binary for memory leaks.\n"
    echo -e "Usage:"
    echo -e "\t cfs-debug memcheck [cfs-arguments]\n"
    echo -e "NOTE: Valgrind slows down the execution up to 10-20 times!\n\n"

    echo -e "3) Valgrind-callgrind run"
    echo -e "-------------------------"
    echo -e "Create dynamic callgraph with profiling information."
    echo -e "Results can be investigeated using 'kcachegrind'.\n"
    echo -e "Usage:"
    echo -e "\t cfs-debug callgrind [cfs-arguments]\n"
    echo -e "NOTE: Valgrind slows down the execution up to 10-20 times!\n\n"
    
    echo -e "4) Valgrind-massif run"
    echo -e "-------------------------"
    echo -e "Create dynamic memory profile of a CFS run."
    echo -e "Results can be investigeated using 'ms_print'.\n"
    echo -e "Usage:"
    echo -e "\t cfs-debug massif [cfs-arguments]\n"
    echo -e "NOTE: Valgrind slows down the execution up to 10-20 times!\n\n"

    echo -e "5) GPerftools-CPU profiler run"
    echo -e "------------------------------"
    echo -e "Create dynamic callgraph with profiling information."
    echo -e "Results can be investigeated using using 'kcachegrind' (if format=callgrind)"
    echo -e "Usage:"
    echo -e "\t cfs-debug gperf-cpu <outfile> <format> [cfs-arguments]\n\n"

    echo -e "6) GPerftools-Heap profiler run"
    echo -e "-------------------------------"
    echo -e "Create dynamic memory profile of a CFS run."
    echo -e "Usage:"
    echo -e "\t cfs-debug gperf-heap <outfile> [cfs-arguments]\n"
    

    exit 1
}

# generic check if command exists
CommandExists () {
    type "$1" &> /dev/null ;
}


# run gdb on the executable
RunGdb()
{
    # check if gdb is in the path
    if CommandExists gdb ; then
        echo -e "----------------"
        echo -e " CFS - GDB RUN  "
        echo -e "----------------"
        echo -e "Executing: gdb --args $CFS_EXE $@ \n\n";
        
        gdb --args $CFS_EXE "$@";  
        PostCfsRun
    else
        echo -e "The gdb executable is not in the path"
    fi
}

# run valgrind-memcheck on the executable
RunMemcheck()
{
    # check if valgrind is in the path
    if CommandExists valgrind ; then
        echo -e "--------------------------------"
        echo -e " CFS - VALGRIND - MEMCHECK RUN  "
        echo -e "--------------------------------"
        echo -e "Executing: valgrind --tool=memcheck $CFS_EXE $@ \n\n";
        
        valgrind --tool=memcheck $CFS_EXE "$@"; 
        PostCfsRun 
  else
      echo -e "The valgrind executable is not in the path"
  fi
}

# run valgrind-callgrind on the executable
RunCallgrind()
{
    # check if valgrind is in the path
    if CommandExists valgrind ; then
        echo -e "---------------------------------"
        echo -e " CFS - VALGRIND - CALLGRIND RUN "
        echo -e "---------------------------------"
        echo -e "Executing: valgrind --tool=callgrind $CFS_EXE $@ \n\n";

        valgrind --tool=callgrind $CFS_EXE "$@";  
        PostCfsRun
    else
        echo -e "The valgrind executable is not in the path"
    fi
}

# run valgrind-massif heap checker on the executable
RunMassif()
{
    # check if valgrind is in the path
    if CommandExists valgrind ; then
        echo -e "---------------------------------"
        echo -e " CFS - VALGRIND - MASSIF RUN "
        echo -e "---------------------------------"
        echo -e "Executing: valgrind --tool=massif $CFS_EXE $@ \n\n";
        
        valgrind --tool=massif $CFS_EXE "$@";
        PostCfsRun  
    else
        echo -e "The valgrind executable is not in the path"
    fi
}

# run google perftools - cpuprofler
RunGperfCpu()
{
   
    # check for at least 3 arguments
    if [ $# -lt 3 ]; then
          echo -e "At least three arguments have to be passed to gperf-cpu. Usage:"
      echo -e "\tcfs-debug gperf-cpu <outfile> <format> [cfs-arguments]\n"
      exit 1
    fi

    FOUND=0

    # try to locate libprofiler.so and preload it
    if [ -e /usr/lib/libprofiler.so ]; then
        export LD_PRELOAD=/usr/lib/libprofiler.so:$LD_PRELOAD
        FOUND=1
    fi

    if [ -e /usr/lib64/libprofiler.so ]; then
        export LD_PRELOAD=/usr/lib64/libprofiler.so:$LD_PRELOAD
        FOUND=1
    fi

    if [ -e /usr/local/lib/libprofiler.so ]; then
        export LD_PRELOAD=/usr/local/lib/libprofiler.so:$LD_PRELOAD
        FOUND=1
    fi

    # look for pprof tool
    if CommandExists pprof ; then
        echo -e "The pprof executable is not in the path"
    fi

    # check if pprof is in the path
    if  [ $FOUND == 1 ] ; then
        echo -e "-----------------------------------"
        echo -e " CFS - GPERFTOOLS - CPU PROFILING "
        echo -e "-----------------------------------"
        echo -e "output file: $1"
        echo -e "output format: $2"
         
        # assemble arguments for CFS itself
        REST_ARGS=${@:3}
        echo -e "Executing: env CPUPROFILE=$1 $CFS_EXE $@ && pprof --$2 $CFS_EXE $1 > $1.$2\n\n";
        env CPUPROFILE=$1 $CFS_EXE $REST_ARGS && pprof --$2 $CFS_EXE $1 > $1.$2
        PostCfsRun 
    else
        echo -e "The library libprofile.so of the gperftools cound not be found."
    fi
}

# run google perftools - heapprofiler
RunGperfHeap()
{
   
    # check for at least 3 arguments
    if [ $# -lt 2 ]; then
      echo -e "At least two arguments have to be passed to gperf-heap. Usage:"
      echo -e "\tcfs-debug gperf-heap <outfile> [cfs-arguments]\n"
      exit 1
    fi

    FOUND=0

    # try to locate libprofiler.so and preload it
    if [ -e /usr/lib/libtcmalloc.so ]; then
        export LD_PRELOAD=/usr/lib/libtcmalloc:$LD_PRELOAD
        FOUND=1
    fi

    if [ -e /usr/lib64/libtcmalloc.so ]; then
        export LD_PRELOAD=/usr/lib64/libtcmalloc.so:$LD_PRELOAD
        FOUND=1
    fi

    if [ -e /usr/local/lib/libtcmalloc.so ]; then
        export LD_PRELOAD=/usr/local/lib/libtcmalloc.so:$LD_PRELOAD
        FOUND=1
    fi

    # look for pprof tool
    if CommandExists pprof ; then
        echo -e "The pprof executable is not in the path"
    fi

    # check if pprof is in the path
    if  [ $FOUND == 1 ] ; then
        echo -e "------------------------------------"
        echo -e " CFS - GPERFTOOLS - HEAP PROFILING "
        echo -e "------------------------------------"
        echo -e "output file: $1"
         
        # assemble arguments for CFS itself
        REST_ARGS=${@:2}
        echo -e "Executing: env HEAPPROFILE=$1 $CFS_EXE $REST_ARGS \n\n";
        env HEAPPROFILE=$1 $CFS_EXE $REST_ARGS 
        PostCfsRun
        echo -e "\n\nTo get the memory profile, please execute \n\t pprof --text $CFS_EXE $1.XXXX"
    else
        echo -e "The library libtcmalloc.so of the gperftools cound not be found."
    fi
}


PostCfsRun() {

    # Get file state of output HDF5 file
    if [ -r "$hdf5_file_name" ]; then
	if [ "$OS" = "Mac" ]; then
	    eval "$(stat -s $hdf5_file_name)"
	    st_size_after=$st_size
	    st_mtime_after=$st_mtime
	else
	    st_size_after=$(stat --format %s $hdf5_file_name)
	    st_mtime_after=$(stat --format %Y $hdf5_file_name)
	fi
    fi

    # If HDF5 file did not change just exit
    if [ "$st_size_before" = "$st_size_after" ] && [ "$st_mtime_before" = "$st_mtime_after" ]; then
	exit 0
    fi

    # Create OS-specific hardware info files
    if [ "$OS" = "Mac" ]; then
	/usr/sbin/system_profiler SPHardwareDataType SPSoftwareDataType > macosx_info.txt
	OSFILELIST="macosx_info.txt";
	STATCMD="stat -x"
    fi
    if [ "$OS" = "Linux" ]; then
	cat /proc/cpuinfo > linux_cpuinfo.txt
	cat /proc/meminfo > linux_meminfo.txt
	OSFILELIST="linux_cpuinfo.txt linux_meminfo.txt";
	STATCMD="stat"
    fi

    # Create dump of environment (OMP_NUM_THREADS, etc.)
    env | sort > environment_info.txt
    OSFILELIST="$OSFILELIST environment_info.txt"

    # Setup a file list which should be imported to the HDF5 file
    FILELIST="$OSFILELIST ${sim_name}.deb ${sim_name}.info ${sim_name}.info.xml ${sim_name}.las ${sim_name}.mem"

    # Error checking function
    ErrorCheck () {  if [ ! $? -eq 0 ]; then echo "An error occurred while importing $file into HDF5!"; fi }

    # Iterate over all files and import them
    for file in $FILELIST; do
	if [ -r $file ]; then
	    CMDSTR="dataset\ncreate\n$hdf5_file_name\n/UserData\nstring\n${file}\nignore\n"
	    printf $CMDSTR > tmp.dat
	    echo "Output of '$STATCMD $file': " >> tmp.dat
	    $STATCMD $file >> tmp.dat
	    echo >> tmp.dat
	    echo "================================================================================" >> tmp.dat
	    cat ${file} >> tmp.dat
	    $H5TOOL_EXE < tmp.dat > /dev/null; ErrorCheck
	    rm -f tmp.dat
	fi
    done

    # Delete OS-specific files
    for file in $OSFILELIST; do
	if [ -r $file ]; then
	    rm -f $file
	fi
    done
}

# This is the start script for CFS. It should be placed in
# CFS_DIST/bin under the name 'cfs'

# Source shell script for setting some common variables.
COMMON_SH=`dirname $0`/common.sh
if [ ! -x "$COMMON_SH" ]; then
  echo "Could not execute $COMMON_SH. Exiting..."
  exit 1
fi
. $COMMON_SH

# Determine  ANSYS  revision  from .xml  file  in  order  to set  the  correct
# LD_LIBRARY_PATH. The default is v110.
ANSYS_REV="v110"

for param in "$@"; do
    if [ -f "${param}.xml" ]; then
#	echo $param
	RSTTAG=$(fgrep '<rst' "${param}.xml")
	
	for field in $RSTTAG; do 
	    REV=$(echo $field | sed -n '/ansysRevision.*/p' | \
		cut -d'"' -f2 | sed 's/\.//');
	done
#	echo "v$REV"
    fi
done

if [ ! "$REV" = "" ]; then
    ANSYS_REV="v$REV"
fi

SUSEPackageHint()
{
    DISTRO=$1
    DISTRO_VER=$2

    DISTRO_MAJOR_VER=`echo $DISTRO_VER | cut -d'.' -f 1`

    echo
    echo "   python"
    echo "   tcl"
    echo
}

RedhatPackageHint()
{
    DISTRO=$1
    DISTRO_VER=$2

    DISTRO_MAJOR_VER=`echo $DISTRO_VER | cut -d'.' -f 1`

    echo
    echo "   blas"
    echo "   boost"
    echo "   compat-gcc-g77 or gcc-g77"
    echo "   gcc-gfortran"
    echo "   lapack"
    echo "   python"
    echo "   tcl"
    echo "   xerces-c"
    echo
}

DebianPackageHint()
{
    DISTRO=$1
    DISTRO_VER=$2

    DISTRO_MAJOR_VER=`echo $DISTRO_VER | cut -d'.' -f 1`

    echo
    echo "   blas or refblas3"
    echo "   libg2c0"
    echo "   libboost-*"
    echo "   lapack, lapack99, lapack3"
    echo "   python2.4"
    echo "   tcl8.4"
    echo "   libxerces27"
    echo     
}

UbuntuPackageHint()
{
    DISTRO=$1
    DISTRO_VER=$2

    DISTRO_MAJOR_VER=`echo $DISTRO_VER | cut -d'.' -f 1`

    echo
    echo "   refblas3"
    echo "   libboost-*"
    echo "   libg2c0"
    echo "   lapack3"
    echo "   python2.4"
    echo "   tcl8.4"
    echo "   libxerces27"
    echo
}

MandrivaPackageHint()
{
    DISTRO=$1
    DISTRO_VER=$2

    DISTRO_MAJOR_VER=`echo $DISTRO_VER | cut -d'.' -f 1`

   "libblas1.1, libblas3, libblas, blas"
   "libboost1, libboost, boost"
   "gcc3.3-g77"
   "libgfortran"
   "lapack"
   "python, libpython"
   "libtcl8.4, tcl"
   "xerces-c, libxerces-c"
}

GivePackageHint()
{
    DISTRO=$1
    DISTRO_VER=$2

    case "$DISTRO" in
	SUSE) SUSEPackageHint $DISTRO $DISTRO_VER ;;
	OPENSUSE) SUSEPackageHint $DISTRO $DISTRO_VER ;;
	SLES) SUSEPackageHint $DISTRO $DISTRO_VER ;;
	*) break ;;
    esac
}

SetANSYSParameters()
{
    ARCH=$1
    ANSYS_ROOT_DIR=$2

    case "$ARCH" in
	I386)
	    ANS_ARCH=linia32;
	    LIB=/lib ;;
	X86_64)
	    if [ "$SUBARCH" = "OPTERON" ]; then
		ANS_ARCH=linop64;
	    else
		ANS_ARCH=linem64t;
	    fi
	    LIB=/lib64 ;;
	IA64)
	    ANS_ARCH=linia64;
	    LIB=/lib ;;
    esac

    # If ANSYS directory does not exist, try to determine it from executable.
    if [ ! -d "$ANSYS_ROOT_DIR" ]
    then
        PGFLIB=`$LDD $CFS_EXE | grep libpgf90.so | cut -d' ' -f3`

        if [ -f "$PGFLIB" ]
        then
            SEDSTR="s/\\/ansys\\/syslib\\/$ANS_ARCH\\/libpgf90.so//"
            ANSYS_ROOT_DIR=`echo $PGFLIB | sed -e $SEDSTR`
        fi
    fi



    LD_LIBRARY_PATH=$CFS_ROOT_DIR$LIB/$ARCH_STR:$CFS_ROOT_DIR$LIB/$ARCH_STR/$ANSYS_REV/$ANS_ARCH:$ANSYS_ROOT_DIR/ansys/syslib/$ANS_ARCH:$ANSYS_ROOT_DIR/ansys/customize/misc/$ANS_ARCH:$LD_LIBRARY_PATH
    export LD_LIBRARY_PATH
}

SetGIDParameters()
{
  dummy=1
}

# Set XML schema root path
if [ -r $CFS_ROOT_DIR/share/xml/CFS-Simulation/CFS.xsd ]; then
    CFS_SCHEMA_ROOT=$CFS_ROOT_DIR/share/xml
    export CFS_SCHEMA_ROOT
fi

# Get settings concerning the distribution type of CFS: GiD/ANSYS
#if [ "$CFS_DIST_TYPE" != "" ]
#then 
#    CFS_DIST_TYPE_TEMP=$CFS_DIST_TYPE 
#fi

if [ "$ANSYS_ROOT_DIR" != "" ]
then 
    ANSYS_ROOT_DIR_TEMP=$ANSYS_ROOT_DIR 
fi

# Check if a CFS config file exists in user's home directory.
if [ -e $HOME/.nacsrc ]
then 
    . $HOME/.nacsrc;
fi

# environment variables override variables from config file.
#if [ "$CFS_DIST_TYPE_TEMP" != "" ]
#then 
#    CFS_DIST_TYPE=$CFS_DIST_TYPE_TEMP
#    unset CFS_DIST_TYPE_TEMP
#fi

if [ "$ANSYS_ROOT_DIR_TEMP" != "" ]
then 
    ANSYS_ROOT_DIR=$ANSYS_ROOT_DIR_TEMP
    unset ANSYS_ROOT_DIR_TEMP
fi

CFS_DIST_TYPE="ANSYS"

if [ "$CFS_DIST_TYPE" = "" ]
then 
    echo "Cannot determine distribution type of CFS."
    echo "CFS_DIST_TYPE should be one of GID / ANSYS."
    exit 1
fi

if [ "$CFS_SCRIPT_DEBUG" = "1" ]
then
    echo "CFS_DIST_TYPE: $CFS_DIST_TYPE"
    echo "CFS_SCHEMA_ROOT: $CFS_SCHEMA_ROOT"
    echo "OS: $OS"
    echo "ARCH_STR: $ARCH_STR"
    echo "DISTRO: $DISTRO"
    echo "DISTRO_VER: $DISTRO_VER"
    echo "ARCH: $ARCH"
fi

# Set path to CFS executable
CFS_EXE=$CFS_ROOT_DIR/bin/$ARCH_STR/cfsbin

# Set paths to HDF5 executables
H5IMPORT_EXE=$CFS_ROOT_DIR/bin/$ARCH_STR/h5import
H5DUMP_EXE=$CFS_ROOT_DIR/bin/$ARCH_STR/h5dump
H5TOOL_EXE=$CFS_ROOT_DIR/bin/$ARCH_STR/h5tool

# Set parameters according to distribution type.
case "$CFS_DIST_TYPE" in
    ANSYS)
	SetANSYSParameters $ARCH $ANSYS_ROOT_DIR ;;
    GID)
	SetGIDParameters ;;
    *)
	echo "Unknown distribution type $CFS_DIST_TYPE.";
	echo "Should be one of GID / ANSYS.";
	exit 1;;
esac

# Check if we have the necessary libraries for the current arch.
if [ "$BINARY_TREE" = "0" ]; then
    if [ ! -d "$CFS_ROOT_DIR/$LIB/$ARCH_STR" ]
    then 
        echo "Cannot find CFS library path for architecture $ARCH_STR."
        exit 2
    fi
fi

if [ "$CFS_SCRIPT_DEBUG" = "1" ]
then
    echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
fi

# Check if we have the necessary executable for the current arch.
if [ ! -e $CFS_EXE ]
then 
    echo "Cannot find CFS++ executable for architecture $ARCH_STR."
    exit 3
fi

if [ "$CFS_SCRIPT_DEBUG" = "1" ]
then
    echo "Libraries:"
    $LDD $CFS_EXE
fi

# Check if some system libraries are missing.
CFS_EXE_LDD=`$LDD $CFS_EXE | grep "not found"`

if [ "$CFS_EXE_LDD" != "" ]
then 
    echo "Some dependencies on system libraries could not be resolved."
    echo "These were:"
    echo "$CFS_EXE_LDD";
    echo
    echo "CFS++ depends on the following packages on $DISTRO $DISTRO_VER:"
    GivePackageHint $DISTRO $DISTRO_VER
    echo "Please install the required packages."
    exit 4
fi

# Check if OMP_NUM_THREADS has been previously set and set it to 1 if not.
if [ "$OMP_NUM_THREADS" = "" ]
then
    OMP_NUM_THREADS=1
fi

if [ "$CFS_SCRIPT_DEBUG" = "1" ]
then
    echo "Setting OMP_NUM_THREADS=$OMP_NUM_THREADS"
fi

export OMP_NUM_THREADS

# Check if MKL_NUM_THREADS has been previously set and set it to
# OMP_NUM_THREADS if not.
if [ "$MKL_NUM_THREADS" = "" ]
then 
    MKL_NUM_THREADS=$OMP_NUM_THREADS
fi

if [ "$CFS_SCRIPT_DEBUG" = "1" ]
then
    echo "Setting MKL_NUM_THREADS=$MKL_NUM_THREADS"
fi

export MKL_NUM_THREADS

if [ $OMP_NUM_THREADS != $MKL_NUM_THREADS ]
then
    echo "Warning: OMP_NUM_THREADS($OMP_NUM_THREADS) != MKL_NUM_THREADS($MKL_NUM_THREADS)."
    echo "Warning: MKL_NUM_THREADS overrides OMP_NUM_THREADS for Intel MKL!"
fi

# Determine name of simulation for extending result HDF5 file.
last_was_param=0

for token in "$@"; do
#    echo ${token%[^-]*}
#    echo ${token%%[^-]*}
#    echo ${token#[^-]*}
#    echo ${token##[^-]*}

    param=`echo $token | sed 's/[^-]*$//g'`
    #param=${token%%[^-]*}

    if [ "$param" = "" ]; then
#        echo "some kind of name"
        if [ $last_was_param -eq 0 ]; then
            sim_name=$token
        fi
        last_was_param=0
    else
#        echo "some parameter"
        last_was_param=1
    fi

done

# Initialize st_size and st_mtime to defined values and get the before/after
# values of these variables to check if HDF5 file has changed.
st_size="0"
st_mtime="0"


hdf5_file_name="results_hdf5/${sim_name}.h5"
if [ ! "$sim_name" = "" ] && [ -r "$hdf5_file_name" ]; then
    if [ "$OS" = "Mac" ]; then
        eval "$(stat -s $hdf5_file_name)"
        st_size_before=$st_size
        st_mtime_before=$st_mtime
    else
        st_size_before=$(stat --format %s $hdf5_file_name)
        st_mtime_before=$(stat --format %Y $hdf5_file_name)
    fi
fi


# Execute the CFS executable with arguments from this script
if [ $# != 0 ]; then
    REST_ARGS=${@:2}
    case "$1" in
        "gdb")
            RunGdb $REST_ARGS
            ;;
        "memcheck")
            RunMemcheck $REST_ARGS
            ;;
        "callgrind")
            RunCallgrind $REST_ARGS
            ;;
         "massif")
            RunMassif $REST_ARGS
            ;;
         "gperf-cpu")
            RunGperfCpu $REST_ARGS
            ;;
         "gperf-heap")
            RunGperfHeap $REST_ARGS
            ;;
        *)
            PrintUsage
    esac
       
else
 PrintUsage
fi



