#!/bin/sh

# This is the start script for CFSDAT. It should be placed in
# CFS_DIST/bin under the name 'cfsdat'

# Source shell script for setting some common variables.
COMMON_SH=`dirname $0`/common.sh
if [ ! -x "$COMMON_SH" ]; then
  echo "Could not execute $COMMON_SH. Exiting..."
  exit 1
fi
. $COMMON_SH

$CFS_BIN_DIR/$ARCH_STR/cfsdatbin $@
