#!/bin/sh

# This is the start script for CFSTOOL. It should be placed in
# CFS_DIST/bin under the name 'cfstool'

# Source shell script for setting some common variables.
COMMON_SH=`dirname $0`/common.sh
if [ ! -x "$COMMON_SH" ]; then
  echo "Could not execute $COMMON_SH. Exiting..."
  exit 1
fi
. $COMMON_SH

$CFS_BIN_DIR/LINUX_X86_64/cfstoolbin $@
