#!/bin/sh

# Source shell script for setting some common variables.
. `dirname $0`/common.sh

if [ ! -d $CFS_ROOT_DIR ]; then
   echo "Cannot find CFS_ROOT_DIR dir '$CFS_ROOT_DIR'!"
   exit 1
fi

if [ ! -f $DISTRO_SH ]; then
    echo "Can not find '$DISTRO_SH'!"
    exit 1
fi

EXECUTABLE="$CFS_ROOT_DIR/bin/$ARCH_STR/cplreader"

if [ ! -f $EXECUTABLE ]; then
    echo "Can not find cplreader executable '$EXECUTABLE'!"
    exit 1
fi

errorExit ()
{
    echo "Can not run $EXEFORMAT cplreader on $PLATFORM platform!"
    exit 1
}

$EXECUTABLE "$@"
