
SET(CMAKE_SYSTEM_NAME Darwin)

SET(CMAKE_CROSSCOMPILING_TARGET Darwin)

SET(CMAKE_OSX_ARCHITECTURES x86_64
  CACHE STRING "Build architectures for OSX")

SET(OSX_DEVELOPER_ROOT "/opt/pckg/macosx_10.6_dev")

SET(CMAKE_TOOLCHAIN_PREFIX "i686-apple-darwin10")

SET(SDKROOT "/opt/pckg/macosx_10.6_dev/lib/apple/SDKs/MacOSX10.6.sdk")
SET(CMAKE_OSX_SYSROOT "${SDKROOT}"
  CACHE PATH "OSX system root")

SET(TOOL_BASE "${OSX_DEVELOPER_ROOT}/bin/${CMAKE_TOOLCHAIN_PREFIX}")

# which compilers to use for C, C++ and Fortran
SET(CMAKE_C_COMPILER "${TOOL_BASE}-gcc"
  CACHE FILEPATH "OSX gcc")
SET(CMAKE_CXX_COMPILER "${TOOL_BASE}-g++"
  CACHE FILEPATH "OSX g++")
SET(CMAKE_Fortran_COMPILER "${TOOL_BASE}-gfortran"
  CACHE FILEPATH "OSX gfortran")
SET(CMAKE_RANLIB "${TOOL_BASE}-ranlib"
  CACHE FILEPATH "OSX ranlib")
SET(CMAKE_AR "${TOOL_BASE}-ar"
  CACHE FILEPATH "OSX ar")
SET(CMAKE_LINKER "${TOOL_BASE}-ld"
  CACHE FILEPATH "OSX ld")
SET(CMAKE_STRIP "${TOOL_BASE}-strip"
  CACHE FILEPATH "OSX strip")
SET(CMAKE_INSTALL_NAME_TOOL "${TOOL_BASE}-install_name_tool"
  CACHE FILEPATH "OSX install_name_tool")

SET (CMAKE_FIND_ROOT_PATH "${SDKROOT}")
SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
