#
C_DIR=../../../..
#
src = algebraicsys.cc blocksys.cc baseparameter.cc basegraph.cc \
	basevector.cc fullvector.cc \
	basematrix.cc scalarmatrix.cc blockmatrix.cc fullmatrix.cc mixedmatrix.cc \
	baseprecond.cc idprecond.cc jacprecond.cc ssorprecond.cc mgprecond.cc \
	basehierarchy.cc basetransfer.cc basesmoother.cc basecoarse.cc \
	basesolver.cc rsolver.cc cgsolver.cc qmrsolver.cc densevector.cc clock.cc \
	scalarhierarchy.cc scalarsmoother.cc scalartransfer.cc standardcoarse.cc \
	basetopology.cc standardtopology.cc \
	blockhierarchy.cc blocktransfer.cc blocksmoother.cc densematrix.cc \
	fullhierarchy.cc fullsmoother.cc

#
lib = multigrid-piles

libpath = libsrc/AlgebraicSystem/PILES/multigrid
CFLAGS3 =
#
include ../../../makefile.inc

# DO NOT DELETE
