#include <iostream>

//#include <boost/program_options/cmdline.hpp>
//#include <boost/program_options/options_description.hpp>
//#include <boost/program_options/parsers.hpp>
//#include <boost/program_options/variables_map.hpp>
#include "DataInOut/ProgramOptions.hh"
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/filesystem/exception.hpp>

#if defined(WIN32)
  #include <shlobj.h>
#else
  #if defined(__APPLE__) // OSX
    #include <mach-o/dyld.h>
  #else // Linux
    #include <unistd.h>
  #endif
#endif

namespace fs = boost::filesystem;

#include "General/Exception.hh"
#include "DataInOut/Logging/LogConfigurator.hh"

#include "HelperFuncs.hh"
#include "ParamsInit.hh"

using namespace CoupledField;

namespace CFSTool
{

// cfstool program options macro

  namespace po = boost::program_options;

  void ParamsInit(int argc, char* argv[],
                  PtrParamNode& param,
                  shared_ptr<LogConfigurator>& logConf)
  {
    // Variable names generated by CMake
    std::string file1 = "";
    std::string file2 = "";
    std::string file3 = "";
    std::string file4 = "";
    std::string param_eps = "1.0e-6";
    std::string param_freeCoord = "";
    std::string param_mode = "scalardiff";
    std::string param_forceSegFault = "false";
    std::string param_limits = "false";
    std::string param_printLimits = "";
    std::string param_wvtArgs = "";
    std::string param_formatArgs = "";
    std::string param_logConfFile = "";
    PtrParamNode pNode;

    // Copy command line into vector
    std::vector<std::string> args;
    for ( int i = 1; i < argc; ++i )
    {
      args.push_back((std::string)argv[i]);
    }

    // Obtain paths of cfstool, the openCFS base and home directory and build
    // a list of possible locations of the cfstool config file.
    // cf. http://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe
    StdVector<fs::path> configFiles;
    char buf[4096];
#if defined(WIN32) // Windows
    GetModuleFileName(NULL, buf, sizeof(buf));
#else
#if defined(__APPLE__) // OSX
    uint32_t size = sizeof(buf);
    _NSGetExecutablePath(buf, &size);
#else // Linux
//    std::cout << "EMPTY BUFFER: "<< buf << std::endl;
    int success_ = readlink("/proc/self/exe", buf, sizeof(buf));
    
//    std::cout << success_ << std::endl;
//    std::cout << "BUFFER AFTER READLINK: " << buf << std::endl;
    
    // added char(0) to end of the read in path to ensure that the path ends correctly
    // reason: during the last build I sometimes encountered errors when starting cfstoolsbin;
    // errormsg: boost::filesystem::canonical: No such file or directory: "/home/lse21/staff/mnierla/5_FESPACE_magstrict/fespace_mnierla/cfstool`

    buf[success_] = char(0);
//    std::cout << "BUFFER AFTER MOD: " << buf << std::endl;    
#endif    
#endif

    fs::path cfstool = fs::canonical(buf);
    fs::path cfsbasedir;
    cfsbasedir = cfstool.parent_path().parent_path().parent_path();
    fs::path cfstoolconfig;
    fs::path home;

#if defined(WIN32)

    // Try to obtain paths to application data folders on Windows.
    TCHAR szPath[MAX_PATH];
    
    if(SUCCEEDED(SHGetFolderPath(NULL, 
                                 CSIDL_LOCAL_APPDATA|CSIDL_FLAG_DONT_VERIFY, 
                                 NULL, 
                                 0, 
                                 szPath))) 
    {
      home = szPath;
      cfstoolconfig = home;
      cfstoolconfig += "/cfs++.mdmt.tuwien.ac.at/cfstool.xml";
      configFiles.Push_back(cfstoolconfig);
    
      cfstoolconfig = home;
      cfstoolconfig += "/cfs++.mdmt.tuwien.ac.at/cfstool.json";
      configFiles.Push_back(cfstoolconfig);
    }

    if(SUCCEEDED(SHGetFolderPath(NULL, 
                                 CSIDL_APPDATA|CSIDL_FLAG_DONT_VERIFY, 
                                 NULL, 
                                 0, 
                                 szPath))) 
    {
      home = szPath;
      cfstoolconfig = home;
      cfstoolconfig += "/cfs++.mdmt.tuwien.ac.at/cfstool.xml";
      configFiles.Push_back(cfstoolconfig);
      
      cfstoolconfig = home;
      cfstoolconfig += "/cfs++.mdmt.tuwien.ac.at/cfstool.json";
      configFiles.Push_back(cfstoolconfig);
    }      

#else
    home = getenv("HOME");

    cfstoolconfig = home;
    cfstoolconfig += "/.config/cfs++.mdmt.tuwien.ac.at/cfstool.xml";
    configFiles.Push_back(cfstoolconfig);

    cfstoolconfig = home;
    cfstoolconfig += "/.config/cfs++.mdmt.tuwien.ac.at/cfstool.json";
    configFiles.Push_back(cfstoolconfig);

#endif
    cfstoolconfig = cfsbasedir;
    cfstoolconfig += "/share/xml/config/cfstool.xml";
    configFiles.Push_back(cfstoolconfig);

    cfstoolconfig = cfsbasedir;
    cfstoolconfig += "/share/xml/config/cfstool.json";
    configFiles.Push_back(cfstoolconfig);

    // Try to open cfstool config file.
    PtrParamNode configNode;
    for(UInt i=0; i<configFiles.GetSize(); i++) 
    {
      if( fs::exists(configFiles[i]) ) 
      {
        configNode = ParamNodeFromPropertyTree( configFiles[i].string(),
                                                "cfstoolConfig");

        // Add name of config file as attribute to root node.
        pNode = PtrParamNode(new ParamNode());
        pNode->SetName("configFile");
        pNode->SetValue(configFiles[i].string());
        pNode->SetType(ParamNode::ATTRIBUTE);
        configNode->AddChildNode(pNode);
        break;
      }
    }

    // If no config file could be found build up the parameter tree from hand.
    if(!configNode) 
    {
      configNode = PtrParamNode(new ParamNode());
      configNode->SetName("cfstoolConfig");
    }
    
    if(!configNode->Has("fileFormats"))
    {
      pNode = PtrParamNode(new ParamNode());
      pNode->SetName("fileFormats");
      configNode->AddChildNode(pNode);
    }
    if(!configNode->Get("fileFormats")->Has("input"))
    {
      pNode = PtrParamNode(new ParamNode());
      pNode->SetName("input");
      configNode->Get("fileFormats")->AddChildNode(pNode);
    }
    if(!configNode->Get("fileFormats")->Has("output"))
    {
      pNode = PtrParamNode(new ParamNode());
      pNode->SetName("output");
      configNode->Get("fileFormats")->AddChildNode(pNode);
    }
    
    // Put config tree into global param node.
    configNode.swap(param);
    // get children of param to set them
    ParamNodeList &leafs = param->GetChildren();

    // Put path to cfstool into global param node.
    pNode = PtrParamNode(new ParamNode());
    pNode->SetName("cfstool");
    pNode->SetValue(cfstool.string());
    param->AddChildNode(pNode);

    // Put openCFS base directory into global param node.
    pNode = PtrParamNode(new ParamNode());
    pNode->SetName("cfsBaseDir");
    pNode->SetValue(cfsbasedir.string());

    param->AddChildNode(pNode);
    
    pNode = PtrParamNode(new ParamNode());
    leafs[leafs.GetSize()-1]->SetName("domain");
    leafs[leafs.GetSize()-1]->SetValue("default");
    param->AddChildNode(pNode);

    try
    {
      // Declare the supported options. This is accomplished in cfstool_options.cmake
      po::options_description desc("Allowed options");
      desc.add_options()
        ("help,h", "Produce help message")
        ("version", "Print version information")
        ("eps,e", \
            po::value<std::string>(&param_eps)->default_value("1.0e-6"),
            "Sets the tolerance for check if two vector are the same.")
        ("freeCoord", \
            po::value<std::string>(&param_freeCoord)->default_value(""),
            "Arguments needed: 'comp start stop inc'.\n\
            E.g.  'x 0 1 0.1'")
        ("mode,m", \
            po::value<std::string>(&param_mode)->default_value("scalardiff"),
            "Type of mode: calcAverage | convert | scalardiff | L2diff | absL2diff | relL2diff | meshdiff | meshdiffnormed | wvt")
        ("forceSegFault", \
            po::value<std::string>(&param_forceSegFault)->implicit_value("true")->default_value("false"),
            "Force a segmentation fault at exceptions.")
        ("checkLimits", \
            po::value<std::string>(&param_limits)->implicit_value("false"),
            "Enable or disable node and element limits during diff operations. If the reference file has the extension .h5ref the limits get automatically enabled and must be explicitly disabled. For all other cases the default is false.")
        ("printLimits", \
            po::value<std::string>(&param_printLimits)->implicit_value("default"),
            "Print the hard-coded node and element limits. The value 'cmake' may be specified as optional argument.")
        ("wvtArgs", \
            po::value<std::string>(&param_wvtArgs)->default_value(""),
            "Arguments for WVT. Either in XML or JSON format. Can be given as file or string: 'file.[xml|json]' or e.g. '{\"rho_0\":1000,\"s1_name\":\"s_1\"}'.")
        ("formatArgs", \
            po::value<std::string>(&param_formatArgs)->default_value(""),
            "Arguments for conversion: unv_flavor=ideas|capa|gid.")
        ("logConfFile,l", \
            po::value<std::string>(&param_logConfFile)->default_value(""),
            "Name of configuration file for logging streams.")
        ;
      po::options_description cmdInvisible("Files needed");

      cmdInvisible.add_options()
        ("file1", po::value<std::string>(&file1)->default_value(""),
         "Input file or reference file for comparisons.");
      cmdInvisible.add_options()
        ("file2", po::value<std::string>(&file2)->default_value(""),
         "File under test for comparisons or output file.");
      cmdInvisible.add_options()
        ("file3", po::value<std::string>(&file3)->default_value(""),
         "Output or mean velocity file (WVT).");
      cmdInvisible.add_options()
        ("file4", po::value<std::string>(&file4)->default_value(""),
         "Output file (WVT).");

      po::variables_map vm;
      // Make positional parameters for input and output files.
      po::positional_options_description p;
      p.add( "file1",1).add("file2",1).add("file3",1).add("file4",1);

      // Combine visible and invisble options to commandLine options.
      po::options_description cmdLineOptions;
      cmdLineOptions.add(desc).add(cmdInvisible);
      po::store( po::command_line_parser( args ).
          options( cmdLineOptions ).positional( p ).run(),
          vm );

      po::store(po::parse_command_line(argc, argv, cmdLineOptions), vm);
      po::notify(vm);

      // If no argument is given, print help.
      if (vm.count("help") || argc == 1)
      {
        std::cout << "usage: cfstool --mode MODE [OPTIONS] FILE1 FILE2 [FILE3] [FILE4]" << std::endl << std::endl;
        std::cout << "Files can be given as positional arguments Examples:" << std::endl;
        std::cout << "\t$>cfstool -m scalardiff input.h5 referenceFile.h5" << std::endl;
        std::cout << "\t$>cfstool -m convert input.h5 output.post.bin" << std::endl;
        std::cout << "\t$>cfstool -m meshdiff input.h5 referenceFile.h5 output.h5" << std::endl;
        std::cout << "See below if you want to use parameters." << std::endl << std::endl;
        cmdLineOptions.print(std::cout);
        // Print out generall help.
        std::cout <<
          "Different modes are available:" << std::endl;
        std::cout <<
          "'calcAverage' [NOT YET IMPLEMENTED] calculates the average over a domain for" << std::endl <<
          "\teach time step separately. Optional is the argument --freeCoord." << std::endl;
        std::cout <<
          "\tCall: cfstool --calcAverage [--freeCoord 'comp start stop inc']" << std::endl;
        std::cout <<
          "'convert' converts files from one type to another. The following types of" << std::endl <<
          "\tconversions are supported:" << std::endl <<
          "\tinput:  .h5 (openCFS), .mesh (openCFS|NACS|CAPA), .msh (Gmsh), " << std::endl <<
          "\t        .unv[erg|ref] (Ideas|CAPA), .mphtxt (COMSOL mesh)," << std::endl <<
          "\t        .refelem (reference elements e.g. HEXA20.refelem)" << std::endl <<
          "\toutput: .h5 (openCFS++), .post.[res|bin] (GiD), .msh (Gmsh)," << std::endl <<
          "\t        .xmf (Xdmf2 format for openCFS HDF5), .unv[erg|ref] (Ideas|CAPA)," << std::endl <<
          "\t        .rst (ANSYS)" << std::endl;
        std::cout <<
          "\tCall: cfstool --mode convert input_file output_file" << std::endl;
        std::cout <<
          "'scalardiff' calculates the difference between two vectors and checks if \n\tit is smaller than a given tolerance. Option '--eps' is obligatory." << std::endl;
        std::cout <<
          "\tCall: cfstool --mode scalardiff reference_file file_under_test --eps 'eps'" << std::endl;
        std::cout <<
                  "'L2diff' calculates the L2 norm of the difference between two vectors, as well as the \n\t" <<
                  " normalized L2 (by L2 of the reference vector) and checks if either is smaller than a given tolerance.\n\t" <<
                  "Option '--eps' is obligatory." << std::endl;
        std::cout <<
                  "'relL2diff' calculates like 'L2diff' but only checks if the relative L2 norm < 'eps'." << std::endl;
        std::cout <<
                  "'absL2diff' calculates like 'L2diff' but only checks if the absolute L2 norm < 'eps'." << std::endl;
        std::cout <<
                  "\tCall: cfstool --mode scalardiff reference_file file_under_test --eps 'eps'" << std::endl;
        std::cout <<
          "'meshdiff' calculates the difference between two meshes." << std::endl;
        std::cout <<
          "\tCall: cfstool --mode meshdiff reference_file file_under_test out_file \n\ti.e. out = in_1 - in_2" << std::endl;
        std::cout <<
          "'meshdiffnormed' calculates the difference between two meshes normed \n\tto the max value of the second mesh:" << std::endl;
        std::cout <<
          "\tCall: cfstool --mode meshdiffnormed reference_file file_under_test out_file \n\ti.e. out = (in_1 - in_2) / max(in_2) "
          << std::endl;
        std::cout <<
          "'wvt' calculates the weight vector and phase difference from flow fields at" << std::endl <<
          "\tlateral mode, coriolis mode and the mean flow. The fields are" << std::endl <<
          "\tstored in three different files:" << std::endl;
        std::cout <<
          "\tCall: cfstool --mode wvt lateral_mode_file coriolis_mode_file \\\n"
          "\t              mean_velocity_file [output_file]\n"
          << std::endl;
        exit(0);
      }

      if (vm.count("version")) {
        ProgramOptions::PrintVersion(std::cout, false);
        exit(0);
      }

      if (vm.count("printLimits"))
      {
        pNode = PtrParamNode(new ParamNode());
        pNode->SetName("printLimits");
        pNode->SetValue(param_printLimits);
        param->AddChildNode(pNode);
      }
      if (vm.count("checkLimits"))
      {
        pNode = PtrParamNode(new ParamNode());
        pNode->SetName("checkLimits");
        pNode->SetValue(param_limits);
        param->AddChildNode(pNode);
      }

    } catch(std::exception &ex) {
      EXCEPTION("Error while parsing command line: " << ex.what());
    }

    // Settings generated by CMake
    pNode = PtrParamNode(new ParamNode());
    pNode->SetName("file1");
    pNode->SetValue(file1);
    param->AddChildNode(pNode);
    pNode = PtrParamNode(new ParamNode());
    pNode->SetName("file2");
    pNode->SetValue(file2);
    param->AddChildNode(pNode);
    pNode = PtrParamNode(new ParamNode());
    pNode->SetName("file3");
    pNode->SetValue(file3);
    param->AddChildNode(pNode);
    pNode = PtrParamNode(new ParamNode());
    pNode->SetName("file4");
    pNode->SetValue(file4);
    param->AddChildNode(pNode);
    pNode = PtrParamNode(new ParamNode());
    pNode->SetName("eps");
    pNode->SetValue(param_eps);
    param->AddChildNode(pNode);
    pNode = PtrParamNode(new ParamNode());
    pNode->SetName("freeCoord");
    pNode->SetValue(param_freeCoord);
    param->AddChildNode(pNode);
    pNode = PtrParamNode(new ParamNode());
    pNode->SetName("mode");
    pNode->SetValue(param_mode);
    param->AddChildNode(pNode);
    pNode = PtrParamNode(new ParamNode());
    pNode->SetName("forceSegFault");
    pNode->SetValue(param_forceSegFault);
    param->AddChildNode(pNode);

    // Parse inputs to formatArgs parameter and build parameter tree.
    pNode = ParamNodeFromPropertyTree( param_formatArgs, "formatArgs" );

    PtrParamNode inputNode, outputNode;
    
    if(pNode)
    {
      if(pNode->GetName() == "fileFormats") {
        std::cout << "fileFormats" << std::endl;
        
        if(pNode->Has("input")) { inputNode = pNode->Get("input"); }        
        if(pNode->Has("output")) { outputNode = pNode->Get("output"); }
      } else if(pNode->GetName() == "input") {
        inputNode = pNode;
      } else if(pNode->GetName() == "output") {
        outputNode = pNode;
      }
      
      // Merge  parameters provided  on command  line into  existing parameter
      // tree from config file.
      MergeParamNodes(inputNode, param->Get("fileFormats")->Get("input"));
      MergeParamNodes(outputNode, param->Get("fileFormats")->Get("output"));
    }

    // Parse inputs to wvtArgs parameter and build parameter tree.
    pNode = ParamNodeFromPropertyTree( param_wvtArgs, "wvtArgs" );

    PtrParamNode wvtNode = PtrParamNode(new ParamNode());
    wvtNode->SetName("wvt");
    param->AddChildNode(wvtNode);

    if(pNode) 
    {
      if(pNode->GetName() == "wvt") {
        MergeParamNodes(pNode, wvtNode);
      }
      else if(pNode->GetName() == "cfstoolConfig") {
        MergeParamNodes(pNode, param);
      }
      else
      {
        wvtNode->AddChildNode( pNode );
      }
    }

    // param->ToXML(std::cout);

    LogConfigurator::ParseLogConfFile(param_logConfFile);
  }
}
