#include <iostream>

#include <boost/program_options/cmdline.hpp>
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/filesystem/convenience.hpp>
#include <boost/filesystem/exception.hpp>

namespace fs = boost::filesystem;

#include "General/Exception.hh"
#include "DataInOut/ProgramOptions.hh"
#include "ParamsInit.hh"

namespace CoupledField
{

// cfstool program options macro

  namespace po = boost::program_options;

  void ParamsInit(int argc, char* argv[])
  {
    // Variable names generated by CMake
    std::string inputFile = "";
    std::string compareFile = "";
    std::string outputFile = "";
    std::string param_eps = "1.0e-6";
    std::string param_freeCoord = "";
    std::string param_mode = "scalardiff";
    std::string param_forceSegFault = "false";
    // copy command line into vector
    std::vector<std::string> args;
    //args.resize( argc-1 );
    for ( int i = 1; i < argc; ++i )
    {
      args.push_back((std::string)argv[i]);
    }

    try
    {
      // Declare the supported options. This is accomplished in cfstool_options.cmake
      po::options_description desc("Allowed options");
/*        ("files,f", \
*            po::value<std::string>(&param_files)->default_value(""), \
*            "choose reference_file compare_file and if required outfile")
*/            
      desc.add_options()
        ("help,h", "Produce help message")
        ("version", "Print version information")
        ("eps,e", \
            po::value<std::string>(&param_eps)->default_value("1.0e-6"),
            "Sets the tolerance for check if two vector are the same.")
        ("freeCoord", \
            po::value<std::string>(&param_freeCoord)->default_value(""),
            "Arguments needed: 'comp start stop inc'.\n\
            E.g.  'x 0 1 0.1'")
        ("mode,m", \
            po::value<std::string>(&param_mode)->default_value("scalardiff"),
            "Type of mode:  \n\
            calcAverage | convert | scalardiff |meshdiff | meshdiffnormed")
        ("forceSegFault", \
            po::value<std::string>(&param_forceSegFault)->default_value("false"),
            "force a segmentation fault at exceptions")
        ;
      po::options_description cmdInvisible("Files needed");

      cmdInvisible.add_options()
        ("inputFile,r", po::value<std::string>(&inputFile)->default_value(""),
         "choose input file");
      cmdInvisible.add_options()
        ("compareFile,c", po::value<std::string>(&compareFile)->default_value(""),
         "choose reference file, if required");
      cmdInvisible.add_options()
        ("outputFile,o", po::value<std::string>(&outputFile)->default_value(""),
         "choose output file, if required");

      po::variables_map vm;
      // make the input,compare and output files the positional parameters
      po::positional_options_description p;
      p.add( "inputFile", 1 ).add("compareFile",1).add("outputFile",1);

      // Combine visible and invisble options to commandLine options
      po::options_description cmdLineOptions;
      cmdLineOptions.add(desc).add(cmdInvisible);
      po::store( po::command_line_parser( args ).
          options( cmdLineOptions ).positional( p ).run(),
          vm );

      po::store(po::parse_command_line(argc, argv, cmdLineOptions), vm);
      po::notify(vm);

      // if no argument is given print help
      if (vm.count("help") || argc == 1)
      {
        std::cout << "usage: cfstool --mode MODE [OPTIONS] FILE1 FILE2 [FILE3]" << std::endl << std::endl;
        std::cout << "Files can be given as positional arguments Examples:" << std::endl;
        std::cout << "\t$>cfstool -m scalardiff input.h5 referenceFile.h5" << std::endl;
        std::cout << "\t$>cfstool -m convert input.h5 output.post.bin" << std::endl;
        std::cout << "\t$>cfstool -m meshdiff input.h5 referenceFile.h5 output.h5" << std::endl;
        std::cout << "See below if you want to use parameters." << std::endl << std::endl;
        cmdLineOptions.print(std::cout);
        // print out generall help
        std::cout <<
          "Different modes are available:" << std::endl;
        std::cout <<
          "'calcAverage' [NOT YET IMPLEMENTED] calculates the average over a domain for each time step \n\tseparately. Optional is the argument ---freeCoord." << std::endl;
        std::cout <<
          "\tCall: cfstool --calcAverage [--freeCoord 'comp start stop inc]" << std::endl;
        std::cout <<
          "'convert' converts files from one type to another. Following types \n conversions are supported: \n\tinput: .mesh .h5 .unv[erg|ref] .gmv \n\toutput: .h5, .post.res, .post.bin, .gmv .rst" << std::endl;
        std::cout <<
          "\tCall: cfstool --mode convert infile outfile" << std::endl;
        std::cout <<
          "'scalardiff' calculates the difference between two vectors and checks if \n\tit is smaller than a given tolerance. Option '--eps' is obligatory." << std::endl;
        std::cout <<
          "\tCall: cfstool --mode scalardiff reference_file compare_file --eps 'eps'" << std::endl;
        std::cout <<
          "'meshdiff' calculates the difference between two meshes." << std::endl;
        std::cout <<
          "\tCall: cfstool --mode meshdiff reference_file compare_file outfile \n\ti.e. out = in_1 -in_2" << std::endl;
        std::cout <<
          "'meshdiffnormed' calculates the difference between two meshes normed \n\tto the max value of the second mesh:" << std::endl;
        std::cout <<
          "\tCall: cfstool --mode meshdiffnormed reference_file compare_file outfile \n\ti.e. out = (in_1 - in_2) / max(in_2 "
          << std::endl;
        exit(0);
      }

      if (vm.count("version")) {
        ProgramOptions::GetVersionString(std::cout, false);
        exit(0);
      }
    } catch(std::exception &ex) {
      EXCEPTION("Error while parsing command line: " << ex.what());
    }

    // get children of param to set them
    ParamNodeList &leafs = param->GetChildren();
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("domain");
    leafs[leafs.GetSize()-1]->SetValue("default");
    // Settings generated by CMake
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("inputFile");
    leafs[leafs.GetSize()-1]->SetValue(inputFile);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("compareFile");
    leafs[leafs.GetSize()-1]->SetValue(compareFile);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("outputFile");
    leafs[leafs.GetSize()-1]->SetValue(outputFile);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("eps");
    leafs[leafs.GetSize()-1]->SetValue(param_eps);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("freeCoord");
    leafs[leafs.GetSize()-1]->SetValue(param_freeCoord);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("mode");
    leafs[leafs.GetSize()-1]->SetValue(param_mode);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("forceSegFault");
    leafs[leafs.GetSize()-1]->SetValue(param_forceSegFault);

  }
}
