#include <iostream>

#include <boost/program_options/cmdline.hpp>
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/program_options/variables_map.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/filesystem/convenience.hpp>
#include <boost/filesystem/exception.hpp>

namespace fs = boost::filesystem;

#include "General/Exception.hh"
#include "DataInOut/ProgramOptions.hh"
#include "ParamsInit.hh"

namespace CoupledField
{

// cfstool program options macro

  namespace po = boost::program_options;

  void ParamsInit(int argc, char* argv[], PtrParamNode param)
  {
    // Variable names generated by CMake
    std::string file1 = "";
    std::string file2 = "";
    std::string file3 = "";
    std::string file4 = "";
    std::string param_eps = "1.0e-6";
    std::string param_freeCoord = "";
    std::string param_mode = "scalardiff";
    std::string param_forceSegFault = "false";
    std::string param_limits = "false";
    std::string param_printLimits = "";

    // copy command line into vector
    std::vector<std::string> args;
    //args.resize( argc-1 );
    for ( int i = 1; i < argc; ++i )
    {
      args.push_back((std::string)argv[i]);
    }

    // get children of param to set them
    ParamNodeList &leafs = param->GetChildren();
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("domain");
    leafs[leafs.GetSize()-1]->SetValue("default");

    try
    {
      // Declare the supported options. This is accomplished in cfstool_options.cmake
      po::options_description desc("Allowed options");
/*        ("files,f", \
*            po::value<std::string>(&param_files)->default_value(""), \
*            "choose reference_file compare_file and if required outfile")
*/            
      desc.add_options()
        ("help,h", "Produce help message")
        ("version", "Print version information")
        ("eps,e", \
            po::value<std::string>(&param_eps)->default_value("1.0e-6"),
            "Sets the tolerance for check if two vector are the same.")
        ("freeCoord", \
            po::value<std::string>(&param_freeCoord)->default_value(""),
            "Arguments needed: 'comp start stop inc'.\n\
            E.g.  'x 0 1 0.1'")
        ("mode,m", \
            po::value<std::string>(&param_mode)->default_value("scalardiff"),
            "Type of mode: calcAverage | convert | scalardiff | meshdiff | meshdiffnormed | wvt")
        ("forceSegFault", \
            po::value<std::string>(&param_forceSegFault)->default_value("false"),
            "Force a segmentation fault at exceptions.")
        ("checkLimits", \
            po::value<std::string>(&param_limits)->implicit_value("false"),
            "Enable or disable node and element limits during diff operations. If the reference file has the extension .h5ref the limits get automatically enabled and must be explicitly disabled. For all other cases the default is false.")
        ("printLimits", \
            po::value<std::string>(&param_printLimits)->implicit_value("default"),
            "Print the hard-coded node and element limits. The value 'cmake' may be specified as optional argument.")
        ;
      po::options_description cmdInvisible("Files needed");

      cmdInvisible.add_options()
        ("file1", po::value<std::string>(&file1)->default_value(""),
         "Input file or reference file for comparisons.");
      cmdInvisible.add_options()
        ("file2", po::value<std::string>(&file2)->default_value(""),
         "File under test for comparisons or output file.");
      cmdInvisible.add_options()
        ("file3", po::value<std::string>(&file3)->default_value(""),
         "Output or mean velocity file (WVT).");
      cmdInvisible.add_options()
        ("file4", po::value<std::string>(&file4)->default_value(""),
         "Output file (WVT).");

      po::variables_map vm;
      // make the input,compare and output files the positional parameters
      po::positional_options_description p;
      p.add( "file1",1).add("file2",1).add("file3",1).add("file4",1);

      // Combine visible and invisble options to commandLine options
      po::options_description cmdLineOptions;
      cmdLineOptions.add(desc).add(cmdInvisible);
      po::store( po::command_line_parser( args ).
          options( cmdLineOptions ).positional( p ).run(),
          vm );

      po::store(po::parse_command_line(argc, argv, cmdLineOptions), vm);
      po::notify(vm);

      // if no argument is given print help
      if (vm.count("help") || argc == 1)
      {
        std::cout << "usage: cfstool --mode MODE [OPTIONS] FILE1 FILE2 [FILE3] [FILE4]" << std::endl << std::endl;
        std::cout << "Files can be given as positional arguments Examples:" << std::endl;
        std::cout << "\t$>cfstool -m scalardiff input.h5 referenceFile.h5" << std::endl;
        std::cout << "\t$>cfstool -m convert input.h5 output.post.bin" << std::endl;
        std::cout << "\t$>cfstool -m meshdiff input.h5 referenceFile.h5 output.h5" << std::endl;
        std::cout << "See below if you want to use parameters." << std::endl << std::endl;
        cmdLineOptions.print(std::cout);
        // print out generall help
        std::cout <<
          "Different modes are available:" << std::endl;
        std::cout <<
          "'calcAverage' [NOT YET IMPLEMENTED] calculates the average over a domain for" << std::endl <<
          "\teach time step separately. Optional is the argument --freeCoord." << std::endl;
        std::cout <<
          "\tCall: cfstool --calcAverage [--freeCoord 'comp start stop inc']" << std::endl;
        std::cout <<
          "'convert' converts files from one type to another. The following types of" << std::endl <<
          "\tconversions are supported:" << std::endl <<
          "\tinput:  .h5 (CFS++), .mesh (CFS++|NACS|CAPA), .msh (Gmsh), .gmv (GMV)," << std::endl <<
          "\t        .unv[erg|ref] (Ideas|CAPA), .mphtxt (COMSOL mesh)," << std::endl <<
          "\t        .refelem (reference elements e.g. HEXA20.refelem)" << std::endl <<
          "\toutput: .h5 (CFS++), .post.[res|bin] (GiD), .gmv (GMV), .msh (Gmsh)," << std::endl <<
          "\t        .xmf (Xdmf2 format for CFS++ HDF5), .unv[erg|ref] (Ideas|CAPA)," << std::endl <<
          "\t        .rst (ANSYS)" << std::endl;
        std::cout <<
          "\tCall: cfstool --mode convert input_file output_file" << std::endl;
        std::cout <<
          "'scalardiff' calculates the difference between two vectors and checks if \n\tit is smaller than a given tolerance. Option '--eps' is obligatory." << std::endl;
        std::cout <<
          "\tCall: cfstool --mode scalardiff reference_file file_under_test --eps 'eps'" << std::endl;
        std::cout <<
          "'meshdiff' calculates the difference between two meshes." << std::endl;
        std::cout <<
          "\tCall: cfstool --mode meshdiff reference_file file_under_test out_file \n\ti.e. out = in_1 - in_2" << std::endl;
        std::cout <<
          "'meshdiffnormed' calculates the difference between two meshes normed \n\tto the max value of the second mesh:" << std::endl;
        std::cout <<
          "\tCall: cfstool --mode meshdiffnormed reference_file file_under_test out_file \n\ti.e. out = (in_1 - in_2) / max(in_2) "
          << std::endl;
        std::cout <<
          "'wvt' calculates the weight vector and phase difference from flow fields at" << std::endl <<
          "\tlateral mode, coriolis mode and the mean flow. The fields are" << std::endl <<
          "\tstored in three different files:" << std::endl;
        std::cout <<
          "\tCall: cfstool --mode wvt lateral_mode_file coriolis_mode_file \\\n"
          "\t              mean_velocity_file output_file\n"
          << std::endl;
        exit(0);
      }

      if (vm.count("version")) {
        ProgramOptions::GetVersionString(std::cout, false);
        exit(0);
      }

      if (vm.count("printLimits"))
      {
        leafs.Push_back(PtrParamNode(new ParamNode()));
        leafs[leafs.GetSize()-1]->SetName("printLimits");
        leafs[leafs.GetSize()-1]->SetValue(param_printLimits);
      }
      if (vm.count("checkLimits"))
      {
        leafs.Push_back(PtrParamNode(new ParamNode()));
        leafs[leafs.GetSize()-1]->SetName("checkLimits");
        leafs[leafs.GetSize()-1]->SetValue(param_limits);
      }

    } catch(std::exception &ex) {
      EXCEPTION("Error while parsing command line: " << ex.what());
    }

    // Settings generated by CMake
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("file1");
    leafs[leafs.GetSize()-1]->SetValue(file1);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("file2");
    leafs[leafs.GetSize()-1]->SetValue(file2);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("file3");
    leafs[leafs.GetSize()-1]->SetValue(file3);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("file4");
    leafs[leafs.GetSize()-1]->SetValue(file4);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("eps");
    leafs[leafs.GetSize()-1]->SetValue(param_eps);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("freeCoord");
    leafs[leafs.GetSize()-1]->SetValue(param_freeCoord);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("mode");
    leafs[leafs.GetSize()-1]->SetValue(param_mode);
    leafs.Push_back(PtrParamNode(new ParamNode()));
    leafs[leafs.GetSize()-1]->SetName("forceSegFault");
    leafs[leafs.GetSize()-1]->SetValue(param_forceSegFault);
  }
}
