#
C_DIR= ../..
include ../../main/Makefile.option
#
src =   basePDE.cc\
	elecPDE.cc\
	mechPDE.cc\
	acousticPDE.cc\
	newmark.cc\
	timestepping.cc\
	BaseEQN.cc\
	ScalarNodeEQN.cc\
	smoothPDE.cc\
	magneticPDE.cc\
	trapezoidal.cc\
	acouFlowNoise.cc\
	piezoPDE.cc
#
lib = pde
CFLAGS3 =
#
include ../makefile.inc

# DO NOT DELETE


