#
C_DIR= ../..
include ../../main/Makefile.option
#
src =   basePDE.cc\
	StdPDE.cc\
	SinglePDE.cc\
	elecPDE.cc\
	mechPDE.cc\
	acousticPDE.cc\
	newmark.cc\
	timestepping.cc\
	smoothPDE.cc\
	magneticPDE.cc\
	trapezoidal.cc\
	pdememento.cc\
	acouFlowNoise.cc\
	newmarkFracDamp.cc \
	newmarkFracDampMech.cc \
	mpcciPDE.cc \
	nrbcPDE.cc \
	heatCondPDE.cc \
	acousticXYZPDE.cc \
	stokesFluidPDE.cc \
	eqnMap.cc \
	bubblePDE.cc
#
CFLAGS3 =
#
include ../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE


