#
C_DIR= ../..
include ../../main/Makefile.option
#
src =   basePDE.cc\
	StdPDE.cc\
	SinglePDE.cc\
	elecPDE.cc\
	mechPDE.cc\
	acousticPDE.cc\
	newmark.cc\
	timestepping.cc\
	baseEQN.cc\
	nodeEQN.cc\
	scalarnodeEQN.cc\
	blocknodeEQN.cc\
	scalarblockEQN.cc\
	smoothPDE.cc\
	magneticPDE.cc\
	trapezoidal.cc\
	pdememento.cc\
	acouFlowNoise.cc\
	piezoPDE.cc \
	newmarkFracDamp.cc \
	newmarkFracDampMech.cc \
	mpcciPDE.cc \
	heatCondPDE.cc

#
lib = pde
CFLAGS3 =
#
include ../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE


