#
C_DIR=../..
#
src = myclock.cc storesol.cc tools.cc vector.cc tracing.cc Coil.cc ApproxData.cc SmoothSpline.cc
#
lib = utils
libpath = libsrc/Utils
CFLAGS3 =
#
include ../makefile.inc

# DO NOT DELETE this line


