#
C_DIR= ../..
include ../../main/Makefile.option
#
src =   myclock.cc nodestoresol.cc elemstoresol.cc tools.cc vector.cc\
	tracing.cc Coil.cc ApproxData.cc SmoothSpline.cc\
	mathfunctions.cc hysteresis.cc preisach.cc LinInterpolate.cc jiles.cc
#
lib = utils
libpath = libsrc/Utils
CFLAGS3 =
#
include ../makefile.inc
-include $(DEPEND_FILE)
# DO NOT DELETE this line



