#
# Makefile for discretization
C_DIR=../../..
#
src =  rectangle.cc quad1.cc quad2.cc getriangle.cc triangle1.cc triangle2.cc rectanglefe.cc quad1fe.cc \
       trianglefe.cc triangle1fe.cc
#
lib = elements2d
libpath = libsrc/Elements/2D
CFLAGS3 =
#
include ../../makefile.inc

# DO NOT DELETE


