#
# Makefile for discretization
C_DIR=../../..
#
src =  rectanglefe.cc quad1fe.cc quad2fe.cc trianglefe.cc triangle1fe.cc
#
lib = elements2d
libpath = libsrc/Elements/2D
CFLAGS3 =
#
include ../../makefile.inc

# DO NOT DELETE


