#
# Makefile for discretization
C_DIR=../../..
#
src =  linefe.cc line1fe.cc line2fe.cc
#
lib = elements1d
libpath = libsrc/Elements/2D
CFLAGS3 =
#
include ../../makefile.inc
-include $(Dependencies)
# DO NOT DELETE


