import numpy as np

import cfs # module generated by openCFS

# number of design variables
n = 0
# number of constraints
m = 0
max_iter = 0
options = 0

# optional for cfs. 
# raise an exception if there are issues 
def setup():
  print('ocm.py: setup() called')

  cfs.opt_register_log_property('lambda',"-1")
  cfs.opt_register_log_property('lambda_iters',"-1")


# mandatory init with 5 options
# raise an exception if there are issues
def init(n_des, n_constr, n_iter, sim_name, ops):
  assert n_des > 0
  assert n_iter > 0
  assert n_constr == 1 # necessary for ocm
  
  global n, m, max_iter, options
  n = n_des
  m = n_constr
  max_iter = n_iter
  options = ops
  
  print('ocm.py: init() called n=',n, 'm=',m, 'max_iter=',max_iter, 'name=', sim_name, 'options=', options)
  
  
  
# expected and called by cfs
# @return an integer with 0 for ok
def solve():
  global n, m, max_iter, options
  
  # design
  x = np.zeros(n)
  cfs.initialdesign(x)
  
  # volume constraint gradient only required once
  dv = np.zeros(n) 
  cfs.evalgradconstrs(x, dv)
  
  # for initial design
  dc = np.zeros(n)
  cfs.evalgradobj(x,dc) 
  cfs.commitIteration()
  
  # bounds
  xl = np.zeros(n)
  xu = np.zeros(n)
  gl = np.zeros(m)
  gu = np.zeros(m)
  cfs.bounds(xl,xu,gl,gu)
  print('bounds gl',gl, 'gu',gu)
  assert gl[0] <= gu[0]
  bound = gu[0]
  assert bound > 0

  move = float(options["move"])
  damp = float(options["damp"])
  
  print('magic numbers: move_limit',move,'damping',damp)
  
  iter = 0
  while iter < max_iter and not cfs.dostop():
    x, lmbd = oc(x, bound, dc, dv, xl, xu, move, damp)
    cfs.evalgradobj(x,dc)
    cfs.evalgradconstrs(x, dv)    
    cfs.commitIteration()
    #print('ocm.py: next iter', np.average(x), lmbd)
    iter += 1    
  
  return 0

# calc volume
def calc_g(x):
  g = np.zeros(1)
  cfs.evalconstrs(x, g)
  return g[0]

# calc the next oc-step.  
# @param x the 1D numpy design array
# @param bound constraint value (volume constraint)
# @param dc objective function gradient (compliance gradient)
# @param dv constraint gradient (volume gradient). Assumed to be constant over iterations, homogeneous on regular mesh
# @return new design and lmbd
def oc(x,bound,dc,dv, xl, xu, move, damp):
  l1=0
  l2=1e5

  xnew = x.copy()

  cnt = 0
  while (l2-l1)/(l1+l2)>1e-5:
    cnt += 1
    lmbd=0.5*(l2+l1)
    
    Be = -dc/(lmbd*dv)
    
    # original updated value
    tmp = np.power(Be,damp) * x  
 
    # bound from below, must not be blow lower bound and not too much smaller than org x
    lower = np.maximum(xl, x-move)
    
    # bound from above, must not be more than xu and must not be more than org plus move
    upper = np.minimum(xu, x+move)
    
    # candidate respecting bounds
    xnew = np.maximum(lower,np.minimum(upper,tmp))
    
    cmp = calc_g(xnew) - bound
     
    #print(lmbd, calc_g(xnew), cmp, np.average(xnew)) 
    if cmp > 0:
      l1=lmbd
    else:
      l2=lmbd
      
  cfs.opt_set_log_property("lambda", str(lmbd))
  cfs.opt_set_log_property("lambda_iters", str(cnt))
      
  return xnew, lmbd
