#-------------------------------------------------------------------------------
# Set prefix path and path to Boost sources according to ExternalProject.cmake 
#-------------------------------------------------------------------------------
set(boost_prefix  "${CMAKE_CURRENT_BINARY_DIR}/cfsdeps/boost")
set(boost_source  "${boost_prefix}/src/boost")

#-------------------------------------------------------------------------------
# Set arguments to Boost CMake according to current configuration 
#-------------------------------------------------------------------------------
SET(CMAKE_ARGS
  "-DCMAKE_COLOR_MAKEFILE:BOOL=OFF"
  "-DINSTALL_VERSIONED:BOOL=OFF"
  "-DCMAKE_INSTALL_PREFIX:PATH=${CFS_BINARY_DIR}"
  "-DZLIB_INCLUDE_DIR:PATH=${CFS_BINARY_DIR}/include"
  "-DZLIB_LIBRARY:FILEPATH=${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}/libz${CMAKE_SHARED_LIBRARY_SUFFIX}"
  "-DBZIP2_INCLUDE_DIR:PATH=${CFS_BINARY_DIR}/include"
  "-DBZIP2_LIBRARIES:FILEPATH=${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}/libbz2${CMAKE_SHARED_LIBRARY_SUFFIX}"
  "-DBOOST_EXPORTS_INSTALL_DIR:STRING=${LIB_SUFFIX}/${CFS_ARCH_STR}"
  "-DBOOST_LIB_INSTALL_DIR:STRING=${LIB_SUFFIX}/${CFS_ARCH_STR}"
  "-DWITH_MPI:BOOL=NO"
)

IF(CFS_ARCH STREQUAL "X86_64")
  LIST(APPEND CMAKE_ARGS "-DLIB_SUFFIX:STRING=64")
ENDIF(CFS_ARCH STREQUAL "X86_64")

#-------------------------------------------------------------------------------
# Set list of Boost libraries to be built 
#-------------------------------------------------------------------------------
SET(BOOST_BUILD_LIBS
  "date_time"
  "filesystem"
  "iostreams"
  "program_options"
  "python"
  "regex"
  "serialization"
  "signals"
  "system"
  "thread"
)

SET(BPROJ "-DBUILD_PROJECTS:STRING=")
foreach(BLIB IN LISTS BOOST_BUILD_LIBS)
#  MESSAGE("BLIB: ${BLIB}\n${BPROJ}")
    SET(BPROJ "${BPROJ},${BLIB}")
endforeach(BLIB)

LIST(APPEND CMAKE_ARGS
  ${BPROJ})

#MESSAGE("CMAKE_ARGS ${CMAKE_ARGS}")

#-------------------------------------------------------------------------------
# The Boost external project
#-------------------------------------------------------------------------------
ExternalProject_Add(boost
  DEPENDS zlib-shared zlib-static bzip2-shared bzip2-static
  LIST_SEPARATOR ,
  PREFIX "${boost_prefix}"
  DOWNLOAD_DIR ${CFS_DEPS_CACHE_DIR}/sources/boost
  URL ${BOOST_URL}/${BOOST_GZ}
  URL_MD5 ${BOOST_MD5}
  CMAKE_ARGS
    ${CMAKE_ARGS}
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
    -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
  )

#-------------------------------------------------------------------------------
# Set names of patch file and template file.
#-------------------------------------------------------------------------------
SET(PFN_TEMPL "${CFS_SOURCE_DIR}/cfsdeps/boost/boost-patch.cmake.in")
SET(PFN "${boost_prefix}/boost-patch.cmake")
CONFIGURE_FILE("${PFN_TEMPL}" "${PFN}" @ONLY) 


#-------------------------------------------------------------------------------
# We do not use the PATCH_COMMAND  of ExternalProject_Add since we do not only
# want to apply the patch script  during configuration time but also if it has
# changed.  Therefore,   we  need  a   dependency  on  the   configured  patch
# script. This can be achieved by  adding an additional build step between the
# download and configure steps.
#
# NOTE: The  patch script should  be designed  in such a  way, that it  can be
# applied to  an already patched  source tree. This  is due to the  fact, that
# ExternalProject_Add only extracts the source if the MD5 sum has has changed.
#-------------------------------------------------------------------------------
ExternalProject_Add_Step(boost custom_patch
   COMMAND ${CMAKE_COMMAND} -P "${PFN}"
   DEPENDEES download
   DEPENDERS configure
   DEPENDS "${PFN}"
   WORKING_DIRECTORY ${boost_source}
)

# These variables are used to find Boost by other projects
SET(Boost_INCLUDE_DIR "${CFS_BINARY_DIR}/include" CACHE PATH "Boost include dir.")
SET(Boost_LIBRARY_DIR "${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}" CACHE PATH "Boost library dir.")

MARK_AS_ADVANCED(Boost_INCLUDE_DIR)
MARK_AS_ADVANCED(Boost_LIBRARY_DIR)

IF(UNIX)
  SET(BOOST_LIB_SUFFIX_DEBUG "-mt-d.a")
  SET(BOOST_LIB_SUFFIX_RELEASE "-mt.a")
  
  SET(BOOST_LIB_PREFIX "${Boost_LIBRARY_DIR}/lib")
ENDIF(UNIX)

IF(WIN32)
  SET(BOOST_LIB_PREFIX "${Boost_LIBRARY_DIR}/lib")
ENDIF(WIN32)

#-----------------------------------------------------------------------------
# Set Boost Debug library paths in cache.
#-----------------------------------------------------------------------------
SET(BOOST_DATE_TIME_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_date_time${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_DATE_TIME_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_DATE_TIME_LIB_DEBUG)
SET(BOOST_FILESYSTEM_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_filesystem${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_FILESYSTEM_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_FILESYSTEM_LIB_DEBUG)
SET(BOOST_IOSTREAMS_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_iostreams${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_IOSTREAMS_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_IOSTREAMS_LIB_DEBUG)
SET(BOOST_PRG_EXEC_MONITOR_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_prg_exec_monitor${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_PRG_EXEC_MONITOR_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_PRG_EXEC_MONITOR_LIB_DEBUG)
SET(BOOST_PROGRAM_OPTIONS_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_program_options${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_PROGRAM_OPTIONS_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_PROGRAM_OPTIONS_LIB_DEBUG)
SET(BOOST_PYTHON_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_python${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_PYTHON_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_PYTHON_LIB_DEBUG)
SET(BOOST_REGEX_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_regex${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_REGEX_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_REGEX_LIB_DEBUG)
SET(BOOST_SERIALIZATION_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_serialization${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SERIALIZATION_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_LIB_DEBUG)
SET(BOOST_SERIALIZATION_HDF5_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_serialization_hdf5${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SERIALIZATION_HDF5_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_HDF5_LIB_DEBUG)
SET(BOOST_SIGNALS_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_signals${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SIGNALS_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SIGNALS_LIB_DEBUG)
SET(BOOST_SYSTEM_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_system${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SYSTEM_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SYSTEM_LIB_DEBUG)
SET(BOOST_TEST_EXEC_MONITOR_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_test_exec_monitor${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_TEST_EXEC_MONITOR_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_TEST_EXEC_MONITOR_LIB_DEBUG)
SET(BOOST_THREAD-MT_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_thread-mt${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_THREAD-MT_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_THREAD-MT_LIB_DEBUG)
SET(BOOST_THREAD_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_thread${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_THREAD_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_THREAD_LIB_DEBUG)
SET(BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_unit_test_framework${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG)
SET(BOOST_WSERIALIZATION_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_wserialization${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_WSERIALIZATION_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_WSERIALIZATION_LIB_DEBUG)


#-----------------------------------------------------------------------------
# Set Boost Release library paths in cache.
#-----------------------------------------------------------------------------
SET(BOOST_DATE_TIME_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_date_time${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_DATE_TIME_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_DATE_TIME_LIB_RELEASE)
SET(BOOST_FILESYSTEM_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_filesystem${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_FILESYSTEM_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_FILESYSTEM_LIB_RELEASE)
SET(BOOST_IOSTREAMS_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_iostreams${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_IOSTREAMS_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_IOSTREAMS_LIB_RELEASE)
SET(BOOST_PRG_EXEC_MONITOR_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_prg_exec_monitor${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_PRG_EXEC_MONITOR_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_PRG_EXEC_MONITOR_LIB_RELEASE)
SET(BOOST_PROGRAM_OPTIONS_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_program_options${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_PROGRAM_OPTIONS_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_PROGRAM_OPTIONS_LIB_RELEASE)
SET(BOOST_PYTHON_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_python${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_PYTHON_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_PYTHON_LIB_RELEASE)
SET(BOOST_REGEX_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_regex${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_REGEX_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_REGEX_LIB_RELEASE)
SET(BOOST_SERIALIZATION_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_serialization${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SERIALIZATION_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_LIB_RELEASE)
SET(BOOST_SERIALIZATION_HDF5_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_serialization_hdf5${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SERIALIZATION_HDF5_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_HDF5_LIB_RELEASE)
SET(BOOST_SIGNALS_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_signals${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SIGNALS_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SIGNALS_LIB_RELEASE)
SET(BOOST_SYSTEM_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_system${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SYSTEM_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SYSTEM_LIB_RELEASE)
SET(BOOST_TEST_EXEC_MONITOR_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_test_exec_monitor${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_TEST_EXEC_MONITOR_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_TEST_EXEC_MONITOR_LIB_RELEASE)
SET(BOOST_THREAD-MT_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_thread-mt${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_THREAD-MT_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_THREAD-MT_LIB_RELEASE)
SET(BOOST_THREAD_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_thread${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_THREAD_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_THREAD_LIB_RELEASE)
SET(BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_unit_test_framework${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE)
SET(BOOST_WSERIALIZATION_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_wserialization${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_WSERIALIZATION_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_WSERIALIZATION_LIB_RELEASE)


#-----------------------------------------------------------------------------
# Set Boost library paths according to current config.
#-----------------------------------------------------------------------------
IF(DEBUG)
  SET(BOOST_DATE_TIME_LIB "${BOOST_DATE_TIME_LIB_DEBUG}")
  SET(BOOST_FILESYSTEM_LIB "${BOOST_FILESYSTEM_LIB_DEBUG}")
  SET(BOOST_IOSTREAMS_LIB "${BOOST_IOSTREAMS_LIB_DEBUG}")
  SET(BOOST_PRG_EXEC_MONITOR_LIB "${BOOST_PRG_EXEC_MONITOR_LIB_DEBUG}")
  SET(BOOST_PROGRAM_OPTIONS_LIB "${BOOST_PROGRAM_OPTIONS_LIB_DEBUG}")
  SET(BOOST_PYTHON_LIB "${BOOST_PYTHON_LIB_DEBUG}")
  SET(BOOST_REGEX_LIB "${BOOST_REGEX_LIB_DEBUG}")
  SET(BOOST_SERIALIZATION_LIB "${BOOST_SERIALIZATION_LIB_DEBUG}")
  SET(BOOST_SERIALIZATION_HDF5_LIB "${BOOST_SERIALIZATION_HDF5_LIB_DEBUG}")
  SET(BOOST_SIGNALS_LIB "${BOOST_SIGNALS_LIB_DEBUG}")
  SET(BOOST_SYSTEM_LIB "${BOOST_SYSTEM_LIB_DEBUG}")
  SET(BOOST_TEST_EXEC_MONITOR_LIB "${BOOST_TEST_EXEC_MONITOR_LIB_DEBUG}")
  SET(BOOST_THREAD-MT_LIB "${BOOST_THREAD-MT_LIB_DEBUG}")
  SET(BOOST_THREAD_LIB "${BOOST_THREAD_LIB_DEBUG}")
  SET(BOOST_UNIT_TEST_FRAMEWORK_LIB "${BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG}")
  SET(BOOST_WSERIALIZATION_LIB "${BOOST_WSERIALIZATION_LIB_DEBUG}")
ELSE(DEBUG)
  SET(BOOST_DATE_TIME_LIB "${BOOST_DATE_TIME_LIB_RELEASE}")
  SET(BOOST_FILESYSTEM_LIB "${BOOST_FILESYSTEM_LIB_RELEASE}")
  SET(BOOST_IOSTREAMS_LIB "${BOOST_IOSTREAMS_LIB_RELEASE}")
  SET(BOOST_PRG_EXEC_MONITOR_LIB "${BOOST_PRG_EXEC_MONITOR_LIB_RELEASE}")
  SET(BOOST_PROGRAM_OPTIONS_LIB "${BOOST_PROGRAM_OPTIONS_LIB_RELEASE}")
  SET(BOOST_PYTHON_LIB "${BOOST_PYTHON_LIB_RELEASE}")
  SET(BOOST_REGEX_LIB "${BOOST_REGEX_LIB_RELEASE}")
  SET(BOOST_SERIALIZATION_LIB "${BOOST_SERIALIZATION_LIB_RELEASE}")
  SET(BOOST_SERIALIZATION_HDF5_LIB "${BOOST_SERIALIZATION_HDF5_LIB_RELEASE}")
  SET(BOOST_SIGNALS_LIB "${BOOST_SIGNALS_LIB_RELEASE}")
  SET(BOOST_SYSTEM_LIB "${BOOST_SYSTEM_LIB_RELEASE}")
  SET(BOOST_TEST_EXEC_MONITOR_LIB "${BOOST_TEST_EXEC_MONITOR_LIB_RELEASE}")
  SET(BOOST_THREAD-MT_LIB "${BOOST_THREAD-MT_LIB_RELEASE}")
  SET(BOOST_THREAD_LIB "${BOOST_THREAD_LIB_RELEASE}")
  SET(BOOST_UNIT_TEST_FRAMEWORK_LIB "${BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE}")
  SET(BOOST_WSERIALIZATION_LIB "${BOOST_WSERIALIZATION_LIB_RELEASE}")
ENDIF(DEBUG)

SET(Boost_FOUND 1)
