#-------------------------------------------------------------------------------
# Boost provides free peer-reviewed portable C++ source libraries.
# Needed by Botan and CGAL
#
# Project Homepage
# http://www.boost.org
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Set prefix path and path to Boost sources according to ExternalProject.cmake 
#-------------------------------------------------------------------------------
set(boost_prefix  "${CMAKE_CURRENT_BINARY_DIR}/cfsdeps/boost")
set(boost_source  "${boost_prefix}/src/boost")

#-------------------------------------------------------------------------------
# Set arguments to Boost CMake according to current configuration 
#-------------------------------------------------------------------------------
SET(CMAKE_ARGS
  -DCMAKE_COLOR_MAKEFILE:BOOL=${CMAKE_COLOR_MAKEFILE}
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DCMAKE_MAKE_PROGRAM:FILEPATH=${CMAKE_MAKE_PROGRAM}
  -DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}
  -DCMAKE_CXX_FLAGS:STRING=${CFSDEPS_CXX_FLAGS}
  -DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
  -DCMAKE_C_FLAGS:STRING=${CFSDEPS_C_FLAGS}
  -DINSTALL_VERSIONED:BOOL=OFF
  -DCMAKE_INSTALL_PREFIX:PATH=${CFS_BINARY_DIR}
  -DZLIB_INCLUDE_DIR:PATH=${ZLIB_INCLUDE_DIR}
  -DBZIP2_INCLUDE_DIR:PATH=${BZIP2_INCLUDE_DIR}
  -DBOOST_EXPORTS_INSTALL_DIR:STRING=${LIB_SUFFIX}/${CFS_ARCH_STR}
  -DBOOST_LIB_INSTALL_DIR:STRING=${LIB_SUFFIX}/${CFS_ARCH_STR}
  -DPYTHON_INCLUDE_PATH:PATH=${PYTHON_INCLUDE_PATH} 
  -DPYTHON_EXECUTABLE:FILEPATH=${PYTHON_EXECUTABLE} 
  -DPYTHON_LIBRARIES:FILEPATH=${PYTHON_LIBRARIES}
  -DWITH_ICU:BOOL=NO
  -DWITH_MPI:BOOL=NO
)

# Let's deactivate dynamic libraries for Boost, since the CMake build of Boost
# has obviously  some problems when building  the thread lib and  we only need
# static libs anyway.
 
if(MSVC)
  LIST(APPEND CMAKE_ARGS
    -DENABLE_SHARED:BOOL=OFF
    -DENABLE_STATIC:BOOL=ON
    )
else()
  LIST(APPEND CMAKE_ARGS
    -DENABLE_SHARED:BOOL=ON
    -DENABLE_STATIC:BOOL=ON
    )
endif()

IF(CMAKE_TOOLCHAIN_FILE)
  LIST(APPEND CMAKE_ARGS
    -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${CMAKE_TOOLCHAIN_FILE}
  )
ENDIF()

IF(MINGW)
  LIST(APPEND CMAKE_ARGS
    -DZLIB_LIBRARY:FILEPATH=${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}/${CMAKE_IMPORT_LIBRARY_PREFIX}zlib${CMAKE_IMPORT_LIBRARY_SUFFIX}
    -DBZIP2_LIBRARIES:FILEPATH=${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}/${CMAKE_IMPORT_LIBRARY_PREFIX}bz2${CMAKE_IMPORT_LIBRARY_SUFFIX}
  )
ELSE(MINGW)
  IF(WIN32)
    SET(ZLIB_LIB "zlib")
    IF(DEBUG)
      SET(ZLIB_LIB "${ZLIB_LIB}d")
    ENDIF()

    LIST(APPEND CMAKE_ARGS
      -DZLIB_LIBRARY:FILEPATH=${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}/${CMAKE_IMPORT_LIBRARY_PREFIX}${ZLIB_LIB}${CMAKE_IMPORT_LIBRARY_SUFFIX}
      -DBZIP2_LIBRARIES:FILEPATH=${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}/${CMAKE_IMPORT_LIBRARY_PREFIX}bz2${CMAKE_IMPORT_LIBRARY_SUFFIX}
      )
  ELSE(WIN32)
    LIST(APPEND CMAKE_ARGS
      -DZLIB_LIBRARY:FILEPATH=${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}/${CMAKE_SHARED_LIBRARY_PREFIX}z${CMAKE_SHARED_LIBRARY_SUFFIX}
      -DBZIP2_LIBRARIES:FILEPATH=${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}/${CMAKE_SHARED_LIBRARY_PREFIX}bz2${CMAKE_SHARED_LIBRARY_SUFFIX}
      )
  ENDIF(WIN32)
ENDIF(MINGW)

#IF(CFS_DISTRO STREQUAL "MACOSX")
#  SET(CMAKE_ARGS
#    ${CMAKE_ARGS}
#    -DCMAKE_OSX_ARCHITECTURES:STRING=${CMAKE_OSX_ARCHITECTURES}
#    -DCMAKE_OSX_SYSROOT:PATH=${CMAKE_OSX_SYSROOT}
#    )
#ENDIF(CFS_DISTRO STREQUAL "MACOSX")

IF(DEBUG)
  SET(CMAKE_ARGS
    ${CMAKE_ARGS}
    -DENABLE_DEBUG:BOOL=ON
    -DENABLE_RELEASE:BOOL=OFF
    )
ELSE(DEBUG)
  SET(CMAKE_ARGS
    ${CMAKE_ARGS}
    -DENABLE_DEBUG:BOOL=OFF
    -DENABLE_RELEASE:BOOL=ON
    )
ENDIF(DEBUG)

IF(CFS_ARCH STREQUAL "X86_64")
  LIST(APPEND CMAKE_ARGS -DLIB_SUFFIX:STRING=64)
ENDIF(CFS_ARCH STREQUAL "X86_64")

#-------------------------------------------------------------------------------
# Set list of Boost libraries to be built 
#-------------------------------------------------------------------------------
SET(BOOST_BUILD_LIBS
  "date_time"
  "filesystem"
  "iostreams"
  "program_options"
  "python"
  "regex"
  "serialization"
  "signals"
  "system"
  "thread"
  "chrono"
)

SET(BPROJ "-DBUILD_PROJECTS:STRING=")
foreach(BLIB IN LISTS BOOST_BUILD_LIBS)
#  MESSAGE("BLIB: ${BLIB}\n${BPROJ}")
    SET(BPROJ "${BPROJ},${BLIB}")
endforeach(BLIB)

LIST(APPEND CMAKE_ARGS
  ${BPROJ})

#MESSAGE("CMAKE_ARGS ${CMAKE_ARGS}")

#-------------------------------------------------------------------------------
# Set names of patch file and template file.
#-------------------------------------------------------------------------------
SET(PFN_TEMPL "${CFS_SOURCE_DIR}/cfsdeps/boost/boost-patch.cmake.in")
SET(PFN "${boost_prefix}/boost-patch.cmake")
CONFIGURE_FILE("${PFN_TEMPL}" "${PFN}" @ONLY) 

#-------------------------------------------------------------------------------
# Set up a list of publicly available mirrors, since the non-standard port 
# number of the FTP server on the CFS++ development server  may not be
# accessible from behind firewalls.
# Also set name of local file in CFS_DEPS_CACHE_DIR and MD5_SUM which will be
# used to configure the download CMake file for the library.
#-------------------------------------------------------------------------------
SET(MIRRORS
  "http://freefr.dl.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2"
  "${BOOST_URL}/${BOOST_GZ}"
)
SET(LOCAL_FILE "${CFS_DEPS_CACHE_DIR}/sources/boost/${BOOST_GZ}")
SET(MD5_SUM ${BOOST_MD5})

SET(DLFN "${boost_prefix}/boost-download.cmake")
CONFIGURE_FILE(
  "${CFS_SOURCE_DIR}/cmake_modules/cfsdeps_download.cmake.in"
  "${DLFN}"
  @ONLY
  )

#-------------------------------------------------------------------------------
# The Boost external project
#-------------------------------------------------------------------------------
ExternalProject_Add(boost
  DEPENDS zlib bzip2-shared bzip2-static
  LIST_SEPARATOR ,
  PREFIX "${boost_prefix}"
  URL ${LOCAL_FILE}
  URL_MD5 ${BOOST_MD5}
  PATCH_COMMAND ${CMAKE_COMMAND} -P "${PFN}"
  CMAKE_ARGS
    ${CMAKE_ARGS}
  )

#-------------------------------------------------------------------------------
# Add custom download step to be able to download from a list of mirrors
# instead of just a single URL.
#-------------------------------------------------------------------------------
ExternalProject_Add_Step(boost cfsdeps_download
   COMMAND ${CMAKE_COMMAND} -P "${DLFN}"
   DEPENDERS download
   DEPENDS "${DLFN}"
   WORKING_DIRECTORY ${boost_prefix}
)

#-------------------------------------------------------------------------------
# Add project to global list of CFSDEPS
#-------------------------------------------------------------------------------
SET(CFSDEPS
  ${CFSDEPS}
  boost
)

# These variables are used to find Boost by other projects
SET(Boost_INCLUDE_DIR "${CFS_BINARY_DIR}/include" CACHE PATH "Boost include dir.")
SET(Boost_LIBRARY_DIR "${CFS_BINARY_DIR}/${LIB_SUFFIX}/${CFS_ARCH_STR}" CACHE PATH "Boost library dir.")

MARK_AS_ADVANCED(Boost_INCLUDE_DIR)
MARK_AS_ADVANCED(Boost_LIBRARY_DIR)

IF(UNIX)
  SET(BOOST_LIB_SUFFIX_DEBUG "-mt-d${CMAKE_STATIC_LIBRARY_SUFFIX}")
  SET(BOOST_LIB_SUFFIX_RELEASE "-mt${CMAKE_STATIC_LIBRARY_SUFFIX}")
  
  SET(BOOST_LIB_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
ENDIF(UNIX)

IF(MINGW)
  SET(BOOST_LIB_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")

  STRING(REPLACE "." ";" COMPVER "${CFS_CXX_COMPILER_VER}")
  LIST(GET COMPVER 0 COMPVER_MAJOR)
  LIST(GET COMPVER 1 COMPVER_MINOR)

  SET(BOOST_LIB_SUFFIX_DEBUG "-gcc${COMPVER_MAJOR}${COMPVER_MINOR}-mt-d-1_52${CMAKE_STATIC_LIBRARY_SUFFIX}")
  SET(BOOST_LIB_SUFFIX_RELEASE "-gcc${COMPVER_MAJOR}${COMPVER_MINOR}-mt-1_52${CMAKE_STATIC_LIBRARY_SUFFIX}")
ENDIF(MINGW)

#-----------------------------------------------------------------------------
# Set Boost Debug library paths in cache.
#-----------------------------------------------------------------------------
SET(BOOST_DATE_TIME_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_date_time${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_DATE_TIME_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_DATE_TIME_LIB_DEBUG)
SET(BOOST_FILESYSTEM_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_filesystem${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_FILESYSTEM_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_FILESYSTEM_LIB_DEBUG)
SET(BOOST_IOSTREAMS_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_iostreams${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_IOSTREAMS_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_IOSTREAMS_LIB_DEBUG)
SET(BOOST_PRG_EXEC_MONITOR_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_prg_exec_monitor${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_PRG_EXEC_MONITOR_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_PRG_EXEC_MONITOR_LIB_DEBUG)
SET(BOOST_PROGRAM_OPTIONS_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_program_options${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_PROGRAM_OPTIONS_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_PROGRAM_OPTIONS_LIB_DEBUG)
SET(BOOST_PYTHON_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_python${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_PYTHON_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_PYTHON_LIB_DEBUG)
SET(BOOST_REGEX_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_regex${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_REGEX_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_REGEX_LIB_DEBUG)
SET(BOOST_SERIALIZATION_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_serialization${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SERIALIZATION_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_LIB_DEBUG)
SET(BOOST_SERIALIZATION_HDF5_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_serialization_hdf5${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SERIALIZATION_HDF5_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_HDF5_LIB_DEBUG)
SET(BOOST_SIGNALS_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_signals${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SIGNALS_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SIGNALS_LIB_DEBUG)
SET(BOOST_SYSTEM_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_system${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_SYSTEM_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_SYSTEM_LIB_DEBUG)
SET(BOOST_TEST_EXEC_MONITOR_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_test_exec_monitor${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_TEST_EXEC_MONITOR_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_TEST_EXEC_MONITOR_LIB_DEBUG)
SET(BOOST_THREAD-MT_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_thread-mt${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_THREAD-MT_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_THREAD-MT_LIB_DEBUG)
SET(BOOST_THREAD_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_thread${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_THREAD_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_THREAD_LIB_DEBUG)
SET(BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_unit_test_framework${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG)
SET(BOOST_WSERIALIZATION_LIB_DEBUG
  "${BOOST_LIB_PREFIX}boost_wserialization${BOOST_LIB_SUFFIX_DEBUG}"
  CACHE STRING "BOOST_WSERIALIZATION_LIB_DEBUG")
MARK_AS_ADVANCED(BOOST_WSERIALIZATION_LIB_DEBUG)


#-----------------------------------------------------------------------------
# Set Boost Release library paths in cache.
#-----------------------------------------------------------------------------
SET(BOOST_DATE_TIME_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_date_time${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_DATE_TIME_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_DATE_TIME_LIB_RELEASE)
SET(BOOST_FILESYSTEM_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_filesystem${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_FILESYSTEM_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_FILESYSTEM_LIB_RELEASE)
SET(BOOST_IOSTREAMS_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_iostreams${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_IOSTREAMS_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_IOSTREAMS_LIB_RELEASE)
SET(BOOST_PRG_EXEC_MONITOR_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_prg_exec_monitor${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_PRG_EXEC_MONITOR_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_PRG_EXEC_MONITOR_LIB_RELEASE)
SET(BOOST_PROGRAM_OPTIONS_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_program_options${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_PROGRAM_OPTIONS_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_PROGRAM_OPTIONS_LIB_RELEASE)
SET(BOOST_PYTHON_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_python${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_PYTHON_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_PYTHON_LIB_RELEASE)
SET(BOOST_REGEX_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_regex${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_REGEX_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_REGEX_LIB_RELEASE)
SET(BOOST_SERIALIZATION_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_serialization${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SERIALIZATION_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_LIB_RELEASE)
SET(BOOST_SERIALIZATION_HDF5_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_serialization_hdf5${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SERIALIZATION_HDF5_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SERIALIZATION_HDF5_LIB_RELEASE)
SET(BOOST_SIGNALS_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_signals${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SIGNALS_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SIGNALS_LIB_RELEASE)
SET(BOOST_SYSTEM_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_system${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_SYSTEM_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_SYSTEM_LIB_RELEASE)
SET(BOOST_TEST_EXEC_MONITOR_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_test_exec_monitor${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_TEST_EXEC_MONITOR_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_TEST_EXEC_MONITOR_LIB_RELEASE)
SET(BOOST_THREAD-MT_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_thread-mt${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_THREAD-MT_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_THREAD-MT_LIB_RELEASE)
SET(BOOST_THREAD_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_thread${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_THREAD_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_THREAD_LIB_RELEASE)
SET(BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_unit_test_framework${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE)
SET(BOOST_WSERIALIZATION_LIB_RELEASE
  "${BOOST_LIB_PREFIX}boost_wserialization${BOOST_LIB_SUFFIX_RELEASE}"
  CACHE STRING "BOOST_WSERIALIZATION_LIB_RELEASE")
MARK_AS_ADVANCED(BOOST_WSERIALIZATION_LIB_RELEASE)


#-----------------------------------------------------------------------------
# Set Boost library paths according to current config.
#-----------------------------------------------------------------------------
IF(DEBUG)
  SET(BOOST_DATE_TIME_LIB "${Boost_LIBRARY_DIR}/${BOOST_DATE_TIME_LIB_DEBUG}")
  SET(BOOST_FILESYSTEM_LIB "${Boost_LIBRARY_DIR}/${BOOST_FILESYSTEM_LIB_DEBUG}")
  SET(BOOST_IOSTREAMS_LIB "${Boost_LIBRARY_DIR}/${BOOST_IOSTREAMS_LIB_DEBUG}")
  SET(BOOST_PRG_EXEC_MONITOR_LIB "${Boost_LIBRARY_DIR}/${BOOST_PRG_EXEC_MONITOR_LIB_DEBUG}")
  SET(BOOST_PROGRAM_OPTIONS_LIB "${Boost_LIBRARY_DIR}/${BOOST_PROGRAM_OPTIONS_LIB_DEBUG}")
  SET(BOOST_PYTHON_LIB "${Boost_LIBRARY_DIR}/${BOOST_PYTHON_LIB_DEBUG}")
  SET(BOOST_REGEX_LIB "${Boost_LIBRARY_DIR}/${BOOST_REGEX_LIB_DEBUG}")
  SET(BOOST_SERIALIZATION_LIB "${Boost_LIBRARY_DIR}/${BOOST_SERIALIZATION_LIB_DEBUG}")
  SET(BOOST_SERIALIZATION_HDF5_LIB "${Boost_LIBRARY_DIR}/${BOOST_SERIALIZATION_HDF5_LIB_DEBUG}")
  SET(BOOST_SIGNALS_LIB "${Boost_LIBRARY_DIR}/${BOOST_SIGNALS_LIB_DEBUG}")
  SET(BOOST_SYSTEM_LIB "${Boost_LIBRARY_DIR}/${BOOST_SYSTEM_LIB_DEBUG}")
  SET(BOOST_TEST_EXEC_MONITOR_LIB "${Boost_LIBRARY_DIR}/${BOOST_TEST_EXEC_MONITOR_LIB_DEBUG}")
  SET(BOOST_THREAD-MT_LIB "${Boost_LIBRARY_DIR}/${BOOST_THREAD-MT_LIB_DEBUG}")
  SET(BOOST_THREAD_LIB "${Boost_LIBRARY_DIR}/${BOOST_THREAD_LIB_DEBUG}")
  SET(BOOST_UNIT_TEST_FRAMEWORK_LIB "${Boost_LIBRARY_DIR}/${BOOST_UNIT_TEST_FRAMEWORK_LIB_DEBUG}")
  SET(BOOST_WSERIALIZATION_LIB "${Boost_LIBRARY_DIR}/${BOOST_WSERIALIZATION_LIB_DEBUG}")
ELSE(DEBUG)
  SET(BOOST_DATE_TIME_LIB "${Boost_LIBRARY_DIR}/${BOOST_DATE_TIME_LIB_RELEASE}")
  SET(BOOST_FILESYSTEM_LIB "${Boost_LIBRARY_DIR}/${BOOST_FILESYSTEM_LIB_RELEASE}")
  SET(BOOST_IOSTREAMS_LIB "${Boost_LIBRARY_DIR}/${BOOST_IOSTREAMS_LIB_RELEASE}")
  SET(BOOST_PRG_EXEC_MONITOR_LIB "${Boost_LIBRARY_DIR}/${BOOST_PRG_EXEC_MONITOR_LIB_RELEASE}")
  SET(BOOST_PROGRAM_OPTIONS_LIB "${Boost_LIBRARY_DIR}/${BOOST_PROGRAM_OPTIONS_LIB_RELEASE}")
  SET(BOOST_PYTHON_LIB "${Boost_LIBRARY_DIR}/${BOOST_PYTHON_LIB_RELEASE}")
  SET(BOOST_REGEX_LIB "${Boost_LIBRARY_DIR}/${BOOST_REGEX_LIB_RELEASE}")
  SET(BOOST_SERIALIZATION_LIB "${Boost_LIBRARY_DIR}/${BOOST_SERIALIZATION_LIB_RELEASE}")
  SET(BOOST_SERIALIZATION_HDF5_LIB "${Boost_LIBRARY_DIR}/${BOOST_SERIALIZATION_HDF5_LIB_RELEASE}")
  SET(BOOST_SIGNALS_LIB "${Boost_LIBRARY_DIR}/${BOOST_SIGNALS_LIB_RELEASE}")
  SET(BOOST_SYSTEM_LIB "${Boost_LIBRARY_DIR}/${BOOST_SYSTEM_LIB_RELEASE}")
  SET(BOOST_TEST_EXEC_MONITOR_LIB "${Boost_LIBRARY_DIR}/${BOOST_TEST_EXEC_MONITOR_LIB_RELEASE}")
  SET(BOOST_THREAD-MT_LIB "${Boost_LIBRARY_DIR}/${BOOST_THREAD-MT_LIB_RELEASE}")
  SET(BOOST_THREAD_LIB "${Boost_LIBRARY_DIR}/${BOOST_THREAD_LIB_RELEASE}")
  SET(BOOST_UNIT_TEST_FRAMEWORK_LIB "${Boost_LIBRARY_DIR}/${BOOST_UNIT_TEST_FRAMEWORK_LIB_RELEASE}")
  SET(BOOST_WSERIALIZATION_LIB "${Boost_LIBRARY_DIR}/${BOOST_WSERIALIZATION_LIB_RELEASE}")
ENDIF(DEBUG)

SET(BOOST_THREAD_LIB "${BOOST_THREAD_LIB}")
IF(NOT MINGW)
  LIST(APPEND BOOST_THREAD_LIB -lpthread)
ENDIF(NOT MINGW)

SET(Boost_FOUND 1)
