#
# Makefile for discretization
C_DIR=../..
#
src =  baseelem.cc rectangle.cc quad1.cc getriangle.cc triangle1.cc 
#
lib = elements
libpath = libsrc/Elements
CFLAGS3 =
#
include ../makefile.inc

# DO NOT DELETE


